### ISSUE TITLE
Install Alexa

### ISSUE THREAD

**Issue by Wolf6660** [NorthernMan54/homebridge-alexa#1]
Hi,
my English is not so good i hope you understand it.

i want to install homebridge-alexa. can you tell me what i to do?

install the Plugin of my RaspberryPi is done (Npm install -g https://github.com/NorthernMan54/homebridge-alexa)

and now?

Thanks

**Comment by NorthernMan54** [comment]
Sorry, I missed this.  I have changed the approach and installation method.  Please read the new instructions on the README Page.  I'm not following a plugin based approach anymore, as it was too complicated and instead have changed homebridge and hap-nodes to enable the feature.

**Comment by simonrb2000** [comment]
Is there no way of adding this to existing Homebridge? Just about to go out and buy an Echo just for this so it saves using Watch or Phone to control the house, means anyone babysitting can still use the house. I have a very stable Homebridge running and a lot has gone into setting up the rooms and scenes. I would rather not mess about with all that again.. 

Many Thanks

**Comment by NorthernMan54** [comment]
@simonrb2000 as long as your homebridge was recently installed, ( within a few months ), it should seamlessly install and not break anything.  All your doing is upgrading the homebridge version.

The old approach would work as well, just the complexity of getting it working is very high ;-(

**Comment by simonrb2000** [comment]
Yes, recently install. I've just got back from town and didn't buy one. Might have to make another trip to grab an echo.

On 17 Apr 2017, at 12:33, NorthernMan54 <notifications@github.com<mailto:notifications@github.com>> wrote:


@simonrb2000<https://github.com/simonrb2000> as long as your homebridge was recently installed, ( within a few months ), it should seamlessly install and not break anything. All your doing is upgrading the homebridge version.

The old approach would work as well, just the complexity of getting it working is very high ;-(
