### ISSUE TITLE
Just wanna say "Thank you"

### ISSUE THREAD

**Issue by c-o-m-m-a-n-d-e-r** [NorthernMan54/homebridge-alexa#10]
I just wanna say thank you.
got my echo dot gen 2 today ... prepared the homebridge with your version and my homebridge-knx config ... and voila... out of the box everything is working as aspected ... 

fantastic! keep up this good work!!

P.S: Please mark this not as an issue ;)

**Comment by NorthernMan54** [comment]
Awesome, glad to hear it worked.  Awesome

**Comment by samsonrosen** [comment]
Second this! Have been using Homebridge for ages and got an Echo Dot yesterday. Can't believe how well this works!
