### ISSUE TITLE
Add valve/sprinkler support 

### ISSUE THREAD

**Issue by dehsgr** [NorthernMan54/homebridge-alexa#100]
It would be nice, if sprinkler devices could be added to alexa. A first step could be to add such devices as switch or outlet.

**Comment by NorthernMan54** [comment]
For sprinklers, is it just on/off?  If so this should be a simple mapping, give me a couple of days.

**Comment by dehsgr** [comment]
On/off should be enough, as it is a (timer)-switch in HomeKit, which will automatically turn off, after a pre-defined time.

Thanks a lot!

**Comment by NorthernMan54** [comment]
I just added support to a test branch.  Can you give it a try and let me know how it works.

You install the test branch with this command, restart homebridge, then ask Alexa to discover devices again.

sudo npm install -g northernman54/homebridge-alexa#sprinkler

**Comment by dehsgr** [comment]
Great Job! 

It works as expected and – that is the best – triggers sprinkler in HomeKit with its timer based settings, if they‘re set.

Thank you so much!!!
