### ISSUE TITLE
does alexa needs to rediscover all devices after homebridge restart?

### ISSUE THREAD

**Issue by boradayioglu** [NorthernMan54/homebridge-alexa#104]
Hi,
I`m running homebridge from terminal(osx), but every time when I need to kill/restart the homebridge alexa is loosing my devices, so I have to forget all/rediscover from alexa app. Is this expected and is there any way around it?

It`s an awesome plugin, thanks for the great effort!

**Comment by NorthernMan54** [comment]
@boradayioglu This is not normal behaviour, this should only happen if devices are added etc.  Do you devices move to default room at the same time?  Do you know which plugins you are using?

**Comment by boradayioglu** [comment]
Thanks mate, I managed to fix this by setting my homebridge to run on the specific port number alexa plugin was trying to communicate to.

**Comment by NorthernMan54** [comment]
As others have reported similar issues, do you know why your homebridge was not using a static port number?

**Comment by NorthernMan54** [comment]
Tks

I added this issue as a troubleshooting tip
