### ISSUE TITLE
No reaction from any device in Alexa

### ISSUE THREAD

**Issue by MikeDeltaHH** [NorthernMan54/homebridge-alexa#105]
Hi!
Since yesterday the plugin doesn´t work properly! The plugin is running, my account is connected and all devices are online in Alexa but all devices which comes over your plugin to alexa doesn´t react on any command...

Regards!
Mike

**Comment by NorthernMan54** [comment]
Mike,

Just checked, and everything is okay with the backend of the home skill, and has been working fine with out issue for a while now.  Have you tried discover devices again?

**Comment by MikeDeltaHH** [comment]
Hi!
I have to delete all devices from Alexa and do a full new discovery - after that it works again! Thanks a lot for this great plugin!
