### ISSUE TITLE
Blinds in HomeKit are modelled as bulbs in Alexa

### ISSUE THREAD

**Issue by nautigar** [NorthernMan54/homebridge-alexa#108]
Thanks for this great plugin!
I just have one minor issue: I use the Loxone plugin to interface to my blinds and fans (via KNX), and they are correctly displayed in the Apple Home App as blinds and fans. In the Alexa App, however, they are displayed as bulbs and switches. As a consequence, I have to say "switch the blinds off" instead of "open the blinds". Is there any way to change the type of a device?

**Comment by NorthernMan54** [comment]
Unfortunately Alexa doesn’t support blinds yet, so as a work around I mapped them to a light bulb.

**Comment by nautigar** [comment]
Thanks! I guess the same is true for fans?

**Comment by NorthernMan54** [comment]
Yes
