### ISSUE TITLE
Status of the Devices in Homekit & Alexa different

### ISSUE THREAD

**Issue by Shana611** [NorthernMan54/homebridge-alexa#109]
I installed your Homebridge-alexa its working amazingly thank you so much. But there is a problem with my gate status in between Alexa & Homekit. When the gate opens Alexa shows Off status & Homekit shows Open status & when the gate closes Alexa shows On Status but Homekit shows Close status. Any solution of this Pls. Thanks

**Comment by NorthernMan54** [comment]
@Shana611 Door, blinds and gates etc aren't supported by Alexa, so it is a bit of a hack.  And the status reporting is really wacky as you have found.  Basically I had to map them all to a light bulb as you found.

I won't be able to do a lot with this until Alexa catches up with HomeKit and offers native support for these devices.
