### ISSUE TITLE
Question : Which Word is used

### ISSUE THREAD

**Issue by c-o-m-m-a-n-d-e-r** [NorthernMan54/homebridge-alexa#11]
Hey,
can you tell me which config Words is used?

If i look at my knx_config.json i have

- DeviceName
- ServiceName

And Rooms via Home App. Also ih can create Groups via Alexa App.
I understand i can create group "Bedroom" and add the Light but which word is used if i want a single object?

Thanks

**Comment by NorthernMan54** [comment]
Sorry I'm not familiar with Knx plugin, and am not aware of those config names.   Can you explain further what you are attempting to do?

**Comment by c-o-m-m-a-n-d-e-r** [comment]
hi,
yes i use the homebridge with KNX Plugin to switch my light etc. thats working good.
Alexa is switching too but not 100% sure about different naming in the rooms etc.

I'm not sure about config two lamps in one room and then say : switch on the light into the kitchen .. 

I have a little bit of time tonight so i will testing with my configuration myself ... will report back then..
thanks
