### ISSUE TITLE
AlexaPi not working 

### ISSUE THREAD

**Issue by miguelmolez** [NorthernMan54/homebridge-alexa#111]
Hi,

I seem to have all the devices populated in the Alexa Ap, but AlexaPi will not action my requests. It doesn't seem to think there is any smart home device enabled. Is there any further configuration for AlexaPi?

**Comment by NorthernMan54** [comment]
Sorry I’m not familiar with AlexaPI, so am not aware of any additional configuration requirements.

Do your requests from AlexaPI show up in the app?  In the history section.

Also do voice requests work from the app?

Sean

**Comment by miguelmolez** [comment]
Hi Sean,

Yes the requests do show up in the history. 
I’ve tried switch on TV, switch on lamp in office etc. Alexa doesn’t seem to work from the AlexaPi. They do work fine from the app.

**Comment by NorthernMan54** [comment]
That is between AlexaPI and the Alexa backend.  The device mapping is handled by amazon before it gets to my skill. My only thought is that AlexaPI is connected to a different amazon account.

**Comment by miguelmolez** [comment]
My email for the Homebridge-Alexa is different to my actual Amazon account email. So should they be the same?

**Comment by NorthernMan54** [comment]
No they do not need to be the same.  The linking between your amazon account and homebridge Alexa is done during the linking step when you enabled the smart home skill in the app.
