### ISSUE TITLE
Commands not working after changing IP address

### ISSUE THREAD

**Issue by sebastianpopp** [NorthernMan54/homebridge-alexa#112]
Hi there,

I'm running homebridge-alexa on a Raspberry to control some devices through homebridge-fhem on the same device. The IP address of my Raspberry recently changed through DHCP from 10.0.2.8 to 10.0.1.4. Since then my devices are not available anymore. I got the following debug output which indicated that it's still trying to use the old ip address.

```
  alexaLocal Emitting Alexa.PowerController +3s
  alexaHAP Homebridge Control failed 10.0.2.8:51826 {"characteristics":[{"aid":9,"iid":10,"value":0}]} { Error: connect EHOSTUNREACH 10.0.2.8:51826
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '10.0.2.8',
  port: 51826,
  attempts: 1 } +3s
[2018-7-22 11:50:36] [Alexa] PowerController TurnOff 10.0.2.8 51826 undefined { Error: connect EHOSTUNREACH 10.0.2.8:51826
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '10.0.2.8',
  port: 51826,
  attempts: 1 }
```

It looks to me like the IP address is not saved on my side, but coming from homebridge.cloudwatch.net. Is there a way to update it?

PS: I was trying to ask my question in the Slack channel mentioned in the readme, but it looks like you need to be invited.

**Comment by NorthernMan54** [comment]
Try discover devices from Alexa, this will update the ip addresses.

**Comment by sebastianpopp** [comment]
Okay, I figured it out. Just telling Alexa to find devices didn't help (Alexa just told me it couln't find any new devices and the problem persisted). But deleting all my smart devices in the Alexa app and and adding them back in worked. I guess I'll have to configure a static IP for my Raspberry, so I don't have to setup my routines all over again. Thank you for your help!
