### ISSUE TITLE
Nothing visible in homekit

### ISSUE THREAD

**Issue by Ghost108** [NorthernMan54/homebridge-alexa#113]
Hello :)

maybe I misunderstand this plugin.
I installed the Alexa homebridge plugin and set this config:

`{
            "platform": "Alexa",
            "name": "Alexa",
            "username": "Username", <-- MY USERNAME
            "password": "Password", <-- MY PASSWORD
            "pin": "xxx-xx-xx", <-- MY HOMEBRIDGE PIN
            "refresh": 15
        },`

Secondly I installed the homebridge plugin in the Alexa iPhone App.
But I can't see any new "button" in homekit.

Where is my mistake ?

**Comment by NorthernMan54** [comment]
With this plugin, nothing appears in the Home app.   After you have everything installed, ask Alexa to discover devices.   And they will appear in the Alexa app

**Comment by Ghost108** [comment]
ah yes, okay I unterstand. the devices are there. but Is it possible to control the devices, which are only available in the Alexa app, via Siri ?

**Comment by NorthernMan54** [comment]
No, this is only a connection for homebridge devices to Alexa

**Comment by Ghost108** [comment]
mmmh :(
okay thanks a lot :)
