### ISSUE TITLE
Using Scenes

### ISSUE THREAD

**Issue by allistoncarlos** [NorthernMan54/homebridge-alexa#114]
Is it possible to create scenes using the homebridge devices? If not, it could be an improvement 😁
Thanks, and congrats for the hard work!

**Comment by NorthernMan54** [comment]
When your suggesting scenes, isn’t that just like an Alexa routine, or group?

**Comment by allistoncarlos** [comment]
When I select Scenes in my Alexa app, it shows that no Smart Home Skill is enabled... But when I select Smart Home menu, it shows that Homebridge is enabled.

**Comment by NorthernMan54** [comment]
That is expected as the plugin doesn’t support scenes, this is because HomeKit scenes aren’t visible to homebridge

**Comment by allistoncarlos** [comment]
So I can’t create my own scenes on Alexa app? There’s something similar that I could use?

**Comment by NorthernMan54** [comment]
I use routines in the Alexa app

**Comment by allistoncarlos** [comment]
Oh... I don't know why, but I can't activate Routines in my Alexa app... But hey, thanks for the attention and patience!
