### ISSUE TITLE
i have 2 homebridge running on a pie how to prevent alexa to load on the 2nd homebridge?

### ISSUE THREAD

**Issue by mahdi89X** [NorthernMan54/homebridge-alexa#115]
i have 2 homebridge running on a pie how to prevent alexa to load on the 2nd homebridge?
i have some device that are already alexa compatible(tplink) ..
some i made a second homebridge just for tplink
and on the original homebridge i install homebridge-alexa (localy and not gloabaly) and load it using 
this HOMEBRIDGE -I -U /var/lib/homebridge -P /var/lib/homebridge
but alexa still recognizing all deviced in homebridge2!
thats weird
any help?

**Comment by NorthernMan54** [comment]
Double check your startup script, it is the -I command line option that enables homebridge-alexa to see all the devices

**Comment by mahdi89X** [comment]
i should remove the -I ?
why homebridge-alexa  see devices? on other homebridge config.. thats weid?

any solution ?
homebridge-alexa is only installed under one of the both server
but all deviced on homebridge1 and homeridge2 are showing

**Comment by NorthernMan54** [comment]
The plugin uses -I unsecure mode to see the devices on each instance

**Comment by mahdi89X** [comment]
after romving the -I am getting  ERROR: HAP Discovery failed, please review config
and alexa local error 
alexaLocal error { Error: connect ECONNREFUSED 35.169.132.61:8883
Aug  1 12:10:59 piDNS-Kit homebridge[3897]:     at Object._errnoException (util.js:992:11)
any solution? to make here listen to one instance? without removing the insecure mode?

**Comment by NorthernMan54** [comment]
The HAP Discovery failed is normal for the plugin when it finds a homebridge instance it can't talk too.

unfortunately removing insecure mode is the only way.

**Comment by sommo** [comment]
Hi, 
i have a rpi running multiple instance of homebridge (ssytemd), i will create a newone dedicated to run only your plugin and i will execute it with -I, could it works? or to gain access to all the other systemd instance, also them need to be run with -I ?
thank you.
Another question (out of topic), the registration via https://homebridge.cloudwatch.net is an onetimeshot connection?
Best regards,

**Comment by sommo** [comment]
> 
> 
> Hi,
> i have a rpi running multiple instance of homebridge (ssytemd), i will create a newone dedicated to run only your plugin and i will execute it with -I, could it works? or to gain access to all the other systemd instance, also them need to be run with -I ?
> thank you.
> Another question (out of topic), the registration via https://homebridge.cloudwatch.net is an onetimeshot connection?
> Best regards,

Ok, i reread better and i saw that all the instance need to be run with -I ... what does it means to be less secure? thank you

**Comment by NorthernMan54** [comment]
What -I does is allow access to homebridge without HomeKit encryption and pairing.  And would allow anyone with access to your home/local network to control your devices outside of the HomeKit eco system.  It does not allow access from outside your network, so risk is minimal and contained to your local network.

The website https://homebridge.cloudwatch.net <https://homebridge.cloudwatch.net/> is also used as an Alexa message router/bridge between the Amazon cloud and the plugin on your home network.  It does all the heavy lifting.

**Comment by sommo** [comment]
The option -I very clear explanation, thank you! Is there a chance in future to get it works without the insecure option?

For the website, to understand, if the homebridge cloud watch site is down, it will affect the alexa to homebridge service right?

Best regards

Inviato da iPhone

> Il giorno 27 ott 2018, alle ore 15:10, Northern Man <notifications@github.com> ha scritto:
> 
> What -I does is allow access to homebridge without HomeKit encryption and pairing. And would allow anyone with access to your home/local network to control your devices outside of the HomeKit eco system. It does not allow access from outside your network, so risk is minimal and contained to your local network.
> 
> The website https://homebridge.cloudwatch.net <https://homebridge.cloudwatch.net/> is also used as an Alexa message router/bridge between the Amazon cloud and the plugin on your home network. It does all the heavy lifting.
>
