### ISSUE TITLE
Need to restart Homebridge

### ISSUE THREAD

**Issue by LeBaron90** [NorthernMan54/homebridge-alexa#116]
Hi

At first, thank you very much for this great plugin. I use it with Alexa AND Siri.
But I have a little problem:

When I start my Raspberry Pi, I need to type "sudo killall homebridge" and then "homebridge -I" to get Alexa work.
Homebridge starts on my Pi at start, but don't ask me how. There are 5 ways for it.

I already tried your possibilities to launch "homebridge -I" on startup but it won't work.

Please help me, I was surprising my wife with this cool feature but I cant configure it how it have to work.

If you need any logs or something, just let me know.

PS: the /etc/default/homebridge file is empty and the /etc/default/homebridge is empty too.

Thank you very much & best regards

**Comment by LeBaron90** [comment]
Problem solved by: made a clean reinstall of OS Noobs and Homebridge.

**Comment by NorthernMan54** [comment]
Glad to hear
