### ISSUE TITLE
GMT alexaLocal error { Error: connect ECONNREFUSED...

### ISSUE THREAD

**Issue by ipa64** [NorthernMan54/homebridge-alexa#117]
Hi,I use my iPhone with Alexa app to try to discover devices, but haven't discovered anything: discovered failed  .
Homebridg 0.4.44
Homebridge-config-ui 3.8.5
Here the log file (only alexa lines):

[2018-8-8 05:53:53] Loaded plugin: homebridge-alexa
[2018-8-8 05:53:53] Registering platform 'homebridge-alexa.Alexa'
...
[2018-8-8 05:53:53] Loading 3 platforms...
[2018-8-8 05:53:53] [Alexa] Initializing Alexa platform...
...
Wed, 08 Aug 2018 05:53:53 GMT alexaHAP Starting Homebridge instance discovery
Wed, 08 Aug 2018 05:53:53 GMT alexaLocal Connecting to Homebridge Smart Home Skill
[2018-8-8 05:53:54] Homebridge is running on port 51826.
...
Wed, 08 Aug 2018 05:53:54 GMT alexaLocal error { Error: connect ECONNREFUSED 35.169.132.61:8883
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '35.169.132.61',
  port: 8883 }
Wed, 08 Aug 2018 05:53:54 GMT alexaLocal offline
Wed, 08 Aug 2018 05:53:54 GMT alexaHAP HAP Device discovered Homebridge-CAD8 [ '192.168.1.100', 'fe80::211:32ff:fe55:1809', '10.8.0.1' ]
Wed, 08 Aug 2018 05:53:54 GMT alexaHAP HAP instance address: Homebridge-CAD8 -> CC_22_3D_E3_CE_30.local -> 192.168.1.100
Wed, 08 Aug 2018 05:53:54 GMT alexaHAP Homebridge instance discovered Homebridge-CAD8 with 8 accessories
...
Wed, 08 Aug 2018 05:53:59 GMT alexaLocal reconnect
Wed, 08 Aug 2018 05:54:00 GMT alexaLocal connect command/iPa64/#
Wed, 08 Aug 2018 05:54:48 GMT alexaHAP Ending Homebridge instance discovery
Wed, 08 Aug 2018 06:08:53 GMT alexaHAP Starting Homebridge instance discovery
Wed, 08 Aug 2018 06:08:55 GMT alexaHAP HAP Device discovered Homebridge-CAD8 [ '192.168.1.100', 'fe80::211:32ff:fe55:1809', '10.8.0.1' ]
Wed, 08 Aug 2018 06:08:55 GMT alexaHAP HAP instance address: Homebridge-CAD8 -> CC_22_3D_E3_CE_30.local -> 192.168.1.100
Wed, 08 Aug 2018 06:08:55 GMT alexaHAP Homebridge instance discovered Homebridge-CAD8 with 8 accessories
Wed, 08 Aug 2018 06:09:48 GMT alexaHAP Ending Homebridge instance discovery

Thanks for advice

**Comment by NorthernMan54** [comment]
That is weird, are you running any firewalls etc, that would block the plugin from opening a MQTT connection to Alexa?

**Comment by ipa64** [comment]
No firewall are running.
Homebridge is installed in a docker on my NAS Synology.

**Comment by NorthernMan54** [comment]
Just looking at the system logs and it appears you didn't complete the setup.  Did you complete the amazon account linking step?  And did you do discover devices?

**Comment by NorthernMan54** [comment]
Can we jump over to slack, and go direct.  I need your cloudwatch account name to trace, and don’t want it in an issue for the world to see.

**Comment by ipa64** [comment]
Ok, i have just installed slack

**Comment by NorthernMan54** [comment]
I'm in the #hap-alexa channel

**Comment by NorthernMan54** [comment]
My suspicion on the actual issue is one of two possible things

1 - the end user only has the iPhone app, and no physical device.  Am thinking the smart home skills may not work without a physical device.  ( I thought someone else had a similar issue ).  Need to test this

2 - the end user is a amazon France user, located in Asia.  Is that a supported config from amazon.

**Comment by drfrode1** [comment]
I face the same issue (Norwegian amazon user). 

HomeBridge is running on CentOs, firewall is open for tcp/8883.

**Comment by NorthernMan54** [comment]
@drfrode1 Can you elaborate on the error you are receiving, as opening a outbound firewall is not normally required.  If you do have a firewall blocking outbound connections, can you also open port 1883.  This is required for MQTT to work

**Comment by drfrode1** [comment]
@NorthernMan54 I went through my configuration again and I made a dummy mistake.. Used email as username. Only inbound firewall, so closed 8883 again. Now it works like a charm

**Comment by ipa64** [comment]
I bought an echo dot, now it’s working 👍🏻
So you need to have at least one physical device

**Comment by NorthernMan54** [comment]
Tks for confirming this, much appreciated.
