### ISSUE TITLE
Updating this homebridge 

### ISSUE THREAD

**Issue by jat80** [NorthernMan54/homebridge-alexa#12]
Just wondering if your version of homebridge follows the updates of the original homebridge. (Sorry if this is a stupid question). Do I update everything as per normal?

**Comment by NorthernMan54** [comment]
Yes it follows the same update pattern as regular homebridge

sudo npm -g update

**Comment by creedda** [comment]
I think what he is asking (and I think it is a good question!) is if all f the updates being made to homebridge are being mirrored in this version?

I believe the answer is no. Though maybe major releases are being synced?

**Comment by NorthernMan54** [comment]
Thanks for the clarification

I have been mirroring the updates to homebridge and hap-nodejs about once a month, typically about a month behind.

**Comment by jat80** [comment]
Thanks @NorthernMan54 and @creedda for the quick responses.
