### ISSUE TITLE
Camera support

### ISSUE THREAD

**Issue by b2un0** [NorthernMan54/homebridge-alexa#124]
Feature Request:

Camera support for Echo Show/Spot and/or Fire TV.

Can be tested with https://github.com/KhaosT/homebridge-camera-ffmpeg and an `m3u8` Stream URL from https://livespotting.tv.

if you test it with an livespotting.tv url, you must remove manually the `-map 0:0` Option, see here my issue
https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/208

Thank You!

**Comment by NorthernMan54** [comment]
This sounds like a great feature and as a user homebridge-camera-ffmpeg makes sense.  And I can add it to my backlog, but it may be a while before I can tackle this as I would need to purchase the device and go forward from there.  And would need WAF approval on the cost. If someone wants to tackle this, I will gladly accept a pull request with the change.  The source for the skill and plugin are fully available on GitHub.
