### ISSUE TITLE
Devices aren't been discovered  

### ISSUE THREAD

**Issue by GhostViper396** [NorthernMan54/homebridge-alexa#125]
Hi 

Same to be having trouble with the discovery. 

Config (cut out the other plugins... just trying to get to work):

`{
	"bridge": {
		"name": "pi",
		"username": "DD:14:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"platforms": [{
		"platform": "Alexa",
		"name": "Alexa",
		"username": "",
		"password": "",
		"refresh": 15
	}]
}`

Log from DEBUG=alexa* homebridge -I

`alexaHAP Starting Homebridge instance discovery +0ms
  alexaLocal Connecting to Homebridge Smart Home Skill +17ms
[2018-9-1 17:22:15] Homebridge is running on port 51826.
  alexaLocal error { Error: connect ECONNREFUSED 35.169.132.61:8883
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '35.169.132.61',
  port: 8883 } +649ms
  alexaLocal offline +26ms
  alexaHAP HAP Device discovered Philips hue - 7888FF [ 'fe80::217:88ff:fe78:88ff', '192.168.1.69' ] +22ms
  alexaHAP HAP instance address: Philips hue - 7888FF -> Philips-hue.local -> 192.168.1.69 +5ms
  alexaHAP HAP Discover failed Philips hue - 7888FF http://192.168.1.69:8080 error code 470 +189ms
  alexaHAP HAP Device discovered pi-B823 [ '192.168.1.84', 'fe80::5691:8763:8515:99fe' ] +538ms
  alexaHAP HAP instance address: pi-B823 -> DD_14_3D_E3_CE_30.local -> 192.168.1.84 +1ms
  alexaHAP Homebridge instance discovered pi-B823 with 1 accessories +79ms
  alexaLocal reconnect +4s
  alexaLocal connect command/***/# +267ms
  alexaHAP Ending Homebridge instance discovery +49s
  alexaLocal Emitting Alexa.Discovery +4m
  alexaTranslator Alexa Controllable pi-B823 0 +22ms
[2018-9-1 17:26:49] [Alexa] ERROR: HAP Discovery failed, please review config
`
I have 2 eve elgato plugs trying to get alexa to tun them on and off. Also a few hue bulbs, not fussyed about them. Home bridge is running on my pi (no firewall). 

When i started, i had another plugin configured to talk to turn my xbox on and that worked from Alexa.

Any idea why it can't find my devices? 

Cheers

**Comment by NorthernMan54** [comment]
Just looking at the log and the first error can be ignored.  Looking at the homebridge instance discovery below that it finds your hue hub which supports HomeKit and pi-B823 with only 1 device connected.  Your hue hub is not supported with homebridge-Alexa, and she just ignores it.

Is this what you expected?  Or should you have more homebridge instances or devices?

**Comment by NorthernMan54** [comment]
The plugin only supports devices connected thru homebridge, so the elgato devices are not supported.

What do you have connected to homebridge, and which plugin?

**Comment by GhostViper396** [comment]
ah that explains why it does work then :) 

thanks 

found away around it using
https://www.npmjs.com/package/homebridge-fakebulb

So I create a fake bulb which Alexa and homekit can see. Then in the home kit automation, if fake bulk turn on then turn on plug, same for off. hackie work around :)

**Comment by NorthernMan54** [comment]
Awesome workaround
