### ISSUE TITLE
multiple apple tv with same label

### ISSUE THREAD

**Issue by hroman73** [NorthernMan54/homebridge-alexa#127]
All is working fine but I see double of all buttons labeled with "Living Room Apple TV" instead of a set for living room and a set for master bedroom. Am I doing something wrong?

Here is my config:
{
            "platform": "AppleTV",
            "name": "Apple TV",
            "devices": [
                {
                    "id": "livingroom",
                    "name": "Living Room Apple TV",
                    "credentials": "..."
                },
                {
                    "id": "masterbedroom",
                    "name": "Master Bedroom Apple TV",
                    "credentials": "..."
                }
            ],
            "hideWelcomeMessage": true,
            "showDefaultSwitches": true,
            "defaultSwitchesIncludeATVName": true,
            "showPairSwitches": false
 }

**Comment by NorthernMan54** [comment]
I saw that you raised a ticket with homebridge-apple-tv, are you seeing doubles in the home app?

**Comment by hroman73** [comment]
Yes in both...I noticed right after opening the issue with yours...

**Comment by hroman73** [comment]
I also noticed in the home app that it’s not actually double one has both names appended:

Sleep (Living Room Apple TV)

Sleep (Living Room Apple TV) (Master Bedroom Apple TV)

Strange...I will shorten the names though, it is annoying to give such long winded commands...I configured this while at work and didn’t test things fully

**Comment by NorthernMan54** [comment]
I have never tested Alexa with 2 Apple TV’s so I’m not sure it will work correctly the first time.   Fingers crossed

**Comment by hroman73** [comment]
i shortened the names to tv1 and tv2 and still the same:

Sleep (TV1)
Sleep (TV1)(TV2)

This is on both the Alexa and the Homekit side...I'm going to assume this is a homebridge-apple-tv issue and not a homebridge-alexa issue.

**Comment by NorthernMan54** [comment]
Yes, it is definitely on the homebridge-Apple-tv side.

**Comment by hroman73** [comment]
okay so i figured out that with multiple apple tv's the "showDefaultSwitches": true will mess things up. i defined each one and now i'm able to see the switches as intended. thank you for being so responsive.
