### ISSUE TITLE
Fan state

### ISSUE THREAD

**Issue by hroman73** [NorthernMan54/homebridge-alexa#128]
When I power on the fan via siri i can see that the fan is on as well as within the alexa app just as expected but if i power on the fan via alexa it will change to on then off within 2 seconds and with Siri she does't see its on at all.

**Comment by hroman73** [comment]
Nothing in the log but getswitchstate true...I can turn on debug to see if there is more info

**Comment by NorthernMan54** [comment]
Yes please do

**Comment by hroman73** [comment]
i enabled debug from the docker...i'm not sure if its working because i still see the same set of logs:

getSwitchState: true but the app shows its off

it works perfectly from homekit app but alexa app is not accepting the true and the app stay on

**Comment by NorthernMan54** [comment]
Okay, which plugin is controlling your fan?

**Comment by hroman73** [comment]
It’s handled by my broadlink rm pro via homebridge-broadlink-rm plugin

**Comment by NorthernMan54** [comment]
I thought I could spot something wacky in the plugin itself but saw nothing, can you share the logs from when you are controlling the fan?  Both with Alexa and Siri

Tks
