### ISSUE TITLE
Cant link homebridge.cloudwatch.net account with homebridge alexa skill

### ISSUE THREAD

**Issue by Sanani555** [NorthernMan54/homebridge-alexa#129]
Hi, i Cant link homebridge.cloudwatch.net account with homebridge alexa skill. Alexa app says "we were unable to link the skill at this time". Tried it a few times now. what am i doing wrong? thx
Nip

**Comment by NorthernMan54** [comment]
What country/region/language are you?

Also can you share a screen shot of the error.

Tks

**Comment by Sanani555** [comment]
Germany/German

![fehler](https://user-images.githubusercontent.com/13527341/45737400-011ba680-bbee-11e8-948d-e99637d94b2f.png)

**Comment by NorthernMan54** [comment]
I’m out of the country until Sunday, without access to the detailed logs etc.  Could you try again on Sunday, and let me know afterwards, and also send the time in GMT from your attempt so I can look at the logs in detail at that time.

Tks

**Comment by b2un0** [comment]
try it with your Laptop/Desktop directly under http://alexa.amazon.de with deactivated (!) PopUp Blocker.
