### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SzilagyiR** [NorthernMan54/homebridge-alexa#13]
Hi!

I already used Homebridge, and install it the special version to use it with Alexa.
Now it wont start:

```
pi@raspberrypi:~ $ sudo homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
/usr/local/lib/node_modules/homebridge/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n2/build/curve.node
 → /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n2/build/Debug/curve.node
 → /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n2/build/Release/curve.node
 → /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n2/out/Debug/curve.node
 → /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n2/Debug/curve.node
 → /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n2/out/Release/curve.node
 → /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n2/Release/curve.node
 → /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n2/build/default/curve.node
 → /usr/local/lib/node_modules/homebridge/node_modules/curve25519-n2/compiled/7.8.0/linux/arm/curve.node
    at bindings (/usr/local/lib/node_modules/homebridge/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/curve25519-n2/index.js:1:96)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/encryption.js:5:18)

```

**Comment by NorthernMan54** [comment]
This error is related to the more recent version of homebridge I'm using as the underpinnings for this.   And I took a look at the homebridge issue log and saw this.

https://github.com/nfarina/homebridge/issues/962

It could also be caused by having homebridge installed twice.  If you enter 

which homebridge

What does the output say?

**Comment by SzilagyiR** [comment]
Hi!

which homebridge says: /usr/local/bin/homebridge

NODE version v7.8.0
NPM version: 5.0.3

Trying `sudo npm install -g bindings`, no error massage, but the error is the same.

Trying ```
cd /usr/local/lib/node_modules/homebridge/node_modules/ed25519
sudo node-gyp BUILDTYPE=Release rebuild
```
I gave this error:
```
In file included from ../src/ed25519.cc:4:0:
../../nan/nan.h:326:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
ed25519.target.mk:122: recipe for target 'Release/obj.target/ed25519/src/ed25519.o' failed
make: *** [Release/obj.target/ed25519/src/ed25519.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/homebridge/node_modules/ed25519/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.4.50-v7+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "BUILDTYPE=Release" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/ed25519
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 

```

**Comment by NorthernMan54** [comment]
See the bottom of the error trace, it shows other versions of node.  Could you have 2 copies of node installed?  One from apt-get and the other manually?

**Comment by SzilagyiR** [comment]
Yes, it's possible, I tried to follow this tutorial: https://heathpaddock.com/2017/02/02/making-amazon-echo-alexa-sing-to-openhab2

**Comment by NorthernMan54** [comment]
Can you try the following

which node
which nodes
node -v
nodejs -v

If they are different you need to remove the apt-get version

sudo apt-get remove nodejs

**Comment by NorthernMan54** [comment]
That tutorial didn't include installing nodejs but other things.

**Comment by SzilagyiR** [comment]
Hi!

I reinstalled my backup, and install your homebridge version and all works fine! My Echo Dot works fine!

Thanks for your help!
