### ISSUE TITLE
error in debug

### ISSUE THREAD

**Issue by senadman** [NorthernMan54/homebridge-alexa#130]
all is ok except I get this in debug

 alexaLocal error { Error: connect ECONNREFUSED 35.169.132.61:8883
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '35.169.132.61',
  port: 8883 } +179ms
  alexaLocal offline +8ms

Any ideas??

**Comment by NorthernMan54** [comment]
That can be ignored

**Comment by senadman** [comment]
I think it has something to do with Alexa discovery. Homebridge is registered as a skill in the app (following your setup) but cannot discover devices. 

In debug all homebridge instances/ devices in home are discovered, only issue is the error as listed. 

I have homebridge-Alexa running as a separate instance/bridge, no errors there.

**Comment by NorthernMan54** [comment]
Please share a debug log, including when you ask Alexa to discover devices.

The earlier message is not an error, but an unused future enhancement, and can be ignored.

**Comment by senadman** [comment]
this is what I get in debug, when I ask Alexa app/website to discover devices it fails and has no log in the debug:

  alexaLocal Connecting to Homebridge Smart Home Skill +13ms
[2018-10-21 10:38:27] Homebridge is running on port 51706.
  alexaLocal error { Error: connect ECONNREFUSED 35.169.132.61:8883
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '35.169.132.61',
  port: 8883 } +711ms
  alexaLocal offline +19ms
  alexaHAP HAP Device discovered Alexa-9FF2 [ '192.168.1.36', 'fe80::3104:cfa6:bd31:eb07' ] +772ms
  alexaHAP HAP instance address: Alexa-9FF2 -> AA_22_3D_E3_CE_30.local -> 192.168.1.36 +3ms
  alexaHAP Homebridge instance discovered Alexa-9FF2 with 1 accessories +437ms
  alexaHAP HAP Device discovered 8 Gym-6D77 [ '192.168.1.8', 'fe80::82ee:73ff:feb0:1932' ] +743ms
  alexaHAP HAP instance address: 8 Gym-6D77 -> EB_BE_90_42_EF_43.local -> 192.168.1.8 +1ms
  alexaHAP HAP Device discovered 6 Side Path-475A [ '192.168.1.8', 'fe80::82ee:73ff:feb0:1932' ] +10ms
  alexaHAP HAP instance address: 6 Side Path-475A -> D8_27_55_5D_B1_EF.local -> 192.168.1.8 +1ms
  alexaHAP HAP Device discovered 5 Poolside-2BAE [ '192.168.1.8', 'fe80::82ee:73ff:feb0:1932' ] +6ms
  alexaHAP HAP instance address: 5 Poolside-2BAE -> E3_94_B0_44_F8_CD.local -> 192.168.1.8 +1ms
  alexaHAP HAP Device discovered IPCameras-4A14 [ '192.168.1.8', 'fe80::82ee:73ff:feb0:1932' ] +7ms
  alexaHAP HAP instance address: IPCameras-4A14 -> C3_22_3D_E3_CE_30.local -> 192.168.1.8 +0ms
  alexaHAP HAP Device discovered 3 Front Yard-3878 [ '192.168.1.8', 'fe80::82ee:73ff:feb0:1932' ] +6ms
  alexaHAP HAP instance address: 3 Front Yard-3878 -> 09_D5_55_FD_64_9B.local -> 192.168.1.8 +1ms
  alexaHAP HAP Device discovered 4 Pool-CC7F [ '192.168.1.8', 'fe80::82ee:73ff:feb0:1932' ] +6ms
  alexaHAP HAP instance address: 4 Pool-CC7F -> E9_32_5B_D4_A6_16.local -> 192.168.1.8 +1ms
  alexaHAP HAP Device discovered 2 Garage-A0AF [ '192.168.1.8', 'fe80::82ee:73ff:feb0:1932' ] +8ms
  alexaHAP HAP instance address: 2 Garage-A0AF -> DE_89_26_6F_90_92.local -> 192.168.1.8 +1ms
  alexaHAP HAP Device discovered 7 Courtyard-0A3A [ '192.168.1.8', 'fe80::82ee:73ff:feb0:1932' ] +6ms
  alexaHAP HAP instance address: 7 Courtyard-0A3A -> 61_22_6A_C8_79_44.local -> 192.168.1.8 +1ms
  alexaHAP HAP Device discovered 1 Intercom-15B8 [ '192.168.1.8', 'fe80::82ee:73ff:feb0:1932' ] +8ms
  alexaHAP HAP instance address: 1 Intercom-15B8 -> 9E_93_56_B4_C1_B6.local -> 192.168.1.8 +1ms
  alexaHAP HAP Device discovered CBus-Windows-3D36 [ '192.168.1.33', 'fe80::581f:a0e8:98c:a831' ] +6ms
  alexaHAP HAP instance address: CBus-Windows-3D36 -> EE_22_3D_E3_CE_30.local -> 192.168.1.33 +1ms
  alexaHAP HAP Device discovered ElkM1-E6BD [ '192.168.1.30', 'fe80::3fe1:23af:7205:b329' ] +6ms
  alexaHAP HAP instance address: ElkM1-E6BD -> CC_22_33_44_CE_30.local -> 192.168.1.30 +1ms
  alexaHAP HAP Device discovered CBus-Blinds-9EAB [ '192.168.1.32', 'fe80::2638:e6b9:f48:1bbc' ] +8ms
  alexaHAP HAP instance address: CBus-Blinds-9EAB -> AA_BB_3D_E3_CE_30.local -> 192.168.1.32 +1ms
  alexaHAP HAP Device discovered CBus-Lights-5AE4 [ '192.168.1.31', 'fe80::33c0:3fcc:9f9d:1889' ] +7ms
  alexaHAP HAP instance address: CBus-Lights-5AE4 -> AA_11_BB_33_BB_30.local -> 192.168.1.31 +1ms
  alexaHAP Homebridge instance discovered 8 Gym-6D77 with 1 accessories +73ms
  alexaHAP Homebridge instance discovered 6 Side Path-475A with 1 accessories +4ms
  alexaHAP Homebridge instance discovered 5 Poolside-2BAE with 1 accessories +4ms
  alexaHAP Homebridge instance discovered IPCameras-4A14 with 1 accessories +5ms
  alexaHAP Homebridge instance discovered 3 Front Yard-3878 with 1 accessories +4ms
  alexaHAP Homebridge instance discovered 4 Pool-CC7F with 1 accessories +4ms
  alexaHAP Homebridge instance discovered 2 Garage-A0AF with 1 accessories +4ms
  alexaHAP Homebridge instance discovered 7 Courtyard-0A3A with 1 accessories +4ms
  alexaHAP Homebridge instance discovered 1 Intercom-15B8 with 1 accessories +4ms
  alexaHAP Homebridge instance discovered CBus-Blinds-9EAB with 35 accessories +144ms
  alexaHAP Homebridge instance discovered CBus-Windows-3D36 with 29 accessories +11ms
  alexaHAP Homebridge instance discovered ElkM1-E6BD with 68 accessories +34ms
  alexaHAP Homebridge instance discovered CBus-Lights-5AE4 with 87 accessories +29ms
  alexaLocal reconnect +3s
  alexaLocal connect command/senadman/# +524ms
  alexaHAP Ending Homebridge instance discovery +49s

**Comment by NorthernMan54** [comment]
Looking at this, everything looks good with your plugin install, and homebridge instance discovery.

When I looked over on the server side I see this

senadman	Sat Oct 20 2018 07:44:13 GMT+0000 (UTC)	Sat Oct 20 2018 07:44:13 GMT+0000 (UTC)	0	Sat Oct 20 2018 07:44:13 GMT+0000 (UTC)	0


It shows that you have created an account correctly on the webs set, but have yet to link your Alexa account to the Homebridge-Alexa skill, and discover devices.  On the Alexa app on your phone, please ensure you have found the homebridge smart home skill and linked it to your account, then discover devices

PS In the above line, the two zeros are message counters, first being messages from Amazon to your account, and the second being messages back to Amazon from the plugin.  And the dates are, sign up date, last Amazon message and last plugin message

Here is a sample from someone else who signed up after you today

XXXXXX	Sat Oct 20 2018 10:57:45 GMT+0000 (UTC)	Sat Oct 20 2018 23:51:25 GMT+0000 (UTC)	2392	Sat Oct 20 2018 23:51:26 GMT+0000 (UTC)	2370

**Comment by senadman** [comment]
I think I'm doing the right thing with the account. The homebridge skill has and was linked, I have re-linked it and tried also. When I try and discover it complains "there was an error discovering your devices".

![img_1445](https://user-images.githubusercontent.com/38054092/47262541-d4cdaf80-d536-11e8-92be-0b965c17b7fb.jpg)
![img_1448](https://user-images.githubusercontent.com/38054092/47262547-deefae00-d536-11e8-8929-235ae99aab10.jpg)

is there any port forwarding etc required?

**Comment by NorthernMan54** [comment]
I would to like to look at the homeskill server logs at the same time as you attempt discovery.  Can you contact me on slack?

Tks

PS No port forwarding etc required.

**Comment by NorthernMan54** [comment]
Also what region / country are you physically in, and where is your Alexa registered/setup against?

**Comment by senadman** [comment]
In Australia, how do I get to you through slack

**Comment by senadman** [comment]
Australia, whats the best way to get you on slack?

**Comment by NorthernMan54** [comment]
Details on signing up for slack are here

https://github.com/nfarina/homebridge#community

What I want to see in the logs, is the following

1 - Unlink the smarthome skill
2 - Relink smarthome Skill
3 - Discover devices

I think something is happening on the Amazon side, as you are in Australia, but have a US account ( that’s my working theory ) and the discover devices request never leaves the amazon cloud and connects to my Skill.

I have seen similar issues with other users from the Far East, but then a few days later it just starts working again for them.

**Comment by senadman** [comment]
I probably should have asked first, do I need to have an Alexa device ie dot etc on the network for this to discover or can discovery be via website without Alexa device - because I don’t have an Alexa device atm.

**Comment by NorthernMan54** [comment]
Unfortunately I don’t know for sure about that scenario, as I have an Alexa device, but I can recall someone else in a similar situation then they bought an Alexa and it started working.  So I’m thinking likely not

**Comment by senadman** [comment]
Well I can confirm that this is correct. I have since purchased an Alexa device and it discovered all of my 160 devices straight away, very impressive. Is it possible to control Home app automations and scenes?

**Comment by NorthernMan54** [comment]
Sorry, Direct control of home automations and home app scenes is not feasible.  Home automations and scenes are not visible to homebridge, and without that visibility I can’t share them with Alexa.  But I have heard of people using the dummy switch plugin and automations to fake it.

They used the dummy switch to trigger an automation, that controlled a scene.  Now which exact plugin they used I don’t recall, but I think it was dummy switch.

I’m very glad it is working for you, and I will include your issue regarding owning an Alexa to the known issues list.
