### ISSUE TITLE
no new devices discovered

### ISSUE THREAD

**Issue by DaJansenGit** [NorthernMan54/homebridge-alexa#132]
I just saw that my homebridge instance isn't detecting any new homebridge devices. The already detected ones are working fine, so the connection seems to be fine. When doing a new search for devices with alexa i just get
`[AELXA] ERROR: HAP Discovery failed, please review config`
in the homebridge log.
In the troubleshooting section i found the hint for insecure mode, but insecure mode is enabled.

PS: Im running homebridge in a docker container and just added a second hue gateway (deconz) which works fine with homebridge. Don't know if there might be any connection between the things going on here

**Comment by NorthernMan54** [comment]
Docker has been problematic for some people, as the plugin communicates to all your homebridge instances and to the Alexa cloud.  It looks like the cloud communications are okay, but it is having challenges with your local homebridge instances.  That error message comes up when it failed to discover any local homebridge instances and extract an accessory list from them.  Earlier in the DEBUG log it may give further clues, but typically the challenge is getting the -I parameter set correctly and the PIN.  If your using docker, oznu’s docker containers have been tested with this.

**Comment by DaJansenGit** [comment]
Hey thanks for your fast reply. 
I’m using the container from oznu;) 
I just figured out that when in only use one device in the filter of home bridge Alexa plugin the discovery works fine so it might be the syntax that I’m using for multiple devices... 
Is the following correct? It’s a valid Json ...
"filter": ["Computer", "Mikrowelle"]

**Comment by DaJansenGit** [comment]
You are right, I expected the filter parameter to work different ;)
Thanks for your hint I created a second homebridge instance for Alexa and everything works fine. Thanks again!
