### ISSUE TITLE
Homebridge Alexa Skill in Italy

### ISSUE THREAD

**Issue by Marco1097** [NorthernMan54/homebridge-alexa#133]
Hi, i can't find the homebridge skill on the Italian store, are you planning to publish it in Italy too?
Have a nice day, 
Marco

**Comment by NorthernMan54** [comment]
I’m doing a beta right now for Italy, if you can send me your amazon account I can add you.  I prefer a direct message on slack, so your amazon account doesn’t end up being in an issue on GitHub

**Comment by NorthernMan54** [comment]
Still tbd, I need to submit it for certification, but was planning on adding a couple of features first.

**Comment by sommo** [comment]
I do not know yet if i will buy an echo but i'm interested in..there are some point to let me decide..
italian support is the first of the list, hope your plugin will gain this certification.
another point is the way to execute -I for homebridge instance (https://github.com/NorthernMan54/homebridge-alexa/issues/115)

**Comment by NorthernMan54** [comment]
I answered the -I question in the other Issue you raised.

**Comment by sommo** [comment]
Thank you

Inviato da iPhone

> Il giorno 27 ott 2018, alle ore 15:14, Northern Man <notifications@github.com> ha scritto:
> 
> I answered the -I question in the other Issue you raised.
> 
> 
>

**Comment by Marco1097** [comment]
> 
> I’m doing a beta right now for Italy, if you can send me your amazon account I can add you. I prefer a direct message on slack, so your amazon account doesn’t end up being in an issue on GitHub
> […](#)
> On Oct 23, 2018, at 6:36 PM, Marco ***@***.***> wrote: Hi, i can't find the homebridge skill on the Italian store, are you planning to publish it in Italy too? Have a nice day, Marco — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Echo should be delivered on 30/10, so I wanted to know how I can contact you for the beta since I can not create a Slack account, email or telegram could be fine if you give me your contact

**Comment by NorthernMan54** [comment]
For me preferred is slack, details on creating a slack account are here

https://github.com/NorthernMan54/homebridge-alexa#issues-questions-or-problems <https://github.com/NorthernMan54/homebridge-alexa#issues-questions-or-problems>

**Comment by dvd2000k** [comment]
I'm interested too. I can't create a slack account, it give me an error during registration (object object)...
How can I contact you?

**Comment by Marco1097** [comment]
> 
> 
> I'm interested too. I can't create a slack account, it give me an error during registration (object object)...
> How can I contact you?

Me and another guy are waiting for an answer here (https://github.com/nfarina/homebridge/issues/2049), I think they have to fix something in the invitation link

**Comment by NorthernMan54** [comment]
@Marco1097 @dvd2000k Since slack isn't working, you can email me directly at northern.man1@gmail.com

Also as part of publishing a skill in Italy, I need to provide Italian text for the skill, so was wondering if you could review the Italian here, and make sure it makes sense ?  I used google translate, so I expect it to be a bit wacky.

https://github.com/NorthernMan54/alexaAwsBackend/blob/master/skillPublish/skill_publish_text.md

**Comment by iShortOne** [comment]
@NorthernMan54 I’m interested too, how I can help you?
I will have the echo tomorrow!

**Comment by Marco1097** [comment]
> 
> 
> @Marco1097 @dvd2000k Since slack isn't working, you can email me directly at [northern.man1@gmail.com](mailto:northern.man1@gmail.com)
> 
> Also as part of publishing a skill in Italy, I need to provide Italian text for the skill, so was wondering if you could review the Italian here, and make sure it makes sense ? I used google translate, so I expect it to be a bit wacky.
> 
> https://github.com/NorthernMan54/alexaAwsBackend/blob/master/skillPublish/skill_publish_text.md

There is some wrong phrase, In my opinion it is better to write it this way
@iShortOne , @dvd2000k se siete italiani potreste controllare che non ci siano errori grammaticali e se secondo voi va bene, o se cambiereste qualcosa

**One Sentence Description**
Usa Alexa per controllare i tuoi dispositivi Homebridge

**Full Skill Description**
Questa Skill permette di controllare i proprio dispositivi Homebridge attraverso Amazon Alexa.

Per maggiori informazioni riguardanti Homebridge consultare https://homebridge.io.

Per maggiori informazioni riguardanti il controllo dei dispositivi Homebridge attraverso Amazon Alexa e l’installazione del plugin Homebridge-Alexa consultare https://github.com/NorthernMan54/homebridge-alexa.

I dispositivi Homebridge supportati includono:
luci, prese di corrente, interruttori, ventole e sensori di temperatura

**Comment by iShortOne** [comment]
> > @Marco1097 @dvd2000k Since slack isn't working, you can email me directly at [northern.man1@gmail.com](mailto:northern.man1@gmail.com)
> > Also as part of publishing a skill in Italy, I need to provide Italian text for the skill, so was wondering if you could review the Italian here, and make sure it makes sense ? I used google translate, so I expect it to be a bit wacky.
> > https://github.com/NorthernMan54/alexaAwsBackend/blob/master/skillPublish/skill_publish_text.md
> 
> There is some wrong phrase, In my opinion it is better to write it this way
> @iShortOne , @dvd2000k se siete italiani potreste controllare che non ci siano errori grammaticali e se secondo voi va bene, o se cambiereste qualcosa
> 
> **One Sentence Description**
> Usa Alexa per controllare i tuoi dispositivi Homebridge
> 
> **Full Skill Description**
> Questa Skill permette di controllare i propri dispositivi Homebridge attraverso Amazon Alexa.
> 
> Per maggiori informazioni riguardanti Homebridge consultare https://homebridge.io.
> 
> Per maggiori informazioni riguardanti il controllo dei dispositivi Homebridge attraverso Amazon Alexa e l’installazione del plugin Homebridge-Alexa consultare https://github.com/NorthernMan54/homebridge-alexa.
> 
> I dispositivi Homebridge supportati includono:
> luci, prese di corrente, interruttori, ventole e sensori di temperatura

Yes, I’m italian. It’s correct! There are some other way I can help you?

**Comment by Marco1097** [comment]
@iShortOne i think that if you sent an email to @NorthernMan54, he can add you to the beta

**Comment by NorthernMan54** [comment]
@Marco1097 @dvd2000k @iShortOne 

Tks for the input, I have updated the page

https://github.com/NorthernMan54/alexaAwsBackend/blob/master/skillPublish/skill_publish_text.md

**Comment by stefano-garzarella** [comment]
@NorthernMan54 I'm also interested in the beta. I'll send you an email!

**Comment by andreaconfa** [comment]
@NorthernMan54 i tried to write you via Slack but i’m hacking some problems. 
I received today my echo and i want to subscribe to the italian beta. My Amazon email is andreaconfalonieri@hotmail.com 
Thanks

**Comment by AdsoDaMelk** [comment]
@NorthernMan54 i  also tried to write you via Slack but i can't receive invite...
I'd like to subscribe to the italian beta too, now that i got my new echo dot. Can you please add roberto.squarci@gmail.com ?
Thanks a lot.

**Comment by NorthernMan54** [comment]
I have added yourself

**Comment by ragian** [comment]
@NorthernMan54 it seems there are some problems with slack.
This is my email to test for the italian.

**Comment by NorthernMan54** [comment]
Invite sent, good luck

**Comment by NorthernMan54** [comment]
I have just submitted the skill for certification with Amazon, this should take about a week. Fingers crossed

**Comment by dvd2000k** [comment]
Perfect! Thank you very much!

**Comment by maury77** [comment]
I want partecipate to beta 

I have homebridge With same device xiaomi and Amazon Echo

My mail si Maurizio.galandrino@gmail.com

**Comment by NorthernMan54** [comment]
As I have submitted the skill for certification I can not add further testers to the beta, sorry.  It should take about a week stay tuned

**Comment by sommo** [comment]
any feedback from the italian betatester ?I'm undecided whether to buy an echo spot... let us know how the plugin works with homekit device, thank you

**Comment by andreaconfa** [comment]
The plugin works very well. No problems detected.

Inviato da iPhone

Il giorno 5 nov 2018, alle ore 13:12, sommo <notifications@github.com<mailto:notifications@github.com>> ha scritto:


any feedback from the italian betatester ?I'm undecided whether to buy an echo spot... let us know how the plugin works with homekit device, thank you

**Comment by ragian** [comment]
I confirm, it is ok.


Il giorno lun 5 nov 2018 alle ore 13:17 andreaconfa <
notifications@github.com> ha scritto:

**Comment by NorthernMan54** [comment]
I'm going to close this, and for folks anxious about status, please watch the README page
