### ISSUE TITLE
Homebridge skill in Spain

### ISSUE THREAD

**Issue by nikosillo** [NorthernMan54/homebridge-alexa#134]
Hello
Next Tuesday Alexa is also launched in Spain, do you plan to launch the skill in Spanish? It would be great to have him
Great job, greetings!

**Comment by NorthernMan54** [comment]
Spain, Italy and India are in the backlog and will be a few weeks.  I was working on further enhancements prior to re-submitting for Amazon certification, and wanted to complete prior.  If you want access now, I can add yourself to the Beta and you will be to use it on launch.

**Comment by nikosillo** [comment]
ohh yes please, I would like to participate

**Comment by NorthernMan54** [comment]
To contact myself via slack, details are here

https://github.com/NorthernMan54/homebridge-alexa#issues-questions-or-problems <https://github.com/NorthernMan54/homebridge-alexa#issues-questions-or-problems>

**Comment by nikosillo** [comment]
I'm trying to get an invitation in the way indicated but it gives some kind of error, I have placed an incidence in the nfarina github ...

**Comment by NorthernMan54** [comment]
@nikosillo Since slack invites are broke, you can email directly at Northern.Man1@gmail.com

Also as part of publishing in Spain, I need to provide Spanish text, and was wondering if you review my spanish text for the skill

https://github.com/NorthernMan54/alexaAwsBackend/blob/master/skillPublish/skill_publish_text.md

I used Google translate for the spanish, so I figure it is likely a bit wacky

**Comment by nikosillo** [comment]
Perfect! I have sent a pull request with the modifications that make the most sense in Spanish

**Comment by NorthernMan54** [comment]
@nikosillo Tks very much I merged your pull request

https://github.com/NorthernMan54/alexaAwsBackend/blob/master/skillPublish/skill_publish_text.md

**Comment by NorthernMan54** [comment]
Tks

**Comment by oscarodb** [comment]
@NorthernMan54 

I have used the homebridge app with my Alexa devices in English and now that I can update alexa to Spanish I would like to continue using this skill. I can help with the translation or revise the texts. It would be a pleasure to participate in the beta phase.

Greetings,

**Comment by nikosillo** [comment]
Hello again
Since the devices arrived on Tuesday, I have been testing the skill. I must say that my homebridge is via Jeedom, easier to configure yet.
For now everything works fine. I miss the support for thermostats and cameras, but the rest of devices, for now, everything is fine.
Congratulations!
If there is anything I can contribute, please let me know

**Comment by NorthernMan54** [comment]
I’m glad to hear it is working great for you.

For helping, if your a coder I would gladly accept a pull request for thermostats or Camera’s.  Thermostats shouldn’t be that complex but cameras would have some complexity with the data stream requirements.

**Comment by NorthernMan54** [comment]
@nowindi To add yourself to the beta, I need your amazon id.  If look back in this issue, I posted my email address.

**Comment by nikosillo** [comment]
It's a shame, I'm not a programmer and I have little knowledge (the righteous), but I've commented on the Jeedom telegram group in Spanish in case someone wants to collaborate
And I apologize for my English, I must use Google translator :(

**Comment by NorthernMan54** [comment]
I have just submitted the skill for certification with Amazon, this should take about a week.  Fingers crossed

**Comment by NorthernMan54** [comment]
I'm closing this, please watch the README for current status.
