### ISSUE TITLE
Humidity sensor

### ISSUE THREAD

**Issue by Marco1097** [NorthernMan54/homebridge-alexa#135]
It would be nice to have humidity sensors as well as temperature sensors

**Comment by NorthernMan54** [comment]
Unfortunately Alexa doesn’t have a humidity sensor option.

**Comment by NorthernMan54** [comment]
Okay

**Comment by nixmeer** [comment]
Hello :) has anything changed by now and are humidity sensors supported by now?

**Comment by NorthernMan54** [comment]
I just checked and Humidity sensors still aren’t supported

https://developer.amazon.com/en-US/docs/alexa/device-apis/smart-home-general-apis.html
