### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by fazerize** [NorthernMan54/homebridge-alexa#136]
alexaLocal error { Error: connect ECONNREFUSED 35.169.132.61:8883
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1173:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '35.169.132.61',
  port: 8883 } +317ms
  alexaLocal offline +11ms

**Comment by nikosillo** [comment]
https://github.com/NorthernMan54/homebridge-alexa/blob/master/Troubleshooting.MD
