### ISSUE TITLE
Does homebridge-alexa work with homebridge-webos-tv?

### ISSUE THREAD

**Issue by MrRobotoGit** [NorthernMan54/homebridge-alexa#140]
Since we are still waiting skill approval for Italy (8 days today!) I'm curious to know if the alexa plugin can work with homebridge-webos-tv switches.

**Comment by NorthernMan54** [comment]
I took a quick look at the homebridge-webos-tv plugin, and it appears that it will work.  Each function on the TV appears to be mapped to HomeKit Switch, and HomeKit switches are supported.  For it to work seamlessly, you may need to create some routines to map natural language to the plugin’s switches.

**Comment by MrRobotoGit** [comment]
That’s great. Thank you.



> Il giorno 12 nov 2018, alle ore 00:40, Northern Man <notifications@github.com> ha scritto:
> 
> I took a quick look at the homebridge-webos-tv plugin, and it appears that it will work. Each function on the TV appears to be mapped to HomeKit Switch, and HomeKit switches are supported. For it to work seamlessly, you may need to create some routines to map natural language to the plugin’s switches.
> 
> 
> 
> 
>
