### ISSUE TITLE
Failed Amazon Smart Home Skill Certification 

### ISSUE THREAD

**Issue by NorthernMan54** [NorthernMan54/homebridge-alexa#141]
Issues with skill in Japanese (Japan)
___________________________________________________________________________________

1. One of the language variants of your skill includes functionality that is not yet available for Alexa in that locale. Please remove any unsupported functionality from the skill and resubmit your skill for certification.
 
~~Unsupported Functionality: Temperature sensor (温度センサー)
Language(s) Impacted: Japanese (JP)~~
 
___________________________________________________________________________________

Issues with skill in French (France)
___________________________________________________________________________________

1. The description displayed in the skill’s detail card must contain accurate information so users are well informed on how to use the skill.
 
Please change the information provided in the skill's details page as follows:
~~Actual: " Cette compétence permet d'accéder à vos appareils contrôlés par HomeBridge à partir de votre Amazon Alexa. "
Expected: " Cette skill permet d'accéder à vos appareils contrôlés par HomeBridge à partir de votre Amazon Alexa. "~~
 
Please see test case 3.2 from our Submission Checklist for guidance on skill descriptions.
 
___________________________________________________________________________________

Issues with skill in Spanish (Spain)
___________________________________________________________________________________

1. All customer facing example phrases presented either as example phrases or in the skill’s description must be in the same format as the sample utterances for the skill’s API.
 
~~First example phrase:
Actual : Alexa, enciende la lámpara de la sala
Expected: Alexa, enciende la lámpara de la sala de estar~~
 
~~Second example phrase:
Actual: Alexa, establece la lámpara de la sala de estar al 50 por ciento
Expected: Alexa, pon la sala de estar a la mitad de brillo~~
 
~~Third example phrase:
Actual: Alexa, apaga la lámpara de la sala
Expected: Alexa, apaga la lámpara de la sala de estar~~

For Smart Home skills, please see our Smart Home Publishing Guide for more guidance on creating example phrases for Smart Home skills.
 
2. The description displayed in the skill’s detail card must contain accurate information so users are well informed on how to use the skill.
 
~~Please modify the description as following:
Actual:"Esta habilidad permite el acceso a sus dispositivos controlados por HomeBridge desde su Amazon Alexa. "
Expected:"Esta skill permite el acceso a sus dispositivos controlados por HomeBridge desde su Amazon Alexa. "~~
 
~~Actual:"Los dispositivos homebridge compatibles incluyen:
Luces, puntos de venta, interruptores, ventiladores y sensores de temperatura."
Expected:"Los dispositivos homebridge compatibles incluyen:
luces, puntos de venta, interruptores, ventiladores y sensores de temperatura."~~
 
Please see test case 3.2 from our Submission Checklist for guidance on skill descriptions.
 
3. The skill’s description fails to capture all prerequisites needed for use of the skill. Please be sure to include all information needed for users to access the core functionality of the skill.
 
Please make sure that the description provides detailed information about the account linking process.
 
Please see test case 3.2 from our Submission Checklist for guidance on skill descriptions.
 
4. There are currently no online devices for the Smart Home and/or Video interaction model(s) associated with your test account when completing the device discovery step. There must be at least one device that is online, can be used for your Smart Home and/or Video interaction model(s), and is discoverable associated with your test account. This is required for our team to complete testing. Please ensure that the test devices are online 24/7 for the certification team to test.
 
~~Steps to Reproduce:~~
~~1. Enable the skill.
2. Use the credentials provided in the testing instructions
3. After a successful login, go to “Smart Home” Section in the Alexa app.
4. Tap on “Discover Devices” and wait for 20 sec. (attempted 3 times)
5. No online devices for your Smart Home or Video interaction model(s) are found.~~
 
Please see our Smart Home Publishing Guide for more guidance.
___________________________________________________________________________________

Issues with skill in Spanish (Mexico)
___________________________________________________________________________________

1. All customer facing example phrases presented either as example phrases or in the skill’s description must be in the same format as the sample utterances for the skill’s API.
 
~~First example phrase:
Actual : Alexa, enciende la lámpara de la sala
Expected: Alexa, enciende la lámpara de la sala de estar~~
 
~~Second example phrase:
Actual: Alexa, establece la lámpara de la sala de estar al 50 por ciento
Expected: Alexa, pon la sala de estar a la mitad de brillo~~
 
~~Third example phrase:
Actual: Alexa, apaga la lámpara de la sala
Expected: Alexa, apaga la lámpara de la sala de estar~~
 
For Smart Home skills, please see our Smart Home Publishing Guide for more guidance on creating example phrases for Smart Home skills.
 
2. The description displayed in the skill’s detail card must contain accurate information so users are well informed on how to use the skill.
 
Please modify the description as following:
~~Actual:"Esta habilidad permite el acceso a sus dispositivos controlados por HomeBridge desde su Amazon Alexa. "
Expected:"Esta skill permite el acceso a sus dispositivos controlados por HomeBridge desde su Amazon Alexa. "~~
 
~~Actual:"Los dispositivos homebridge compatibles incluyen: Luces, puntos de venta, interruptores, ventiladores y sensores de temperatura."
Expected:"Los dispositivos homebridge compatibles incluyen: luces, puntos de venta, interruptores, ventiladores y sensores de temperatura."~~
 
Please see test case 3.2 from our Submission Checklist for guidance on skill descriptions.
 
3. The skill’s description fails to capture all prerequisites needed for use of the skill. Please be sure to include all information needed for users to access the core functionality of the skill.
 
Please make sure that the description provides more details about the account linking process. Also, note that some of the links provided in the description with the intructions does not function properly.
 
Please see test case 3.2 from our Submission Checklist for guidance on skill descriptions.
 
4. There are currently no online devices for the Smart Home and/or Video interaction model(s) associated with your test account when completing the device discovery step. There must be at least one device that is online, can be used for your Smart Home and/or Video interaction model(s), and is discoverable associated with your test account. This is required for our team to complete testing. Please ensure that the test devices are online 24/7 for the certification team to test.
 
~~Steps to Reproduce:~~
~~1. Enable the skill.
2. Use the credentials provided in the testing instructions
3. After a successful login, go to “Smart Home” Section in the Alexa app.
4. Tap on “Discover Devices” and wait for 20 sec. (attempted 3 times)
5. No online devices for your Smart Home or Video interaction model(s) are found.~~
 
Please see our Smart Home Publishing Guide for more guidance.

**Comment by NorthernMan54** [comment]
I have updated the skill text based on Amazon's feedback, https://github.com/NorthernMan54/alexaAwsBackend/blob/master/skillPublish/skill_publish_text.md

Before submission I need to provide some text for #3 in Spanish

**Comment by NorthernMan54** [comment]
@nikosillo Can you take a look at the comments from Amazon

**Comment by nikosillo** [comment]
There is something wrong, this is not the Spanish text that I sent you, I changed the term "habilidad" for the original Skill that is not translated in Spanish, also the term for prise is "enchufe", not "punto de venta" that has nothing to do ... it's strange...

Please consider this change, it is valid for Spanish ES and MX

-----------------------------
Esta Skill permite controlar sus dispositivos asociados a Homebridge con Amazon Alexa.

Para ampliar información sobre Homebridge, consulte https://homebridge.io.

Para controlar sus dispositivos de Homebridge a través de Amazon Alexa es necesario que instale el plugin Homebridge-Alexa" tal y como se describe en  https://github.com/NorthernMan54/homebridge-alexa

Los dispositivos en Homebridge compatibles son:

Luces, enchufes, interruptores, ventiladores y sensores de temperatura.
----------------------------------

**Comment by nikosillo** [comment]
Another consideration, example 2 does not work with Alexa in Spanish as suggested Amazon.... The correct term (tested) would be:

"Alexa, pon la sala de estar al 50 por ciento"

**Comment by MrRobotoGit** [comment]
Since amazon rejected the skill is it possible to jump into the beta testing now?

**Comment by NorthernMan54** [comment]
Yes it is possible

**Comment by MrRobotoGit** [comment]
Where can I find your email? 


> Il giorno 15 nov 2018, alle ore 17:16, Northern Man <notifications@github.com> ha scritto:
> 
> Yes it is possible 
>

**Comment by MrRobotoGit** [comment]
Ok, I sent you a message on Slack

Thank you 

> Il giorno 15 nov 2018, alle ore 17:16, Northern Man <notifications@github.com> ha scritto:
> 
> Yes it is possible 
>

**Comment by NorthernMan54** [comment]
@nikosillo Tks for the changes, I have updated the skill description text in the beta based on the feedback.  Could you check if what you see in the app is okay?  Tks

If you think there are any issues, can you let me know.  Tks

https://github.com/NorthernMan54/alexaAwsBackend/blob/master/skillPublish/skill_publish_text.md

**Comment by nikosillo** [comment]
I see it well, now let's cross our fingers :)

**Comment by sherazan** [comment]
Hi, waiting Amazon feedback, is it possible test beta version of plugin for the Italian Skills?
Thanks

**Comment by NorthernMan54** [comment]
I’m going to resubmit in a couple of hours, if you can get me your amazon logon Id, I can add yourself

**Comment by sherazan** [comment]
Thanks! my logon id registered in the Alexa plugin istructions, is: vzlgdu

**Comment by NorthernMan54** [comment]
Sorry, I need your amazon logon Id, and not the homebridge-alexa id

**Comment by sherazan** [comment]
Sorry: vzlgdu@gmail.com

Inviato da Posta per Windows 10

Da: Northern Man
Inviato: venerdì 16 novembre 2018 14:21
A: NorthernMan54/homebridge-alexa
Cc: sherazan; Comment
Oggetto: Re: [NorthernMan54/homebridge-alexa] Failed Amazon Smart Home SkillCertification (#141)

Sorry, I need your amazon logon Id, and not the homebridge-alexa id

**Comment by sherazan** [comment]
Should I reload something to test Alexa speaking in Italian?

Inviato da Posta per Windows 10

Da: Northern Man
Inviato: venerdì 16 novembre 2018 14:27
A: NorthernMan54/homebridge-alexa
Cc: sherazan; Comment
Oggetto: Re: [NorthernMan54/homebridge-alexa] Failed Amazon Smart Home SkillCertification (#141)

I just added yourself

**Comment by NorthernMan54** [comment]
To be honest I don’t know. If your using the beta version with Spanish language turned on, I thought it should work.

**Comment by sherazan** [comment]
Hi, let me better understand: you have loaded my amazon userid in the beta version of your plugin; I haven’t’ changed anything in my configuration, I’ve only restarted homberidge with the Alexa plugin and my Alexa echo dot. Now if I ask to Alexa to turn on a light (using the name that I see in HomeKit and using Italian language) Alexa answares that it doesn’t find a light with this name…



> Il giorno 16 nov 2018, alle ore 16:35, Northern Man <notifications@github.com> ha scritto:
> 
> To be honest I don’t know. If your using the beta version with Spanish language turned on, I thought it should work.
>

**Comment by sherazan** [comment]
In the previous post you wrote: "...If your using the beta version..." but I'm using the version downloaded from github... where is the beta version?

**Comment by NorthernMan54** [comment]
For the homebridge-alexa plugin itself, it is not language aware at all and there is is only one version and no beta version of the plugin.  In the Amazon Smart Skill cloud there are two versions of the plugin, the first version is the production version ( being used by a lot of people ) but it is only available in certain countries/languages.  There is a Beta version of the skill, ( used by about 30 people ), that has several more languages available.

When I was mentioning beta version i was referring to this, a couple of early adopters have multiple amazon accounts in several countries, and for some of them they have one account in the beta, and on account in the production skill.

But with that said, I think this is getting confused by translation.

With the homebridge-alexa skill, both the plugin and the backend code, it is not language aware.  So any language challenges are coming either from Amazon or based on your device naming. I just pass your device names from homebridge to Alexa without changing them, so if they work for Siri, they should work for Alexa.


PS With the beta and adding additional languages it was only a skill documentation change on my part, I did not need to change the code in the plugin or the skill backend at all

**Comment by sherazan** [comment]
Hi, thanks very much for this clarify.

I executed more tests, but I can confirm that if I ask (in Italian) to Siri to manage a device, asking Alexa to manage the same device name, the answers from Alexa is “sorry I can’t find this device”…



> Il giorno 17 nov 2018, alle ore 15:33, Northern Man <notifications@github.com> ha scritto:
> 
> For the homebridge-alexa plugin itself, it is not language aware at all and there is is only one version and no beta version of the plugin. In the Amazon Smart Skill cloud there are two versions of the plugin, the first version is the production version ( being used by a lot of people ) but it is only available in certain countries/languages. There is a Beta version of the skill, ( used by about 30 people ), that has several more languages available.
> 
> When I was mentioning beta version i was referring to this, a couple of early adopters have multiple amazon accounts in several countries, and for some of them they have one account in the beta, and on account in the production skill.
> 
> But with that said, I think this is getting confused by translation.
> 
> With the homebridge-alexa skill, both the plugin and the backend code, it is not language aware. So any language challenges are coming either from Amazon or based on your device naming. I just pass your device names from homebridge to Alexa without changing them, so if they work for Siri, they should work for Alexa.
> 
> 
> PS With the beta and adding additional languages it was only a skill documentation change on my part, I did not need to change the code in the plugin or the skill backend at all
> 
>

**Comment by NorthernMan54** [comment]
@sherazan Can we open this in a separate issue as this is not related to the skill submission, and prior to opening the issue can you collect the logs and share them in the issue.  It seems that your setup is having issues

**Comment by sherazan** [comment]
Yes, I will do. Thanks

**Comment by capilus** [comment]
I live in Spain I would like to participate in beta test many thanks I could help you for translations have family in Mexico too

**Comment by capilus** [comment]
Also have lot off xiaomi products can help you for the correct comands in Spanish

**Comment by NorthernMan54** [comment]
If you send me your Amazon login ID, I can you add your self to the beta.

For the translations, the text is available here

https://github.com/NorthernMan54/alexaAwsBackend/blob/master/skillPublish/skill_publish_text.md <https://github.com/NorthernMan54/alexaAwsBackend/blob/master/skillPublish/skill_publish_text.md>

**Comment by capilus** [comment]
My user is juanpcabello@gmail.com
Many thanks

**Comment by NorthernMan54** [comment]
@capilus I Just added yourself

**Comment by filippocobelli** [comment]
Hi
Can you add my id to your beta tester for Italian market?

**Comment by NorthernMan54** [comment]
@filippocobelli Unfortunately I resubmitted a couple of hours ago.   Please stay tuned
