### ISSUE TITLE
Lock and Security System support

### ISSUE THREAD

**Issue by silentcossack** [NorthernMan54/homebridge-alexa#146]
Awesome job with this plugin! Works smoothly on first try. However, 3 of my homebridge defined devices are not being returned by the plugin for alexa to discover. Two locks and my security system. All three work fine in HomeKit through homebridge homeseer plugin. Not sure if this is an issue or not, but from other issues I read on here it looks like locks should be supported through homebridge. Thanks.

**Comment by NorthernMan54** [comment]
At the present time the plugin does not support locks, and security systems.  I took a look and Alexa does support locks but not security systems.  As I don't actually have a lock in my setup I won't be able to support for it, but would gladly accept a pull request adding support for locks.

**Comment by silentcossack** [comment]
Ok thanks for clarifying. Lot's of code to get through as I have not looked at it yet, but perhaps i'll dive into it after my current project slows down.

**Comment by NorthernMan54** [comment]
Tks
