### ISSUE TITLE
Certification failed again

### ISSUE THREAD

**Issue by NorthernMan54** [NorthernMan54/homebridge-alexa#150]
Just received this back from Amazon.  I haven't had time to digest it yet.  The Japan language one I can understand, as the description was lacking.  But the Spanish one I don't get as it was the same text for both spain and mexico.

The published text is here https://github.com/NorthernMan54/alexaAwsBackend/blob/master/skillPublish/skill_publish_text.md

> Thank you for the recent submission of your skill, Homebridge. 
> Your skill submission has failed the certification process. We’ve included a description of the issue(s) and steps to reproduce below. Please address these and resubmit the skill at your earliest convenience.
> 
> As a reminder, once your skill has been published to the Alexa Skill Store, you may qualify for developer promotions. For more information on the promotions for Alexa developers, see the terms and conditions for your country: US, UK, Germany, Japan, Australia, India, France, and Canada.
> 
> Issues with skill in Japanese (Japan)
> 
> ___________________________________________________________________________________
> 
> The skill description does not cover all the prerequisites necessary to use the skill. Make sure to include all the information necessary for the users to access the skill's core functions. 
>  
> Please see test case 3.2 from our Submission Checklist for guidance on skill descriptions.
https://developer.amazon.com/ja/docs/custom-skills/define-skill-metadata.html
> ___________________________________________________________________________________
> 
> Issues with skill in Spanish (Mexico)
> 
> ___________________________________________________________________________________
> 
> The description displayed in the skill’s detail card must contain accurate information so users are well informed on how to use the skill.
>  
> Actual: Esta Skill está dirigida a usuarios de Homebridge y requiere la instalación y configuración de la plataforma Homebridge y el complemento Homebridge-Alexa.
>  
> Expected: Esta skill permite el acceso a sus dispositivos controlados por HomeBridge desde su Amazon Alexa. Para utilizar esta skill, necesitas instalar y configurar la plataforma Homebridge y el complemento Homebridge-Alexa.
>  
> Please see test case 3.2 from our Submission Checklist for guidance on skill descriptions.

This is 3.2 https://developer.amazon.com/docs/custom-skills/functional-testing-for-a-custom-skill.html#cert-skill-description

**Comment by nikosillo** [comment]
Laugh? Cry?
Maybe the one who certifies the language in Mexico understands things differently. The text that Amazon suggests is correct, just as the Spanish text now seems correct. If it's just that change then I think you can put the suggested

**Comment by NorthernMan54** [comment]
@nikosillo I agree, so I'm will make that update and re-submit again.  But as the Japanese needs more effort, I'm going to remove Japan from the submission and try for it separately.

For the folks watching, I will be able to add more people to the Beta until Sunday AM Eastern Time.  If you can reach out to me via slack, I will be able to add yourself. 

For slack access, you can get a slack invite from the Homebridge readme, here

https://github.com/nfarina/homebridge#community

And you can find me in the channel #HAP-Alexa

**Comment by metalmarco** [comment]
Hi, and thank you very much for your effort. 
I’m also waiting for Italian language support. 
My question is: if I become part of the beta, it doesn’t mean that I will find the Skill in the Alexa Store, right?

**Comment by NorthernMan54** [comment]
Correct, for the BETA you will receive an email from Amazon with a LINK to enable the BETA.

**Comment by juanmito** [comment]
Hi.

Does it mean that I can install the skill for Alexa in spanish (ES)? I couldn't find it. Or, if any language fail, all the skills fails?
BTW, if you need help for spanish skill, just ping me :)

Thanks for your work!

**Comment by marcodesantis71** [comment]
HI

But for Italian language is passed or not? Can I join to BETA program for Italian?

**Comment by NorthernMan54** [comment]
@marcodesantis71 Sure just reach out to me over Slack

@juanmito You are correct, if one language in the submission fails, they all fail ;-(. In regards to help, I have been working with Kike, so I think I'm good that way.  If you want to try the Beta, please reach out over Skype

**Comment by marcodesantis71** [comment]
@NorthernMan54 ok. I do it.

**Comment by NorthernMan54** [comment]
Everyone, I just submitted for Amazon certification again.  Fingers crossed, that the third time gets thru

**Comment by NorthernMan54** [comment]
@giannimp As I'm in certification, adding more people to the beta is closed.  Fingers crossed it passes.

**Comment by giannimp** [comment]
Ok, fingers crossed !!!

**Comment by giannimp** [comment]
Hi, news??????

**Comment by NorthernMan54** [comment]
Not yet, I’m giving them another week

**Comment by rounakkumar** [comment]
How about English IN?

**Comment by NorthernMan54** [comment]
English India is also part of the current certification

**Comment by NorthernMan54** [comment]
Latest from amazon

_Dear Developer,

Thank you very much for having developed and submitted an Alexa Skill in Spanish (MX) for certification. Like you, many other developers have enthusiastically welcomed the possibility of developing Skills in Spanish (MX) for Alexa. The Alexa certification team is working hard to process all of the Skills that have been submitted. We appreciate your patience and, while waiting for your skill to be tested, we encourage you to continue developing new Skills for Alexa.

Thank you,

Alexa Skills Team_

**Comment by NorthernMan54** [comment]
And just received this from Amazon

> 
> Thank you for the recent submission of your skill, Homebridge. 
> Your skill submission has failed the certification process. We’ve included a description of the issue(s) and steps to reproduce below. Please address these and resubmit the skill at your earliest convenience.
> 
> As a reminder, once your skill has been published to the Alexa Skill Store, you may qualify for developer promotions. For more information on the promotions for Alexa developers, see the terms and conditions for your country: US, UK, Germany, Japan, Australia, India, France, and Canada.
> 
>  
> 
> Issues with skill in Japanese:
> 
> ___________________________________________________________________________________
> 
> Issues observed on devices without display (Echo, Echo Dot)
> 
> FunctionalTesting
> 
> 1. The description displayed in the skill’s detail card must contain accurate information so users are well informed on how to use the skill.
> 
>  
> 
> Actual1:
> 
> この技術の設定はホームブリッジのユーザーにして、必要なホームブリッジ　とホームブリッジ-―アレクサ のプラグインのインストールと設定の説明です。
> 
>  
> 
> Expected1:
> 
> このスキルはホームブリッジのユーザーを対象としており、ホームブリッジとホームブリッジ―アレクサのプラグインのインストールと設定が必要です。
> 
>  
> 
>  
> 
> Actual2:
> 
> アレクサアプリに「スキルの启用」のボタンを押してください
> 
>  
> 
> Expected2:
> 
> アレクサアプリの「有効にする」ボタンを押してください
> 
>  
> 
> Please see test case 3.2 from our Submission Checklist for guidance on skill descriptions.
> 
> ___________________________________________________________________________________
> 
> Issues with skill in Spanish (Mexico):
> 
> ___________________________________________________________________________________
> 
> Issues observed on devices without display (Echo, Echo Dot)
> 
> 
> 
> FunctionalTesting
> 
> 1. All customer facing example phrases presented either as example phrases or in the skill’s description must be in the same format as the sample utterances for the skill’s API.
> 
>  
> 
> Actual: Alexa, enciende la lámpara de la sala de estar
> 
> Expected: Alexa, enciende la lámpara del salón
> 
>  
> 
> Actual: Alexa, pon la lámpara de la sala de estar al 50 por ciento
> 
> Expected: Alexa, sube la lámpara del salón al 50 por ciento
> 
>  
> 
> Actual: Alexa, apaga la lámpara de la sala de estar
> 
> Expected: Alexa, apaga la lámpara del salón
> 
> ___________________________________________________________________________________
> 
> Issues with skill in Spanish (Spain):
> 
> ___________________________________________________________________________________
> 
> Issues observed on devices without display (Echo, Echo Dot)
> 
> FunctionalTesting
> 
> 1. All customer facing example phrases presented either as example phrases or in the skill’s description must be in the same format as the sample utterances for the skill’s API.
> 
>  
> 
> Actual: Alexa, enciende la lámpara de la sala de estar
> 
> Expected: Alexa, enciende la lámpara del salón
> 
>  
> 
> Actual: Alexa, pon la lámpara de la sala de estar al 50 por ciento
> 
> Expected: Alexa, sube la lámpara del salón al 50 por ciento
> 
>  
> 
> Actual: Alexa, apaga la lámpara de la sala de estar
> 
> Expected: Alexa, apaga la lámpara del salón
> 
> ___________________________________________________________________________________
>

**Comment by NorthernMan54** [comment]
Also, as certification failed again.  The BETA is open for new users, so if you are interested, please reach out to me via Slack, and I will add you.

**Comment by giannimp** [comment]
Hi, thank you, how do I connect with you via Slack ? Help me please

Inviato da iPhone

**Comment by rounakraj** [comment]
Can you please give beta-access to krounak@icloud.com. Also, what is your slack ID

**Comment by giannimp** [comment]
My slack is: gimprota76.slack.com
Can you send the invite me , because I don’t use slack

Inviato da iPhone

**Comment by NorthernMan54** [comment]
Slack details are here

https://github.com/NorthernMan54/homebridge-alexa/blob/master/README.md#issues-questions-or-problems

**Comment by giannimp** [comment]
Sorry, bus I can not login to channel slack
https://homebridgeteam.slack.com/messages/hap-alexa/
Help me

**Comment by NephilimDM** [comment]
Hi NorthernMan54,
can you at least submit the Italian skill that doesn't seem to have any problems?
Thanks!

**Comment by rounakkumar** [comment]
Please send beta invite to krounak@icloud.com. Not able to slack you

**Comment by giannimp** [comment]
Please send beta invite to gianni.improta@tin.it italian skill 
Thank you !!!

**Comment by ilvolodel** [comment]
Hello please send me an invite: filippo.savarese@gmail.com
And thanks for your job!

**Comment by SCLavender** [comment]
Japanese translation here.
I  hope this translation will be helpful to you. 

[JP.txt](https://github.com/NorthernMan54/homebridge-alexa/files/2702375/JP.txt)

**Comment by NorthernMan54** [comment]
@ilvolodel @giannimp You should receive an email from Amazon shortly with instructions on how to enable

**Comment by NorthernMan54** [comment]
@SCLavender Tks very much for that

The full text for all languages is here

https://github.com/NorthernMan54/alexaAwsBackend/blob/master/skillPublish/skill_publish_text.md

As I don't understand Japanese, and am just using google translate, does what I have work, or should I make some changes?

**Comment by SCLavender** [comment]
@NorthernMan54 

Sorry, I'm github noob.

So I don't know how to use pull request.

[Here](https://gist.github.com/SCLavender/f89ec4faa69bfbf0dd6088eda6d6bf08) is translated skill_publish_text.md

**Comment by iomax** [comment]
@NorthernMan54 
I'd like to partecipate to Italian beta skill.
Slack noob here, could you invite me ?

**Comment by Mgc499** [comment]
Hi, I have 3 active Homebridge, is possible to partecipate to the italian beta test?

**Comment by iomax** [comment]
@NorthernMan54 
Please use massimo.romagnoli@gmail.com.

**Comment by iomax** [comment]
Got it ! Thanks !

**Comment by NephilimDM** [comment]
https://github.com/NorthernMan54

Meanwhile i'd like to participate to the italian beta skill. Please send me an invite to andrea.cioli@gmail.com

Thx!

**Comment by NorthernMan54** [comment]
@NephilimDM I have added yourself, expect an email from Amazon shortly

**Comment by NephilimDM** [comment]
> @NephilimDM I have added yourself, expect an email from Amazon shortly

Thanks!

**Comment by XattSPT** [comment]
Can I participate on spanish beta? Gerard.ricart@gmail.com

**Comment by NorthernMan54** [comment]
@XattSPT I have added yourself, please expect an email from Amazon shortly

**Comment by samuele4414** [comment]
Can you please send me an invite to samuele.despo@gmail.com
Thank you!!!

**Comment by NorthernMan54** [comment]
@samuele4414 I have added yourself, please expect an email from Amazon shortly

**Comment by psp95** [comment]
Please invite me beta tester lcdsrn@gmail.com thank you

**Comment by NorthernMan54** [comment]
@psp95 You should receive an email from Amazon shortly

**Comment by NorthernMan54** [comment]
I have re-submitted to Amazon for certification again, fingers crossed they are okay with the Spanish and Japanese text this time.

**Comment by samuele4414** [comment]
I have some problem with the pin
I tried to change it but the error is the same : alexa state response
homebridge Auth failed invalid pin 03145155


Il giorno mer 26 dic 2018, 15:38 Northern Man <notifications@github.com> ha
scritto:

**Comment by NorthernMan54** [comment]
@samuele4414 Please open a new issue for this on GitHub.

PS You only need the PIN parameter if you had changed the PIN on your homebridge installations
