### ISSUE TITLE
External server?

### ISSUE THREAD

**Issue by nixmeer** [NorthernMan54/homebridge-alexa#153]
Hello :)
This is a general question and maybe it’s not in the right place here. 

Why do you use an external server? If I get it right, Alexa communicates to the cloudwatch server which will then communicate to Homebridge in order to get the action to be done. 

I guess there is a good reason for this, but it’s also a potential risk, isn’t it? Having a company such as Apple or Amazon communicating out of my LAN, is fine with me since these companies invest millions in safety even tough it doesn’t mean there is NO risk at all. Any other smaller company or project is a higher risk. 

So is there no way to expose my Homebridge devices to Alexa locally?

Best from Germany :)

**Comment by nixmeer** [comment]
Hey again,

first of all: yes I know, and it’s the same with me. I do it just for fun and that’s why I try to avoid digging hole in my network. I just wanted to know the reason. 

So the local Alexa interface does not offer color options etc.?

**Comment by NorthernMan54** [comment]
When I last used it, it did not have colour options.
