### ISSUE TITLE
ERROR: HAP Discovery failed, please review config

### ISSUE THREAD

**Issue by djrams10** [NorthernMan54/homebridge-alexa#156]
Hello, I'm french, I use a synology server and run the plugin with the docker application. how can I access the DEBUG log with docker on synology? I have this error that comes up every time I want to do a device search with the alexa application "ERROR: HAP Discovery failed, please review config". i mainly use siri with homekit, then i make compatible my homekit devices with alexa? If so, can you explain the procedure? thank you so much

**Comment by NorthernMan54** [comment]
I was working with someone else with the same challenge, and they found this screen to enable insecure mode

![image](https://user-images.githubusercontent.com/19808920/50384331-68d00a80-0691-11e9-89ee-85dcf7e906f5.png)

**Comment by djrams10** [comment]
hello, thank you it's settled.
