### ISSUE TITLE
'HeaterCooler' devices

### ISSUE THREAD

**Issue by NephilimDM** [NorthernMan54/homebridge-alexa#157]
Hi @NorthernMan54 ,

I'm running the Italian beta version of the skill (thank you!). It works very well.
I have a problem with an accessory that is not recognized related to the homebridge plugin: https://github.com/SebastianOsinski/HomebridgePluginSamsungAirConditioner.
It seems that this plugin sets the device as 'HeaterCooler' which is the correct one for air conditioners. Could you add support to this type of device as well? I would really appreciate it! 

Nephilim

**Comment by NorthernMan54** [comment]
@NephilimDM I can add this to the backlog of future enhancements, but it could be a while before I can try wiring this.  If you're up to it, I would gladly accept a pull request with this added as an enhancement.

**Comment by NephilimDM** [comment]
@NorthernMan54 
I can try but I'm not very experienced about Node and HAP. I'd probably take a lot longer than you anyway.
Thanks a lot anyway.

**Comment by NorthernMan54** [comment]
@NephilimDM It looks like I have some free time coming up, so will be able to look into this further shortly.  And in prep for this, I need a dump from homebridge of the HomeKit devices, so I can build a parser between HomeKit and Alexa.  Can you run this against your homebridge instance with the heater/cooler device attached, and attached the output to this.  Tks

`curl -X PUT http://127.0.0.1:51826/accessories --header "Content-Type:Application/json" --header "authorization: 031-45-154"`

PS This command line assumes that you are running this from the command line of the machine running homebridge, that homebridge is running on the default port 51826 and the PIN is default.  You may need to adjust it to match your environment.

**Comment by NephilimDM** [comment]
@NorthernMan54 Hi, I'm really sorry for the delay in my response! I'm very happy that you can work a little on this implementation. I ran the script you gave me, the output is attached [data.log](https://github.com/NorthernMan54/homebridge-alexa/files/2856126/data.log)

I hope this will help and thank you again!

**Comment by NorthernMan54** [comment]
Thanks for that it looks like it will be straight forward.  But have some questions around mapping of the HomeKit interface to the Alexa Interface.  The HomeKit interface looks like this


Service.HeaterCooler = function(displayName, subtype) {
  Service.call(this, displayName, '000000BC-0000-1000-8000-0026BB765291', subtype);

  // Required Characteristics
  this.addCharacteristic(Characteristic.Active); 
  this.addCharacteristic(Characteristic.CurrentHeaterCoolerState);
  this.addCharacteristic(Characteristic.TargetHeaterCoolerState);
  this.addCharacteristic(Characteristic.CurrentTemperature);

  // Optional Characteristics
  this.addOptionalCharacteristic(Characteristic.LockPhysicalControls);
  this.addOptionalCharacteristic(Characteristic.Name);
  this.addOptionalCharacteristic(Characteristic.SwingMode);
  this.addOptionalCharacteristic(Characteristic.CoolingThresholdTemperature);
  this.addOptionalCharacteristic(Characteristic.HeatingThresholdTemperature);
  this.addOptionalCharacteristic(Characteristic.TemperatureDisplayUnits);
  this.addOptionalCharacteristic(Characteristic.RotationSpeed);


And I need to map these into the Alexa API, which is documented here.

https://developer.amazon.com/docs/smarthome/build-smart-home-skills-for-hvac-devices.html

To map these over, which HomeKit characteristics do you actively use, and would make sense to add to Alexa.  And if you could look at the Alexa documents and see what makes sense on the Alexa side

This was the first pass thru my translator logic, after telling the translator to recognize Heater/Cooler.  It mapped over the temperature sensor and the “Rotation Speed”, but the rotation speed was mapped to just a %.

{
    "event": {
        "header": {
            "namespace": "Alexa.Discovery",
            "name": "Discover.Response",
            "payloadVersion": "3",
            "messageId": "1bd5d003-31b9-476f-ad03-71d471922820"
        },
        "payload": {
            "endpoints": [
                {
                    "endpointId": "Q0M6MjI6M0Q6RTM6Q0U6MzAtcGFyc2VUZXN0LVtvYmplY3QgT2JqZWN0XS1DYW1lcmEtMDAwMDAwQkMtMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx",
                    "friendlyName": "Camera",
                    "description": "parseTest Camera Other 000000BC",
                    "manufacturerName": "[object Object]",
                    "displayCategories": [
                        "OTHER"
                    ],
                    "cookie": {
                        "AdjustPowerLevel": "{\"host\":\"127.0.0.1\",\"port\":51826,\"aid\":2,\"iid\":17}",
                        "SetPowerLevel": "{\"host\":\"127.0.0.1\",\"port\":51826,\"aid\":2,\"iid\":17}",
                        "ReportState": "[{\"interface\":\"Alexa.TemperatureSensor\",\"host\":\"127.0.0.1\",\"port\":51826,\"aid\":2,\"iid\":13},{\"interface\":\"Alexa.PowerLevelController\",\"host\":\"127.0.0.1\",\"port\":51826,\"aid\":2,\"iid\":17}]"
                    },
                    "capabilities": [
                        {
                            "type": "AlexaInterface",
                            "interface": "Alexa",
                            "version": "3"
                        },
                        {
                            "type": "AlexaInterface",
                            "interface": "Alexa.TemperatureSensor",
                            "version": "3",
                            "properties": {
                                "supported": [
                                    {
                                        "name": "temperature"
                                    }
                                ],
                                "proactivelyReported": false,
                                "retrievable": true
                            }
                        },
                        {
                            "type": "AlexaInterface",
                            "interface": "Alexa.PowerLevelController",
                            "version": "3",
                            "properties": {
                                "supported": [
                                    {
                                        "name": "powerLevel"
                                    }
                                ],
                                "proactivelyReported": false,
                                "retrievable": true
                            }
                        }
                    ]
                },

**Comment by NephilimDM** [comment]
Hi @NorthernMan54 , thanks for your reply.
I'm really sorry but I can't understand what kind of help you need. On the Alexa side I think that all the HVAC device capabilities (Alexa.TemperatureSensor, Alexa.PowerController, Alexa.PercentageController) may be implemented.  Regarding the rotation speed it seems that both Alexa and Homekit use a percentage, even in this case I think I have not understood the problem, sorry.

**Comment by NephilimDM** [comment]
Hi @NorthernMan54 ,
any news?

Thanks!

**Comment by NorthernMan54** [comment]
I have completed initial integration and you should be able to turn on/off the unit and control the fan speed.  As I don't have a unit I'm not able to test or validate that it is working correctly.

To test this, you will need to install the Events version of the plugin,  and instructions are available here.

https://github.com/NorthernMan54/homebridge-alexa/blob/event/README.md#beta-test-for-sending-events-to-alexa-and-using-in-routines

**Comment by NephilimDM** [comment]
Hi @NorthernMan54 ,
thank you very much.
I'm testing the plugin a bit and the on/off seem to work, but I can't control the fan speed. What are the voice commands to use?

**Comment by NorthernMan54** [comment]
It should be ‘Alexa, set name to 30’, but I don’t control the wording at all.  If you watch the logs you should see the homebridge commands come from Alexa to homebridge.  And if you enable DEBUG mode it gets really verbose on the details.

There is a possibility I have the mapping wrong, so as you try different phrases keep that in mind.

**Comment by NephilimDM** [comment]
Hi @NorthernMan54 ,
‘Alexa, set name to 30’ seems to work for the fan. Perhaps it is appropriate, however, to be able to specify that you are setting the fan, such as 'Alexa sets the fan of name to x'. Is this possible? Is there any news about being able to set the mode and temperature? 
Thanks a lot!!!

**Comment by NorthernMan54** [comment]
You can track progress with issue #201

**Comment by NorthernMan54** [comment]
@NephilimDM I have the first draft of Heater / Cooler control ready for testing.  The following features should be fully enabled

1 - Changing modes between HEAT, COOL, AUTO and OFF
2 - Set a new target temperature

As I don't have a heater/cooler device to test this, you will need to test this for me. If you could let me know how it works, much appreciated.

For these changes I'm using a special version of the plugin to ensure that everything works okay prior to releasing to the world, so please follow these instructions to install the special version.

https://github.com/NorthernMan54/homebridge-alexa/issues/201#issuecomment-480307601

Also, if you have not updated your plugin version recently, I made a major change about a month ago that causes all devices to be lost, and you need to discover again.  Please take this into account before installing.

**Comment by NephilimDM** [comment]
Hi @NorthernMan54 ,
I'll be happy to test these devices for you. I have already installed the special version of the plugin. Could you tell me which voice commands are for setting the mode and temperature?

Thanks.

**Comment by NorthernMan54** [comment]
Substitute house for your device name

“Alexa – set house to heat”
“Alexa – set house to cool”
“Alexa – set house to auto”
“Alexa – set house to off”
Alexa – set house to 20 degrees”
