### ISSUE TITLE
Esp homekit firmware Support ?? 

### ISSUE THREAD

**Issue by wroblewski6** [NorthernMan54/homebridge-alexa#159]
Did you succeed to ad homekit devices with firmware like this or similar https://github.com/RavenSystem/esp-homekit-devices ?? 
No I have my Sonoffs on Tasmota and Mqtt and there ale cinneteced by Homebridge so I can use your plugin to connect them with Alexa but I want change firmware to RavenCore to make it more simple homekitvdevice but I will loose ability to connect to Alexa . 
Or maybe there is another way to connect homekit devices to Alexa but with out Homebridge ??

**Comment by NorthernMan54** [comment]
Sorry, I haven’t been looking at those devices at all.  But they should support my plugin if they can support “Insecure Mode” like homebridge.  That would be a question for the developers of that firmware.

**Comment by NorthernMan54** [comment]
@wroblewski6 I have asked the question

https://github.com/RavenSystem/esp-homekit-devices/issues/309
