### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SzilagyiR** [NorthernMan54/homebridge-alexa#16]
Hi!

The Homebridge with Alexa working fine, but 
after a few days it stops with this error massage:

/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:381
    var mac = hueDevices[lightid].uniqueid.split(':');
                                 ^

TypeError: Cannot read property 'uniqueid' of undefined
    at _getOiid (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:381:34)
    at hueToHK (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:168:14)
    at Object.handleHueApi (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:55:24)
    at HAPServer._handleHueApi (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:923:7)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:220:47)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by NorthernMan54** [comment]
Try rediscovering all your homebridge devices from Alexa.   I believe she is calling the wrong address for a device.  When you discover devices, homebridge shares the internal address of all the devices to Alexa, and Alexa uses this address when controls a device.   The homebridge internal address changes when you add devices, and some platform plugins may do this internally.

If this doesn't resolve the issue, please turn on DEBUG logging and share the section of log around the error. In a debug log, there would logging of the actual call from Alexa to homebridge that caused the error.

**Comment by SzilagyiR** [comment]
Thanks for the hint, I'm testing it!

If it happens again, how can I turn on debug logging?

**Comment by NorthernMan54** [comment]
When you start homebridge add DEBUG=* to the start of the command line. Ie

DEBUG=* homebridge

**Comment by SzilagyiR** [comment]
It happens again, I trying debuge mode!

**Comment by SzilagyiR** [comment]
It stops again, here is the log:

`
     reachable: true },
  type: 'Dimmable light',
  name: 'Use Pc',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:28:09-00',
  swversion: '66012040' } +2ms
  hue device response 29 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Watch Tv',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:29:09-00',
  swversion: '66012040' } +1ms
  hue device response 33 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Play Bluetooth Music',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:33:09-00',
  swversion: '66012040' } +2ms
  hue device response 30 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Play Movie',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:30:09-00',
  swversion: '66012040' } +1ms
  hue device response 31 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Pause Movie',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:31:09-00',
  swversion: '66012040' } +2ms
  hue device response 32 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Stop Movie',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:32:09-00',
  swversion: '66012040' } +2ms
  hue device response 2 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Pc',
  modelid: 'LWB004',
  manufacturername: 'Microsoft',
  uniqueid: 'cc:22:3d:e3:ce:30:02:09-00',
  swversion: '66012040' } +1ms
  hue device response 3 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Micro Pc',
  modelid: 'LWB004',
  manufacturername: 'Microsoft',
  uniqueid: 'cc:22:3d:e3:ce:30:03:09-00',
  swversion: '66012040' } +2ms
  hue device response 5 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'gate',
  modelid: 'LWB004',
  manufacturername: 'ITEAD',
  uniqueid: 'cc:22:3d:e3:ce:30:05:09-00',
  swversion: '66012040' } +2ms
  hue device response 16 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'door',
  modelid: 'LWB004',
  manufacturername: 'ITEAD',
  uniqueid: 'cc:22:3d:e3:ce:30:16:09-00',
  swversion: '66012040' } +1ms
  hue device response 7 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'heater',
  modelid: 'LWB004',
  manufacturername: 'ITEAD',
  uniqueid: 'cc:22:3d:e3:ce:30:07:09-00',
  swversion: '66012040' } +2ms
  hue device response 4 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'stand lamp',
  modelid: 'LWB004',
  manufacturername: 'ITEAD',
  uniqueid: 'cc:22:3d:e3:ce:30:04:09-00',
  swversion: '66012040' } +2ms
  hue device response 15 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'night lamp',
  modelid: 'LWB004',
  manufacturername: 'ITEAD',
  uniqueid: 'cc:22:3d:e3:ce:30:15:09-00',
  swversion: '66012040' } +2ms
  hue device response 17 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'living room',
  modelid: 'LWB004',
  manufacturername: 'ITEAD',
  uniqueid: 'cc:22:3d:e3:ce:30:17:09-00',
  swversion: '66012040' } +1ms
  hue device response 18 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'upstairs',
  modelid: 'LWB004',
  manufacturername: 'ITEAD',
  uniqueid: 'cc:22:3d:e3:ce:30:18:09-00',
  swversion: '66012040' } +2ms
  hue device response 14 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'bedroom',
  modelid: 'LWB004',
  manufacturername: 'ITEAD',
  uniqueid: 'cc:22:3d:e3:ce:30:14:09-00',
  swversion: '66012040' } +2ms
  EventedHTTPServer [::ffff:192.168.0.20] HTTP Response is finished +4ms
  EventedHTTPServer [::ffff:192.168.0.20] New connection from client +4ms
  EventedHTTPServer [::ffff:192.168.0.20] HTTP server listening on port 44717 +1ms
  EventedHTTPServer [::ffff:192.168.0.20] HTTP request: /api/pkBovaHrTjmiUwGqH7m6q7eecgD3VXVrR3BPE1qK/groups/0 +16ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /api/pkBovaHrTjmiUwGqH7m6q7eecgD3VXVrR3BPE1qK/groups/0 +0ms
  EventedHTTPServer [::ffff:192.168.0.20] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:192.168.0.20] HTTP request: /api/pkBovaHrTjmiUwGqH7m6q7eecgD3VXVrR3BPE1qK/lights/11 +253ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /api/pkBovaHrTjmiUwGqH7m6q7eecgD3VXVrR3BPE1qK/lights/11 +0ms
  hue hueDevices not cached { '2': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'Pc',
     modelid: 'LWB004',
     manufacturername: 'Microsoft',
     uniqueid: 'cc:22:3d:e3:ce:30:02:09-00',
     swversion: '66012040' },
  '3': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'Micro Pc',
     modelid: 'LWB004',
     manufacturername: 'Microsoft',
     uniqueid: 'cc:22:3d:e3:ce:30:03:09-00',
     swversion: '66012040' },
  '4': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'stand lamp',
     modelid: 'LWB004',
     manufacturername: 'ITEAD',
     uniqueid: 'cc:22:3d:e3:ce:30:04:09-00',
     swversion: '66012040' },
  '5': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'gate',
     modelid: 'LWB004',
     manufacturername: 'ITEAD',
     uniqueid: 'cc:22:3d:e3:ce:30:05:09-00',
     swversion: '66012040' },
  '7': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'heater',
     modelid: 'LWB004',
     manufacturername: 'ITEAD',
     uniqueid: 'cc:22:3d:e3:ce:30:07:09-00',
     swversion: '66012040' },
  '14': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'bedroom',
     modelid: 'LWB004',
     manufacturername: 'ITEAD',
     uniqueid: 'cc:22:3d:e3:ce:30:14:09-00',
     swversion: '66012040' },
  '15': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'night lamp',
     modelid: 'LWB004',
     manufacturername: 'ITEAD',
     uniqueid: 'cc:22:3d:e3:ce:30:15:09-00',
     swversion: '66012040' },
  '16': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'door',
     modelid: 'LWB004',
     manufacturername: 'ITEAD',
     uniqueid: 'cc:22:3d:e3:ce:30:16:09-00',
     swversion: '66012040' },
  '17': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'living room',
     modelid: 'LWB004',
     manufacturername: 'ITEAD',
     uniqueid: 'cc:22:3d:e3:ce:30:17:09-00',
     swversion: '66012040' },
  '18': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'upstairs',
     modelid: 'LWB004',
     manufacturername: 'ITEAD',
     uniqueid: 'cc:22:3d:e3:ce:30:18:09-00',
     swversion: '66012040' },
  '19': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'Learn',
     modelid: 'LWB004',
     manufacturername: 'Broadlink',
     uniqueid: 'cc:22:3d:e3:ce:30:19:09-00',
     swversion: '66012040' },
  '20': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'Scan Frequency',
     modelid: 'LWB004',
     manufacturername: 'Broadlink',
     uniqueid: 'cc:22:3d:e3:ce:30:20:09-00',
     swversion: '66012040' },
  '21': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'TV',
     modelid: 'LWB004',
     manufacturername: 'Broadlink',
     uniqueid: 'cc:22:3d:e3:ce:30:21:09-00',
     swversion: '66012040' },
  '22': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'Receiver',
     modelid: 'LWB004',
     manufacturername: 'Broadlink',
     uniqueid: 'cc:22:3d:e3:ce:30:22:09-00',
     swversion: '66012040' },
  '23': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'Media Player',
     modelid: 'LWB004',
     manufacturername: 'Broadlink',
     uniqueid: 'cc:22:3d:e3:ce:30:23:09-00',
     swversion: '66012040' },
  '25': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'Shutdown Movie',
     modelid: 'LWB004',
     manufacturername: 'Broadlink',
     uniqueid: 'cc:22:3d:e3:ce:30:25:09-00',
     swversion: '66012040' },
  '26': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'Shutdown',
     modelid: 'LWB004',
     manufacturername: 'Broadlink',
     uniqueid: 'cc:22:3d:e3:ce:30:26:09-00',
     swversion: '66012040' },
  '27': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'Watch a Movie',
     modelid: 'LWB004',
     manufacturername: 'Broadlink',
     uniqueid: 'cc:22:3d:e3:ce:30:27:09-00',
     swversion: '66012040' },
  '28': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'Use Pc',
     modelid: 'LWB004',
     manufacturername: 'Broadlink',
     uniqueid: 'cc:22:3d:e3:ce:30:28:09-00',
     swversion: '66012040' },
  '29': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'Watch Tv',
     modelid: 'LWB004',
     manufacturername: 'Broadlink',
     uniqueid: 'cc:22:3d:e3:ce:30:29:09-00',
     swversion: '66012040' },
  '30': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'Play Movie',
     modelid: 'LWB004',
     manufacturername: 'Broadlink',
     uniqueid: 'cc:22:3d:e3:ce:30:30:09-00',
     swversion: '66012040' },
  '31': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'Pause Movie',
     modelid: 'LWB004',
     manufacturername: 'Broadlink',
     uniqueid: 'cc:22:3d:e3:ce:30:31:09-00',
     swversion: '66012040' },
  '32': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'Stop Movie',
     modelid: 'LWB004',
     manufacturername: 'Broadlink',
     uniqueid: 'cc:22:3d:e3:ce:30:32:09-00',
     swversion: '66012040' },
  '33': 
   { state: 
      { on: false,
        bri: 0,
        hue: 0,
        sat: 0,
        effect: 'none',
        ct: 0,
        alert: 'none',
        reachable: true },
     type: 'Dimmable light',
     name: 'Play Bluetooth Music',
     modelid: 'LWB004',
     manufacturername: 'Broadlink',
     uniqueid: 'cc:22:3d:e3:ce:30:33:09-00',
     swversion: '66012040' } } 11 +1ms
  hue device response 19 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Learn',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:19:09-00',
  swversion: '66012040' } +101ms
  hue device response 20 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Scan Frequency',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:20:09-00',
  swversion: '66012040' } +1ms
  hue device response 21 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'TV',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:21:09-00',
  swversion: '66012040' } +2ms
  hue device response 22 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Receiver',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:22:09-00',
  swversion: '66012040' } +1ms
  hue device response 23 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Media Player',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:23:09-00',
  swversion: '66012040' } +1ms
  hue device response 25 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Shutdown Movie',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:25:09-00',
  swversion: '66012040' } +1ms
  hue device response 26 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Shutdown',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:26:09-00',
  swversion: '66012040' } +1ms
  hue device response 27 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Watch a Movie',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:27:09-00',
  swversion: '66012040' } +2ms
  hue device response 28 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Use Pc',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:28:09-00',
  swversion: '66012040' } +1ms
  hue device response 29 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Watch Tv',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:29:09-00',
  swversion: '66012040' } +1ms
  hue device response 33 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Play Bluetooth Music',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:33:09-00',
  swversion: '66012040' } +1ms
  hue device response 30 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Play Movie',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:30:09-00',
  swversion: '66012040' } +1ms
  hue device response 31 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Pause Movie',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:31:09-00',
  swversion: '66012040' } +1ms
  hue device response 32 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Stop Movie',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:32:09-00',
  swversion: '66012040' } +1ms
  hue device response 2 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Pc',
  modelid: 'LWB004',
  manufacturername: 'Microsoft',
  uniqueid: 'cc:22:3d:e3:ce:30:02:09-00',
  swversion: '66012040' } +0ms
  hue device response 3 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Micro Pc',
  modelid: 'LWB004',
  manufacturername: 'Microsoft',
  uniqueid: 'cc:22:3d:e3:ce:30:03:09-00',
  swversion: '66012040' } +1ms
  hue device response 5 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'gate',
  modelid: 'LWB004',
  manufacturername: 'ITEAD',
  uniqueid: 'cc:22:3d:e3:ce:30:05:09-00',
  swversion: '66012040' } +1ms
  hue device response 16 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'door',
  modelid: 'LWB004',
  manufacturername: 'ITEAD',
  uniqueid: 'cc:22:3d:e3:ce:30:16:09-00',
  swversion: '66012040' } +1ms
  hue device response 7 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'heater',
  modelid: 'LWB004',
  manufacturername: 'ITEAD',
  uniqueid: 'cc:22:3d:e3:ce:30:07:09-00',
  swversion: '66012040' } +0ms
  hue device response 4 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'stand lamp',
  modelid: 'LWB004',
  manufacturername: 'ITEAD',
  uniqueid: 'cc:22:3d:e3:ce:30:04:09-00',
  swversion: '66012040' } +1ms
  hue device response 15 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'night lamp',
  modelid: 'LWB004',
  manufacturername: 'ITEAD',
  uniqueid: 'cc:22:3d:e3:ce:30:15:09-00',
  swversion: '66012040' } +1ms
  hue device response 17 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'living room',
  modelid: 'LWB004',
  manufacturername: 'ITEAD',
  uniqueid: 'cc:22:3d:e3:ce:30:17:09-00',
  swversion: '66012040' } +0ms
  hue device response 18 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'upstairs',
  modelid: 'LWB004',
  manufacturername: 'ITEAD',
  uniqueid: 'cc:22:3d:e3:ce:30:18:09-00',
  swversion: '66012040' } +1ms
  hue device response 14 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'bedroom',
  modelid: 'LWB004',
  manufacturername: 'ITEAD',
  uniqueid: 'cc:22:3d:e3:ce:30:14:09-00',
  swversion: '66012040' } +1ms
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:381
    var mac = hueDevices[lightid].uniqueid.split(':');
                                 ^

TypeError: Cannot read property 'uniqueid' of undefined
    at _getOiid (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:381:34)
    at hueToHK (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:168:14)
    at Object.handleHueApi (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:55:24)
    at HAPServer._handleHueApi (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:923:7)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:220:47)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
`

**Comment by NorthernMan54** [comment]
Tks for that log

When error happened, Alexa was trying to control or inquire about device number 11.  And homebridge no longer had a device number 11.

I can add trapping to no longer crash when this happens, but I can't see why device 11 disappeared for homebridge.  I suspect one of the plugins deleted and re added it's devices causing this.  Do any of your devices constantly get moved to the 'default room'?  Do you know what device was number 11?  Alexa would would have known about device 11 since the last discover devices.

**Comment by NorthernMan54** [comment]
I have added logic to catch that error and it should no longer crash.  Please reinstall and try again.

**Comment by SzilagyiR** [comment]
The number 11 is the bedroom light, it is work well. The default room is empty in Home app.


Thanks for your help, I try to reinstall and check in if error happens again!

**Comment by NorthernMan54** [comment]
In the log you sent, ‘bedroom’ is number 14.   Was it 11 earlier in the log?

**Comment by SzilagyiR** [comment]
No, I just make a mistatake, sorry!

**Comment by SzilagyiR** [comment]
How can I remove existing homebridge, to reinstall vith the new one on Raspberry Pi?

"sudo npm uninstall homebridge" gives error

**Comment by NorthernMan54** [comment]
You should be able to just reinstall overtop of the existing.  No need to remove

**Comment by SzilagyiR** [comment]
Thanks, I updeted it, and testing!
