### ISSUE TITLE
http window blinds not visible for alexa

### ISSUE THREAD

**Issue by aschmidt74** [NorthernMan54/homebridge-alexa#161]
I use the plugin 'homebridge-http-window-blinds v2.5.3', which works fine on the homekit side, and all switches work in homekit and in the alexa-world via your bridge - thank you for that!
However those blinds aren't translated into bulbs or anything else.
Nothing unusual in the logs.

**Comment by NorthernMan54** [comment]
Thats odd, as they are included in the code.  I don't have any so I can't test them, but they are included and should show up as Type Other.

Can you share a DEBUG log?

**Comment by aschmidt74** [comment]
all log messages containing alexa:

[2019-1-4 20:08:14] Loaded plugin: homebridge-alexa
[2019-1-4 20:08:14] Registering platform 'homebridge-alexa.Alexa'
[2019-1-4 20:08:19] [Alexa] Initializing Alexa platform...
[2019-1-4 20:08:19] [Alexa] homebridge-alexa v0.1.70, node v11.4.0, homebridge v0.4.45
Fri, 04 Jan 2019 19:08:19 GMT alexaHAP Starting Homebridge instance discovery
Fri, 04 Jan 2019 19:08:19 GMT alexaLocal Connecting to Homebridge Smart Home Skill
Fri, 04 Jan 2019 19:08:19 GMT alexaHAP HAP Device discovered tado Internet Bridge IBxxx [ '192.168.6.xxx', 'fe80::21b:c507:3115:e3ed' ]
Fri, 04 Jan 2019 19:08:19 GMT alexaHAP HAP instance address: tado Internet Bridge IBxxxx -> tadoBridgeIBxxxx.local -> 192.168.6.xxx
Fri, 04 Jan 2019 19:08:19 GMT alexaHAP HAP Device discovered Philips hue - 0140DB [ '192.168.6.xxx', 'fe80::eeb5:faff:fe01:40db' ]
Fri, 04 Jan 2019 19:08:19 GMT alexaHAP HAP instance address: Philips hue - 0140DB -> MP16-HUE.local -> 192.168.6.xxx
Fri, 04 Jan 2019 19:08:19 GMT alexaLocal error { Error: connect ECONNREFUSED 35.169.132.61:8883
Fri, 04 Jan 2019 19:08:19 GMT alexaLocal offline
Fri, 04 Jan 2019 19:08:19 GMT alexaHAP HAP Discover failed Philips hue - 0140DB http://192.168.6.xxx:8080 error code 470
Fri, 04 Jan 2019 19:08:21 GMT alexaHAP HAP Device discovered Homebridge-CAD8 [ '192.168.6.xxx',
Fri, 04 Jan 2019 19:08:21 GMT alexaHAP HAP instance address: Homebridge-CAD8 -> CC_22_3D_E3_CE_30.local -> 192.168.6.xxx
Fri, 04 Jan 2019 19:08:21 GMT alexaHAP Homebridge instance discovered Homebridge-CAD8 with 34 accessories
Fri, 04 Jan 2019 19:08:24 GMT alexaLocal reconnect
Fri, 04 Jan 2019 19:08:25 GMT alexaLocal connect command/aschmidt74/#
Fri, 04 Jan 2019 19:09:14 GMT alexaHAP Ending Homebridge instance discovery
Fri, 04 Jan 2019 19:09:14 GMT alexaHAP HAP Discover failed tado Internet Bridge IBxxx http://192.168.6.xxx:3000 error ESOCKETTIMEDOUT

**Comment by NorthernMan54** [comment]
Humm that looks okay

Can you share the output from this?  This generates an extract of all your accessories from homebridge.  I want to run it thru the code to see why it doesn't work with your blinds

`curl -X PUT http://127.0.0.1:51826/accessories --header "Content-Type:Application/json" --header "authorization: 031-45-154"`

**Comment by NorthernMan54** [comment]
Found the problem, a defect in homebridge-http-window-blinds.  I added a workaround into the code, and it should be okay now.  Please install the plugin again and discover devices.

**Comment by aschmidt74** [comment]
that was quick ;) but not working yet. The Alexa-App found both blinds, they're not listet as LIGHTS and got no slider in their properties.
[devices.json.txt](https://github.com/NorthernMan54/homebridge-alexa/files/2728428/devices.json.txt)

**Comment by NorthernMan54** [comment]
Have you tried voice?   They are listed as other, and other doesn’t get controls in the App.

**Comment by aschmidt74** [comment]
Now I renamed it and tried voice - and **it works**! Thank you!

**Comment by NorthernMan54** [comment]
Good luck and enjoy
