### ISSUE TITLE
KNX devices?

### ISSUE THREAD

**Issue by ErikMeinders** [NorthernMan54/homebridge-alexa#163]
Hi! It would be great to be able to use homebridge to connect Alexa to my smart home. most of it is KNX based, so I use homenbridge-knxd to connect homebridge to the knx bus. however, these devices are not discovered by the homebridge-alexa plug-in. Any pointers?

**Comment by NorthernMan54** [comment]
I’m thinking it could be one of two possible issues, first being a bad configuration of the plugin/environment and discovery is failing as a result.  Second being that the devices being returned by KNX are not supported by the plugin.

For the first, if you can collect a DEBUG log from homebridge when you are asking Alexa to discovery devices it will show what happens or is not happening during discovery.

**Comment by NorthernMan54** [comment]
Closed due to lack of activity
