### ISSUE TITLE
Amazon Certification Failed Again - Jan 11

### ISSUE THREAD

**Issue by NorthernMan54** [NorthernMan54/homebridge-alexa#164]
Issues with skill in Italian (Italy)

___________________________________________________________________________________

1. All customer facing example phrases presented either as example phrases or in the skill’s description must be in the same format as the sample utterances for the skill’s API. 
 
Actual: Alexa, imposta la Lampada del soggiorno al 50 percento 
Expected:  Alexa, imposta la lampada del soggiorno al 50 per cento 
 
2. The skill’s description fails to capture all prerequisites needed for use of the skill. Please be sure to include all information needed for users to access the core functionality of the skill.
  
Please include all the details/pre-requisites needed in order to use the skill, like for example what account users need.
 
Please see test case 3.2 from our Submission Checklist for guidance on skill descriptions.
___________________________________________________________________________________

Issues with skill in Spanish (Spain)

___________________________________________________________________________________

3. All customer facing example phrases presented either as example phrases or in the skill’s description must be in the same format as the sample utterances for the skill’s API. 
 
Actual: Alexa, sube la lámpara del salón al 50 por ciento 
Expected: Alexa, aumenta la lámpara del salón un cincuenta por ciento
___________________________________________________________________________________

Issues with skill in Spanish (Mexico)

___________________________________________________________________________________

4. All customer facing example phrases presented either as example phrases or in the skill’s description must be in the same format as the sample utterances for the skill’s API.
 
Actual: Alexa, sube la lámpara del salón al 50 por ciento
Expected: Alexa, aumenta la lámpara del salón un cincuenta por ciento

**Comment by NorthernMan54** [comment]
For folks following along, the submitted text is here

https://github.com/NorthernMan54/alexaAwsBackend/blob/master/skillPublish/skill_publish_text.md

And for items #1,3 and 4 I'm going to just resubmit with their supplied text.  But I will need some assistance with #2 Italian

Looking at their response in regards to number 2, it looks like I need a translation of the updated English text for Italian.  If a member of the community could supply some text, much appreciated.

The guidelines they mention are here

https://developer.amazon.com/docs/custom-skills/functional-testing-for-a-custom-skill.html#cert-skill-description

**Comment by teogira** [comment]
I'm italian, look at my corrections at https://github.com/NorthernMan54/alexaAwsBackend/pull/10

**Comment by NorthernMan54** [comment]
@teogira @metalmarco @marcodesantis71 @giannimp @NephilimDM @iomax @samuele4414

Everyone,

I'm looking to have the updated full skill description translated from english to Italian, the english text and the original Italian skill description are here.  This is item #2 from the response from Amazon.

https://github.com/NorthernMan54/alexaAwsBackend/blob/master/skillPublish/skill_publish_text.md

If someone could take a stab at it, much appreciated.

PS @teogira Tks for that change, I also need this text as well

**Comment by teogira** [comment]
I will update in a few hours 

Matteo Girardi

**Comment by teogira** [comment]
Updated

**Comment by NorthernMan54** [comment]
@teogira Tks very much, I have updated the Amazon side.  If you look at the Amazon App, you should now see your updated text.

If everything looks good, I'm going to re-submit again tomorrow.

**Comment by teogira** [comment]
Great!
Let me know if you need further assistance ;-)

Matteo Girardi

**Comment by teogira** [comment]
It’s not literal, but more suited to the Amazon rules.
Let me know If you need a strict translation.

Matteo Girardi
iOS Senior Developer
www.matteogirardi.com

**Comment by andrimanna** [comment]
Hi, can I join at the beta testing of the Italian one? I'm waiting it for a long time. I can also help you for the translation and some other stuff. andrea.mannarella@gmail.com

**Comment by sn0wst0rm** [comment]
I'd really like to be a beta tester for Italian too, I really need this skill and I'm also happy to help you debug it if any problem shows up!

Mail: ricox1997@gmail.com

**Comment by NorthernMan54** [comment]
@sn0wst0rm @fmonllor @andrimanna 

I have added yourselves to the beta test, please watch out for an email from Amazon with a link that enables the beta on your account

**Comment by sn0wst0rm** [comment]
@NorthernMan54 I've set up the skill and the Homebridge plugin. I have a lot of xiaomi devices configured with mi aqara plugin and yeelight plugin. Regarding the first: I can't control the gateway light, meaning it is discovered by Alexa but then I can't turn it on or off. Regarding the second, the discovery produces twice all the lights found:
For every light two devices are discovered by Alexa. Both of them work to power on or off the light but are different in the other settings.
For example I have a Xiaomi Yeelight Ceiling that only supports various types of white. Then, one device is seen "correctly" since it only shows the various whites aviable but the other one shows instead only color controls (yellow, red, green, etc) which shouldn't be aviable. This things repeats for all the devices I have. It's not a really big problem since I've disabled the wrong devices, but I'd like to know whether exist a more proper fix or workaround.

Thank you for your great work, btw!

**Comment by NorthernMan54** [comment]
@sn0wst0rm Can you open this as a separate issue, and in the issue can you share the output from this script ( it will dump from homebridge all your accessories. )

`curl -X PUT http://127.0.0.1:51826/accessories --header "Content-Type:Application/json" --header "authorization: 031-45-154"`

**Comment by bellag96** [comment]
Hi, I would like to become a beta tester to help in the translation of the Italian language and to report possible bugs, my mail is:
bellag96@gmail.com 
Thanks in advance

**Comment by Mangaxhombro** [comment]
I and thank you very much a oír your work NorthernMan. I am a spanish user with homebridge installed as stand aliñe and also integrated as jeedom plugin. I would like to be a betatester in order to help with spanish translation and also with tests with jeedom homebridge plugin integration. Thanksnin advance. My email: david.boticario@gmail.com

**Comment by Robercap7** [comment]
Hi, I would also like to become a beta tester to help with the translation of the Spanish language (Spain) and to report possible errors.
My email is: robercap7@gmail.com

Thank you

**Comment by NorthernMan54** [comment]
@bellag96 @Mangaxhombro @Robercap7 I have added yourselves to the beta, please expect an email from Amazon shortly with a link to enable your account for the Beta.

**Comment by lucadistefano** [comment]
Hi, I would like to become a beta tester to help in the translation of the Italian language and to report possible bugs, my mail is:
lucadistefano@tiscali.it
Thanks in advance

**Comment by NorthernMan54** [comment]
I have added yourself, you should see an email from amazon shortly with a link to enable the skill.  Please go back and edit you earlier comment and remove your account details

**Comment by NorthernMan54** [comment]
@piccoloale I have added yourself, you should see an email from amazon shortly with the details.  Please go back and edit out your email

**Comment by alexcarsso** [comment]
Hi, if possible I would like to contribute even for the Italian language, if you want this is my email: alexcarsetti@me.com
Thank you

**Comment by piccoloale** [comment]
Is it normal that I haven’t received uet the invitation? Maybe my mail was write wrong? alessandromar@gmail.com

**Comment by NorthernMan54** [comment]
@alexcarsso I have added you to the beta, you should receive an email from amazon with the details.  Please go back and edit out your email.

@piccoloale I checked and you were added, and I have asked amazon to resend the email.  Please check your junk folder.

**Comment by alexcarsso** [comment]
Thank you very much, if you want my girlfriend is a South American native speaker and can help you in Spanish translations. Thanks for the invite

**Comment by piccoloale** [comment]
> @alexcarsso I have added you to the beta, you should receive an email from amazon with the details. Please go back and edit out your email.
> 
> @piccoloale I checked and you were added, and I have asked amazon to resend the email. Please check your junk folder.

Thank you. I checked all the e-mail (also in the junk folder) but still nothing. I will wait :)

**Comment by piccoloale** [comment]
> @piccoloale I have added yourself, you should see an email from amazon shortly with the details. Please go back and edit out your email

Could you please send me the URL invitation directly by mail at alessandromar@gmail.com? so I can add the skill directly without waiting for the amazon mail?

**Comment by DidodaRM** [comment]
Hi, very good day!! I would like to be a beta tester. My email is rraniolo@tiscali.it. Thank you very much !!

**Comment by stilighen** [comment]
Hi, I've been waiting for the certification since the echo devices are available in Italy, I hope you are lucky this time and thank you for your job.. in the meantime could I become a beta tester please?
My email is andreaenrico85@gmail.com

Thank you!!!!

**Comment by NorthernMan54** [comment]
@DidodaRM @stilighen I have added you to the beta, you should receive an email from amazon with the details. Please go back and edit out your email.

**Comment by DidodaRM** [comment]
> @DidodaRM @stilighen I have added you to the beta, you should receive an email from amazon with the details. Please go back and edit out your email.

thanks a lot !!

**Comment by NorthernMan54** [comment]
I just asked Amazon to resend, please check your junk or spam folder

**Comment by NorthernMan54** [comment]
@lucadistefano If it doesn't turn up within an hour, please let me know

**Comment by lucadistefano** [comment]
nothing received, checked junk & spam  .

**Comment by sn0wst0rm** [comment]
@NorthernMan54 I just got kicked from the beta testing, could you tell me why? was it an error? Thank you in advance

**Comment by paquitodr** [comment]
Same here. I received an email saying that the beta was end! :(

Now I can’t manage my house!
Is there any problem?

**Comment by NorthernMan54** [comment]
Amazon rolled over the beta, you should receive a new email momentarily with a new link

**Comment by NorthernMan54** [comment]
It sent an email to everyone about an hour ago

**Comment by paquitodr** [comment]
Received new beta invitation.

Thank you so much!

**Comment by NorthernMan54** [comment]
@ciapamusche I have added yourself, you should receive an email from amazon shortly with the details.

**Comment by felixekman** [comment]
I'd love to give this a try if you have more spots open!
betagithub@zinomedia.com

**Comment by NorthernMan54** [comment]
I have added yourself, please expect an email from Amazon with the details shortly.  Please go back and edit out your email.

**Comment by marcodesantis71** [comment]
HI all,

me too. I can't see Homebridge app on Alexa.

**Comment by NorthernMan54** [comment]
@Pylotto @marcodesantis71 Please check your mail box

@Pylotto Please go back and edit out your email address

**Comment by marcodesantis71** [comment]
@NorthernMan54 Ok. Now it works again. tnx

**Comment by Robercap7** [comment]
sorry , nothing received, checked junk & spam , sniff

please, my email is rguez.tortosa@gmail.com

**Comment by NorthernMan54** [comment]
@Robercap7 Please check again

**Comment by martinorob** [comment]
Hi, I also would like to contribute even for the Italian language, this is my email: m@rtino.info
Thank you

**Comment by giannimp** [comment]
Hi NorthernMan54 , how are you??
Have you  update for my accessory?
"accessories": [
        {
            "accessory": "GPIODevice",
            "type": "LockMechanism",
            "name": "Portone Palazzo",
            "pin": 6,
            "inverted": true,
            "duration": 1
        },
Alexa doesn't see my LockMechanism
thank you, for your work!

**Comment by NorthernMan54** [comment]
Currently locks are not supported by the plugin, I can add it to the backlog, but it may be a while.

**Comment by NorthernMan54** [comment]
@exkape @martinorob I have added yourself to the beta test, please check your email for the details.  Also could you back and edit out your emails.  Tks

**Comment by NorthernMan54** [comment]
Everyone watching I have just submitted again.  Stay tuned

**Comment by gaojie429** [comment]
Do you still have certification problem in Japanese skill ?
 I saw at issue#150, and I know you seem to have a problem with description.
If your skill havent verified yet, I can help you as far as I can. (For example, I can translate discription into Japanese.)
