### ISSUE TITLE
Support for FR CA ?

### ISSUE THREAD

**Issue by natcl** [NorthernMan54/homebridge-alexa#166]
Would it be possible to support French Canadian? Thanks!

**Comment by NorthernMan54** [comment]
It would be definitely possible to add French CA.  As part of the submission process I need to submit French Skill Details, and was wondering if you could review the French FR details here, and let me know if a simple copy and paste would suffice?

https://github.com/NorthernMan54/alexaAwsBackend/blob/master/skillPublish/skill_publish_text.md

PS I can add yourself to the current Beta with FR CA support as well, just need your amazon ID

**Comment by natcl** [comment]
Hello, yes French FR is fine ! Thanks !
Where can I send my ID ? (is it the email that is tied to my account or something else ?

**Comment by NorthernMan54** [comment]
It is the email

**Comment by natcl** [comment]
Thanks, sent it as a pm via reddit !

**Comment by NorthernMan54** [comment]
Got it, give me about 12 hours

**Comment by natcl** [comment]
Thanks !

Le mar. 15 janv. 2019, à 10 h 31, Northern Man <notifications@github.com> a
écrit :

> Got it, give me about 12 hours
>
> > On Jan 15, 2019, at 10:06 AM, Nathanaël Lécaudé <

**Comment by natcl** [comment]
Everything seems to work !
I have one small issue where my platform-wemo plugin will show devices 2 times in the Alexa app, not sure if it's a problem on their side or with Alexa, but they still work. Will test more extensively !

**Comment by NorthernMan54** [comment]
If you have a device connected to homebridge and directly to Alexa you will have 2 devices.   That is likely the cause.

**Comment by natcl** [comment]
Oh that's possible, I assume Alexa autodetected the wemo plugs but I did not notice, I'll try deleting one of them.
Pretty happy so far, was able to trigger a homekit scene from Alexa by setting a listener in homekit and a fake accessory in homebridge.
Thanks for the great work !

**Comment by NorthernMan54** [comment]
Awesome, good luck and enjoy
