### ISSUE TITLE
Cant Setup Plug in correctly with Homebridge App

### ISSUE THREAD

**Issue by homohurre123** [NorthernMan54/homebridge-alexa#167]
i have installed Homebridge through the Homebridge App on iOS. Now i Followed your Guide and I dont really get how I am supposed to enter  insecure Mode. I‘m also Not quite sure in i Need this Mode permanently or just for recognising the HomeKit Stuff in the First Place.

I‘ve read through a lot of closed  issues Here but I dont seem to find the Solution.
At  the Moment i get the error Message 
„You have an issue ... Review the readme“
If you could hint  me Whats wrong i Would much appreciate it. 
thanks in Advance for your Time and effort!

**Comment by NorthernMan54** [comment]
You need the -I flag permanently, as that allows Alexa to control your devices.  With your homebridge setup, I presume it is running on a raspberryPI?

It is likely using systemd to control homebridge under the covers so look for a file called /etc/default/homebridge and add the -I as per the README.

**Comment by homohurre123** [comment]
Well I don‘t have the file in there...
I actually think I know what should work.
I dont know if you Unterstand german or get what hes describing.
https://forum.smartapfel.de/forum/thread/1475-homebridge-im-insecure-mode-starten/
#3 and Hits Point 3 possibility should work Since i found the file i Can modify.
But when i Try to modify the file and Save it it tells me i dont have permission for it. IThought of doing it with ssh but i dont really know the Command to modify a file.

**Comment by NorthernMan54** [comment]
The command to edit a file is **vi**, it is a very old text editor for unix.  From the command line try this

**sudo vi filename**

**Comment by NorthernMan54** [comment]
You should be able to google a manual for vi

**Comment by homohurre123** [comment]
Okay thanks a lot I will try it

**Comment by NorthernMan54** [comment]
What messages are you currently getting in the log files?

**Comment by homohurre123** [comment]
Okay I wanted to start search process of Alexa to see the error message again but this time it worked.
Only issue after adding devices to my Alexa account I still can't control the devices because it tells me 
"Homebridge auth failed invalid Pin. I added the 
"pin": "031-45-***" 
line to my config with my Pin don't get why its not authenticating correctly.
But im a bit confused since I never managed to enter insecure mode...

**Comment by homohurre123** [comment]
For your information I'm trying to find a solution in here:
https://forum.smartapfel.de/forum/thread/2783-homebridge-app-insecure-modus-dauerhaft-starten/?postID=49482#post49485
I will report back if I manage to make it work.

**Comment by NorthernMan54** [comment]
Okay

I’m here and on Slack if needed

**Comment by homohurre123** [comment]
Okay it does work now so I'm pretty happy but I'm not quite sure why..
I guess would be that I just needed to wait a bit after restarting Homebridge since it did fail again the same way after restarting Homebridge. (and it worked before) after 10 Minutes it worked again. 
Thanks a lot for your work and Help. Awesome Work now that I see it working :)

**Comment by NorthernMan54** [comment]
Okay, glad to hear
