### ISSUE TITLE
Can be this useful to connect a Echo Plus to Node Red?

### ISSUE THREAD

**Issue by Barabba11** [NorthernMan54/homebridge-alexa#168]
Hi there, sorry for create an issue to ask simply a question, thank you for your patience and help.
Unfortunately Node Red does not support yet Echo Plus, it doesn't discover Node Red and the development is sadly stopped from months(( Maybe installing your module to Homebridge and pass Node Red messages by mqtt?
Does it work with Echo Plus? Thank you

**Comment by NorthernMan54** [comment]
Did you try this node-red Alexa skill?

https://github.com/hardillb/node-red-contrib-alexa-home-skill

**Comment by NorthernMan54** [comment]
Good luck
