### ISSUE TITLE
Bticino Roller Shutter

### ISSUE THREAD

**Issue by piccoloale** [NorthernMan54/homebridge-alexa#169]
Hi, 
I created a routine in Alexa that when I say "Alexa, chiudi tutte le tapparelle/Alexa, close all the roller shutter" all the roller shutter in the house (5 controlled by homebridge-myhome-tng) are closed automatically. 
The problem is that if 2 of 5 are already closed, the routine start to close the 3 open and open the 2 that are already closed. With Siri I don't have this kind of problem and only the 3 yet open are close while the 2 remain closed.
It seems that the routine change the state from on to off (or viceversa) without making a check of the state (if it's already off remain off). 
Hope I'm enough clear :)

**Comment by NorthernMan54** [comment]
@piccoloale I think we need some assistance of the plugin developer on this, @angeloxx, as all the plugin is doing is sending an open or close command to Homebridge directly and it is not aware of the state.  It seems that the plugin is not managing state correctly and opening a closed blind.

Homebridge-alexa takes an on and maps it to target position 100% and off to target position 0%.  This is from the code

cookie["TurnOn"] = _cookieV(100);
cookie["TurnOff"] = _cookieV(0);

https://github.com/NorthernMan54/homebridge-alexa/blob/f50c18fa47aa1c7253238de7e0f3613bda251e16/lib/alexaTranslator.js#L242

**Comment by DidodaRM** [comment]
I also have the same issue. 
Indeed I have some scenarios in MyHome that close all the roller shutter but Alexa doesn’t recognize the command for them so I’m trying to duplicate scenario in Alexa.
Is this the correct path or Alexa should be able to interface scenario correctly ?

Thx

**Comment by piccoloale** [comment]
> I also have the same issue.
> Indeed I have some scenarios in MyHome that close all the roller shutter but Alexa doesn’t recognize the command for them so I’m trying to duplicate scenario in Alexa.
> Is this the correct path or Alexa should be able to interface scenario correctly ?
> 
> Thx

I use the Alexa Routine and it works.

@NorthernMan54 in the last two days both the plugin homebridge-alexa and homebridge-myhome-tnt by @angeloxx seems to work fine together. I will do other test and update the issue.

**Comment by NorthernMan54** [comment]
@piccoloale @DidodaRM Can we close this?

**Comment by DidodaRM** [comment]
I’ve replicated MyHOME’s scenario in Alexa using routine and is fine from my side. 

@piccoloale to be sure to close a/all roller shutter (avoiding to reopen if it is already closed) I have set “accensione/off”

Thanks

**Comment by piccoloale** [comment]
> I’ve replicated MyHOME’s scenario in Alexa using routine and is fine from my side.
> 
> @piccoloale to be sure to close a/all roller shutter (avoiding to reopen if it is already closed) I have set “accensione/off”
> 
> Thanks

@DidodaRM yes, I can confirm with Alexa Routine it works as expected.

**Comment by NorthernMan54** [comment]
@piccoloale @DidodaRM I have been working on triggering Alexa routines from various sensor devices, and should be able to trigger an Alexa routine based on your blinds.

If your interested, please take a look at this.  

https://github.com/NorthernMan54/homebridge-alexa/tree/event#beta-test-for-sending-events-to-alexa-and-using-in-routines
