### ISSUE TITLE
[Feature request]TV accessory support

### ISSUE THREAD

**Issue by hivedeejay** [NorthernMan54/homebridge-alexa#171]
Hi, in iOs 12.2 beta, support for new devices has been added. 
[KhaosT has already added compatibility](https://github.com/KhaosT/HAP-NodeJS/blob/414cd96ca9708596b1f71304bd4e6dff5ab045fc/lib/Accessory.js#L120), can you do the same thing with your plugin?
thank you so much.

**Comment by NorthernMan54** [comment]
I’m also looking at this as well, as I have a number of TV and Stereo plugins that use fans instead of actual speakers etc.  But for me adding this will be after 12.2 goes public as a fast follower.  First will be my device plugins, then this plugin.

Control of my TV is a top WAF item for me, so it will be top of mind.

**Comment by jelvs** [comment]
I updated my samsung-tizen plugin and it stopped working turn on/off the TV , and only after I realised why! Waiting for the feature to come :)

**Comment by NorthernMan54** [comment]
@jelvs If you could send an accessory from your homebridge instance with the new TV, I can take a look at it.  I'm in the middle of adding some more accessory support and can add this to the list

```
curl -X PUT http://127.0.0.1:51826/accessories --header "Content-Type:Application/json" --header "authorization: 031-45-154"
```

**Comment by jelvs** [comment]
I'll send you later today, that would be great!

**Comment by NorthernMan54** [comment]
I saw the slack message come by, but for some reason i lost it.  Can you resend?

**Comment by NorthernMan54** [comment]
@jelvs I ran it thru the new parser, and it found the on/off switch right way.  You may want to give it a try

https://github.com/NorthernMan54/homebridge-alexa/issues/201#issuecomment-480307601

As you would be the first user of this branch, please be prepared to undo the change if needed.

**Comment by jelvs** [comment]
so have to use the new one (homebridge-alexa#ServiceParsing)?

**Comment by NorthernMan54** [comment]
Yes, install instructions are here

https://github.com/NorthernMan54/homebridge-alexa/issues/201#issuecomment-480307601

**Comment by NorthernMan54** [comment]
The speaker config.json error is now fixed in the latest codebase.

With the TV, it should expose it as On/Off at this time, I still have more work to do on the interface

**Comment by francescob** [comment]
I haven't tried the new commit yet, but i can confirm that Alexa can turn on and off my Sony Bravia Tv and my SkyQ box. Great work! Do you think that will be possibile for alexa to control other functions of the skyQ box like pausing, restarting and recording? I can already do that through siri

**Comment by NorthernMan54** [comment]
The mapping of HomeKit TV’s to Alexa is on my list, stay tuned.

**Comment by NorthernMan54** [comment]
@jelvs I have been working thru this, and am about 50% of the way there.

Looking at the HomeKit TV accessory and the available Alexa options, I should be able to allow alexa to be able to turn on/off, control volume, and select inputs.  For the remote keys, I will be mapping them to playback controls which offers limited option ( no up or down ). One issue with inputs is that Alexa comes with a predetermined list of inputs, while HomeKit allows free form input.  And after looking at my Yamaha Receiver, found that the options where lacking.  My Yamaha has a option to select "Spotify" but there is not corresponding option for Alexa.   The options are here

https://developer.amazon.com/docs/device-apis/alexa-inputcontroller.html#discovery

I'm thinking there will need to be a configuration option to allow manual mapping.

**Comment by NorthernMan54** [comment]
Release v0.4.11 includes support for Television on/off and volume.  Still trying to figure out how to map inputs.

**Comment by jelvs** [comment]
Sorry for the late reply, i'am currently travelling, I'll take a look tonight, thank you

**Comment by francescob** [comment]
I can confirm that volume control works on Sony Bravia and Panasonic tvs

**Comment by NorthernMan54** [comment]
@francescob Tks for the report of success

**Comment by jelvs** [comment]
I updated yesterday but didn't find volume control @francescob how did you test it?

**Comment by francescob** [comment]
with voice commands:

"Alexa, lower volume on tv"

**Comment by NorthernMan54** [comment]
@jelvs, can you control the volume thru HomeKit?

**Comment by jelvs** [comment]
I tried now, no I can't :(

Cumprimentos,

Tiago Sousa

**Comment by NorthernMan54** [comment]
@francescob Can you share the name of the plugins you are using, and I will add to the README.

@jelvs I think I see what is happening, give me a couple of days.

Looking at the HomeKit API, their are two separate volume options, and I'm wired to one and not the other.  Let me wire the other up, and I would like to run thru the various voice commands.

**Comment by jelvs** [comment]
Thks I appreciate

Best Regards,

Tiago Sousa

**Comment by francescob** [comment]
> @francescob Can you share the name of the plugins you are using, and I will add to the README.

here they are:
Panasonic TV: 
homebridge-panasonic-viera-tv@4.1.0
Alexa can turn on and off and control volume
Sony Bravia TV (Android TV)
homebridge-bravia@1.1.0
Alexa can turn on and off and control volume
Sky Q decoder : 
homebridge-sky-q-experimental@1.0.2
Alexa can turn on and off, iOS remote can also control playback and interface navigation

**Comment by NorthernMan54** [comment]
@francescob Try these commands as well with your homebridge-sky-q-experimental.  I had wired the the Alexa Playback controls to some of the control options

Alexa, pause device ( Pause / Play control )
Alexa, play device ( Pause / Play control )
Alexa, resume device ( Pause / Play control )
Alexa, stop device ( Back control )
Alexa, next on device ( Right )
Alexa, rewind on device ( Left )
Alexa, previous on device ( Left )

**Comment by NorthernMan54** [comment]
@jelvs I added support for the alternate volume control, you should now be able to ask Alexa to raise and lower the volume.  As I don't have the ability to test this, please let me know how it works.  You should be able to ask Alexa to raise or lower the volume.

One thing with the interface, Alexa allows you to raise or lower with a number, but the HomeKit interface only supports 1.  ie Alexa raise volume by 20 or alexa lower the volume by 20

I'm wondering if I need to improve the code by having the plugin sending the homekit command multiple times?

**Comment by jelvs** [comment]
I've tested, and it works to raise and lower volume by 1

**Comment by NorthernMan54** [comment]
Tks for the update, I’m going to close this
