### ISSUE TITLE
Fan shown as a light

### ISSUE THREAD

**Issue by andrimanna** [NorthernMan54/homebridge-alexa#172]
Hi. I'm in the Italian beta testing program of your skill. I love it, I works really great!
But the only issue (not serious actually) is that I have most of my devices working with homebridge-http-advanced-accessory including a fan: ![fan](https://user-images.githubusercontent.com/10048654/52052947-49fa4900-2558-11e9-8b71-b31f1d1248de.png)
with this configuration:
`{
        "accessory": "HttpAdvancedAccessory",
        "service": "Fan",
        "forceRefreshDelay": 10,
        "name": "Aspiratore",
        "debug": false,
        "urls": {
            "getOn":{
                "url" : "http://192.168.2.16/ons"
            },
            "setOn": {
                "url": "http://192.168.2.16/on",
                "httpMethod":"POST",
                "body" : "{value}"
            }
        }
    }`
The problem is that homebridge-alexa discovers the fan and shows it correctly in the Alexa website:
![Alexa website](https://user-images.githubusercontent.com/10048654/52053393-81b5c080-2559-11e9-914d-3d78e2e01c97.png)
but in the app it recognize it as a light:
![light](https://user-images.githubusercontent.com/10048654/52053430-95f9bd80-2559-11e9-9f5a-2f13a83e896a.jpeg)
So then when I say "Alexa Switch off all the light" she switches off my fan too! Anyway, not a dramatic problem, but it annoy me.

**Comment by NorthernMan54** [comment]
One of the challenges between HomeKit and Alexa is their support for devices types is not the same.  HomeKit has device types not supported by Alexa, and Alexa has devices types not supported by HomeKit.  A good example of this is speakers, Alexa supports speakers and HomeKit doesn’t yet.  And another example is fans, HomeKit supports fans and Alexa doesn’t.  Here is the current list of device types for Alexa.

https://developer.amazon.com/docs/device-apis/alexa-discovery.html#display-categories

So when I wired up Fans, I needed to map a HomeKit fan to something so I chose a light, but then back in early December I moved it from lights to other.  So if you update the plugin to a recent version and discover devices, it should show up as other.

**Comment by andrimanna** [comment]
Thank you very much! I have updated the plugin with npm update -g and now it is shown as other which is good: 
![img_e417e88fa5c1-1](https://user-images.githubusercontent.com/10048654/52057718-09a1c780-2566-11e9-84f1-d39fb2429cbe.jpeg)
I appreciate a lot your fast answer.

**Comment by Ramias1** [comment]
Checking in on this item.  It looks like now Alexa supports Fan devices (I have a Dyson that Alexa sees as a fan).  Any chance this plugin can support fan icons and fan device types in Alexa?  Currently shows as a switch.  Under settings, it shows as a homebridge  Fan v2. Thanks

**Comment by NorthernMan54** [comment]
Tks for noticing this

https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-discovery.html#display-categories

Will take a look at changing the icon with the next release

**Comment by NorthernMan54** [comment]
Resolved

![image](https://user-images.githubusercontent.com/19808920/111566385-717df100-8773-11eb-92d7-e828743da077.png)
