### ISSUE TITLE
homebridge-alexa skill for Japanese?

### ISSUE THREAD

**Issue by gaojie429** [NorthernMan54/homebridge-alexa#174]
Do you still have certification problem in Japanese skill ?
I saw issue#150, and I knew you seem to have a problem with description.
If your skill havent verified yet, I can help you as far as I can. (For example, I can translate discription into Japanese.)

I really want to use this skill in Japanese, so I want help you.

**Comment by NorthernMan54** [comment]
At the present time the Japanese language version is in for certification, with the other languages so I can't add anyone at this time.  They have given a rough timeline of Mid February, so you may want to check back around then.

For the Japanese translation, the text I'm using is here.  

https://github.com/NorthernMan54/alexaAwsBackend/blob/master/skillPublish/skill_publish_text.md

**Comment by gaojie429** [comment]
OK, I'll check it out around Mid February.
