### ISSUE TITLE
Homebridge-ALexa AppleTV

### ISSUE THREAD

**Issue by poudenes** [NorthernMan54/homebridge-alexa#175]
Hi all,

Everything work perfect. I want add AppleTV also but get a error that there is no plugin loaded.

Can someone tell me how to do this? SO i can use AppleTV on my Alexa Echo

Cheers
Peter

**Comment by NorthernMan54** [comment]
In order for Alexa to control your Apple TV, first you need to have installed and configured the homebridge-apple-tv plugin.  And in the configuration of homebridge-apple-tv you need to include two configuration options in the homebridge-apple-tv section of the README

```
"showDefaultSwitches": true
"defaultSwitchesIncludeATVName": true

```
Then discover devices, and it will show it.  Please note that the API only supports Play, Pause, Stop and Resume.

https://github.com/NorthernMan54/homebridge-alexa/blob/master/README.md#appletv
