### ISSUE TITLE
unable to add "stop tv" to Alexa routine

### ISSUE THREAD

**Issue by martinorob** [NorthernMan54/homebridge-alexa#176]
Hi, is there a way to add the "stop tv" command as Alexa routine on "goodnight"? Thanks

**Comment by NorthernMan54** [comment]
I’m sorry I don’t understand the question 

You can create routines to control devices, so if your tv is a controlled device just add it to your rountine.

**Comment by martinorob** [comment]
I have the Apple TV device and I can tell Alexa to play, stop etc etc, but when I create a routine, when i
 go to "add device" the tv isn't in the list.

![img_0594](https://user-images.githubusercontent.com/6664936/52492100-d34cf380-2bc8-11e9-969c-f5a4b8962b3d.PNG)

**Comment by NorthernMan54** [comment]
I just looked and I’m seeing a similar behaviour with mine as well.  As this is likely something within the Amazon Alexa backend, I posted the question there.

https://forums.developer.amazon.com/questions/199289/is-the-usage-of-playbackcontroller-and-speaker-cap.html <https://forums.developer.amazon.com/questions/199289/is-the-usage-of-playbackcontroller-and-speaker-cap.html>

As temporary workaround, you could add a second stop button, as long as the name is different than “Stop” my plugin won’t see it and will pass the second button to Alexa as an additional button/control.  I was playing with a netflix button, and have this working.

I don’t expect anything from Amazon on this issue in the short term, so this is probably your best course of action.

**Comment by martinorob** [comment]
Great... but, how Can I add a second stop button?

**Comment by NorthernMan54** [comment]
Sorry, I don’t have an example available, but if you review the instructions for homebridge-apple-tv, they show how to add controls/buttons.  Just create a “Stop” button, but don’t call it “Stop”.

**Comment by martinorob** [comment]
i have added new stop accessory but nothing has changed...

`{
	    "platform":"AppleTV",
	    "name":"Apple TV",
	    "devices": [{
            "id": "Salotto",
            "name": "TV",
            "credentials": "token" }
            ],
	   "accessories": [
       		{
          	"deviceID": "lounge",
          	"name": "Stoppa",
          	"command": "stop"
        	}],
            "showDefaultSwitches": true,
            "defaultSwitchesIncludeATVName": true,
            "showPairSwitches": false,
            "hideWelcomeMessage": true
	},`

**Comment by NorthernMan54** [comment]
Awesome, great news
