### ISSUE TITLE
Triggering Alexa Routines from Motion and Contact Sensors

### ISSUE THREAD

**Issue by sejoki** [NorthernMan54/homebridge-alexa#177]
After some initial hick ups, I got the plugin working and all the devices I expect to show up do show up, I can control them and it works.
My main reason for getting the Echo was to have a cheap smart speaker for my bedroom that starts playing music with my good morning scene. I thought I could use some dummy switches that are triggered in HomeKit with the scene and set up an automation rule in Alexa.
The dummy switch shows up, can be controlled, but it can’t be used as a “trigger”.
When I set up a routine and go to devices, it says that there are no supported devices. Is that what you mean with “Implement Alexa Events and Proactive reporting for Home Skills” in the roadmap and the feature doesn’t exist yet, or is it an issue on my end?

**Comment by NorthernMan54** [comment]
The ability to trigger routines is limited to motion and contact sensors and not available for other device types.

For readiness, I have it all pulled together and working at this time.  And am just completing final testing before making it generally available. I also need Amazon to certify the current package in for certification before it’s generally available.  For people in the current Spanish, and Italian demo they would be able to enable it now.

**Comment by martinorob** [comment]
You are talking about Philips Hue motion sensor? Because I can't add it.. now is possible? Thanks!!

**Comment by NorthernMan54** [comment]
This is from my test environment, where I'm playing with having Alexa Routines triggered by Homebridge Contact sensors, Motion Sensors, Garage Doors and Blinds.  It works well, just haven't found the winning combination yet for a high WAF score.  I'm currently thinking that a washer/dryer done notification may drive a high score.

![image](https://user-images.githubusercontent.com/19808920/52541098-4daf7c00-2d5f-11e9-89e5-ddcd83449be3.png)

For more details, take a read of this ( Please note that this is only available to participants of the current Spanish, Italian, English India, Japanese and French Canada beta )

https://github.com/NorthernMan54/homebridge-alexa/tree/event#beta-test-for-sending-events-to-alexa-and-using-in-routines

**Comment by martinorob** [comment]
Wow. Thanks. I'll try.. even if without the event plugin, when I search devices, my Philips motion device aren't showing up on Alexa.. (in iPhone Home app works!)

**Comment by martinorob** [comment]
```
2019-02-11T09:08:23.811Z hapClient HAP Discover failed BSB002 http://192.168.3.25:8080 error code 470

/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/lib/httpParser.js:145
  })();
    ^
TypeError: Cannot read property 'Content-Length' of null
    at /usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/lib/httpParser.js:115:30
    at httpMessageParser (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/lib/httpParser.js:145:5)
    at Socket.client.on (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/lib/eventedHttpClient.js:44:18)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)
```

can you help me?

**Comment by sejoki** [comment]
Okay, thanks for the clarification. Unfortunately, I won't be able to join the beta, I just have to wait for the regular release.

**Comment by NorthernMan54** [comment]
Error code 470 is unsupported native HomeKit device.

**Comment by martinorob** [comment]
Philips Hue is unippoeted native HomeKit? 😕

**Comment by NorthernMan54** [comment]
Philips hue native is not supported, but Philips hue connected thru homebridge-hue is.

**Comment by martinorob** [comment]
i will try! Thank you!

**Comment by martinorob** [comment]
@NorthernMan54 thanks for your info.. I understand that hue is not compatible with Alexa so I have installed homebridge-hue and it works but I have the same error. In Troubleshooting.MD there is a "These are other HomeKit devices on your network, that are not compatible with homebridge-alexa. These errors can be ignored.".

but I can't ignore this problem because it crash my home bridge instance. 

how I can workaround the discovery of hue?

Thanks again

**Comment by NorthernMan54** [comment]
@martinorob I didn't realize that you where using the Events Beta Plugin.  In order to support events, I needed to make significant changes to that section of code.  I have added code to hopefully catch that error.  Please re-install and try again.  Fingers crossed.

**Comment by martinorob** [comment]
@NorthernMan54 works fine now.. but sometime I have this error that crash homebridge instance:


`/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/lib/eventedHttpClient.js:46
      if (response.headers['Transfer-Encoding'] && response.headers['Transfer-Encoding'].toLowerCase() === 'chunked' && data.slice(-7).toString() !== '\r\n0\r\n\r\n') {
                          ^
TypeError: Cannot read property 'Transfer-Encoding' of null
    at Socket.client.on (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/lib/eventedHttpClient.js:46:27)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)`

**Comment by martinorob** [comment]
I also have the error:

[2/13/2019, 10:57:20 AM] [Alexa] ERROR: HAP Discovery failed, please review config

this is my start home bridge command: 

/usr/local/bin/homebridge DEBUG=alexa* -I -U /Users/username/.homebridge/


is correct?

**Comment by NorthernMan54** [comment]
The debug mode start command is

DEBUG=* /usr/local/bin/homebridge-I -U /Users/username/.homebridge/

With the beta version, I’m still playing with debug logging so pleas use *

For the other issue, I will make a code change tonight

PS thanks for beta testing this for me.  It has been running without issue in my setup for a bit, but it still has a few warts

**Comment by martinorob** [comment]
Thanks to you for your work!

**Comment by NorthernMan54** [comment]
I have made a fix for the earlier issue

How is it working for you?

**Comment by martinorob** [comment]
Is working like a Sharm! (but I have to test for a little bit...) Thank you!!!!

**Comment by martinorob** [comment]
I think that with the last update my home bridge not crash any more but on Alexa I haven't anymore my Philips Hue sensor (that yesterday there were)...

**Comment by NorthernMan54** [comment]
Did you install it this way?

sudo npm install -g https://github.com/NorthernMan54/homebridge-alexa#event

Also, I was looking at the dashboard and I don't think you have events fully enabled yet.  Did you add the events config.json option and you will need to disable/enable the skill the first time to activate the events feature.

**Comment by martinorob** [comment]
I'l try tonight (Italy time) but I think that I've done all correctly. 
or.. maybe.. it was the npm-check plugin that I use to update nom packagers, that update the packages on the no #event version..


`$  npm view homebridge-alexa version
0.1.72`

**Comment by NorthernMan54** [comment]
For the events branch, I’m not updating npm version numbers.  So they can’t be trusted.

But I will check my side as well.

**Comment by martinorob** [comment]
okay because

```
sudo npm install -g https://github.com/NorthernMan54/homebridge-alexa#event
+ homebridge-alexa@0.1.71
updated 1 package in 7.32s
npm view homebridge-alexa version
0.1.72

```

so I don't know if I'm using the right version..

**Comment by martinorob** [comment]
sorry, on a rollback because home bridge crash, I comment out the "events:true" option..

now I have 

[2/14/2019, 4:15:25 PM] [Alexa] ERROR: HAP Discovery failed, please review config


😕

**Comment by NorthernMan54** [comment]
Can you share a DEBUG log, showing the discovery phase and the crash?  

Also I just changed the version number of the events version to 0.2.0.

PS As an FYI, I have reports of two other users who have this working successfully

**Comment by martinorob** [comment]
```
Accessory [Homebridge Martino] Got Characteristic "Name" value: Sleep (TV) +0ms
  EventedHTTPServer [::ffff:192.168.3.51] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:192.168.3.51] HTTP request: /characteristics?id=99.5 +7ms
  HAPServer [CC:20:3D:D3:CC:33] HAP Request: GET /characteristics?id=99.5 +0ms
  Accessory [Homebridge Martino] Getting value for Characteristic "Name" +1ms
  Accessory [Homebridge Martino] Got Characteristic "Name" value: Allarme Casa +0ms
  EventedHTTPServer [::ffff:192.168.3.51] HTTP Response is finished +1ms
  alexaLocal Emitting Alexa.Discovery +35s
  alexaTranslator Alexa Controllable Soggiorno Webcam 0 +28s
  alexaTranslator Alexa Controllable Cucina Webcam 0 +0ms
  alexaTranslator Alexa Controllable Camera Webcam 0 +1ms
  alexaTranslator Alexa Controllable MacMini Webcam 0 +0ms
  alexaTranslator Alexa Controllable MacBook Webcam 0 +0ms
[2/14/2019, 4:21:09 PM] [Alexa] ERROR: HAP Discovery failed, please review config
  alexaLocal Emitting Alexa.Discovery +749ms
  alexaTranslator Alexa Controllable Soggiorno Webcam 0 +748ms
  alexaTranslator Alexa Controllable Cucina Webcam 0 +0ms
```

**Comment by NorthernMan54** [comment]
That error is caused by it not returning any devices.  Can you restart and share from startup?

**Comment by martinorob** [comment]
I don't know why.. but now is working.. I'll keep you update!

Thanks!!!!

**Comment by NorthernMan54** [comment]
I was just looking at the backend logs, and I haven't seen any events from your account yet.

**Comment by NorthernMan54** [comment]
For others watching this, with the certification of my recent version of the Skill, this feature is now available to everyone.  I will continue with a limited beta for a short period of time with the feature, and if your interested in trying it out, details are here.  ( With this beta, it is just a new version of the plugin, no need special enrolment. ). And you can rollback at anytime by installing the regular version of the plugin.

https://github.com/NorthernMan54/homebridge-alexa/tree/event#beta-test-for-sending-events-to-alexa-and-using-in-routines

PS I have a couple of people using it already, so it should be stable, but YMMV

**Comment by martinorob** [comment]
> I was just looking at the backend logs, and I haven't seen any events from your account yet.

Now you find my events log? :)

**Comment by NorthernMan54** [comment]
Just looking, 1,448 events have been sent to Alexa so far ;-)


martinorob	Wed Jan 30 2019 14:02:25 GMT+0000 (UTC)	Mon Feb 18 2019 07:10:16 GMT+0000 (UTC)	698	Mon Feb 18 2019 07:10:16 GMT+0000 (UTC)	663	Mon Feb 18 2019 07:50:49 GMT+0000 (UTC)	1488

Columns are

Date Created, Last Alexa Command, # of Alexa Commands, Last Response from Plugin, # of plugin responses, Last Event, Total Events

**Comment by sherazan** [comment]
Hi, I've joined to beta test for the Italian skill and I'm using it with succes. I can control all my devices: lights, cameras (Logitech & Arlo) and some mqtt switches, but the following are not discovered: Philips Hue Motion sensors, Elgato Eve Motion Sensors, Bticino Legrand Contact sensor. Do you have some suggest? Thanks

**Comment by NorthernMan54** [comment]
@sherazan Are you using the Beta plugin mentioned above or the regular?

**Comment by sherazan** [comment]
Beta (I’m Italian)


Guido Vizioli

**Comment by NorthernMan54** [comment]
@sherazan, Can you update to the latest version of the Beta plugin, and try again.   Please remember that Native HomeKit devices are not supported by the plugin.  If you are not using a homebridge plugin to expose the device to HomeKit, Alexa will not be able to use it using my Alexa Skill.

**Comment by sherazan** [comment]
Ok, I understood: Elgato Eve Motion and Philips Hue Motion are native Homekit devices so Alexa can’t recognise them…

Thanks for explanation.

**Comment by NorthernMan54** [comment]
I have not tried this, but would you may be able to expose hue motion sensors thru the homebridge-hue plugin.  Then expose it to Alexa.

**Comment by sherazan** [comment]
Yes, but the Hue Motion Sensor is already visible in Homekit by default, so if I expose also by Homebridge plugin, the result will be duplicate sensors...

> Il giorno 19 feb 2019, alle ore 21:59, Northern Man <notifications@github.com> ha scritto:
> 
> I have not tried this, but would you may be able to expose hue motion sensors thru the homebridge-hue plugin. Then expose it to Alexa.
>

**Comment by martinorob** [comment]
I use hue motion sensor with Alexa trough the homebridge-hue e Alexa event

**Comment by martinorob** [comment]
> Yes, but the Hue Motion Sensor is already visible in Homekit by default, so if I expose also by Homebridge plugin, the result will be duplicate sensors...
> […](#)

i understand now.. duplicate on Home app not on Alexa.. true.. but never mind.. i'dont use home app for home automation since I meet Alexa on my life.. 😃

**Comment by NorthernMan54** [comment]
@sherazan You could create another instance of Homebridge, install the hue plugin into it.  And don't add it to the Home app.  Homebridge-alexa will discover it, and allow you to control via Alexa, and it won't be duplicate in the Home app.

**Comment by sherazan** [comment]
Yes, this is a good idea. Thanks for your suggest. I will try!

**Comment by sejoki** [comment]
> Yes, but the Hue Motion Sensor is already visible in Homekit by default, so if I expose also by Homebridge plugin, the result will be duplicate sensors...
> […](#)

If you’re using the Homebridge-hue Plugin, remove the bridge from HomeKit completely. I was running a setup where I only had Homebridge expose non-supported lights and had hue lamps and sensors through the hue bridge, but it was kind of a mess and also not compatible with this plugin. 
I finally redid everything and now the entire hue bridge is running through homebridge, much cleaner. The only downside is the extended latency of the sensors and switches, takes a couple of seconds to respond.

I‘m actually amazed how well this plugin works, when I tell Siri to turn off a device, it takes a couple of seconds. Alexa turns it off the second I stop talking and the command goes from my home to the Amazon server, from there to the homebridge.ca server, then back to my home.

 Is the next release going to support the sensors yet? Or are you keeping it in beta for a while? These „routines“ Amazon provides are slowly starting to piss me off :D

**Comment by NorthernMan54** [comment]
The event/sensor release is an open beta, you just need to install the beta version of the plugin, and follow the steps in the readme to enable sensors and events.  I haven’t published it as the main version yet as I had made some large scale code changes to support events and wanted to ensure it was 100% stable before wide scale launch.

There are a handful of people using it already, so if your anxious please go ahead and give it a try.

PS If Alexa routines are annoying, and the home app automations are doing it for you, check out my other side project Hap-NodeRed.  It also use of the really awesome NodeRed automation rules engine to control all your homebridge devices.

**Comment by sejoki** [comment]
I can’t find it anymore, but I think somewhere I read that the beta is only available for certain countries? If Germany is one of them, I’ll give it a try.

The main issue isn’t controlling HomeKit from Alexa, I can do that with a dummy switch that triggers a scene and like I said, it works better than through Siri. But it seems the only way to do it the other way around (like starting Spotify on the Echo in a HomeKit scene) is with a sensor.

But I’ll try the beta and also give your nodered plugin a try. My scenes and rules are working right now, but some of them are pretty cumbersome because of the limitations in HomeKit.

**Comment by NorthernMan54** [comment]
Originally it was limited to particular countries, as I needed to update the backend components to support events, and the updated backend was only visible to members in the new country support beta.  But since it was launched a few weeks ago, that restriction is gone and it is now an open beta.

Regarding homebridge-dummy, if you look in my repo’s I modified homebridge-dummy, and created homebridge-dummy-contact that exposes a contact controlled by the dummy switch.  That has not been published to the world yet, so the install instructions are broken at this time.  I haven’t yet decided if I’m going to use this to create custom contacts yet or NodeRed.  With the existing HomeKit NodeRed module, you can easily create virtual switches so my custom version of dummy could be redundant ( not mine ).

My NodeRed module allows creation of rules to control your existing homebridge accessories, and the other NodeRed module allows you to create virtual accessories.

**Comment by lily148** [comment]
Not sure why, I notice the door contact information is the opposite of homekit device.
Example: In homekit, door sensor show "Closed" but in Alexa, it show "Open". When I open the door - homekit show "Open" but Alexa turn to "Close"
Alexa report the wrong direction. Previously seem okay.... I notice this today.

**Comment by NorthernMan54** [comment]
All the mapping between HomeKit and Alexa is done in the plugin itself, so unless you updated the plugin the behaviour shouldn’t have changed.  But with that said, I may have it backwards as I don’t have a door in my setup, only garage door and motion sensors.

I’m out of the country for a week, so I won’t be able to look at this for about bit, but it is a simple change expect something after I’m back.

**Comment by lily148** [comment]
Yes, it is just the message stage is in wrong direction. I fork this project and try to change it... now the door contact is in correct status with homekit.

**Comment by NorthernMan54** [comment]
If you submit it back as a pull request, I can merge it remotely.  Pull request would need to be against the event branch.

**Comment by lily148** [comment]
Done, submitted a pull request for event branch :)

**Comment by NorthernMan54** [comment]
This is now the default version, with pull request #197
