### ISSUE TITLE
change the mode and turn on/off thermostat

### ISSUE THREAD

**Issue by gaojie429** [NorthernMan54/homebridge-alexa#179]
Finally I can use homebridge-alexa in Japan and it's works very well on my all Echo devices and Home bridge devices.
However I think it's better that I can change the mode and turn on or off my thermostat.
Of course, I read all description of this plugin and know that what this plugin can change is the target temperature of thermostat.
Do you have a plan to add this feature?

**Comment by NorthernMan54** [comment]
I'm looking at this and heater / cooler devices #157 

So your looking for the "Mode" button ?

**Comment by gaojie429** [comment]
May be slightly different.
I can change temperature of airconditioner. However, when I say "turn on airconditioner" or "set the mood to warm", alexa say that this airconditioner doesn't correspond to this kind of operation.
But I can turn on or set the mode to warm it through Apple Home app.
So,, I mean that I want you to add the feature that enable alexa to turn on airconditioner and change mode of it.


Thanks!
