### ISSUE TITLE
Status -70402

### ISSUE THREAD

**Issue by naish666** [NorthernMan54/homebridge-alexa#183]
Hello,

All devices are ok, but when I try to use a GarageDoorOpener it gave me the status -70402 and do nothing.

```
[2019-2-16 10:25:38] [Alexa] PowerController TurnOff 192.168.0.89 51826 { charac
teristics: [ { aid: 15, iid: 19, status: -70402 } ] } null
```
I have tried chage GarageDoorOpener to Lightbulb but same status error. 
Do you know why?

**Comment by NorthernMan54** [comment]
Homebridge error -70402 is from the accessory/platform plugin when the plugin itself returns an error.

The debug log should show exactly what is happening.  If you can run homebridge with debug logging enabled and collect the logs around 2 events.   First collect the log from when control your garage door with the Home app, and a second log from when you use Alexa.

This logging will be verbose, and the devil will be in the details as it will show the exact details of how the Home apps controls the door, versus Alexa.

To collect a debug log, start homebridge like this

DEBUG=* homebridge -I

**Comment by naish666** [comment]
I have fix the problem, using device type Lightbulb and reinstalling. Can I use any tipe of device that can open or close the device in %? The device are blinds, are there any solution?

**Comment by NorthernMan54** [comment]
Please keep in mind that Alexa does not support opening or closing blinds or doors at this time.   To work around this I mapped them as a on/off device.  On being open, and off being closed.

Personally I use the HomeKit type “Fan” for devices not supported by Alexa.  With HomeKit fans, on/off and % is mapped to Alexa.

For the wording issues with Alexa, I use a routine with my wording to make it easier to use

For my garage door, I added a routine ‘Open the Garage Door’, and mapped it turning on the garage door.

**Comment by naish666** [comment]
But, how dod you do to open the blind 50%? or 30%?
Define the device tipe in config.json to Fan and say: Alexa, turn on blidX at 50%?

**Comment by NorthernMan54** [comment]
Sorry, lets start again

Which plugin are you using for your Blinds?  

Currently I have mapped HomeKit "Window Covering/0000008C" to an Other/Blind in Alexa.  The interface is mapped like this

Turn On/Off - Open and close the blinds
Alexa set the power to 40% on `device` - Set the blinds to 40% open

PS I don't have any blinds, so this is all going to be trial and error

**Comment by Darko2** [comment]
I have shades through HomeWizard plugin.
Alexa recognizes them as Type Other (icon looks like a envelop). The device can not be set from Alexa devices, no controls.
But if I create a Routine and select this device I can select properties Power or Power level. The second gives me the option to set the blinds at 50% or any other value.
Now I can tell Alexa to run a routine as “Set shades to favorite” or Open shades...

Let me thank you NorthernMan54 for all the work and effort you put into this great plugin!

Hope this helps you naish666.

**Comment by naish666** [comment]
What you are saying is to create a routine that open the blind to a %? but If I want to open o close the blind to any % it is no possible? I have to create as much routines as % I want to use?

**Comment by Darko2** [comment]
I never tried to open to any other % as 50...
But effectively, yes.
Alternatively you can try voice like: alexa set power level on device to x%

One more thing I noticed, device discovery finds the same blind as a light and as other, so it is listed 2 times with same name.
The option to select type fan would work out greatly I think.

**Comment by Darko2** [comment]
Hello,

after the March 22 update Alexa only recognizes my blinds as switches (or lights) and it is not possible to set a % value on them.

Is there a workaround?

**Comment by NorthernMan54** [comment]
@Darko2 I had added an option to go

**Comment by NorthernMan54** [comment]
Can you open this as a new issue, and I can look into in.
