### ISSUE TITLE
outlet not working

### ISSUE THREAD

**Issue by martinorob** [NorthernMan54/homebridge-alexa#184]
Hi, is there a way to add Koogeek P1EU outlet or Elgato eve energy? I have those on Apple Home but I can't see on Alexa! (and on the Alexa Italian Store there trend Koogeek ora Elgato skill).

Thank you

M.

**Comment by NorthernMan54** [comment]
Sorry I can’t help directly with these.  But have you looked at homebridge-dummy?  You could create phantom switches using homebridge-dummy and create an automation in the HomeApp to allow Alexa to control them.

Create a dummy switch called “Fake Koogeek”, then create an automation that is triggered when “Fake Koogeek” is turned on, and turns on the real Koogeek.  And just repeat for the off

**Comment by martinorob** [comment]
okay i have already this, I was talking about a non workaround solution!

So thank you anyway!

#close
