### ISSUE TITLE
French Canadian not working anymore

### ISSUE THREAD

**Issue by natcl** [NorthernMan54/homebridge-alexa#187]
The beta for the French canadian version of the skill expired so I installed the official version. Since that time it doesn't work with voice anymore, if I say turn on the lights it says the skill associated with that command is not activated. Turning lights on and off via the Alexa app works however. Any ideas ?
Thanks!

**Comment by NorthernMan54** [comment]
Using the Alexa app on your phone have you tried disabling the homebridge skill and re-enabling?  Then discovering devices again?

**Comment by natcl** [comment]
Yes tried 2 times, devices are discovered fine and can be controlled through the app but voice fails.

**Comment by natcl** [comment]
More info:
It seems to work for anything that's not a light (wemo plugs work for example)

**Comment by NorthernMan54** [comment]
In the Alexa app there is an option to set the type of a device on the device details page.  Are the devices ‘Lights’ or ‘Plugs’?  For turn on the lights to work the device must be type light.

**Comment by natcl** [comment]
Seems like deleting all the devices and re-discovering did the trick. Strange thing in the past saying "éteindre les lumières" worked but not anymore. "Fermer les lumières" works though.

**Comment by NorthernMan54** [comment]
Hum, I wonder if amazon has made some minor changes to wording?  I have seen her get more particular about wording over time, as she used to respond to open/close as on/off but no longer does.  I wonder if something similar happened here.

**Comment by natcl** [comment]
Closing this for now as deleting the devices fixed the issue. Thanks!
