### ISSUE TITLE
[Feature Request] Friendly/Translated names

### ISSUE THREAD

**Issue by Tezzlicious** [NorthernMan54/homebridge-alexa#188]
Is it possible to add an extra options section where we can map original device names to translated/friendly names? We speak Dutch @ home and Alexa doesn't support Dutch yet. 

It would be cool if I could map some devices their original (in my case Dutch) name to an English name for Alexa.

**Comment by NorthernMan54** [comment]
Good suggestion, have you thought about just normalizing the name to English across the board though?  I find it very hard to keep track of the names of my 50+ devices, so having the home app as a name reference has been immense for other users in my household.

I have been thinking about this, and looking at this new Alexa api.  https://developer.amazon.com/docs/device-apis/resources-and-assets.html

What I can’t say is when I would get to it, I have a couple of things in the backlog so it may be a while, but if your a coder, pull requests for features are greatly appreciated.

**Comment by Tezzlicious** [comment]
That new API seems a perfect fit. Wish I had the time to learn and contribute...

Siri and Google now both speak Dutch, only Alexa has troubles learning it :P

Another thing is that doing it through the config of your plugin is resistant to deleting/resetting/forgetting home/device configs from the Home/Alexa app etc. You'll only have to do it once through the homebridge config.

Patience is the key I guess :) 

Thanks for all your time and hard work you're putting into this.

**Comment by NorthernMan54** [comment]
The ability for additional names being passed as part of the Alexa.discovery response does not appear to be coming any time soon, so closing this.
