### ISSUE TITLE
Feature Request - HomeKit/Siri to control Alexa

### ISSUE THREAD

**Issue by mikesalz** [NorthernMan54/homebridge-alexa#189]
Amazing plugin!  But, I am wondering if there is any way to do the reverse of the communication and allow HomeKit/Siri to control Alexa-enabled devices?  Thoughts?

**Comment by NorthernMan54** [comment]
This is totally unfeasible as Alexa controlled devices are using the vendors cloud to talk to Alexa, and it isn’t something I have systemic acces to. There may be one off devices where someone reverse engineers the api’s Like Tuya, but it is not something where could do wholesale.
