### ISSUE TITLE
Installation size and devDependencies

### ISSUE THREAD

**Issue by Lukcyluke** [NorthernMan54/homebridge-alexa#193]
I'm running _homebridge_ and _homebridge-alexa_ on a RPI zero w with limited storage and try to keep the disk as decluttered as possible. I noticed, that this package has a **75MB** installation size mostly due to npm being a dependency.
I'm not familiar with all the dependencies used in this plugin but it seems that some of them (for instance npm, update) are only used for development. So listing them as devDependencies (see [npm-package.json documentation](https://docs.npmjs.com/files/package.json#devdependencies)) in the `package.json` would save a lot of installation space.

Apart from that the plugin is a breeze to use and very useful. Thanks for that :)

**Comment by NorthernMan54** [comment]
@Lukcyluke That is already fixed in the current development branch "event", so I'm going to close this.

PS The event branch is almost ready for primetime, and will be launched shortly.

From the event branch

  "devDependencies": {
    "ava": "^1.2.1",
    "coveralls": "3.0.2",
    "documentation": "8.1.2",
    "nyc": "13.3.0",
    "xo": "0.23.0"
  },
  "dependencies": {
    "is-my-json-valid": ">=2.19.0",
    "debug": ">2.6.9",
    "mqtt": ">=2.18.8",
    "hap-node-client": ">=0.0.14"
  },

**Comment by Lukcyluke** [comment]
Nice. Thanks for your quick reply. I should have looked into the other branches before posting this 😅
