### ISSUE TITLE
device not responding with pm2

### ISSUE THREAD

**Issue by santiagos5** [NorthernMan54/homebridge-alexa#194]
hello,
i have a problem with homebridge. If I start homebridge in DEBUG mode it works and in alexa app I can see the status of devices (on, off and I can control them) but if I lauch homebridge via "pm2 start homebridge" in alexa app the device not responding if I try to alexa to discover new device nothing found.
I added -I to the file /etc/default/homebridge, maybe i need to add it somewhere else?

**Comment by santiagos5** [comment]
I finally found a solution: 
1. Remove homebridge from pm2 (`pm2 delete homebridge`)
2. Start pm2 with homebridge insecure mode `pm2 start homebridge -- -I`
3. Save (`pm2 save`)
It works! in `pm2 show homebridge` you can see in script args "-I"

**Comment by NorthernMan54** [comment]
@santiagos5 I added this to the README, can you take a moment and review this ?

https://github.com/NorthernMan54/homebridge-alexa/blob/master/README.md#prepare-homebridge-for-plugin-installation

I want to share your steps to help other users.

**Comment by santiagos5** [comment]
It’s right! pm2 show homebridge only for  check argument -I, is not necessary

**Comment by NorthernMan54** [comment]
I changed it up slightly, does that work?

**Comment by santiagos5** [comment]
Yes, it’s perfect! Thanks for your work
