### ISSUE TITLE
Another solution?

### ISSUE THREAD

**Issue by lprhodes** [NorthernMan54/homebridge-alexa#2]
Hey,

I could be wrong but reading this it sounds like there could be a simpler solution: https://digitized.house/2016/08/idevices-bridges-apple-homekit-amazon-alexa-worlds/

**Comment by NorthernMan54** [comment]
I just read that whole article, and they left this tidbit to the bottom

_There is one caveat here related to the Alexa support provided by iDevices. While the HomeKit architecture enables accessories from one manufacturer to be discoverable and controllable from an iOS app published by another manufacturer, the Alexa support in iDevices applies only to genuine iDevices accessories._

It seemed to good to be true.

**Comment by lprhodes** [comment]
Damn it sorry - it makes me wonder an iOS or tvOS app could be the way to go though. Technically if one of the HomeKit apps supported Alexa then they could control devices through the official SDK...

**Comment by NorthernMan54** [comment]
That would be technically feasible, but could be very complex to implement.  What it would expose, is HomeKit rooms, scenes, and groups which would be a huge plus.  Which my approach can't do.
