### ISSUE TITLE
plugin error

### ISSUE THREAD

**Issue by neruve** [NorthernMan54/homebridge-alexa#20]
I can't get this to function at all. 

I get the following:

ERROR LOADING PLUGIN homebridge-alexa:
Error: Cannot find module '/usr/lib/node_modules/homebridge-alexa/index.js'

Not sure what is going on. Help please.

**Comment by NorthernMan54** [comment]
Please read the instructions, this isn't a standard plugin but an updated version of homebridge.  And the install process is different

**Comment by neruve** [comment]
I have read the readme and exceuted the command to install. I just can't seem to get it to work. I have a previous version of homebridge installed that was working well. Do I need to remove the old homebridge alexa plugin that I tried? I'm so confused with this. Please help lol

**Comment by NorthernMan54** [comment]
It should just install overtop of the existing version.  If you could share some logs I could look at them.

**Comment by neruve** [comment]
No problem. Im actually trying a fresh install now. As I had a bunch of other stuff going on. But i used a new SD card. What do you need for a slack invite? It may be easier to troubleshoot.

**Comment by NorthernMan54** [comment]
If you go to the homebridge readme, the invite is there

**Comment by neruve** [comment]
I've looked at just about every readme file there is. All the slack links either don't work or take you to a login page asking for an invite :(

**Comment by neruve** [comment]
So I have the ecoplugs working again. However Alexa won't find anything when you ask it to discover devices

**Comment by neruve** [comment]
When I try to do sudo npm -g update I get the attached. I'm guessing this isn't normal but I can't figure out what the problem is.
[npm_update.txt](https://github.com/NorthernMan54/homebridge-alexa/files/1150589/npm_update.txt)

I've tried to do DEBUG=hue homebridge 

and DEBUG=hue homebridge -D 

and neither create a log in /var/logs

Also alexa instantly says no devides, within two seconds.

**Comment by NorthernMan54** [comment]
Your version of nodejs is way out of date and needs updating.  Please update and try again

**Comment by neruve** [comment]
I've tried so much thoughout the day and now i'm even more lost.

maybe someone will be nice enough to ssh into my pi and set it up for me hahahahahahhaa

**Comment by NorthernMan54** [comment]
The setup from should be simple,  follow one of the homebridge setup tutorials, get it working, then install this overtop. I'm on slack some evenings around 7pm eastern, but depends on what is happening at home and work.  If you ping me there, we find a time that works.

**Comment by Krocko** [comment]
Any chance for an update to 4.22?

**Comment by NorthernMan54** [comment]
Check back in a day or 2, I just need to merge.

**Comment by Krocko** [comment]
Thank you very much 👍🏻

**Comment by neruve** [comment]
Okay, so I have a full working setup. It works how i want it to right now. All but Alexa. How to I make that work? Do i just run the "sudo npm install -g https://github.com/NorthernMan54/homebridge" command. Do I need the --unsafe-perm like just about everything else?

Also how do I update things like HAP-NodeJS I think that is where it was messed up last time :(

**Comment by NorthernMan54** [comment]
For your install if you need —unsafe-perm then please use that option.  The install will update HAP-NodeJS as needed as well, no need for additional steps.

**Comment by neruve** [comment]
This is what I get when I try:

 sudo npm install -g --unsafe-perm https://github.com/NorthernMan54/homebridge
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/NorthernMan54/homebridge.git /root/.npm/_cacache/tmp/git-clone-a1da5ca2
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-a1da5ca2': Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-16T23_36_44_604Z-debug.log

[log.txt](https://github.com/NorthernMan54/homebridge-alexa/files/1151414/log.txt)

**Comment by NorthernMan54** [comment]
The error is saying that it received permission denied on this directory

/root/.npm/_cacache/tmp/git-clone-a1da5ca2


what does ls -l /root/.npm/_cacache/tmp/git-clone-a1da5ca2

show?

PS I’m on slack now and in the # hap-alexia channel

**Comment by neruve** [comment]
I still haven't been able to find the invite for slack. can you post an invite link here?

**Comment by neruve** [comment]
and ls -l /root/.npm/_cacache/tmp/git-clone-a1da5ca2 also says permission denied

**Comment by NorthernMan54** [comment]
For slack, try here

https://slackin-xiwztisllv.now.sh <https://slackin-xiwztisllv.now.sh/>

**Comment by Krocko** [comment]
Try this

sudo chown -R $USER /usr/local && npm install -g https://github.com/NorthernMan54/homebridge
