### ISSUE TITLE
Question/Explanation

### ISSUE THREAD

**Issue by sherazan** [NorthernMan54/homebridge-alexa#200]
Hi, I would ask you a smart clarify about this two points:
1 - "routines": true - how could be used this parameter and what is his utility?
2 - about the sentence "unlink the skill and relink the skill in the Alexa app", should I "deactivate" and reactivate" the skill in the skill section?

Thanks for your support

**Comment by NorthernMan54** [comment]
1 - This setting enables mention and contact sensors to be made available in Alexa routines, so that you can have an Alexa routine triggered by a motion or contact sensor.

I use this with a contact sensor on my garage door, so that Alexa announces my garauge door being opened or closed.

2 - Yes, deactivate and activate the skill in the Alexa app.  The unlink button here

![876905E5-F083-420F-A7FE-02AD794F3553](https://user-images.githubusercontent.com/19808920/55230000-e5283b80-51f4-11e9-822f-e1bd8c9d06a4.png)

**Comment by sherazan** [comment]
Done! Now I see my contacts in the Routines section! Great! Thanks! 


Guido Vizioli

**Comment by sherazan** [comment]
Hi, after I've implemented "routine" parameter, I'm receiving this error:
**[Alexa] ERROR:  Event Gateway Response Code: 400**
Do you have suggest?
Thanks

**Comment by NorthernMan54** [comment]
Try disabling and re-enabling the skill again

Troubleshooting.MD <https://github.com/NorthernMan54/homebridge-alexa/blob/master/Troubleshooting.MD#alexa-error--event-gateway-token-refresh-error-400>

**Comment by sherazan** [comment]
Done. I will monitor and I will update you.

Thanks



> Il giorno 31 mar 2019, alle ore 19:55, Northern Man <notifications@github.com> ha scritto:
> 
> Try disabling and re-enabling the skill again
> 
> Troubleshooting.MD <https://github.com/NorthernMan54/homebridge-alexa/blob/master/Troubleshooting.MD#alexa-error--event-gateway-token-refresh-error-400>
> 
> 
>

**Comment by NorthernMan54** [comment]
Does this change to the README make it easier to fix this? 

master <https://github.com/NorthernMan54/homebridge-alexa/tree/master#optional-parameters>

**Comment by sherazan** [comment]
I would suggest to specify that this is a MUST to have events passed to the plugin, because someone (me?) could understand that is a “nice to have”



> Il giorno 31 mar 2019, alle ore 20:22, Northern Man <notifications@github.com> ha scritto:
> 
> Does this change to the README make it easier to fix this? 
> 
> master <https://github.com/NorthernMan54/homebridge-alexa/tree/master#optional-parameters>
>

**Comment by NorthernMan54** [comment]
Better ?

master <https://github.com/NorthernMan54/homebridge-alexa/tree/master#optional-parameters>

**Comment by sherazan** [comment]
Absolutely yes! :-)

> Il giorno 31 mar 2019, alle ore 20:37, Northern Man <notifications@github.com> ha scritto:
> 
> Better ?
> 
> master <https://github.com/NorthernMan54/homebridge-alexa/tree/master#optional-parameters>
>

**Comment by NorthernMan54** [comment]
Tks
