### ISSUE TITLE
Updated HomeKit parser to handle complex devices

### ISSUE THREAD

**Issue by NorthernMan54** [NorthernMan54/homebridge-alexa#201]
Update HomeKit device parser, based on one device per service to match Home apps creation of one icon per service.  Development is in the ServiceParsing branch

This is needed to resolve issue #192 and #157 

Outstanding items before publishing

# Published as version 0.4.8

* [x] Parsing of basic devices
* [x] Paring of speakers devices
* [x] Parsing of basic devices ( Lights, switches and outlets )
* [x] Parsing of Apple TV Devices into Playback Service
* [x] Combine multiple accessories into TV service ( On/Off and Volume )
* [x] Playback control service from Yamaha stereo / spotify control
* [x] Combine Yamaha Playback with Yamaha Speaker
* [x] Parsing of motion sensor for events
* [x] Parsing of contact sensor for events
* [x] Clean up extraneous debug statements
* [x] Clean up AppleTV Parsing
* [x] Add config.json parameter to allow selective use of new device parser `oldParser`

# Published as version 0.3.7

* [x] Parsing of door locks for discovery
* [x] Controlling door locks

# Published as version 0.4.8

* [x] Parsing of Thermostats
* [x] Control of Thermostats
* [x] Parsing of Heater and Coolers
* [x] Control of Heater and Coolers

# Published as version 0.4.11

* [x] Parsing of new HomeKit TV and Speaker for discovery
* [x] Control of new HomeKit TV and Speaker
* [x] Parsing of Bose Sound touch presets for discovery and mapping to alexa.channelcontroller interface
* [x] Control of alexa.channelcontroller interface

# Future Release

* [x] Flow limits for event messages ( error 429 )
* [x] User status page on homebridge.ca
* [ ] Add device model to presence message

**Comment by NorthernMan54** [comment]
Bose SoundTouch 300 - These are switching from switches to speaker

Dyson Pure Cool Link Fan - The Alexa name is switching from "Dyson Pure Cool Link Fan" to "Dyson Pure Cool Link"

**Comment by NorthernMan54** [comment]
To install this feature branch do this

```
npm install -g NorthernMan54/homebridge-alexa#ServiceParsing
```

And enable the new device parser with this config.json setting `newParser`

```
{
    "platform": "Alexa",
    "name": "Alexa",
    "username": "XXXXXXX",
    "password": "XXXXXXX",
    "routines": true,
    "newParser": true
  }

```

**Comment by NorthernMan54** [comment]
* [x] Parsing of basic devices
* [x] Paring of speakers devices
* [x] Parsing of basic devices ( Lights, switches and outlets )
* [x] Parsing of Apple TV Devices into Playback Service
* [x] Combine multiple accessories into TV service ( On/Off and Volume )
* [x] Playback control service from Yamaha stereo / spotify control
* [x] Combine Yamaha Playback with Yamaha Speaker
* [x] Parsing of motion sensor for events
* [x] Parsing of contact sensor for events
* [x] Parsing of door locks for discovery
* [x] Controlling door locks
* [x] Parsing of Thermostats
* [x] Control of Thermostats
* [x] Parsing of Heater and Coolers
* [x] Control of Heater and Coolers
* [x] Clean up extraneous debug statements
* [x] Clean up AppleTV Parsing
* [x] Add config.json parameter to allow selective use of new device parser `newParser`

**Comment by Zaphor88** [comment]
Pls Support homebridge-samsung-tizen for Samsung TV to use with iOS 12.2.

**Comment by NorthernMan54** [comment]
@Zaphor88, with the current version you should have on/off and limited volume control

**Comment by Zaphor88** [comment]
the Alexa app can not find the Samsung tv.
does the Samsung tv have to have a specific name like the Apple TV since 0.4.8 so it works?

**Comment by NorthernMan54** [comment]
Please open this as a separate issue, and include a homebridge accessory dump so I can troubleshoot why it isn’t discovering your tv.  Details to collect an accessory dump are here.

https://github.com/NorthernMan54/homebridge-alexa#homebridge-accessory-dump
