### ISSUE TITLE
Skill don't find device

### ISSUE THREAD

**Issue by Scialla** [NorthernMan54/homebridge-alexa#202]
Hi,
during normal use and installing some new plugin, i've deleted all device in alexa and try to re-add all device witch a new scan, but Alexa don't find any device.
Log reported no issue:
pi@retropie:~ $ sudo tail -f /var/log/syslog | grep alexa
Apr 11 17:27:06 retropie homebridge[25474]: [2019-4-11 17:27:06] Loaded plugin: homebridge-alexa
Apr 11 17:27:06 retropie homebridge[25474]: [2019-4-11 17:27:06] Registering platform 'homebridge-alexa.Alexa'
Apr 11 17:27:15 retropie homebridge[25474]: [2019-4-11 17:27:15] [Alexa] homebridge-alexa v0.3.7, node v8.15.1, homebridge v0.4.48
Apr 11 17:27:37 retropie homebridge[25474]: [2019-4-11 17:27:37] [Alexa] alexaDiscovery - returned 71 devices
Apr 11 17:29:15 retropie homebridge[25474]: [2019-4-11 17:29:15] [Alexa] alexaDiscovery - returned 71 devices

i've removed skill from alexa and installed again but nothing is changed
i've try to remove plugin and skill eand installed again, nothing in changed
Before that all work fine..
There is any cache persisted ?

How can i do?

Thanks

This is report in debug mode:
Apr 11 18:43:29 retropie homebridge[4033]: [2019-4-11 18:43:29] Loaded plugin: homebridge-alexa
Apr 11 18:43:29 retropie homebridge[4033]: [2019-4-11 18:43:29] Registering platform 'homebridge-alexa.Alexa'
Apr 11 18:43:37 retropie homebridge[4033]: [2019-4-11 18:43:37] [Alexa] homebridge-alexa v0.3.7, node v8.15.1, homebridge v0.4.48
Apr 11 18:43:39 retropie homebridge[4033]: 2019-04-11T16:43:39.501Z alexaLocal Connecting to Homebridge Smart Home Skill
Apr 11 18:43:40 retropie homebridge[4033]: 2019-04-11T16:43:40.927Z alexaLocal connect command/Scialla/#
Apr 11 18:43:59 retropie homebridge[4033]: 2019-04-11T16:43:59.573Z alexaTranslator Alexa Controllable Homebridge 70
Apr 11 18:43:59 retropie homebridge[4033]: [2019-4-11 18:43:59] [Alexa] alexaDiscovery - returned 70 devices

**Comment by NorthernMan54** [comment]
Looking at the log, the plugin returned 71 devices to Alexa so they should be visible in the Alexa app.  Have you tried asking Alexa to discover devices?

**Comment by Scialla** [comment]
Yes but Alexa don't find anything....
i'm continuing removing plugin, reinstalling plugin, removing skill, reinstalling skill. Device are discovered but alexa don't find anything.... :(

**Comment by NorthernMan54** [comment]
I need to look at the server logs, can you share your account?

**Comment by Scialla** [comment]
i found the problem......
the problem is one plugin
the plugin is homebridge-mqtt-power-consumption-log-tasmota

when i installing this plugin, your plugin discover correctly device but alexa skill don't find any device
when i remove plugin homebridge-mqtt-power-consumption-log-tasmota alexa find all device

can you understand why?
if you want i can post my device configuration (not all only part of plugin homebridge-mqtt-power-consumption-log-tasmota)
thanks

**Comment by Scialla** [comment]
This is what i do:
i restore old backup -> work (alexa find device discovered)
i upgrade HB & install other plugin, update configuration (json) -> don't work
i remove new plugin installed, one at time with its part of config in json, and try find device every plugin removed; when i removed homebridge-mqtt-power-consumption-log-tasmota -> work again BUT
i try to install again this plugin and update json one device at time, and try to find device and work
installed all plugin removed, work
i don't understand why, now is the same initial configuration, but work
... testing

thanks for all

**Comment by NorthernMan54** [comment]
Sorry I’m not following the dialog, what are you saying?

**Comment by Scialla** [comment]
Sorry if i wasn’t clear..

the issue is solved

the problem was partial incompatibility with other plugin

you can close issue

Many thanks for your help

Best Regards

> Il giorno 12 apr 2019, alle ore 15:58, Northern Man <notifications@github.com> ha scritto:
> 
> Sorry I’m not following the dialog, what are you saying?
> 
> 
>

**Comment by NorthernMan54** [comment]
Tks
