### ISSUE TITLE
after update (0.4.8) erorr

### ISSUE THREAD

**Issue by marcoschmidt79** [NorthernMan54/homebridge-alexa#205]
hello after update i have a error:

HINWEIS: Apr 15 04:51:55 homebridge Alexa ERROR: Error: getAccessToken Tonken not found

**Comment by NorthernMan54** [comment]
Did you try this?

https://github.com/NorthernMan54/homebridge-alexa/blob/master/Troubleshooting.MD#error--error-getaccesstoken-token-not-found
