### ISSUE TITLE
ERROR:  Event Gateway Response Code: 400

### ISSUE THREAD

**Issue by sherazan** [NorthernMan54/homebridge-alexa#206]
Hi, about this error, i discovered that it is displayed every time a blind is actioned; I don't have any routine that envovles blinds; I've 6 blinds managed in homebridge by bticino plugin and discovered and managed by Alexa, but without any routine. The error is displayed for every up and down command.
Please, let me know.
Thanks

**Comment by NorthernMan54** [comment]
You can ignore this, I have a couple of instances of badly formed event messages when doors and blinds are moving
