### ISSUE TITLE
Blinds can not be set to a % value

### ISSUE THREAD

**Issue by Darko2** [NorthernMan54/homebridge-alexa#207]
Hello,

after the March 22 update Alexa only recognizes my blinds as switches (or lights) and it is not possible to set a % value on them.

Is there a workaround?

I am using Homebridge-homewizard plugin for the blinds.

_Originally posted by @Darko2 in https://github.com/NorthernMan54/homebridge-alexa/issues/183#issuecomment-484864933_

**Comment by Darko2** [comment]
Just an update:

Today I ran Discover devices again. The blinds were found also as type other now.
So every blind is listed as type switch and again as type other.
When I use the blind type other through Routines it gives me options to adjust its Power (on/off) or its Power level (0 to 100 %).
I dont use the Power option, but use the Power level one.
The difference is, the old Homebridge-Alexa did that fine, now the blinds start moving for a second (to 50% Power level setting) then move to the Power setting (although it is not selected in the routine).

**Comment by NorthernMan54** [comment]
@Darko2 I think I found the issue, try installing the latest version ( 0.4.10 )
and running discover devices again.

**Comment by Darko2** [comment]
Hey,
I installed the 0.4.10 version, forgot all devices and ran discover devices again.
Alexa found only one of each blind, as type switch (customizable to light). 
The one with type Other is not present in the device list.
In the Routines I can not set any other option than on/off to a switch device.

I will check and discover devices again tomorrow, as last time alexa needed a night to find blinds as devices with type other (which can be set to a % of value) .

**Comment by Darko2** [comment]
I tried discovery again with echo dot (earlier I did it on the iOS app). Now also the blinds with type other were found and the issue with routines is gone.
I can set a routine, define a power level and it works fine.

Thank you for all your work and help!

**Comment by NorthernMan54** [comment]
Tks for the update.
