### ISSUE TITLE
long delay with lamps in homebridge

### ISSUE THREAD

**Issue by thhuss** [NorthernMan54/homebridge-alexa#208]
since today, routines and groups take a long time. what could be the problem?
Everything worked in the morning.

**Comment by cyberfafu** [comment]
Same here! Maybe a server problem?

**Comment by NorthernMan54** [comment]
If you watch the homebridge / slack channel #hap_alexa you can see the service status is almost real time.  I’m using “Uptime Robot” to monitor the back servers, and they have been grumbling all day.  As of about 4:30pm eastern, it should now be stable.  To stabilize the service I upgraded the homebridge.ca <http://homebridge.ca/> server, basically doubling the capacity.
