### ISSUE TITLE
ssdp conflict with HDHomeRun DVR device

### ISSUE THREAD

**Issue by funkyvisions** [NorthernMan54/homebridge-alexa#21]
Any ideas how to not conflict with a device already using ssdp 1900?

sudo lsof -i :1900
hdhomerun 110 _HDHomeRun   13u  IPv4 0xcc0db234ab963427      0t0  UDP *:ssdp

If I disable that service then I can get homebridge to run.  However, Alexa isn't discovering it.  I'm trying to use this as a bridge from Alexa to my HomeKit enabled Insteon Hub (which then controls it's own protocol devices).

**Comment by NorthernMan54** [comment]
When I open the socket, I'm opening it with the 'reuse' flag.

 udpServer = dgram.createSocket({type: 'udp4', reuseAddr: true});

I'm wondering if your hdhomerun is not opening the socket re-usable?   I also had problems with Kodi using the same socket, and had to set this up to allow it to be opened as shared.   And the problem with Kodi went away.

**Comment by funkyvisions** [comment]
Sorry, was out of town. Just getting back to this.  I'll check on the hdhomerun.  But even if I removed the homerun I still couldn't get it to work.  Shouldn't the device have been discoverable at that point?

**Comment by NorthernMan54** [comment]
Correct,  it should have been discoverable.   If you start in DEBUG mode there is logging around the setup of port 1900 and the discovery process.  I have seen some issues with machines that have multiple network interfaces, but besides that it has worked very well for people.
