### ISSUE TITLE
Unlock smart lock devices by voice PIN

### ISSUE THREAD

**Issue by mazafra1** [NorthernMan54/homebridge-alexa#213]
Any chance to include this new Alexa feature in here?

https://medium.com/@tonykakkar2018/how-to-unlock-smart-locks-with-amazon-alexa-20d794533d02

https://www.howtogeek.com/353671/how-to-unlock-your-smart-locks-with-alexa/

Thanks for your great work!

**Comment by NorthernMan54** [comment]
Are the steps mentioned here available to you? I don’t see this mentioned in the API documentation, hence the question.

**Comment by mazafra1** [comment]
No, they aren't. Might this be only related to the Alexa skill and not on homebridge plugin side?

I've just found this: https://forums.developer.amazon.com/questions/190370/alexa-voice-pin-door-lock.html

Thanks.

**Comment by NorthernMan54** [comment]
I quickly looked at the skill definition screens and nothing jumped out at me.

What I found troubling was that the link you included did not get into any details around how to enable the lock feature.  And when I look at the API documentation I don’t see the PIN being mentioned.

**Comment by NorthernMan54** [comment]
Let’s see what this gets as a response

https://www.reddit.com/r/AmazonEchoDev/comments/biykqq/added_smart_locks_to_my_skill_but_alexa_wont_let/

**Comment by NorthernMan54** [comment]
And since using reddit didn't work, I tried Amazon support forums

https://forums.developer.amazon.com/questions/205373/alexalockcontroller-unable-to-unlock-door.html

**Comment by NorthernMan54** [comment]
I was looking at some other docs, and saw this

Alexa | LockController | Smart home | de-DE, en-US, ja-JP

Lock controller is only supported in these regions, I wonder if that is the issue?

**Comment by mazafra1** [comment]
That would make sense. Let’s wait for someone from one of those regions to test.

**Comment by NorthernMan54** [comment]
@mazafra1 I submitted the skill for certification, and had the test account include smart locks.  Maybe there is a flag on the amazon side that needs to be enabled

**Comment by mazafra1** [comment]
Yes, that could be too., but I'd bet for the region blocking as the main cause.

Thanks for all your work, man.

**Comment by NorthernMan54** [comment]
@mazafra1 and I  just head back that it passed and is published.  And I just checked my Alexa app, and it does not have the ability to set voice pin or  unlock
