### ISSUE TITLE
[Feature Request] Harmony Hub Supprot

### ISSUE THREAD

**Issue by cmb991** [NorthernMan54/homebridge-alexa#214]
Feature Request:

Support for Harmony Hub.  I have two hubs right now, and they are connected to homebridge.  When I use the homebridge-alexa, it only has the 'on and off' functionality.  Support for changing input or running activities would be nice.  "Alexa turn on Bedroom Apple TV" vs "Alexa turn on Bedroom TV"

**Comment by Krocko** [comment]
Why don‘t you use the harmony skill?

**Comment by cmb991** [comment]
The harmony skill only supports 1 hub.  They have a second skill for a secondary hub, and that’s it.  So if you have a hub on a few TVs, you are screwed. :/

**Comment by cmb991** [comment]
I am also willing to provide the bounty for this feature

**Comment by Krocko** [comment]
Ok that is right. 
What Harmony plugin are you using?
I use the homebridge-harmony plugin from @nicoduj. 
https://github.com/nicoduj/homebridge-harmony
I have switches for every activity. 
Maybe you can test if this switches are exposed to alexa.

**Comment by cmb991** [comment]
I am using that same plugin.  The issue is the amount of hubs.  If you have more than one hub, then you need to install the skill “Harmony Secondary Hub”.  That allows two hubs.  If you have 3 hubs or more…. Your screwed.

**Comment by Krocko** [comment]
I understand. 
But have you configured the plugin to have separate switches for every activity?
Have you a switch for every activity in homekit?
I think homebridge-alexa should expose this switches.

**Comment by cmb991** [comment]
If I go into homekit, I have a switch for every activity.  If I look at my devices in alexa, it only shows both devices (so I can only say turn on bedroom tv).  It doesn’t show anything about activities in alexa.

**Comment by Krocko** [comment]
Can you please show your config.json for the homebridge-harmony plugin?

**Comment by cmb991** [comment]
{

            "platform": "HarmonyHubWebSocket",

            "name": "ChrisHarmonyHub",

            "hubIP": "192.168.86.13",

            "showTurnOffActivity": true,

            "TVPlatformMode": true,

            "refreshTimer": 30

        },

        {

            "platform": "HarmonyHubWebSocket",

            "name": "ChrisHarmonyHub2",

            "hubIP": "192.168.86.16",

            "showTurnOffActivity": true,

            "TVPlatformMode": true,

            "refreshTimer": 30

        },

**Comment by Krocko** [comment]
You have the `TVPlatformMode` to `true`
Add your hubs a second time to the config without this line
`    "TVPlatformMode" : true,`

**Comment by cmb991** [comment]
> Any chance you could give me an example config for two hubs with two activities each one?  Please.  I’m still new to this.  I know right now if I go into my home app, it shows me each TV. If I click on each TV, I have an Input option in the bottom left and the activities are in there.  

Hub1
activity 1
activity 2

Hub2
activity1
activity2

**Comment by Krocko** [comment]
{

            "platform": "HarmonyHubWebSocket",

            "name": "ChrisHarmonyHub",

            "hubIP": "192.168.86.13",

            "showTurnOffActivity": true,

            "TVPlatformMode": true,

            "refreshTimer": 30

        },

        {

            "platform": "HarmonyHubWebSocket",

            "name": "ChrisHarmonyHub2",

            "hubIP": "192.168.86.16",

            "showTurnOffActivity": true,

            "TVPlatformMode": true,

            "refreshTimer": 30

        },
{

            "platform": "HarmonyHubWebSocket",

            "name": "ChrisHarmonyHub",

            "hubIP": "192.168.86.13",

            "showTurnOffActivity": true,

            "refreshTimer": 30

        },

        {

            "platform": "HarmonyHubWebSocket",

            "name": "ChrisHarmonyHub2",

            "hubIP": "192.168.86.16",

            "showTurnOffActivity": true,

            "refreshTimer": 30

        },

**Comment by cmb991** [comment]
If I’m not mistaking, this would take the place of the input option in homekit?  So each activity would be listed out.  “Watch TV Living Room”  “Watch Apple TV Living Room” and the off icons as well?

**Comment by Krocko** [comment]
Yes this is correct.
You have your TV accessories in Homekit + separate switches/toggles for every activity.
Now homebridge-alexa exposes this switches to alexa.

![IMG_3601](https://user-images.githubusercontent.com/29394115/57177107-f9e59800-6e60-11e9-80f4-591ee573bbd4.png)

**Comment by nicoduj** [comment]
Hello guys, I don't have alexa devices so can't really help you on this, but concerning the plugin itself be aware of 2 things :
In 0.7 -> you can only have one TV device that will be exposed in Remote app on ios. You need to switch to 1.0.0 to have multiple as external devices. (in rc right now, will be released soon but will need some modification of your config and Only ONE platform and not multiple ones like in your examples).
You have an option to publish each activity switch as individual accessories in homekit or services of the same accessory (by default it is one accessor per switch). Maybe it will have some effect on alexa plugin.
Refreshtimer is sueless in latest version, I have the real state of the hub through eventing

**Comment by cmb991** [comment]
Does your homekit look like this?  Or individual switches?  Bottom pic has the input option.



Input Option:

**Comment by Krocko** [comment]
What do you mean?

**Comment by NorthernMan54** [comment]
For the iOS 12.2 TV Accessories, input's are not wired up as Alexa has a fixed list of input names, and HomeKit allows any name.  As I could not figure out an easy mapping method, so I parked working on it.  I may pick it back up once I change my main TV system to use the iOS 12.2 TV Accessories.

The Amazon list is here

https://developer.amazon.com/docs/device-apis/alexa-property-schemas.html#input

**Comment by cmb991** [comment]
If I’m understanding you correctly, I have two options.  Keep the inputs setup with harmony hub and homebridge, but just have basic turn off/on function with alexa OR map each activity in homebridge as a separate ‘button/switch’ and that mapping will copy over to alexa via this.   Is that correct?

**Comment by NorthernMan54** [comment]
Sorry am not an expert on homebridge-harmony and don’t have it in my setup so can’t comment on the best options.
