### ISSUE TITLE
Cloudservice Buggy? Device Recovery not correct working?

### ISSUE THREAD

**Issue by dlater** [NorthernMan54/homebridge-alexa#215]
Hello, 

after an update of the Homebridge and the current Alexa plugin I will not see devices in the app. I use the following systems: Fibaro Hub (homebridge-fibaro), Harmony Hub, etc. It used to be everything. Now I've reinstalled the Homebridge several times and the new Alexa plugin. Even the Alexa already resettet. Homebridge was started with the parameter -I (homebridge -I) and a new account created in the skill activation and the config adapted. No devices recognize the Alexa and the Homebridge shows only: ([5/4/2019, 8:27:59 PM] [Alexa] alexaDiscovery - returned 24 devices
). I have worked through the complete help and can there exclude any error except for the cloud service. Does anyone or even the developer have an idea?

**Comment by dlater** [comment]
Hello again,

the debug say:

[5/4/2019, 9:00:20 PM] [homebridge-config-ui-x] Console v4.2.0 is listening on :: port 8080
  alexaLocal connect command/Dlater/# +5s
  alexaActions alexaDiscovery +0ms
[5/4/2019, 9:00:36 PM] [Alexa] alexaDiscovery - returned 24 devices
  alexaActions registerEvents [ '{"host":"192.168.178.61","port":51826,"aid":2,"iid":10}': { '0': 'NOT_DETECTED',
    '1': 'DETECTED',
    endpointID:
     'Q0M6MjI6M0Q6RTM6Q0U6MzEtSG9tZWJyaWRnZS1JbENhdG8tSGF1c3TDvHItMDAwMDAwODAtMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx',
    template: 'ContactSensor' },
  '{"host":"192.168.178.61","port":51826,"aid":23,"iid":10}': { endpointID:
     'Q0M6MjI6M0Q6RTM6Q0U6MzEtSG9tZWJyaWRnZS1JbENhdG8tQmV3ZWd1bmdzbWVsZGVyLTAwMDAwMDg1LTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==',
    true: 'DETECTED',
    false: 'NOT_DETECTED',
    template: 'MotionSensor' } ] +48ms
  alexaActions Event Register 192.168.178.61:51826 -> { characteristics:
   [ { aid: 2, iid: 10, ev: true },
     { aid: 23, iid: 10, ev: true } ] } +19ms
  alexaLocal Emitting Alexa.Discovery +1m
  alexaActions alexaDiscovery +1m
[5/4/2019, 9:01:45 PM] [Alexa] alexaDiscovery - returned 24 devices

**Comment by dlater** [comment]
Hello again,

the debug say:

[5/4/2019, 9:00:20 PM] [homebridge-config-ui-x] Console v4.2.0 is listening on :: port 8080
alexaLocal connect command/Dlater/# +5s
alexaActions alexaDiscovery +0ms
[5/4/2019, 9:00:36 PM] [Alexa] alexaDiscovery - returned 24 devices
alexaActions registerEvents [ '{"host":"192.xxx.xxx.XX","port":51826,"aid":2,"iid":10}': { '0': 'NOT_DETECTED',
'1': 'DETECTED',
endpointID:
'Q0M6MjI6M0Q6RTM6Q0U6MzEtSG9tZWJyaWRnZS1JbENhdG8tSGF1c3TDvHItMDAwMDAwODAtMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx',
template: 'ContactSensor' },
'{"host":"192.168.178.61","port":51826,"aid":23,"iid":10}': { endpointID:
'Q0M6MjI6M0Q6RTM6Q0U6MzEtSG9tZWJyaWRnZS1JbENhdG8tQmV3ZWd1bmdzbWVsZGVyLTAwMDAwMDg1LTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==',
true: 'DETECTED',
false: 'NOT_DETECTED',
template: 'MotionSensor' } ] +48ms
alexaActions Event Register 192.168.178.61:51826 -> { characteristics:
[ { aid: 2, iid: 10, ev: true },
{ aid: 23, iid: 10, ev: true } ] } +19ms
alexaLocal Emitting Alexa.Discovery +1m
alexaActions alexaDiscovery +1m
[5/4/2019, 9:01:45 PM] [Alexa] alexaDiscovery - returned 24 devices

**Comment by NorthernMan54** [comment]
Asked a question on slack

**Comment by Shana611** [comment]
After updating the new update of Alexa Homebridge Plug in does not discover Somfy Tahoma products. Can you help me with this issue pls.

**Comment by NorthernMan54** [comment]
@Shana611 please open a separate issue and include an accessory dump

https://github.com/NorthernMan54/homebridge-alexa#homebridge-accessory-dump

**Comment by NorthernMan54** [comment]
Problem ended up being a device name with characters that where not handled by Amazon and caused discovery to fail on the amazon side.  Fixed by stripping invalid characters.
