### ISSUE TITLE
More session on same network

### ISSUE THREAD

**Issue by kiondi** [NorthernMan54/homebridge-alexa#216]
Hi
In my house i have more raspberry for controlling devices.
How can I install more homebridge-alexa plugins in the same network without having the error:
_You have an issue with your installation, please review the README

thank you in advice
Marco

**Comment by NorthernMan54** [comment]
You need to install it only once per house, it will discover the other homebridge instances and connect them all to Alexa.

**Comment by kiondi** [comment]
thanks for the instant reply, I had tried to install only on one of 3 raspberry but in this mode alexa 
does not find other devices on raspberry 2 and 3.

i ha tried to set in config .json the same name:

{
	"bridge": {
		"name": "**Casa**",
		"username": "F4:11:F2:44:11:61",

but alexa still can't find other devices :(
best regrads
Marco

**Comment by NorthernMan54** [comment]
If you start homebridge in DEBUG mode I will log the discovery process and show what it finds.

https://github.com/NorthernMan54/homebridge-alexa#debug-logs

**Comment by kiondi** [comment]
Found it !!

http://192.168.0.113:51827 invalid PIN or homebridge is not running in **insecure mode** 


many thanks for support!!
cheers
Marco

**Comment by NorthernMan54** [comment]
Glad to hear you go it working
