### ISSUE TITLE
Motion sensor detected and show correct status in Alexa device list, but not show up in routines

### ISSUE THREAD

**Issue by huongminh** [NorthernMan54/homebridge-alexa#219]
I could not see my motion sensors iwhen setting a routine in alexa. The motion sensor can be seen in alexa device list and show correct status. The plug in work well with all other devices. I disabled and enabled the skill after Mar 22th but not after I added the line "routines": true in config.json. Do I have to disable and enable the skill again to make  my motion sensors work in routines? Thank you for your great plugin.

**Comment by NorthernMan54** [comment]
You should not have to disable and re-enable the skill to have it appear as an option in routines.  After setting routines to true in config.json, did you ask Alexa to discover devices?

Also what country/language are you using?

**Comment by huongminh** [comment]
Thank you! I delete the sensor and rediscover devices and now it shows up as an option in routines. Interestingly I also found all my curtains in routines as device options that can be selected close/open


Sent from Yahoo Mail for iPhone


On Sunday, May 12, 2019, 8:00 PM, Northern Man <notifications@github.com> wrote:


You should not have to disable and re-enable the skill to have it appear as an option in routines. After setting routines to true in config.json, did you ask Alexa to discover devices?

Also what country/language are you using?

**Comment by NorthernMan54** [comment]
Glad to hear you got it working

Do the curtains work in a routine as expected?  I don’t have any so have never tested them.

**Comment by huongminh** [comment]
Hi, I tried to set a routine with my curtain but it did not work. The curtain shows up as an other device in alexa. In routine it shows up like a contact sensor with close/open to choose. I created a routine and if I click test, it works. However when I close the curtain, it does not trigger my selected device. 
The motion sensor works well anyway. 
Now I came across another issue after reinstall the plugin and put it in another homebridge instance. All my current devices in 2 homebridge instances work well. But new devices are not seen in the Alexa app. I tried to delete some devices and rediscover them but Alexa keeps saying no new device found. In the log, I found that Alexa still discover all my devices (it prints out :...returned xxx devices) but the new and the deleted devices do not show up in the app anymore. I tried to discover on both PC and mobile app but not succsessful. I tried to downgrade the plugin to 04.11 but stilll the same. I deleted and reinstall the mobile app but the same. I even tried to add  the homebridge skill to another alexa account but it found no devices. Now I doubt there is something wrong with the homebridge skill account. Is there anyway to reset it or I will have to try to create another homebridge account and try to link it with my plugin?


Sent from Yahoo Mail for iPhone


On Monday, May 13, 2019, 4:55 AM, Northern Man <notifications@github.com> wrote:

Glad to hear you got it working

Do the curtains work in a routine as expected? I don’t have any so have never tested them.

**Comment by NorthernMan54** [comment]
Please keep in mind that you only install and configure the plugin once for your home, and each homebridge instance needs to have -I set to enable Alexa access.

The homebridge.ca account is stateless so there is nothing behind the account except the identity tokens used to link your amazon account to your homebridge.ca/plugin account. So there is nothing to clean up.

I’m thinking the challenge is just the local setup.

Please keep in mind that devices appear in routines in two sections, first being under “when this happens->devices” and second being “add action”.  Under the first, only “sensors” appear here, and under the second all devices appear.

My garage door shows up under both, my door contact sensors appear only under “when this happens->devices” and the on/off ( open/close ) appear under “add action”.

**Comment by huongminh** [comment]
Thank you for your support. Yes, something was wrong with the local setup as I had moved the alexa plugin to another homebridge instance. After I created a second homebridge skill account and linked it to a new fresh alexa account but sill no device found, I gave up and switched back to my original setup. I reinstaledl the homebridge alexa plugin back to the current version and ran the discovery again. This time all my missing devices including new and those (that I had deleted for testing purpose) reappeared. I was still not clear what had been wrong but I doubt something like cache (might be in the accessories folder of the hombridge instance) not cleared that made the alexa plugin think the deleted devices were still there. My doubt is based on these observations:1. Hombridge alexa plugin still runs well and responsive to all previously found devices, only not finding new devices (either a deleted device or new addition). Log still shows the correct number of devices found everytime I restarted the homebridge (including some devices not show up in alexa)
2. Though I did not try to delete the accessories folder of the homebridge instance to refresh all devices (I did not want to resetup all homekit devieces when not clear it would fix the issue) but after I reinstalled the homebridge alexa I found some  (not all) of my devices were reset (these devices were all from another plugin I had also reinstalled earlier). I now believe this reset of these devices finally made the plugin to find devices again. 3. One more observation,  I notice when alexa did not find new devices during discovery, when I press discover button in alexa app, I did not see anything in the log (journalctl). But when it works, every time the discovery starts, the log shows alexa is emitting and a lot of log line would appear. 
I want to share my experience for those who might come across my situation. 
One thing not related to the issue above:My homekit garage door shows up in alexa app as an other device (not switch) with “door type”. When I say close/open garage door, alexa responds garage door doesn’t support that function. That is not like in the Readme guidance. 
And I cannot turn on/off my air conditioner (like Alexa, turn on/off the air conditioner). Alexa would say that is not supported,  but only can set up temperature (like alexa, set temperature to 25 degree). Alexa would turn on and set the air con to the correct temp. I notice with the latest update, air con status in the alexa app shows up with text and correct staus of my air con (like the air conditioner is off and the current temperature is 27).
Sorry if I wrote too long and disturb you. 
Sent from Yahoo Mail for iPhone


On Thursday, May 16, 2019, 12:30 AM, Northern Man <notifications@github.com> wrote:

Please keep in mind that you only install and configure the plugin once for your home, and each homebridge instance needs to have -I set to enable Alexa access.

The homebridge.ca account is stateless so there is nothing behind the account except the identity tokens used to link your amazon account to your homebridge.ca/plugin account. So there is nothing to clean up.

I’m thinking the challenge is just the local setup.

Please keep in mind that devices appear in routines in two sections, first being under “when this happens->devices” and second being “add action”. Under the first, only “sensors” appear here, and under the second all devices appear.

My garage door shows up under both, my door contact sensors appear only under “when this happens->devices” and the on/off ( open/close ) appear under “add action”.
