### ISSUE TITLE
Multiple Echos ident

### ISSUE THREAD

**Issue by c-o-m-m-a-n-d-e-r** [NorthernMan54/homebridge-alexa#22]
Hey,
is it possible to detect between multiple echos which one is used?
So the Plan if i have one in the kitchen and one in the bedroom. i say "turn the light off" ... and then it turns the light off in the room the echo is...

are there any informations we could use?

**Comment by NorthernMan54** [comment]
For what your asking for to work, first we would need a feature in homebridge to do that with iPhones, then once that was complete I would be able to add the echo to the equation.  For now, this is a dream.
