### ISSUE TITLE
[Enhancement] CHANGELOG.md

### ISSUE THREAD

**Issue by DJay-X** [NorthernMan54/homebridge-alexa#220]
@NorthernMan54 Thanks for your great work and sharing with us. Wouldn't want to miss your plugin. 👍🏻
Any chance to have a CHANGELOG.md in the future to have a easy way to find what has changed. Bonus, looks great when updating with [config-ui-x](https://github.com/oznu/homebridge-config-ui-x) by @oznu

Thanks again.

**Comment by NorthernMan54** [comment]
GitHub does this already 

https://github.com/NorthernMan54/homebridge-alexa/commits/master
