### ISSUE TITLE
Hide Wemo, Nest and Ring Devices

### ISSUE THREAD

**Issue by skbeez** [NorthernMan54/homebridge-alexa#221]
I have a situation where I am getting multiple instances of Wemo, Nest and Ring devices on Alexa. Is there a way to mask these devices from discovery? 

Also is there a possibility of importing Homebridge scenes into Alexa?

**Comment by NorthernMan54** [comment]
In your homebridge setup, move your Wemo, Nest and Ring devices to a separate instance of homebridge, and for this instance only, do not enable the -I flag.  This will block homebridge-alexa from seeing these devices, and making them available.

Homekit scenes are not able to be imported as they are part of the Home app.
