### ISSUE TITLE
Zwave - Qubino roller shutter

### ISSUE THREAD

**Issue by boscorelly** [NorthernMan54/homebridge-alexa#222]
Hi,

have homebridge and homebridge-alexa installed.

Homebridge for homekit is working perfectly.

But with alexa, the roller shutters are "others" device and shown as unsupported".

I'm using qubino ZMNHCD 1 modules.

**Comment by NorthernMan54** [comment]
Can you share an accessory dump from homebridge

https://github.com/NorthernMan54/homebridge-alexa/blob/master/README.md#homebridge-accessory-dump

And indicate which devices are not discovered by Alexa.

Tks

**Comment by boscorelly** [comment]
Hi,

here is the dump.
The devices with "volet" in their name are recognized but not usables.

**Comment by NorthernMan54** [comment]
Ps there was no dump or attachment!

Also for blinds, as Alexa doesn’t handle blinds or doors, try turn on or turn off

**Comment by NorthernMan54** [comment]
Also turn “device” to 50 will open or close half way

**Comment by boscorelly** [comment]
oh sorry !
https://pastebin.com/9ed6s3B5

i can't turn on/off, the type is other, and no action is available.

**Comment by NorthernMan54** [comment]
Type other is by design as Alexa does not support blinds. What you are seeing in the Alexa app is expected.

If you ask her to turn on or off the device do they open or close?

**Comment by boscorelly** [comment]
No, it's says "not available"

**Comment by NorthernMan54** [comment]
I looked at the device parsing, and it appears fine, these are the device names passed to Alexa.

                    "friendlyName": "Chambre - Température",
                    "friendlyName": "Dehors",
                    "friendlyName": "Détecteur - Salon",
                    "friendlyName": "Entrée - Volet",
                    "friendlyName": "Ouverture entrée",
                    "friendlyName": "Salle de bain",
                    "friendlyName": "Salon",
                    "friendlyName": "Salon - Volet",
                    "friendlyName": "Xiaomi RGB Gateway (192.168.1.45)",

My first thought is that the names and the "-" character may be causing issues for Alexa.  Could you try changing the name in the Alexa app, and try again.

If that doesn't work can you run homebridge-alexa in debug mode

https://github.com/NorthernMan54/homebridge-alexa#debug-logs

And try controlling the blinds by voice while watching the logs.  If you could share the log from when you ask her to "turn on Entrée - Volet".

**Comment by boscorelly** [comment]
It was this. The dash was a problem i think :)
I don't have a button to set it un or off for this device. Is it normal ?

**Comment by NorthernMan54** [comment]
@boscorelly In the app, yes it is normal not to have a control in the app.

**Comment by boscorelly** [comment]
i was thinking i will have a button like on a lamp :)

**Comment by NorthernMan54** [comment]
Once Amazon formally supports blinds, then it should have something
