### ISSUE TITLE
"This device is not currently supported" in Routines

### ISSUE THREAD

**Issue by DJBenson** [NorthernMan54/homebridge-alexa#226]
Hi

I am trying to set up some routines for a couple of contact sensors. I've enabled the "routines" option in the config and I see both of the devices in the list of trigger devices but when I select either of them, I get "This device is not currently supported".

I've read through a couple of the closed bugs around routines and I think my setup is correct and that routines should now be supported by default (was previously a beta?)

**Comment by NorthernMan54** [comment]
What country are you in?  I’m in Canada, and they work fine.  I’m wondering if they aren’t supported in your country yet.

https://developer.amazon.com/docs/device-apis/list-of-interfaces.html <https://developer.amazon.com/docs/device-apis/list-of-interfaces.html>

**Comment by DJBenson** [comment]
I’m in the UK. Just checked that link and contact sensors are not enabled in the UK, just US and CA. What a pain :(

Not a bug then. Thanks for the quick response.
