### ISSUE TITLE
Alexa not discovering devices after updating plugin

### ISSUE THREAD

**Issue by saelaenx** [NorthernMan54/homebridge-alexa#228]
As discussed on Slack, Alexa is not discovering devices after updating to latest plugin version, no errors showing in logs as far as I can tell.
Accessory dump attached.
[homebridge accessory dump.txt](https://github.com/NorthernMan54/homebridge-alexa/files/3256152/homebridge.accessory.dump.txt)
Accessory dump from secondary Homebridge installation.
[Homebridge accessory dump 2.txt](https://github.com/NorthernMan54/homebridge-alexa/files/3256184/Homebridge.accessory.dump.2.txt)

**Comment by NorthernMan54** [comment]
Looking at the files

These are the devices from the first file - Please note it is a bit short as the file was short, I don’t think you included everything in the file

                    "friendlyName": "button1",
                    "friendlyName": "shaversocket",
                    "friendlyName": "temperature",
                    "friendlyName": "temperature",
                    "friendlyName": "thermostat",
                    "friendlyName": "deckingLights",
                    "friendlyName": "decklight1",
                    "friendlyName": "decklight2",
                    "friendlyName": "decklight3",
                    "friendlyName": "flame”,

These are the devices from the second file

             "friendlyName": "Front Room",
                    "friendlyName": "Kitchen",
                    "friendlyName": "My Smart Plug",
                    "friendlyName": "temperature",
                    "friendlyName": "temperature",
                    "friendlyName": "thermostat",
                    "friendlyName": "thermostat",
                    "friendlyName": "photon03",
                    "friendlyName": "socket",
                    "friendlyName": "socket02",
                    "friendlyName": "socket03”,

When I run them thru the parser and validator they are passing all the tests

Looking at your devices everything looks fine, the only thing that really changed since last december was the Thermostat.  Could you try temporarily removing the Thermostats from Homebridge and try again.  And by remove I mean just make a backup of your config.json, remove just the thermostat accessories restart homebridge and try again.

Also, what country are you in?

**Comment by saelaenx** [comment]
I tried it without the thermostats but unfortunately had the same result. I disabled and re-enabled the alexa skill before I ran the discovery. I'm not sure if this is relevant or not but I remembered that just before I updated I was clearing out duplicate devices that had appeared and I accidentally deleted one of my accessories in the Alexa app, and that wouldn't reappear after running discovery, so I'm not sure if perhaps there was an underlying problem unrelated to the update? I am in the UK.

**Comment by NorthernMan54** [comment]
If there was a wide spread problem with homebridge-Alexa I’m sure I would have heard from more than one person, currently have about 1400 users.

How about creating a second amazon account, link one of your Alexa’s to it, and only enable the homebridge-Alexa skill. Then try discovery.  You can use the same homebridge.ca account as homebridge.ca is a stateless message router.

Another thought, device names.  Some of yours have numbers within the name, try removing those from the config. Or change the name to be an English word.  Ie “button one”

**Comment by saelaenx** [comment]
I've tried the second amazon account, no luck. I have also tried removing numbers (and anything other than letters) from my device names, unfortunately still no devices are discovered. I'm wondering if the only thing left to try is to start with a completely fresh homebridge install and go from there?

**Comment by NorthernMan54** [comment]
Hold on for resetting everything, as it is unlikely to make a difference

I’m away for the next 24 hours or so, but can you share your homebridge.ca login. Want to review the server logs.

**Comment by saelaenx** [comment]
Username is saelaenx. Will hold off for now, but I have spare raspberry pis lying around all over the place so may set one up for testing if I have a bit of time, in case it’s something I’ve done with updating plugins or something. Will report back if successful :)

**Comment by NorthernMan54** [comment]
Okay, I looked at the logs and nothing jumped out at me at all

I saw discovery response’s being passed back successfully for both accounts you created

From the saelanenx account, these where the device names being passed back

        "friendlyName": "gardenLights",
        "friendlyName": "shaversocket",
        "friendlyName": "Raspberry Pi CPU Temperature",
        "friendlyName": "deckingLights",
        "friendlyName": "decklightOne",
        "friendlyName": "decklightTwo",
        "friendlyName": "decklightThree",
        "friendlyName": "flame",
        "friendlyName": "ledStripTVCabinet",
        "friendlyName": "temperatureBedroomOne",
        "friendlyName": "temperatureBedroomTwo",
        "friendlyName": "temperatureGarden",
        "friendlyName": "temperatureFrontRoom",
        "friendlyName": "temperatureKitchen",
        "friendlyName": "temperatureUpperBedroom",
        "friendlyName": "temperatureUpperLivingRoom",
        "friendlyName": "thermostatBedroom",
        "friendlyName": "thermostatHouse",
        "friendlyName": "thermostatLivingRoom",
        "friendlyName": "RaspberryPi Zero CPU Temperature",
        "friendlyName": "Front Room",
        "friendlyName": "Kitchen",
        "friendlyName": "My Smart Plug”,

My only comment on these is a lot of them are not real words.  Am wondering if she needs real names?  But in my account I have several that are not real names.

My only other thought was to try your your second amazon account.   Could you share the login credentials privately via a Slack direct message?  And leave it connected to homebridge in your house.

**Comment by saelaenx** [comment]
Ok, so randomly and without me doing anything, all my devices have appeared in the Alexa app, and they all seem to work... I can give you the login for the second amazon account if you still want to check it out, as it’s still set up for now?

**Comment by NorthernMan54** [comment]
If your up and running, then I don’t need to look at anything.  Since we didn’t change anything, I’m wondering if amazon had issues.  But I doubt we would ever know, so we should just close this.

**Comment by saelaenx** [comment]
Ok, well thanks for trying to help, I guess Alexa just need a week or so to think about it or something ^_^
