### ISSUE TITLE
Alexa showing AppleTV devices as switches and not Apple TV

### ISSUE THREAD

**Issue by vandykew** [NorthernMan54/homebridge-alexa#229]
Before upgrading alexa would show the apple tv as once device now it discovering 10 or so different switches and adding them all

**Comment by NorthernMan54** [comment]
Weird, what is the name of the devices in the home app?

They should be something like

Left (Apple TV)

The brackets are important

**Comment by vandykew** [comment]
Yes, I have 11 total and they all have the format of" Down (Living Room Apple Tv)"

**Comment by NorthernMan54** [comment]
Can you share an accessory dump, I want to see what is being passed to homebridge Alexa

https://github.com/NorthernMan54/homebridge-alexa#homebridge-accessory-dump

**Comment by vandykew** [comment]
Sure its attached 

[data.txt](https://github.com/NorthernMan54/homebridge-alexa/files/3264506/data.txt)

**Comment by NorthernMan54** [comment]
Tks for that, it was a quick fix.  It didn’t like the spaces in your ATV name

Update to the latest version v0.4.20, and try again

**Comment by NorthernMan54** [comment]
And a big ooops, need more time with this

**Comment by NorthernMan54** [comment]
Try the latest version v0.4.22, this should now be fixed

**Comment by vandykew** [comment]
works like a charm ! 

Thank You

**Comment by NorthernMan54** [comment]
Awesome
