### ISSUE TITLE
Using this with homebridge-broadlink-rm

### ISSUE THREAD

**Issue by jat80** [NorthernMan54/homebridge-alexa#23]
Hi there, 

I'm not sure if this is a problem with my setup or your plugin but i'm having some problems with it controlling homebridge accessories that are created using homebridge-broadlink-rm plugin by @lprhodes.  Using siri to turn the tv (for example) on and off seems to work fine but when I used alexa (via your plugin) it sometimes doesn't work.  It says it's turned it on, and the homekit app says it's on but the physical tv isn't on.

I do have an HDHomerun connect on the network as well but not sure if that would hinder anything.

**Comment by NorthernMan54** [comment]
Can you enable DEBUG logging and share the log when you ask Alexa to discover devices, and when you attempt to control the problematic devices.

Tks

**Comment by jat80** [comment]
Thanks for the reply @NorthernMan54 I've got the logs.  How do I send them to you?

**Comment by NorthernMan54** [comment]
If you look at the bottom of the text entry box for entering issues, it has an option for attaching

**Comment by jat80** [comment]
@NorthernMan54 I should of been more specific - is there anyway to send them to you directly without making the logs public?

**Comment by NorthernMan54** [comment]
As an alternate you can send them to my gmail.com account northern.man1
