### ISSUE TITLE
Routine stop working after some time..

### ISSUE THREAD

**Issue by lily148** [NorthernMan54/homebridge-alexa#230]
Hi, anyone here facing the similar issue?
My alexa routine stop working after a few days until I restart homebridge again.
Weird part is, I still can use my echo to control light and fan in my house... just the routine event is not working.

**Comment by NorthernMan54** [comment]
Please check your logs, there is likely an error causing this behavior.

In my setup, I have not seen this issue

**Comment by lily148** [comment]
Okay, enabled the debug log... will monitor until it fail again then update here.. thanks.

**Comment by NorthernMan54** [comment]
Tks
