### ISSUE TITLE
Problem accessory homekit

### ISSUE THREAD

**Issue by oremic** [NorthernMan54/homebridge-alexa#232]
hi
Problem accessory homekit not supported.
Firmware homekit custom. 
homebridge plugin alexa.
thanks
  hapNodeJSClient Unsupported device found, skipping SHP6-D45B78.local [] +163ms
  hapNodeJSClient Unsupported device found, skipping Shelly_2e5-73FEDB.local [] +2ms
  hapNodeJSClient Unsupported device found, skipping Shelly1PM-B1D72F.local [] +1ms

**Comment by NorthernMan54** [comment]
This plugin only works with Homebridge, other devices are not supported.
