### ISSUE TITLE
More home, different network

### ISSUE THREAD

**Issue by oremic** [NorthernMan54/homebridge-alexa#233]
Hi all,
I 've more home, each home have a single homebridge, including homebridge-alexa.
i use same homebridge.ca account in each installation,
but only one installation seem work; if stop first instance homebridge, 
the second one work fine and in Amazon Alexa app i can see all accessories work fine.
If all instance are on,  in Amazon Alexa app i can't see only accessory loaded in firs instance.
Tnks,
oremic

**Comment by NorthernMan54** [comment]
In my setup, each home uses different accounts for amazon Alexa and homebridge.ca.

I created a separate amazon account and homebridge.ca account for each home.  Works well

**Comment by oremic** [comment]
hi, but in alexa app i can't use more than an account.
I'd like use one app, single account, and manage more device over more bridge.
I'm an user with more home (ex. house and sea house or office) and i'd like use one app on my phone and manage all bridged devices.
Tnks,
oremic

**Comment by NorthernMan54** [comment]
When I switch houses I just switch accounts in the Alexa app but I rarely use the Alexa app and use the Home app.  So maybe 1 trip in 5 I actually use the Alexa app

When I had it setup together, I found device naming to be challenging, as the names in each needed to be unique.  And caused a negative WAF score.
