### ISSUE TITLE
homebridge-tplink-smarhome problem

### ISSUE THREAD

**Issue by shungo27** [NorthernMan54/homebridge-alexa#238]
I added a switch using homebridge-cmdswitch2. Can I operate this switch from Alexa? I can operate from Home.app, but it is not displayed in Alexa.

```
"platform": "cmdSwitch2",
"name": "CMD Switch",
"switches": [
	{
		"name" : "test",
		"on_cmd": "osascript /Applications/test.scpt",
		"off_cmd": "osascript /Applications/test.scpt",
		"state_cmd": "exit 0"
	}
]
```

**Comment by NorthernMan54** [comment]
It should show up, if not please share a homebridge accessory dump

Details are here

https://github.com/NorthernMan54/homebridge-alexa#homebridge-accessory-dump

**Comment by shungo27** [comment]
I found the cause. When I use homebridge-tplink-smarthome, I can not discover new devices.

The following steps are required to discover new devices after using homebridge-tplink-smarthome.

1. Uninstall homebridge-tplink-smarthome
2. Remove the item of homebridge-tplink-smarthome from config.json
3. Delete "accessories" directory and "persist" directory
4. Added new accessories to config.json.
5. Discovery by Alexa.
6. Install homebridge-tplink-smarthome
7. Add the item of homebridge-tplink-smarthome from config.json

This step is required each time you add a new accessory.

homebridge accessory dump:
`{"accessories":[{"aid":1,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Nick Farina","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Homebridge","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Homebridge","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"EC:FA:BC:3B:2D:2C","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"0.4.50","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":2000000008,"type":"49FB9D4D-0FEA-4BF1-8FA6-E7B18AB86DCE","characteristics":[{"iid":9,"type":"77474A2F-FA98-485E-97BE-4762458774D8","perms":["pr","ev"],"format":"uint8","value":0,"description":"State","maxValue":1,"minValue":0,"minStep":1},{"iid":10,"type":"FD9FE4CC-D06F-4FFE-96C6-595D464E1026","perms":["pr","ev"],"format":"string","value":"1.0","description":"Version"},{"iid":11,"type":"5819A4C2-E1B0-4C9D-B761-3EB1AFF43073","perms":["pr","pw","ev"],"format":"data","value":null,"description":"Control Point"}],"primary":false,"hidden":false}]},{"aid":2,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Nature","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Remo","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"スピーカー","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"031-45-154","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000049-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"スピーカー","description":"Name"},{"iid":10,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":false,"description":"On"}],"primary":false,"hidden":false}]},{"aid":4,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Manufacturer","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Model","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"LineIn","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-SerialNumber","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000049-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"LineIn","description":"Name"},{"iid":10,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":false,"description":"On"}],"primary":false,"hidden":false}]},{"aid":5,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"TP-Link","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"HS105(JP)","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"サーキュレーター","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"0C:80:63:04:F8:FC 80063F8E5FB4B9F4FE24D41FFFCBE0891A5B1C70","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.5.7 Build 180202 Rel.075643","description":"Firmware Revision"},{"iid":8,"type":"00000053-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Hardware Revision"}],"primary":false,"hidden":false},{"iid":9,"type":"00000047-0000-1000-8000-0026BB765291","characteristics":[{"iid":10,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"サーキュレーター","description":"Name"},{"iid":11,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":true,"description":"On"},{"iid":12,"type":"00000026-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"bool","value":true,"description":"Outlet In Use"}],"primary":false,"hidden":false}]}]}`

**Comment by NorthernMan54** [comment]
This is pretty odd behaviour.  One thing to keep in mind, is that homebridge-alexa scans for new devices every 15 minutes so if you add something new try waiting 15 minutes then asking Alexa to discover devices.  Also restarting the plugin will force a refresh.

**Comment by shungo27** [comment]
When homebridge-tplink-smarthome is installed, new devices will not be added even if you wait for one hour or reboot homebridge.
