### ISSUE TITLE
Occupancy sensor 

### ISSUE THREAD

**Issue by paskalll** [NorthernMan54/homebridge-alexa#246]
Feature Request:

A Occupancy sensor like homebridge-plex-v2 is not showing up in Alexa.
Did I just miss that's not supported or may its never been working.

**Comment by NorthernMan54** [comment]
If you can collect a homebridge accessory dump from your homebridge instance running the plugin and attach it.  I should be able to add it as a contact sensor.  Details for how to collect an accessory dump are in the README.

**Comment by paskalll** [comment]
`{"accessories":[{"aid":1,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Nick Farina","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Homebridge","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Homebridge","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"CD:22:3D:E3:CE:95","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"0.4.50","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":2000000008,"type":"49FB9D4D-0FEA-4BF1-8FA6-E7B18AB86DCE","characteristics":[{"iid":9,"type":"77474A2F-FA98-485E-97BE-4762458774D8","perms":["pr","ev"],"format":"uint8","value":0,"description":"State","maxValue":1,"minValue":0,"minStep":1},{"iid":10,"type":"FD9FE4CC-D06F-4FFE-96C6-595D464E1026","perms":["pr","ev"],"format":"string","value":"1.0","description":"Version"},{"iid":11,"type":"5819A4C2-E1B0-4C9D-B761-3EB1AFF43073","perms":["pr","pw","ev"],"format":"data","value":null,"description":"Control Point"}],"primary":false,"hidden":false}]},{"aid":4,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Manufacturer","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Model","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Watson","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-SerialNumber","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000049-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Watson","description":"Name"},{"iid":10,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":false,"description":"On"}],"primary":false,"hidden":false}]},{"aid":5,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Manufacturer","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Model","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"PC","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-SerialNumber","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000049-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"PC","description":"Name"},{"iid":10,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":false,"description":"On"}],"primary":false,"hidden":false}]},{"aid":9,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Manufacturer","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Model","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Plex Sensor","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-SerialNumber","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000086-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Plex Sensor","description":"Name"},{"iid":10,"type":"00000071-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"uint8","value":0,"description":"Occupancy Detected","valid-values":[0,1],"maxValue":1,"minValue":0}],"primary":false,"hidden":false}]},{"aid":3,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"RaspberryPi","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"3B","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Pi Temp","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Undefined","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"0.0.7","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"0000008A-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Pi Temp","description":"Name"},{"iid":10,"type":"00000011-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"float","value":54.7,"description":"Current Temperature","unit":"celsius","maxValue":100,"minValue":0,"minStep":0.1}],"primary":false,"hidden":false}]},{"aid":8,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Raumfeld / Teufel","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Virtual Zone","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Virtual Zone","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-SerialNumber","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000049-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":false,"description":"On"}],"primary":false,"hidden":false}]},{"aid":12,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Raumfeld / Teufel","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Raumfeld","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Speaker Wohnzimmer","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-SerialNumber","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000049-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":false,"description":"On"}],"primary":false,"hidden":false}]},{"aid":6,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"AVM","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Fritz!Box","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Guest WLAN","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-SerialNumber","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"07.02","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000049-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Guest WLAN","description":"Name"},{"iid":10,"type":"00000025-0000`

**Comment by NorthernMan54** [comment]
Yes but need the complete response,  as I need to run it thru the accessory parser

**Comment by paskalll** [comment]
so i will do the dump again with triggered sensor right?

**Comment by NorthernMan54** [comment]
Perfect

**Comment by paskalll** [comment]
that's all you need?

**Comment by NorthernMan54** [comment]
It should be, give me a day or so

**Comment by NorthernMan54** [comment]
@paskalll Please update to the latest version and run discovery again.  You should now see your Occupancy sensors as a "Contact Sensor" in Alexa.  And be able to use it in routines.

**Comment by paskalll** [comment]
[2019-8-10 14:35:06] [Alexa] alexaDiscovery - returned 8 devices
[2019-8-10 14:35:02] [Alexa] ERROR: HAP Discovery failed, please review config
[2019-8-10 14:34:51] [Alexa] alexaDiscovery - returned 8 devices

No new device in Alexa. 

      {
          "platform": "Alexa",
          "name": "Alexa",
          "username": "paskalll",
          "password": "123456",
          "pin": "123456",
          "refresh": 15,
          "routines": true
      },

**Comment by NorthernMan54** [comment]
I can't find your username "paskalll" in the backend?

Also that log fragment is very weird as those messages are all part of one IF statement, and it should only have one or the other.

**Comment by paskalll** [comment]
Sorry i throw routines true out of config and now its working. My fault. Thank you.

**Comment by NorthernMan54** [comment]
What country are you in ?

Contact and Motion sensors are only supported in en-CA and en-US

https://developer.amazon.com/docs/device-apis/list-of-interfaces.html

**Comment by paskalll** [comment]
oh shit ok.
Germany.
So no way at the moment. Did not know what 😒

**Comment by NorthernMan54** [comment]
I’m in Canada, so it works for me, but for Germany I’m not 100% sure.  Can you ask on the Slack Channel and see if any other users in Germany can use Routines with Motion or Contact?

**Comment by paskalll** [comment]
I dont know why but today Remote i Could create The routine with Plex Sensor. So should work. Will Test now.

**Comment by paskalll** [comment]
So its working. But the other way arround.

Lets say I want to dim the light on play. I chose when sensor opens dim light to 20%. But then he will dim lights on Pause or stop to 20%.

No big deal I just change the routine the other way around.

**Comment by NorthernMan54** [comment]
I reversed the setting to opposite, so it should now work correctly.  Please update and try again.

**Comment by paskalll** [comment]
Will check it today thank you so much.

**Comment by paskalll** [comment]
Sorry for late feedback. Holidays 🥽
Works like a charm. Thank you very much.
