### ISSUE TITLE
[Question] Stop properly plugin

### ISSUE THREAD

**Issue by WoodySlum** [NorthernMan54/homebridge-alexa#247]
Hi,

I'm using homebridge and homebridge-alexa directly embedded in a nodejs project.
This is done through a "service" which have a `start` and `stop` method.
When I restart the service, homebridge-alexa shows an error "ERROR: ( homebridge-alexa) You have an issue with your installation, please review the README"

Here is the init code (called once) :
```
const Server = require("./../../../node_modules/homebridge/lib/server").Server;
const Plugin = require("./../../../node_modules/homebridge/lib/plugin").Plugin;
const User = require("./../../../node_modules/homebridge/lib/user").User;

const insecureAccess = true;
const conf = api.configurationAPI.getConfiguration() ? api.configurationAPI.getConfiguration() : {};
if (!conf.homebridgeIdentifier) {
    const hid = "AnID";
    conf.homebridgeIdentifier = hid.substr(0,2) + ":" + hid.substr(2,2)  + ":" + hid.substr(4,2)  + ":" + sha256(Math.floor(Math.random() * 100000000).toString()).substr(0,2) + ":" + sha256(Math.floor(Math.random() * 100000000).toString()).substr(0,2) + ":" + sha256(Math.floor(Math.random() * 100000000).toString()).substr(0,2);
    api.configurationAPI.saveData(conf);
}

const platforms = [];
const pin = "021-92-278";
if (conf.alexaUsername && conf.alexaPassword) {
    platforms.push({
        platform: "Alexa",
        name: "Alexa",
        username: conf.alexaUsername,
        password: conf.alexaPassword,
        pin: pin
    });
}

try {
    this.server = new Server({insecureAccess:insecureAccess});
    this.server._config = {
        bridge: {
            name: "A name",
            username: conf.homebridgeIdentifier.toUpperCase(),
            port: port,
            pin: pin
        },
        accessories: devices.concat(sensors).concat(alarm),
        platforms:platforms
    };
    hap.init(User.persistPath());
} catch(e) {
    api.exported.Logger.err(e.message);
    api.exported.Logger.err(e.stack);
}
```

Here is the start code :
`this.server.run();`

Here is the stop code :
```
if (this.server) {
    this.server._teardown();
}
```

On the first start, everything work well. If only service is restarted (i.e. without killing the process), I got the error message above. I don't know if the problem is caused by  homebridge or homebridge-alexa.

Any idea of what is causing this issue ? 

Thanks for the help? The complete code can be found here : https://github.com/WoodySlum/Hautomation-io/blob/master/src/internal-plugins/homebridge/service.js

**Comment by NorthernMan54** [comment]
That message is triggered after the mqtt connection to the Alexa cloud is reset every 5 times.  Likely cause is having the plugin running more than one copy.

**Comment by WoodySlum** [comment]
There is a way to stop / destroy current plugin copies ?

**Comment by NorthernMan54** [comment]
As you are running this outside of homebridge, no clue

**Comment by WoodySlum** [comment]
No problem, thanks
