### ISSUE TITLE
Turn on and turn-off blinds syntax

### ISSUE THREAD

**Issue by acire19** [NorthernMan54/homebridge-alexa#248]
Thank you guys for the plugin, we are implementing it in our zigbee network (approximately 40 devices are already connected to such network). As far as the opening/closing of the blinds and doors is regared, it works fine with the syntax "Turn on XX" and "Turn off YY", but not with "Open XX" and "Open YY" (Alexa tells us that such functionality is not suppoted by the device) (on the other hand, homekit properly supports both syntaxes). Since we are talking to Alexa in italian and not in english, it sounds really bad the corresponding translation for the "turn on/off blinds". Could you please provide us some info to implement the second syntax ourselves? Or, if the effort is not so great, could you please support  them both in a future release?
PS: we arranged to have it working with the "open/close" syntax for few days, but then it stops working without  any change.

**Comment by NorthernMan54** [comment]
Currently Alexa does not support blinds or door, ie devices with open/close so to workaround this issue, create a routine in Alexa with the desired wording.  This is what I did for my garage door

**Comment by acire19** [comment]
thanks for the suggestion, it finally works!
