### ISSUE TITLE
not discovering any devices anymore

### ISSUE THREAD

**Issue by DJay-X** [NorthernMan54/homebridge-alexa#250]
@NorthernMan54 
I hope not to bother, but I'm a little lost and after days of trying I still have the following issue.

I used the plugin for month successfully, with ever update released. However I noticed a couple of days ago, that non of my homebridge devices work with Alexa anymore.
So I removed all devices from Alexa and searched for new ones. No devices found at all.
I deactivated the skill and reconnected it again.
I reset Echo Dot. I uninstalled the plugin and reinstalled it.
And last desperate action I created a new Account on homebridge.ca and run everything from scratch. Unfortunately all without any success. Alexa is not discovering any device from Homebridge.

The Homebridge Log is showing no errors. When I let Alexa discover for new devices the log shows nothing critical I think.
```
[Alexa] WARNING: Duplicate device name Apple TV 4K
[Alexa] WARNING: Duplicate device name Apple TV 4K
[Alexa] WARNING: Duplicate device name Luftbefeuchter II
[Alexa] WARNING: Duplicate device name Luftbefeuchter
[Alexa] alexaDiscovery - returned 170 devices
```

Username "old" was DJay , "new" is HomebridgeDJay

Any help is very much appreciated. Thanks in advance for your time.

**Comment by NorthernMan54** [comment]
Looking at the server logs, it is upset with your Apple TV 4K.  and passed 4 copies over.  Do you have 4 of them with the same name?

**Comment by DJay-X** [comment]
@NorthernMan54 Thanks for having a look and for your reply.

Unfortunately no, I don't have 4 Apple TV 4K. 😅
I checked now (not easy with 192 devices in Homebridge) though, it sounds like this issue depends on the Plugin https://github.com/nicoduj/homebridge-harmony
It's creating 4 Devices switch called "Apple TV 4k" I see in Eve App. But the actual device name is always different like 
"HarmonyHub-Apple TV 4K-DirectionDownDirectionRightDirectionRight"
"HarmonyHub-Apple TV 4K-Home"
"HarmonyHub-Apple TV 4K-Menu"

I now I changed the switch names and the device names to unique names via Eve App, restarted Homebridge but still get no devices discovered by Alexa.

**Comment by NorthernMan54** [comment]
I looked at the server logs, and the name change did not take.  The alexa plugin uses name from the harmony plugin and not the name you can change from the Eve app.  You need to change names in the harmony plugin config.json.

My other worry, was the maximum number of devices Alexa supports per skill, and that is 300.  So we are good here.

https://developer.amazon.com/docs/device-apis/alexa-discovery.html#response <https://developer.amazon.com/docs/device-apis/alexa-discovery.html#response>

**Comment by DJay-X** [comment]
@NorthernMan54 Thank you very much for your friendly support. Your hint with was helpful.
I was able to add an option in the homebridge-harmony plugin to shorten device name.
https://github.com/nicoduj/homebridge-harmony/issues/172#issuecomment-524603232
Thanks to this change and deleting cachedAccessories everything is working again now.
Alexa discovered the 170 devices that your plugin is showing in the HB journal as discovered.
Thanks again for the time you are investing in this plugin and sharing with us. 👍

**Comment by NorthernMan54** [comment]
I have also added more error messages for this particular issue, so others should able to identify the issue faster.
