### ISSUE TITLE
Window Covering - StepSpeaker

### ISSUE THREAD

**Issue by c-o-m-m-a-n-d-e-r** [NorthernMan54/homebridge-alexa#251]
Hey,
first of all ... really Great Skill / Plugin.

Yesterday i did a little fine tune of my setup at home.
I'm using the KNX Plugin for my Home.

I realized that my command for the Window Covering "move XXX up / down" is "working" and translated into percentage Values.

Not sure if it is possible to map the Values to 0 or 100.

I take a look at the StepSpeaker API and think this would be possible isn't it?

I hope you now what i mean :-)

Best

**Comment by NorthernMan54** [comment]
The mapping between Homebridge and Alexa is done here in the code

https://github.com/NorthernMan54/homebridge-alexa/blob/bdf8f8e1b3d0b5b20a8eabb9a1b7b10557feed1c/lib/parse/Characteristic.js#L146

And for the Window Covering I'm using the Alexa.powercontroller interface for On/Off ( Which maps to 0 or 100 ).  And the Alexa.powerlevelcontroller interface to set percentage values.

I believe it is already doing what you are asking about

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Hey,
thanks for reply. I think i explained it wrong :-)

Overall the control is working.
But in daily usage the sentence "alexa, turn my blinds on" ... is mhhh strange and feels wrong you know what i mean? 

I tried several things (in german) and realized that say : "alexa, move my blinds UP / DOWN" is working but its calculate random positions.

So this was my question, isn't it possible to map the Result of UP / DOWN into 0 / 1 ?

Thanks for the Code hint, i will take a look at it.

**Comment by NorthernMan54** [comment]
With mine, I just use an alexa routine with the wording I want to speak.  Works quite well

Maybe I should add this tip to the README?

**Comment by c-o-m-m-a-n-d-e-r** [comment]
indeed this is a solution too ... didn‘t think about that before, thanks. 

i would say its a good hint for the readme!

but a solution without extra work is nice to have :-)
