### ISSUE TITLE
Homekit not finding switches

### ISSUE THREAD

**Issue by csmith408** [NorthernMan54/homebridge-alexa#252]
how do i get it to discover my homekit switches? i have 5 homekit switches  leviton decor smart homekit only switches 

so i installed  plugin put in all the info new username and password from plugin, say discover device new devices cant find any of the homekit switches ( living room light etc)

just tot make sure this is what im thinking this plugin is.... Does it take your exiting homekit switches (that are not compatible with alexa) and make alexa be able to use them.  like by saying alexa turn on game room light?  as no i have to say siri and works fine.  

thank you!

**Comment by NorthernMan54** [comment]
My plugin only works with devices and switches exposed thru homebridge, and not HomeKit devices.

**Comment by csmith408** [comment]
what do you mean by exposed through homebridge? like for example maybe a light switch that doesnt already have a  homebridge plugin already but works with alexa? then you can see it on your homebeidge?

is there any pluging you know of that can make alexa see homekit plugins?  thanks for the quick responce too!

**Comment by NorthernMan54** [comment]
I'm not aware of any plugin for HomeKit devices.
