### ISSUE TITLE
Set custom device type/display category

### ISSUE THREAD

**Issue by hirnschallsebastian** [NorthernMan54/homebridge-alexa#254]
I am using HttpWindowBlinds to control my window blinds using homekit.

However when using alexa I have to say "turn on device" instead of "open device" since alexa does not recognise the window blinds correctly (they are in the 'other' category).

It would be nice to be able to set a custom device type.

**Comment by NorthernMan54** [comment]
As Alexa does not natively support window coverings, doors and blinds you need to create a routine with your wording until native support is available
