### ISSUE TITLE
Alexa can no longer see Homebridge (V1)

### ISSUE THREAD

**Issue by chrisp79** [NorthernMan54/homebridge-alexa#257]
Hi, hope you’re well. Back in 2017 ago you helped me get Alexa-Homebridge (V1) up and running in my home. I’m so grateful – it’s been absolutely brilliant ever since then.

I seem to have developed a bit of a problem in the last fortnight though. It started with Alexa not being able to contact any devices one evening (Homekit still worked fine). The next morning everything seemed fine much to my relief. However, later that day Alexa stopped being able contact any devices again (again Homekit was fine), and it’s never worked again since.

I went onto your Github page to see if I could see any comments from other users, and noticed that you’d released V2. I backed up my existing setup and then tried installing your V2 but I couldn’t get that to work no matter what I tried. I saw there was a new version of Raspbian (Buster) so downloaded a fresh image and tried installing scratch. I tried absolutely everything, but whatever I did I couldn’t get homebridge-rcswitch-gpiomem to install – I keep getting NPM errors. I noticed there were various versions of gpiomen, npm and node and tried quite a few different combinations to no avail. I repeated this on fresh installs of Stretch and Jessie but still no luck. Having spent goodness knows how many days on trying to get new versions to work, I decided to restore my backup and focus on trying to debug that.

I’ve tried all sorts to get the V1 setup working, but am having no luck with that either. Whatever I do, Alexa doesn’t see my Homebridge. I even restored an image I took back in 2017 when I initially got everything up and running fine – in case the RPI had somehow taken an update recently that had caused the problem – but again no luck, Alexa still doesn’t see it. I found some debug steps you sent me back in 2017 and have re-run those – the output seems to match what it was back then, so I’m stumped as to what’s happening.

I’m guessing the fact that Alexa can’t see my Homebridge is therefore something to do with SSDP. I assume my router has an important part to play with this, so was wondering whether my cable provider had pushed an update to it that might’ve caused a problem. But then I realised my that I’d made a copy of my SD and RPI for my Dad back in 2017 to set his home up, and he has the same router and cable provider as me and his install is fine.

So I’m completely flummoxed. If you have any idea what might be going on here I’d be extremely grateful for your help.

Many thanks,
Chris

**Comment by NorthernMan54** [comment]
Chris,

With the V1 approach, Amazon has been slowly dropping support for it for a few years now with each new device.  My guess is that it has now hit the tipping point for yourself and is no longer supported by your devices.

My recommendation would be to get yourself to a recent version of homebridge and your plugins, then layer in the V2 plugin.

And as getting everything running again is a bit of effort, setup it up beside your existing setup, then cut over once it’s stable.

**Comment by chrisp79** [comment]
Thanks for replying so quickly. Not the news I wanted to hear but it's not entirely unexpected. At least I know not to bother wasting any more time trying to get V1 working.

Thanks for the advice.
Chris

**Comment by chrisp79** [comment]
Hi Northern Man,

Thanks for the nudge in the right direction. I’ve now got a Buster/V2 setup working, but I have one last problem remaining which I can’t figure out how to get around.

I can control individual devices with Homekit and Alexa just fine now, but when I try to control a group of devices (through either Homekit or Alexa) all of the relevant instructions appear in Homebridge, but barely any of the devices respond.

I’m guessing it’s because all of the instructions are coming through in quick succession and the RPI can’t send them fast enough and ends up skipping some (most). I seem to remember something about setting a ‘high priority’ for Homebridge (or some other element) when I set V1 up a few years back but for the life of me, I can’t find this online anymore. I did that on my original setup and groups where fine, but I haven’t done that this time around (because I can’t remember how). It’s the only difference / explanation I can come up with.

Does that sound plausible? If so, if you could point me in the right direction to fix this I’d be really grateful.

Thanks!
Chris

**Comment by NorthernMan54** [comment]
Chris,

That sounds more like a plugin issue and the plugin not being able to handle multiple commands at once.

**Comment by chrisp79** [comment]
Thought I’d try disabling the Alexa skill and re-enabling it.

I disabled the skill and when enabling it, Alexa.com took me to https://www.homebridge.ca/auth/start?client_id=1&response_type=code&state=A2SAAE,etc to link my account.

When I enter my original credentials and click Authorise my browser navigates to https://www.homebridge.ca/auth/finish and there’s a message that says…

Error
   at SessionStore.load (/home/ubuntu/awsWeb/node_modules/oauth2orize/lib/txn/session.js:27:25)
   at transactionLoader (/home/ubuntu/awsWeb/node_modules/oauth2orize/lib/middleware/transactionLoader.js:42:24)
   at Layer.handle [as handle_request] (/home/ubuntu/awsWeb/node_modules/express/lib/router/layer.js:95:5)
   at next (/home/ubuntu/awsWeb/node_modules/express/lib/router/route.js:137:13)
   at /home/ubuntu/awsWeb/index.js:520:9
   at Strategy.strategy.success (/home/ubuntu/awsWeb/node_modules/passport/lib/middleware/authenticate.js:201:18)
   at verified (/home/ubuntu/awsWeb/node_modules/passport-local/lib/strategy.js:83:10)
   at InternalFieldObject.ondone (/home/ubuntu/awsWeb/node_modules/passport-local-mongoose/lib/authenticate.js:48:16)

Initially, when I entered my new credentials and clicked Authorise I was seeing an Alexa.com message saying this this couldn’t be done right now, try later. But now I see the same message as above.


From: Chris Platt
Sent: 10 October 2019 19:28
To: NorthernMan54/homebridge-alexa <reply@reply.github.com>; NorthernMan54/homebridge-alexa <homebridge-alexa@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [NorthernMan54/homebridge-alexa] Alexa can no longer see Homebridge (V1) (#257)

Hi, I couldn’t get around this so took a different approach and yesterday got it working more or less as I wanted.

However, today pretty much the same thing that happened to me originally seems to have happened again – all of a sudden, Alexa cannot see my homebridge. Occasionally I see the “ERROR: ( homebridge-alexa) You have an issue with your installation, please review the README.” message in Homebridge. Thinking I’d damaged something while I was fiddling yesterday, I restored an image I took a couple of days ago where Alexa was working, just not properly with my groups. But not even this image is working and I occasionally see that same error message too.

I’ve checked the readme and troubleshooting documents which suggest it could be multiple instances of homebridge-alexa (it can’t be that as the image I restored was fine 4/5 days ago but having the same problem), and that my homebridge.ca credentials could be wrong (but it can’t be that, I’ve signed in in my browser fine, I’ve even set up another account and tried that – no difference). I’ve restarted the router too.

It must be my local network mustn’t it? Can you think of anything else?

**Comment by NorthernMan54** [comment]
The backend had crashed, and I restarted it about an hour ago.  This should be fine now.

**Comment by chrisp79** [comment]
Thanks, yes I’ve been able to link my account back up again and all seems fine.
Cheers



Sent from my iPad

On 11 Oct 2019, at 00:48, Northern Man <notifications@github.com> wrote:

﻿The backend had crashed, and I restarted it about an hour ago. This should be fine now.
