### ISSUE TITLE
Update error?

### ISSUE THREAD

**Issue by jat80** [NorthernMan54/homebridge-alexa#26]
I run the command sudo npm -g update and get the following error:

npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git clone --depth=1 -q -b master https://github.com/NorthernMan54/homebridge.git /Users/myusername/.npm/_cacache/tmp/git-clone-a338b955
npm ERR! /Users/myusername/.npm/_cacache/tmp/git-clone-a338b955/.git: Permission denied
npm ERR! 

any help would be appreciated.  Thanks!

**Comment by NorthernMan54** [comment]
JT

I haven't seen the update command work correctly for this, so please use install.  Also try sudo su - first.  It sometimes helps as well

sudo su -

npm install -g

**Comment by jat80** [comment]
@NorthernMan54 

Tried your suggestion but still error:

Mac-Mini:~ root# npm install -g
npm ERR! code ENOLOCAL
npm ERR! Could not install from "" as it does not contain a package.json file.

**Comment by NorthernMan54** [comment]
Sorry I'm doing this from my iPad so cut and paste doesn't work try this

sudo su -
npm install -g https://github.com/NorthernMan54/homebridge.git

**Comment by jat80** [comment]
Thanks @NorthernMan54 the above worked.
