### ISSUE TITLE
Cannot turn on/off thermostat 

### ISSUE THREAD

**Issue by huongminh** [NorthernMan54/homebridge-alexa#262]
Alexa would say the function is not supported if I say turn on/off air conditioner. However it works if I say set the temperature to xx degrees. This way, I can only turn it on to the degree I want but cannot turn off the air con. I have serveral air conditioners (thermostat type) from homebridge-broadlink-rm. All of them work well with homekit Siri when I say turn on / off the (living room) air conditioner. Recently I set up homebridge-gsh and all the same thermostats also work well with Google Home, too, when I say turn on/off the air conditioner.

**Comment by NorthernMan54** [comment]
To troubleshoot this, please supply a homebridge accessory dump

https://github.com/NorthernMan54/homebridge-alexa#homebridge-accessory-dump

**Comment by huongminh** [comment]
pls find it here:
curl -X PUT http://192.168.1.149:35088/accessories --header "Content-Type:Application/json" --header "authorization: 031-45-159" 
{"accessories":[{"aid":1,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Nick Farina","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Homebridge","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Homebridge-for-alexa","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"CC:22:3D:E3:CE:39","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"0.4.46","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":2000000008,"type":"49FB9D4D-0FEA-4BF1-8FA6-E7B18AB86DCE","characteristics":[{"iid":9,"type":"77474A2F-FA98-485E-97BE-4762458774D8","perms":["pr","ev"],"format":"uint8","value":0,"description":"State","maxValue":1,"minValue":0,"minStep":1},{"iid":10,"type":"FD9FE4CC-D06F-4FFE-96C6-595D464E1026","perms":["pr","ev"],"format":"string","value":"1.0","description":"Version"},{"iid":11,"type":"5819A4C2-E1B0-4C9D-B761-3EB1AFF43073","perms":["pr","pw","ev"],"format":"data","value":null,"description":"Control Point"}],"primary":false,"hidden":false}]}]}

**Comment by NorthernMan54** [comment]
I checked your setup, and it is fine.

With a thermostat, the voice command to turn off the device is

Alexa, set Jojo's Bedroom Air Conditioner to off
Alexa, set Jojo's Bedroom Air Conditioner to cool

If the wording is clumsy, you could create a routine with the wording that works better for yourself.

https://github.com/NorthernMan54/homebridge-alexa#thermostats-and-heater--coolers

**Comment by huongminh** [comment]
thank you for your support! it works for me. Indeed, the Alexa voice command wording to control thermostat is way clumsier than Google home's. When putting in the same group/room, Alexa does not understand short name "air conditioner" but only understand "thermostat".
