### ISSUE TITLE
Alexa keeps losing connection to devices - need homebridge restart

### ISSUE THREAD

**Issue by jcalmeida** [NorthernMan54/homebridge-alexa#263]
I just reinstalled my raspberry pi a couple of weeks ago and did a clean install with the most recente versions of homebridge and homebridge-alexa plugins.

Since then, Alexa keeps losing the connection to the devices, it keeps saying they are not responding. I can still control it with Siri and with Google, on the same homebridge instance. (

If I restart homebridge, Alexa can't work with it again. Seems like something is getting stuck. Also, when it's "stuck", I can't see any entry on the homebridge.log file when I try to communicate with it with Alexa. After the restart, I get "[Hall Lamp] Setting power state to on" and it works great.

What do you guys think? How should I troubleshoot this? (it's working at the time being)

My versions are the following:

- Homebridge  v0.4.50

- homebridge-alexa v0.4.39

- homebridge-gsh v1.0.3

- homebridge-http v0.0.9

- node v10.15.2

Thank you,
Joao

**Comment by NorthernMan54** [comment]
A debug log would be helpful from when the error occurs.
