### ISSUE TITLE
Alexa doesn't show motion sensor to start a routine.

### ISSUE THREAD

**Issue by Sinthos** [NorthernMan54/homebridge-alexa#266]
Hey, I've got Aqara motion sensors on Homebridge-Hue. 
Alexa shows me these in the tab "Devices" as motion sensors, the motion detection also works.

But if I want to create a routine with it, none of the motion sensors shows up. 
Only the ring doorbell can be used as an trigger for a routine in my house.

Is there a solution? Maybe a dummy switch or something similar can be used, if the Aqara motion sensors won't show up here ?

homebridge-hue v0.11.41
homebridge-alexa v0.4.39

**Comment by NorthernMan54** [comment]
Can you attach a homebridge accessory dump from your instance with the motion sensors

Tks

**Comment by Sinthos** [comment]
Thanks for the quick answer, here's the dump: https://justpaste.it/4p9lm

The three motion sensors are called "lumi.sensor_motion.aq2"

**Comment by NorthernMan54** [comment]
The dump looks good, did you set the 'routines' option?

https://github.com/NorthernMan54/homebridge-alexa#optional-parameters

**Comment by Sinthos** [comment]
Well, it could have been that simple. I actually missed it every time in the manual.
Thanks a lot for your help, now everything works fine and without problems.
