### ISSUE TITLE
ERROR: ( homebridge-alexa) You have an issue with your installation, please review the README

### ISSUE THREAD

**Issue by lagunacomputer** [NorthernMan54/homebridge-alexa#272]
no matter what i do i keep getting: ERROR: ( homebridge-alexa) You have an issue with your installation, please review the README

i dont have multiple homebridge instances running, and the username/password is good.  No VPN.
What can I do?  thanks

**Comment by NorthernMan54** [comment]
Please share a log file in DEBUG mode

**Comment by lagunacomputer** [comment]
Hi where can i locate the DEBUG file? i looked in /var/logs
thx

  hapNodeJSClient Starting Homebridge instance discovery +0ms
  alexaLocal Connecting to Homebridge Smart Home Skill +0ms
  EventedHTTPServer Server listening on port 51826 +0ms
[11/29/2019, 7:38:40 AM] Homebridge is running on port 51826.
  hapNodeJSClient HAP Device discovered Homebridge [ '192.168.1.20', 'fe80::b4ef:29ed:5e91:3549' ] +2s
  hapNodeJSClient HAP instance address: Homebridge -> CC_22_3D_E3_CE_30.local -> 192.168.1.20:51826 +50ms
  EventedHTTPServer [::ffff:192.168.1.20] New connection from client +1s
  EventedHTTPServer [::ffff:192.168.1.20] HTTP server listening on port 41837 +12ms
  EventedHTTPServer [::ffff:192.168.1.20] HTTP request: /accessories +113ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +4ms
  EventedHTTPServer [::ffff:192.168.1.20] HTTP Response is finished +85ms
  hapNodeJSClient Homebridge instance discovered Homebridge-CAD8 with 2 accessories +557ms
  EventedHTTPServer [::ffff:192.168.1.20] Client connection closed +135ms
  EventedHTTPServer [::ffff:192.168.1.20] HTTP connection was closed +16ms
  EventedHTTPServer [::ffff:192.168.1.20] HTTP server was closed +10ms
  hapNodeJSClient HAP Device discovered BSB002 [ 'fe80::217:88ff:fe2f:2542', '192.168.1.51' ] +5s
  hapNodeJSClient HAP instance address: BSB002 -> Philips-hue.local -> 192.168.1.51:8080 +6ms
  hapNodeJSClient HAP Device discovered IDEV0001 [ '192.168.1.57' ] +32ms
  hapNodeJSClient HAP instance address: IDEV0001 -> Switch-00071711.local -> 192.168.1.57:80 +4ms
  hapNodeJSClient HAP Discover failed BSB002 http://192.168.1.51:8080 error code 470 +102ms
  hapNodeJSClient HAP Discover failed IDEV0001 http://192.168.1.57:80 error code 470 +10ms
[11/29/2019, 7:38:48 AM] [Garage Door] INITIAL Garage Door state is: CLOSED
[11/29/2019, 7:38:48 AM] [Garage Door] INITIAL Garage Door target state is: CLOSED
[11/29/2019, 7:38:48 AM] [Garage Door] INITIAL Garage Light state is: OFF
  hapNodeJSClient HAP Device discovered IDEV0001 [ '192.168.1.61' ] +146ms
  hapNodeJSClient HAP instance address: IDEV0001 -> Switch-00008155.local -> 192.168.1.61:80 +4ms
  hapNodeJSClient HAP Discover failed IDEV0001 http://192.168.1.61:80 error code 470 +71ms
  hapNodeJSClient HAP Device discovered IDEV0008 [ '192.168.1.58' ] +3s
  hapNodeJSClient HAP instance address: IDEV0008 -> Wall-Switch-00377107.local -> 192.168.1.58:80 +3ms
  hapNodeJSClient HAP Device discovered IDEV0009 [ '192.168.1.52' ] +20ms
  hapNodeJSClient HAP instance address: IDEV0009 -> Wall-Dimmer-00538666.local -> 192.168.1.52:80 +4ms
  hapNodeJSClient HAP Discover failed IDEV0009 http://192.168.1.52:80 error code 470 +2s
  hapNodeJSClient HAP Discover failed IDEV0008 http://192.168.1.58:80 error code 470 +20ms
  EventedHTTPServer [::ffff:192.168.1.224] New connection from client +11s
  EventedHTTPServer [::ffff:192.168.1.224] HTTP server listening on port 42379 +5ms
  EventedHTTPServer [::ffff:192.168.1.224] New connection from client +13ms
  EventedHTTPServer [::ffff:192.168.1.224] HTTP server listening on port 33313 +3ms
  EventedHTTPServer [::ffff:192.168.1.224] HTTP request: /pair-verify +30ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +4ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +18ms
  EventedHTTPServer [::ffff:192.168.1.224] HTTP Response is finished +123ms
  EventedHTTPServer [::ffff:192.168.1.224] HTTP request: /pair-verify +3ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +2ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +5ms
  EventedHTTPServer [::ffff:192.168.1.224] HTTP Response is finished +49ms
  EventedHTTPServer [::ffff:192.168.1.224] HTTP request: /pair-verify +49ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +2ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +9ms
  HAPServer [CC:22:3D:E3:CE:30] Client CDA225FB-7F73-4E47-9276-8916A9AC647E verification complete +25ms
  EventedHTTPServer [::ffff:192.168.1.224] HTTP Response is finished +8ms
  EventedHTTPServer [::ffff:192.168.1.224] HTTP request: /pair-verify +7ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +3ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +4ms
  HAPServer [CC:22:3D:E3:CE:30] Client CDA225FB-7F73-4E47-9276-8916A9AC647E verification complete +24ms
  EventedHTTPServer [::ffff:192.168.1.224] HTTP Response is finished +9ms
  EventedHTTPServer [::ffff:192.168.1.224] HTTP request: /accessories +25ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +3ms
  EventedHTTPServer [::ffff:192.168.1.224] HTTP Response is finished +14ms
  EventedHTTPServer [::ffff:192.168.1.224] HTTP request: /accessories +467ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +15ms
  EventedHTTPServer [::ffff:192.168.1.224] HTTP Response is finished +12ms
  EventedHTTPServer [::ffff:192.168.1.224] HTTP request: /characteristics +376ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +2ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":10,"ev":true},{"aid":3,"iid":11,"ev":true}] +10ms
  Accessory [Homebridge] Registering Characteristic "Current Door State" for events +20ms
  Accessory [Homebridge] Registering Characteristic "Target Door State" for events +4ms
  EventedHTTPServer [::ffff:192.168.1.224] HTTP Response is finished +12ms
  hapNodeJSClient Ending Homebridge instance discovery +7s
  alexaActions alexaDiscovery +0ms
[11/29/2019, 7:39:00 AM] [Alexa] alexaDiscovery - returned 2 devices
  alexaActions registerEvents [ '{"host":"192.168.1.20","port":51826,"aid":3,"iid":10}': { '0': 'DETECTED',
    '1': 'NOT_DETECTED',
    endpointID:
     'Q0M6MjI6M0Q6RTM6Q0U6MzAtSG9tZWJyaWRnZS0oYykgMjAxNyBXYXJyZW4gQXNoY3JvZnQtR2FyYWdlIERvb3ItMDAwMDAwNDEtMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx',
    template: 'ContactSensor' } ] +111ms
  alexaActions Event Register 192.168.1.20:51826 -> { characteristics: [ { aid: 3, iid: 10, ev: true } ] } +18ms
  alexaLocal offline +20s
  EventedHTTPServer [::ffff:192.168.1.20] New connection from client +5s
  EventedHTTPServer [::ffff:192.168.1.20] HTTP server listening on port 36413 +3ms
  EventedHTTPServer [::ffff:192.168.1.20] HTTP request: /characteristics +36ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +3ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":10,"ev":true}] +4ms
  Accessory [Homebridge] Registering Characteristic "Current Door State" for events +4ms
  EventedHTTPServer [::ffff:192.168.1.20] HTTP Response is finished +5ms
  alexaLocal reconnect +5s
  alexaLocal reconnect +25s
  alexaLocal reconnect +25s
[11/29/2019, 7:40:02 AM] [Garage Door] ERROR in _checkStates() - ERROR in _determineDoorState() - An error occurred during the HTTP request: connect ENETUNREACH 192.168.1.59:80 - Local (0.0.0.0:0)
  alexaLocal reconnect +25s
  alexaLocal reconnect +25s
ERROR: ( homebridge-alexa) You have an issue with your installation, please review the README.

**Comment by NorthernMan54** [comment]
In your log file there is this message which is very troubling

alexaLocal reconnect +5s
alexaLocal reconnect +25s
alexaLocal reconnect +25s
alexaLocal reconnect +25s
alexaLocal reconnect +25s
ERROR: ( homebridge-alexa) You have an issue with your installation, please review the README.

Did you see this in troubleshooting?

https://github.com/NorthernMan54/homebridge-alexa/blob/master/Troubleshooting.MD#error--homebridge-alexa-you-have-an-issue-with-your-installation-please-review-the-readme

**Comment by lagunacomputer** [comment]
yes, the username/password is correct because i can log in into the skill in the Alexa app, there isn't another copy of homebridge running anywhere, and there is no VPN software on my pi.....

Any other suggestions? thanks sir

**Comment by NorthernMan54** [comment]
Looking at the system logs, you had been working since Mon Feb 11 2019, but recently started having issues?

In the backend log, it look like this

Nov 29 21:58:38 ip-172-26-1-254 startup[1111]: MQTT Message command/lagunacomputer/1 {"directive":{"header":{"namespace":"Alexa.Discovery","name":"Discover","payloadVersion":"3","messageId":"774ab138-df12-4140-99c8-87a952bc5ed6"},"payload":{}}}
Nov 29 21:58:44 ip-172-26-1-254 startup[1111]: Broker timed out lagunacomputer

Which is Alexa attempting to sending a command to your plugin, but failing as it can't make a connection.

It appears something on your end is interfering with the Mqtt connection on port 1883

**Comment by lagunacomputer** [comment]
thank you very much I will look at it from this perspective, thanks for you time sir

**Comment by lagunacomputer** [comment]
Thank you, this was fixed by  either correcting my Homebridge server/raspberry pi's DNS server settings, or by npm uninstalling the plugin, and reinstalling it.  Thanks for your time.

**Comment by NorthernMan54** [comment]
As it was a connectivity issue to the cloud servers, I would lean heavily on dns setting change.

The plugin itself has not had a significant change since last spring
