### ISSUE TITLE
Expose buttons to Alexa 

### ISSUE THREAD

**Issue by nixmeer** [NorthernMan54/homebridge-alexa#273]
Hello :)
I’m still trying to find a workaround to activate HomeKit scenes using Alexa. 

Is it possible to expose push buttons to Alexa? Then I could create a fake room in HomeKit with fake buttons of which each would trigger a scene, and then create Alexa routines that trigger these. 

Best :)

**Comment by NorthernMan54** [comment]
Yes, the homebridge-dummy plugin works great for that, or for more advanced control there is node-red and the HomeKit-bridged node

**Comment by nixmeer** [comment]
Well, I do have push buttons configured using homebridge-mqttthing and I use them all the time with my Sonoff Touch but they don’t show up in the Alexa app

**Comment by NorthernMan54** [comment]
My mqttthings switches etc show up in the Alexa app as a device

**Comment by nixmeer** [comment]
Do I have to activate the routines option in config.json?

**Comment by NorthernMan54** [comment]
Are you looking to trigger an Alexa routine, then you need use a contact or motion sensor and the routines option. Only contact and motion sensor appear in the routines-> when this happens -> devices option

If you looking to have a routine control a button/light etc, you don’t need anything special.  They should be available

**Comment by nixmeer** [comment]
No, I just want to trigger the scenes that are triggered by the buttons using Alexa. And they don’t show up. I’m not sure if I decided to use a tasmota homebridge plugin. I’m gonna check that later today

**Comment by NorthernMan54** [comment]
If they don’t show, please share a homebridge accessory dump, and I can run it thru the Alexa device parser to see why it isn’t finding your devices.

Details are in the readme

**Comment by nixmeer** [comment]
Thanks for your help!

**Comment by NorthernMan54** [comment]
These are configured as a 3 way switch in HomeKit, but Alexa doesn't have a 3 way switch model.  What type of device in Alexa should they be?

```
    }, {
      "iid": 8,
      "type": "00000089-0000-1000-8000-0026BB765291",
      "characteristics": [{
        "iid": 9,
        "type": "00000023-0000-1000-8000-0026BB765291",
        "perms": ["pr"],
        "format": "string",
        "value": "Kuechenschalter links",
        "description": "Name"
      }, {
        "iid": 10,
        "type": "00000073-0000-1000-8000-0026BB765291",
        "perms": ["pr", "ev"],
        "format": "uint8",
        "value": null,
        "description": "Programmable Switch Event",
        "valid-values": [0, 1, 2],
        "maxValue": 2,
        "minValue": 0
      }],
```

**Comment by nixmeer** [comment]
Hello :) sorry for not answering :/
I created dummy switches using mqttthing, put them all in a separate "Alexa" room added automations that call my scenes whenever a switch is used ➡️ Alexa can trigger these switches and therefore trigger my HomeKit scenes. 
However, stateless buttons in HomeKit do have the advantage that it's possible to assign an action directly to the button without the need of the workaround using automations. So maybe it's possible to expose these stateless switches to Alexa as switches and if Alexa turns them on, they are pushed once in HomeKit?
Best
Jan

**Comment by NorthernMan54** [comment]
With the Alexa API the options are turn on or turn off, and Alexa does not check current status of the device before sending so she is happy to send a turn on to a device that is already on or turn off for a device that is already off.  ( This behaviour does not exist via the home app, as the UI only allows you to turn off a device that is already on )

Basically Alexa treats all switches etc as stateless

**Comment by NorthernMan54** [comment]
If you need to do some advanced automation work, have you tried using node-red and homebridge-automation and HomeKit-bridged.  I used it for this

https://github.com/NorthernMan54/node-red-contrib-homebridge-automation/wiki/Stateful-Lights

Which scored really high on the WAF score

**Comment by nixmeer** [comment]
I thought about something like that before but for now I'd just be able to activate my HomeKit scenes using Alexa. As I said before, it does work now. However, one could save the extra step of adding an automation in the Home app that activates the scene when the switch is activated. Instead, one could add push buttons (no switches) using Homebridge and then connect the scenes directly to the push button.

**Comment by NorthernMan54** [comment]
I think I achieved that by not using scenes, but by wiring them up in node-red.  As scenes are not visible to homebridge-alexa, needed to do it where it could be exposed to Alexa.  See my example.

For the tri state switches you are using

```
"description": "Programmable Switch Event",
        "valid-values": [0, 1, 2],
```

Alexa does not have a device model to support this, ( only on/off ).  But I could wire the "Programmable Switch Event" into the Alexa on / off model and have Alexa turn on send a 1 and turn off send a zero.

Does that work?   You would not have mode 2 available.

**Comment by mkrug1** [comment]
Hello,
Jumping in here...
This is a great plug in.  In addition, I am using the Http Webhooks plug in to make a variety of stateless switches.

**Comment by NorthernMan54** [comment]
@mkrug1 Not sure what your inquiring about here.
