### ISSUE TITLE
Exclude some devices from discovery

### ISSUE THREAD

**Issue by mrgingles** [NorthernMan54/homebridge-alexa#275]
Hi,
do you think it's possible to exclude some devices from the Alexa discovery?

I have the following scenario:
I have a lot of devices which are natively supported by Alexa but not by HomeKit. So I added these devices into my Hoobs in order to have them managed by HomeKit. When I launch Alexa discovery, these devices are listed twice into my Alexa app (one for the native and another one thanks to homebridge-alexa)

1. If I delete them from the Alexa app, they will reappear after the next discovery
2. If i disable them, they cause a name conflict with the native version of the device (Alexa says that can not control the device because it is disabled)
3. If I rename them, Alexa makes confusion (I don't really know why) and the devices are not working as should on every request (it works/doesn't work randomly)

So avoiding completely the discovery of that devices by Alexa would be an elegant-working solution. Do you think is possible?

Thank you!

**Comment by NorthernMan54** [comment]
This is available in a limited fashion via the filter configuration option.

Requires having the devices you don’t want to expose to Alexa via homebridge to be in its own instance

**Comment by mrgingles** [comment]
If I got it right I should start two homebridge instances and move the device I don't want to be managed by Alexa in the second instance. Then use the filter setting of the plugin to let it grab the devices from the first instance... right?

**Comment by NorthernMan54** [comment]
Correct

**Comment by baakoo** [comment]
Hi - i would like to vote for this feature. Sonos, Harmony, Roborock - all these plugins work quite nice with Alexa and I have problems with two devices with the same name ...

Two instances of homebridge sound complicated for me. Maybe this is something you could keep in mind for further versions ...?
