### ISSUE TITLE
SyntaxError after Homebridge has been started

### ISSUE THREAD

**Issue by toheiteddy** [NorthernMan54/homebridge-alexa#276]
Hello, my homebridge is set up on a Raspberry Pi 4B. It runs fine with the homebridge-config-ui-x plugin. Once the homebridge-alexa plugin is installed, the bridge stops with a SyntaxError.
Installed is:

npm v6.12.1
node v12.13.1
homebridge-alexa v0.4.43

Please find attached my config.json and the debug log. The error message in the log is red marked. Thanks for your help!
[config.json.pdf](https://github.com/NorthernMan54/homebridge-alexa/files/3932382/config.json.pdf)
[Log_1.pdf](https://github.com/NorthernMan54/homebridge-alexa/files/3932383/Log_1.pdf)

**Comment by NorthernMan54** [comment]
If you update to the latest, this should be resolved

**Comment by toheiteddy** [comment]
Now it works.
1000 thanks from Germany!
BR
Toheiteddy
