### ISSUE TITLE
Alexa Plugins crashes Homebridge

### ISSUE THREAD

**Issue by gardenalr** [NorthernMan54/homebridge-alexa#278]
**Error Log:**
2019-12-08T15:16:13.570Z alexaLocal connect command/gardenal/#
2019-12-08T15:16:14.273Z hapNodeJSClient HAP Device discovered HomeBridge [ '192.168.1.107', 'fe80::b020:10af:18e5:9527' ]
2019-12-08T15:16:14.330Z hapNodeJSClient HAP instance address: HomeBridge -> CC_22_3D_E3_CE_34.local -> 192.168.1.107:51826
2019-12-08T15:16:16.561Z hapNodeJSClient Homebridge instance discovered HomeBridge-B03F with 10 accessories
2019-12-08T15:16:31.470Z hapNodeJSClient Ending Homebridge instance discovery
2019-12-08T15:16:31.483Z alexaActions alexaDiscovery
[12/8/2019, 1:16:31 PM] TypeError: Cannot read property 'getCharacteristic' of undefined
    at Service.toAlexa (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Service.js:187:60)
    at Accessory.toAlexa (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Accessory.js:142:27)
    at Homebridge.toAlexa (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Homebridge.js:161:27)
    at Homebridges.toAlexa (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Homebridges.js:47:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:100:28)
    at HAPNodeJSClient.HAPaccessories (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:163:3)
    at Object.alexaDiscovery (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:93:14)
    at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:33:20)
    at HAPNodeJSClient.emit (events.js:198:13)
    at HAPNodeJSClient._discoveryEnd (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:149:8)

**My Config File:**
{
    "bridge": {
        "name": "HomeBridge",
        "username": "hidden",
        "port": 51826,
        "pin": "031-45-157"
    },
    "description": "This file is used for plugin configuration.",
    "accessories": [
        {
            "accessory": "lgtv-2012",
            "name": "Volume TV",
            "ip": "192.168.1.106",
            "pairingKey": "280132",
            "min_volume": 2,
            "max_volume": 20,
            "on_command": "MUTE"
        },
        {
            "accessory": "marantz-volume",
            "name": "Volume Denon",
            "host": "192.168.1.188:8080",
            "maxVolume": 65,
            "mapMaxVolumeTo100": true,
            "controlPower": true
        },
        {
            "accessory": "DenonAVR",
            "name": "Input Media Player",
            "ip": "192.168.1.188",
            "requiredInput": "MPLAY",
            "pollInputAll": false
        },
        {
            "accessory": "DenonAVR",
            "name": "Input Game",
            "ip": "192.168.1.188",
            "requiredInput": "GAME"
        },
        {
            "accessory": "DenonAVR",
            "name": "Input Cabo",
            "ip": "192.168.1.188",
            "requiredInput": "SAT%2FCBL"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "amber",
            "sudo": true,
            "standalone": true,
            "restart": "sudo -n systemctl restart homebridge homebridge-config-ui-x",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "log": {
                "method": "custom",
                "command": "sudo -n journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x"
            },
            "platform": "config"
        },
        {
            "platform": "GlobalCacheItach",
            "name": "Global Cache Itach",
            "devices": [
                {
                    "name": "Global Cache Itach",
                    "host": "192.168.1.110",
                    "enableLearnLogging": false,
                    "ports": [
                        {
                            "name": "Luz",
                            "port": "3",
                            "commands": {
                                "on": [
                                    "1,36000,1,1,32,32,64,32,32,64,32,32,32,32,64,32,32,32,32,32,32,32,32,32,32,64,32,3240",
                                    "1,36000,1,1,32,32,32,32,64,64,32,32,32,32,64,32,32,32,32,64,64,64,32,32,32,3240"
                                ],
                                "off": [
                                    "1,36000,1,1,32,32,64,32,32,64,32,32,32,32,64,32,32,32,32,32,32,32,32,32,32,32,32,3272",
                                    "1,36000,1,1,32,32,32,32,64,64,32,32,32,32,64,32,32,32,32,32,32,32,32,32,32,32,32,3272"
                                ]
                            }
                        },
                        {
                            "name": "Luz Cortina",
                            "port": "3",
                            "commands": {
                                "on": [
                                    "1,36000,1,1,32,32,64,32,32,64,32,32,32,32,64,32,32,32,32,32,32,64,64,64,32,3240",
                                    "1,36000,1,1,32,32,32,32,64,64,32,32,32,32,64,32,32,32,32,32,32,64,64,64,32,3240"
                                ],
                                "off": [
                                    "1,36000,1,1,32,32,64,32,32,64,32,32,32,32,64,32,32,32,32,32,32,32,32,32,32,32,32,3272",
                                    "1,36000,1,1,32,32,32,32,64,64,32,32,32,32,64,32,32,32,32,32,32,32,32,32,32,32,32,3272"
                                ]
                            }
                        },
                        {
                            "name": "Ar Condicionado",
                            "port": "2",
                            "commands": {
                                "on": "2,38004,1,1,125,61,16,15,16,15,16,46,16,15,16,46,16,15,16,15,16,15,16,46,16,46,16,15,16,15,16,15,16,46,16,46,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,46,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,46,16,15,16,15,16,15,16,15,16,46,16,46,16,46,16,46,16,46,16,46,16,46,16,46,16,15,16,15,16,46,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,46,16,46,16,15,16,15,16,46,16,15,16,15,16,15,16,46,16,46,16,46,16,15,16,46,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,46,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,15,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,46,16,15,16,15,16,15,16,46,16,15,16,46,16,46,16,46,16,15,16,15,16,3800",
                                "off": "8,38004,1,1,125,61,16,15,16,15,16,46,16,15,16,46,16,15,16,15,16,15,16,46,16,46,16,15,16,15,16,15,16,46,16,46,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,46,16,15,16,15,16,15,16,15,16,15,16,15,16,15,16,46,16,15,16,15,16,15,16,15,16,46,16,15,16,15,16,15,16,15,16,15,16,15,16,46,16,15,16,46,16,46,16,46,16,46,16,46,16,46,16,3800"
                            }
                        },
                        {
                            "name": "TV",
                            "port": "1",
                            "commands": {
                                "on": "1,38000,1,69,340,169,20,20,20,20,20,64,20,20,20,20,20,20,20,20,20,20,20,64,20,64,20,20,20,64,20,64,20,64,20,64,20,64,20,20,20,20,20,20,20,64,20,20,20,20,20,20,20,20,20,64,20,64,20,64,20,20,20,64,20,64,20,64,20,64,20,1544,340,85,20,3663",
                                "off": "1,38000,1,69,340,169,20,20,20,20,20,64,20,20,20,20,20,20,20,20,20,20,20,64,20,64,20,20,20,64,20,64,20,64,20,64,20,64,20,20,20,20,20,20,20,64,20,20,20,20,20,20,20,20,20,64,20,64,20,64,20,20,20,64,20,64,20,64,20,64,20,1544,340,85,20,3663"
                            }
                        }
                    ]
                }
            ]
        },
        {
            "name": "Alexa",
            "username": "hidden",
            "password": "hidden!",
            "pin": "031-45-157",
            "debug": true,
            "platform": "Alexa"
        }
    ]
}

**Comment by NorthernMan54** [comment]
Can you share an accessory dump

https://github.com/NorthernMan54/homebridge-alexa#homebridge-accessory-dump

The Alexa device parser is failing on one of your devices.

**Comment by gardenalr** [comment]
I narrowed down to the plugin that is failing:

Config section:
{
            "accessory": "lgtv-2012",
            "name": "Volume TV",
            "ip": "192.168.1.106",
            "pairingKey": "280132",
            "min_volume": 2,
            "max_volume": 20,
            "on_command": "MUTE"
        }

Plugin:
Git: https://github.com/i0null/homebridge-lgtv-2012#readme
NPM: https://www.npmjs.com/package/homebridge-lgtv-2012

Does it help or you really need the acessory dump?

**Comment by NorthernMan54** [comment]
Need the dump, as I use it as a test case to resolve the issue

**Comment by gardenalr** [comment]
Ok, thanks, will get it

**Comment by gardenalr** [comment]
Hi, here is acessory dump:
https://drive.google.com/open?id=1SOT72Cjh0rdnX5WBJOaOq9A5YODPuTgG
Thanks

**Comment by NorthernMan54** [comment]
Tks for the dump, made it a quick fix

Please update to the latest and try again

**Comment by gardenalr** [comment]
Thanks, it was fixed and it is working fine.

**Comment by santiagos5** [comment]
Hello, same problem here..
Once or twice for day, homebridge still running but not response for accessory
This is my dump file: 
https://www.dropbox.com/s/c03ico5d1to18t1/dump.json?dl=0

**Comment by NorthernMan54** [comment]
I looked at your dump and nothing jumped out at me.  Can you look at your homebridge log and see if any errors are appearing from the plugin itself?  If you run homebridge in DEBUG mode, it will log more details.

**Comment by santiagos5** [comment]
This is last crash: 

0|homebrid | 2020-02-17T16:55:00.117Z hapNodeJSClient HAP instance address: Homebridge -> CC_22_3D_E3_CE_34.local -> 192.168.178.35:51826
0|homebrid | 2020-02-17T16:55:00.243Z hapNodeJSClient Homebridge instance discovered Homebridge-B03F with 49 accessories
0|homebrid | 2020-02-17T16:55:17.964Z hapNodeJSClient Ending Homebridge instance discovery
0|homebrid | 2020-02-17T16:55:17.966Z alexaActions alexaDiscovery
0|homebrid | 2020-02-17T16:55:18.039Z alexaActions registerEvents [ '{"host":"192.168.178.35","port":51826,"aid":12,"iid":10}': { '0': 'DETECTED',
0|homebrid |     '1': 'NOT_DETECTED',
0|homebrid |     endpointID: 'Q0M6MjI6M0Q6RTM6Q0U6MzQtSG9tZWJyaWRnZS1Ccm9hZGxpbmstQ2FuY2VsbG8tMDAwMDAwNDEtMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx',
0|homebrid |     template: 'ContactSensor' },
0|homebrid |   '{"host":"192.168.178.35","port":51826,"aid":13,"iid":10}': { '0': 'DETECTED',
0|homebrid |     '1': 'NOT_DETECTED',
0|homebrid |     endpointID: 'Q0M6MjI6M0Q6RTM6Q0U6MzQtSG9tZWJyaWRnZS1Ccm9hZGxpbmstR2FyYWdlIGVzdGVybm8tMDAwMDAwNDEtMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx',
0|homebrid |     template: 'ContactSensor' } ]
0|homebrid | 2020-02-17T16:55:18.040Z alexaActions Event Register 192.168.178.35:51826 -> { characteristics: 
0|homebrid |    [ { aid: 12, iid: 10, ev: true },
0|homebrid |      { aid: 13, iid: 10, ev: true } ] }


I'll run with DEBUG and let you know..
Thanks

**Comment by NorthernMan54** [comment]
There does not appear to be any issues within that fragment
