### ISSUE TITLE
Homebridge, Alexa and IOS 11

### ISSUE THREAD

**Issue by dmckillican** [NorthernMan54/homebridge-alexa#28]
Hey

The old Homebridge no longer works with IOS 11 (Shows no response on iPhones), however this appears to have been fixed in the most recent update from homebridge. Alas, the Alexa specific homebridge you have created is not updated or working. Is it possible to update the Alexa homebridge version so that it is IOS 11 compatible as with the original homebridge app?

Thanks, Drew

**Comment by NorthernMan54** [comment]
Drew,

I updated it back in August at roughly the same time as the main homebridge was updated.  Just update to the latest and you should be fine

**Comment by SzilagyiR** [comment]
Hi!

Same issue here, hoe can I update?

Thanks!

**Comment by SzilagyiR** [comment]
Hi!

Same issue here, how can I update?

Thanks!

**Comment by SzilagyiR** [comment]
I tried this, but still not responding.

sudo su -
npm install -g https://github.com/NorthernMan54/homebridge.git

**Comment by NorthernMan54** [comment]
Glad to hear, good luck
