### ISSUE TITLE
Filter Causes HAP issue

### ISSUE THREAD

**Issue by meluvalli** [NorthernMan54/homebridge-alexa#281]
Get the following error if I use filter:
<pre>
[Alexa] ERROR: HAP Discovery failed, please review config
</pre>

Trying to run two instances so need it to filter ONLY the one instance.
<pre>
"filter": "192.168.1.50:42701"
</pre>

My bridge is running on that local IP and that port.
<pre>
    "mdns": {
        "interface": "192.168.1.50"
    },
    "bridge": {
        "name": "Homebridge for Homeseer",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 42701,
        "pin": "123-45-678",
    },
</pre>

Works fine if I don't have the filter line in Alexa platform.

**Comment by NorthernMan54** [comment]
A couple of things trigger this message, and one of them is not discovering any Alexa compatible devices.  I’m thinking this is the case.

**Comment by NorthernMan54** [comment]
I believe this is resolved?

**Comment by meluvalli** [comment]
Yes.  I no longer have this issue.  Thanks!
