### ISSUE TITLE
Can't rediscover a deleted device

### ISSUE THREAD

**Issue by lorenzo999** [NorthernMan54/homebridge-alexa#283]
I deleted a device and now I want to re-add it but Alexa does not find it.
I even tried to update the plugin and then disable e re-enable the skill.

Any hints?

**Comment by NorthernMan54** [comment]
If you delete an accessory it will add it again,  Is the homebridge instance with the device still running?

**Comment by lorenzo999** [comment]
Yes I’m currently using it with Siri on HomeKit.

**Comment by NorthernMan54** [comment]
Please attach a homebridge accessory dump, details are in the README

**Comment by lorenzo999** [comment]
Closing the issue, the device was actually discovered but it had a different name from the one on Homekit that I had renamed. Thank you for your help!
