### ISSUE TITLE
Problem with Thermostats when Fahrenheit is used

### ISSUE THREAD

**Issue by mcmspark** [NorthernMan54/homebridge-alexa#285]
The thermostats always communicate in Celsius but the end display converts to Fahrenheit as needed.  My Echo Show is set to Fahrenheit.  If I ask "Alexa what is the temperature in Zone 1" The Echo Show displays it correctly and lets me set the temperature.  This appears to work correctly.
If I navigate to the devices-thermostats in the echo show.  It shows all the temperatures in Celsius.

I am unsure is this is a service issue or an Echo Show issue.

Also When I command Alexa to set the temperatures it is feeding the literal value to the service without conversion.

I think your bridge is not reading the Characteristic.TemperatureDisplayUnits of the thermostat and enforcing the conversion.

Siri works fine and all HomeKit interfaces work fine.

**Comment by NorthernMan54** [comment]
Looking at the code, I never implemented support for FAHRENHEIT.  I had assumed that Alexa would use Celsius as the internal default for everything similar to HomeKit.

```
{"directive":
  {"header":   
    {"namespace": "Alexa.ThermostatController", 
      "name":"SetTargetTemperature", 
      "payloadVersion":"3", 
      ""payload": { "targetSetpoint": 
          {"value":93,"scale":"FAHRENHEIT"}}}}
```

Give me a few days to figure this out

**Comment by NorthernMan54** [comment]
It was a simple change, please upgrade to the latest version and try again

**Comment by mcmspark** [comment]
Thanks, I also added a new validator to my thermostat code to protect against such things.

**Comment by mcmspark** [comment]
Thanks again, I have confirmed the fix.
Your fix, no longer sends Fahrenheit values to the TargetTemperature.

Echo Show still displays in Celsius on some screens.  I thin this is an Amazon bug since it is not consistent. Closing this issue

**Comment by NorthernMan54** [comment]
Tks for confirming
