### ISSUE TITLE
how to exclude an accessory

### ISSUE THREAD

**Issue by giannimp** [NorthernMan54/homebridge-alexa#290]
Hi, Can I exlude enable e disable alarm from alexa?
{
    "platform": "LegrandMyHome",
    "ipaddress": "192.168.x.xxx",
    "port": 2xxx0,
    "ownpassword": "xxxxxx",
    "discovery": false,
    "devices": [
        {
            "accessory": "MHRelay",
            "name": "Luce Ingresso",
            "address": "0/3/1"
        },
        {
            "accessory": "MHRelay",
            "name": "Luce Balcone Cucina",
            "address": "0/2/2"
        },
        {
            "accessory": "MHRelay",
            "name": "Luce Salotto",
            "address": "0/4/1"
        },
        {
            "accessory": "MHRelay",
            "name": "Luce Stanza Ciro",
            "address": "0/5/1"
        },
        {
            "accessory": "MHRelay",
            "name": "Luce Bagno",
            "address": "0/6/1"
        },
        {
            "accessory": "MHRelay",
            "name": "Luce Specchio",
            "address": "0/6/2"
        },
        {
            "accessory": "MHRelay",
            "name": "Luce Camera da Letto",
            "address": "0/7/1"
        },
        {
            "accessory": "MHRelay",
            "name": "Luce Balcone Camera da Letto",
            "address": "0/7/3"
        },
        {
            "accessory": "MHRelay",
            "name": "Luce Corridoio",
            "address": "0/8/4"
        },
        {
            "accessory": "MHRelay",
            "name": "Luce Stanzino",
            "address": "0/8/1"
        },
        {
            "accessory": "MHRelay",
            "name": "Bagno Caldo",
            "address": "0/9/9"
        },
        {
            "accessory": "MHBlind",
            "name": "Tapparella Cucina",
            "address": "0/2/3",
            "time": "5"
        },
        {
            "accessory": "MHBlind",
            "name": "Tapparella Salotto",
            "address": "0/4/2"
        },
        {
            "accessory": "MHBlind",
            "name": "Tapparella Stanza Ciro",
            "address": "0/5/2",
            "time": "5"
        },
        {
            "accessory": "MHRelay",
            "name": "Luce Balcone Ciro",
            "address": "0/5/3"
        },
        {
            "accessory": "MHBlind",
            "name": "Tapparella Bagno",
            "address": "0/6/4",
            "time": "5"
        },
        {
            "accessory": "MHBlind",
            "name": "Tapparella Camera da Letto",
            "address": "0/7/2",
            "time": "5"
        },
        {
            "accessory": "MHRelay",
            "name": "Luce Tavolo",
            "address": "0/2/5"
        },
        {
            "accessory": "MHRelay",
            "name": "Luce Cucina",
            "address": "0/2/1"
        },
        {
            "accessory": "MHRelay",
            "name": "Allarme",
            "address": "0/9/1",
            "frame_on": "*9*1*1##"
        }
    ]
}
only accessory "Allarme", from list of accessories alexa
thank you

**Comment by NorthernMan54** [comment]
Individual device filtering is not a feature of this plugin.  You can only filter at a homebridge instance leve.
