### ISSUE TITLE
Feature request - support for general purpose sensor

### ISSUE THREAD

**Issue by dcaccount** [NorthernMan54/homebridge-alexa#292]
Hello NorthernMan54,
First of all thanks for your great plugin.

Ii would be great if your plugin could support also “general purpose” sensors like smoke, co2, flooding and other types of sensors.

Yesterday I have created a MQTT sensor able to monitor the house consumption and to publish it in Alexa environment, I have had to configure it as motion sensor.

Please be so kind to consider this request!
Thanks,
Dan

**Comment by NorthernMan54** [comment]
Dan,

The support for individual sensor types is limited by Alexa. I have implemented support for most of the devices that Alexa 

Take a read of this

https://developer.amazon.com/en-US/docs/alexa/smarthome/understand-the-smart-home-skill-api.html
