### ISSUE TITLE
Apple TV not discovered

### ISSUE THREAD

**Issue by novillage90** [NorthernMan54/homebridge-alexa#294]
Ive been having some trouble getting the plugin to discover my Apple TV.

Once enabled should the Alexa Discovery pickup the Apple TV? Ive checked my accessories and cannot see any entries listed like example. 

Other devices have been picked up successfully, could it be because my Apple TV is currently a hub or is it just user error?

**Comment by NorthernMan54** [comment]
Please share a homebridge accessory dump, details are in the README.
