### ISSUE TITLE
Homebridge-dummy-contact

### ISSUE THREAD

**Issue by dkahia** [NorthernMan54/homebridge-alexa#297]
I would like to use your dummy-contact plugin with Alexa, but can’t seem to figure out how to install it. I modified a command line to install from your git repo, but it gives me an ssh password error during the install. Is the dummy-contact plugin still supported?

**Comment by NorthernMan54** [comment]
Looking at that package, I had never published it via NPM.  So I just published it, and you should be able to install with

npm install -g homebridge-dummy-contact

However since I wrote that I moved on to using node-red and homebridge-automation and HomeKit-bridged for majority of my "tricks"

**Comment by dkahia** [comment]
I had a rainy weekend here, and set about getting your homebridge-Alexa up and running. My goal has been to trigger routines based on my Homekit automations. I am not planning on using Alexa to initiate activity in Homekit. 

I was able to trigger some routines using homebridge-automation-switches to set up some motion sensors as triggers, but they don’t maintain their state, at least not without additional virtual devices. I am hoping the dummy-contacts will maintain state while offering a trigger via the contact sensor. I wanted to enable and disable Guard mode on Alexa and have Homekit know the current status, but found I can’t automate disabling, so everything I’ve done so far amount to just parlor tricks. 

Thank you for publishing your homebridge-dummy-contact package. I hope it proves helpful to others without creating extra work for you. You might consider referencing it in your homebridge-Alexa documentation.

**Comment by NorthernMan54** [comment]
Here is a good "Rainy Day" option

https://github.com/NorthernMan54/node-red-contrib-homebridge-automation/wiki/Stateful-Lights

After I set this up, you don't even realize how complex things were before
