### ISSUE TITLE
[Alexa] ERROR: HAP Discovery failed, please review config

### ISSUE THREAD

**Issue by the-blaggyS** [NorthernMan54/homebridge-alexa#298]
That's the command I use to start homebridge:
`sudo -u homebridge DEBUG=alexa* homebridge -I -D -U /var/lib/homebridge/`
And this one is the config I use:
`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "accessories": [
        {
            "accessory": "RFOutlet",
            "name": "Fernseher Lampe",
            "type": "Light",
            "rf_on": 1394001,
            "rf_off": 1394004,
            "pulselength": "330",
            "pin": "15"
        },
        {
            "accessory": "RFOutlet",
            "name": "Fensterbank Lampe",
            "type": "Light",
            "rf_on": 1397073,
            "rf_off": 1397076,
            "pulselength": "330",
            "pin": "15"
        },
        {
            "accessory": "RFOutlet",
            "name": "Schreibtisch Lampe",
            "type": "Light",
            "rf_on": 1398033,
            "rf_off": 1398036,
            "pulselength": "330",
            "pin": "15"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "debug": false,
            "platform": "config"
        },
        {
            "platform": "Alexa",
            "name": "Alexa",
            "username": "...",
            "password": "..."
        }
    ]
}`

In the Troubleshooting.md it says, that I forgot the insecure option, which I haven't or that the accessories aren't supported by homebridge-alexa, but the readme says that lights and switches are supported, so I guess these RFOutlets should be supported?

**Comment by NorthernMan54** [comment]
Can you try a homebridge accessory dump, details are in the readme.

Also the log fragment from around the error would be helpful.

**Comment by the-blaggyS** [comment]
This one is the accessory dump:
`{"accessories":[{"aid":1,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Nick Farina","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Homebridge","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Homebridge","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"CC:22:3D:E3:CE:30","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"0.4.50","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":2000000008,"type":"49FB9D4D-0FEA-4BF1-8FA6-E7B18AB86DCE","characteristics":[{"iid":9,"type":"77474A2F-FA98-485E-97BE-4762458774D8","perms":["pr","ev"],"format":"uint8","value":0,"description":"State","maxValue":1,"minValue":0,"minStep":1},{"iid":10,"type":"FD9FE4CC-D06F-4FFE-96C6-595D464E1026","perms":["pr","ev"],"format":"string","value":"1.0","description":"Version"},{"iid":11,"type":"5819A4C2-E1B0-4C9D-B761-3EB1AFF43073","perms":["pr","pw","ev"],"format":"data","value":null,"description":"Control Point"}],"primary":false,"hidden":false}]},{"aid":9,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Manufacturer","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Model","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Fernseher Lampe","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-SerialNumber","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Fernseher Lampe","description":"Name"},{"iid":10,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":false,"description":"On"}],"primary":false,"hidden":false}]},{"aid":10,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Manufacturer","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Model","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Fensterbank Lampe","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-SerialNumber","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Fensterbank Lampe","description":"Name"},{"iid":10,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":false,"description":"On"}],"primary":false,"hidden":false}]},{"aid":11,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Manufacturer","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Model","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Schreibtisch Lampe","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-SerialNumber","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Schreibtisch Lampe","description":"Name"},{"iid":10,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":false,"description":"On"}],"primary":false,"hidden":false}]}]}`
But I'm not sure which parts of the log could help you.
These lines are directly related to Alexa:
`  alexaLocal Connecting to Homebridge Smart Home Skill +0ms
[2/26/2020, 1:35:27 AM] Homebridge is running on port 51826.
  alexaLocal connect command/SweetHome/# +482ms
[2/26/2020, 1:35:31 AM] [Config] Homebridge Config UI X v4.10.3 is listening on :: port 8581
  alexaActions alexaDiscovery +0ms
[2/26/2020, 1:35:46 AM] [Alexa] ERROR: HAP Discovery failed, please review config
  alexaActions registerEvents [] +5ms`

And I get this HAP server warning:
`HAPServer [...] WARNING: Handler for / not implemented +2ms`

And these are the versions I'm using:
`homebridge-alexa v0.4.52, node v12.16.1, homebridge v0.4.50`

If you need the full log, I can upload it maybe to pastebin

**Comment by NorthernMan54** [comment]
The dump looks good, so need to see the log file

```
alexaDiscovery - returned 3 devices
Alexa Message Validation Passed!
                    "friendlyName": "Fensterbank Lampe",
                    "friendlyName": "Fernseher Lampe",
                    "friendlyName": "Schreibtisch Lampe",
```

**Comment by the-blaggyS** [comment]
I uploaded the full debug log here https://pastebin.com/Gk8tUaLA

**Comment by NorthernMan54** [comment]
Something odd is going on here, as the homebridge instance discovery is not returning any homebridge instances.  Are you running this in a container or something?

Instance discovery is using mdns/avahi

**Comment by the-blaggyS** [comment]
I found the culprit! I forgot about a few iptable rules.
I flushed them all and now it's working.
Thank you for your help! I probably had the ports for mdns/avahi blocked too.

**Comment by NorthernMan54** [comment]
Glad to hear
