### ISSUE TITLE
Air conditioner 

### ISSUE THREAD

**Issue by jat80** [NorthernMan54/homebridge-alexa#3]
Will this ever be able to control an air conditioner or other homebridge HomeKit devices in the future?

I currently control my air conditioner with the rm mini 3 homebridge plugin.  Would be great even if alexa could trigger scenes I've setup for it?  Would that be possible?

**Comment by NorthernMan54** [comment]
Adding support for additional devices is feasible, and not the complex.  When I wrote the interface to Alexa I picked a handful of service types to map over, based on devices in my config.  The current code base maps over the service types light, outlet and switch to Alexa, adding more is feasible but the service needs to support the characteristic On, as I have mapped this characteristic to Alexa.  I also mapped over brightness as well.  If you could share which service type and plugin I could look at adding.

Pleaese keep in mind that the API I'm using from Alexa is limited and is mimicking a hue light bulb, and only supports turning on/off and setting a brightness.  Supporting a more robust interface is feasible, but would require writing and deploying custom skill which is is very complex to install.  And would require money to support the cloud services behind it.  Hence I went for the easy to implement, no cost approach.

For HomeKit scenes, these are not visible at the homebridge layer and are not supported. Sorry.

**Comment by jat80** [comment]
Thanks for the response @NorthernMan54.  

Most of my homekit accessories I run via hap-nodejs server on a raspberry pi.  The only accessory I use with my homebridge server on my mac is https://github.com/lprhodes/homebridge-broadlink-rm.  Which I use to control my air conditioner.  I think it comes under thermostat service type and will probably use it to control the volume of the tv at some point when @lprhodes updates it to be able to do that.

Thanks for your time.

**Comment by NorthernMan54** [comment]
@jat80 what accessories are you running with hap-node?  The Alexa code is actually all in hap-node, and the only part in homebridge is the on switch for the feature.  With a couple of lines of code in your accessory it could be enabled.

**Comment by jat80** [comment]
@NorthernMan54 Currently have a Motion sensor, temperature sensor, Lights and a fan.  I can already control the lights and a fan via alexa as they are all running using a sonoff's with the [tasmota](https://github.com/arendst/Sonoff-Tasmota) firmware that i've flashed to them. :)

**Comment by lprhodes** [comment]
@jat80  I'm in the middle of re-writing homebridge-broadlink-rm at the moment and then I'll be moving onto writing an iOS app that will bridge Alexa commands to HomeKit commands.

**Comment by jat80** [comment]
@lprhodes Wow!  Amazing stuff.  Looking forward to the updates. :)  What goodies do you have coming with the re-write of the broadlink plugin?

**Comment by jat80** [comment]
@lprhodes the iOS app sounds awesome!

**Comment by lprhodes** [comment]
@jat80 I'm going through the issues list as I write it but I'll be making accessories more modular so that they can be used more generically. Adding support for increasing/decreasing volume, more channels if you wish, auto-discovery of one or more Broadlink devices, current temperature support where available and a way to quick learn air condition commands one after another.

**Comment by jat80** [comment]
@lprhodes that is amazing mate.  I'm very limited in how to code etc and find people that are able to do all this so talented.  I love tech and home automation and being able to try out all this stuff without having to folk out $$$$ for "official homekit/alexa" devices when I can create them myself is so much fun and rewarding.  Thanks to you and @NorthernMan54 for making all this code available to guys like myself to use.  It's much appreciated. :)

**Comment by NorthernMan54** [comment]
@jat80 I looked at the broadlink plugin, and it is service type thermostat, which I didn't map over to Alexa.  But I was thinking I could map the temperature setting portion over to Alexa, so she would respond to 'Alexa, turn the thermostat to 25'.  Where thermostat would be the device name in your config.  Is that what your looking for?  Or is it a different button or switch?

It should take me a couple of hours to make the update tomorrow after work.

With the mapping to Alexa, I'm limited to on/off and setting to a value.  As Alexa thinks it is a dimmable light bulb.  I was playing with the Yamaha plugin, and had made the on/off and volume map to a light bulb so Alexa could control it.

**Comment by jat80** [comment]
@NorthernMan54 i'm not 100% sure if that would work as currently you have to physically set the mode in the home app (e.g. heating, cooling, auto) then set the temperature via sliding it up or down to the desired degree's for it to turn on.  I set a scene with those parameters so I can just use a one button on or tell siri the scene to turn on.  Maybe @lprhodes could shed some light on this to see if it's feasible.

**Comment by lprhodes** [comment]
@jat80 The heating/cooling is just fake...basically anything under 22 is cooling anything over is heating. It's basically just taking the value you say to Siri or specify in the Home app and checking whether you have a hex code for it...if you do it sends the code. If you don't and it's under 22 then it sends whatever the code is for 16 degrees and if it's more than 22 then whatever the code is for 30 degrees.

**Comment by NorthernMan54** [comment]
@jat80 @lprhodes would it be feasible to send 2 IR codes with the temperature?  i.e. have the plugin send the Cool Mode code and the Temperature setting when the temperature is set?

**Comment by lprhodes** [comment]
@NorthernMan54 No you can't send the commands individually unfortunately; it's a combination of fan speed, temperature and mode - and each air conditioner combines them differently so there's no way to generate an IR code from the numbers

**Comment by jat80** [comment]
@NorthernMan54 I ended up setting up my aircon controls as switches. One for 18degrees cooling on/off and one for 30degrees heating on/off so they would actually work with your plugin i'm assuming now they are switches?

**Comment by NorthernMan54** [comment]
Service switch will work perfectly, please let me know how it goes.

**Comment by jat80** [comment]
@NorthernMan54 would [this](https://reverb.ai) app work with your plugin?  I don't have an echo dot as yet.  It's on order.

**Comment by NorthernMan54** [comment]
Sorry no, it only works with the physical amazon Alexa devices.
