### ISSUE TITLE
Scenes

### ISSUE THREAD

**Issue by samsonrosen** [NorthernMan54/homebridge-alexa#30]
Hi! The new echo update supports 'scenes'. Is it possible to setup scenes with Homebridge, or use the scenes already setup in HomeKit?

Thanks,

Sam

**Comment by NorthernMan54** [comment]
Unfortunately not. HomeKit scenes aren’t available to home bridge

**Comment by samsonrosen** [comment]
No problem, I’ve discovered ‘routines’ are very similar
