### ISSUE TITLE
Plugin suddenly stopped working

### ISSUE THREAD

**Issue by galbartal** [NorthernMan54/homebridge-alexa#301]
Hello,
For some reason the plugin stopped working. 
Logs:
`alexaActions reportState ReportState 192.168.1.188 51827 undefined { Error: connect ECONNREFUSED 192.168.1.188:51827
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)

  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.188',
  port: 51827,
  attempts: 1 } +101ms
ERROR: alexaStateResponse connect ECONNREFUSED 192.168.1.188:51827
  alexaActions reportState {"event":{"header":{"namespace":"Alexa","name":"ErrorResponse","messageId":"a5da2a9a-6c65-4674-92b9-ad8d04b49323","correlationToken":"AAAAAAAAAAD8Y8FHvf8sYHCeNaJTWl+mDAIAAAAAAAB+85kUHr84NKbdnRdz7MJQ9rio65pLk3lT+ZG3E32Ee6bPnmhUaNfbmKPM5rajLUNhZhG9elL8DlVQlAwse0E929oKuairZsprWCLR0HXrKZMKgbGSblbQDHLzsZC+GSJNpeJQqCguG3+uOji9yg6Rzy6oJKKQNDdfPB8m4HNDY7Jd9fD2fD2UTK/e4wE2v2olmWhYokz6T5yLzxQMCajgro5ccFNwp6EmXDuLNtjlBlAk+MIxLop49UV+9GsA+EbqeeqLYu+/wFYqgoA0CQHvsn2Yb9eyRSTICctspxCLNs4IdceZ40zfb6e/YUvoO0VVH5j794WAxLijB6ZmX/6ST1FVRG+RgyIYeIJqLNL6eapWIRFMVxPHPDew7W2Wm6EabmrWhA5L6QCpMFN4J69A4FNGlHt80Pxc5ev+dJBFV5IY8pPNVyBDIH6iUtR2lF7vyMbe2qTe6QugJH2O3AtSePXyMyHUPz0nMkAvG2uPqUVsNfuIHCNvkShPOAj/SRG6JU9fCVzS4n+e7Z2hAyEjdNOnDtXm90QoTlwcXHlxPcgrwI0AO+HO5vS7QgyTuls79mBHvMC+vq2RFjgy9Xi4qXo1cpk5ZqpHc4zACeLDtYdn53vELDl+iNJFXOZB3+vEuMMw+oL5a8plD2YuAgMiCvc5LahhnfpvH+Jx8MXWD6oPnoXAqn8tyM4U4g==","payloadVersion":"3"},"endpoint":{"endpointId":"Q0M6MjI6M0Q6RTM6Q0U6MzEtSG9tZWJyaWRnZS1Tb25vZmYgVG91Y2ggRVVDMS1CZWQgTGFtcHMtMDAwMDAwNDktMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx"},"payload":{"type":"ENDPOINT_UNREACHABLE","message":"connect ECONNREFUSED 192.168.1.188:51827"}}} +57ms
`

**Comment by NorthernMan54** [comment]
Try asking Alexa to discover devices again.

It is trying to contact homebridge at 192.168.1.188:51827 and if you moved things around you need to discover again.

**Comment by galbartal** [comment]
Thanks!
