### ISSUE TITLE
Maybe an issue

### ISSUE THREAD

**Issue by janwagner** [NorthernMan54/homebridge-alexa#302]
Hi there. Since yesterday my alexa ios app has lost connection to my homebridge devices. All lights are green on https://www.homebridge.ca and i already reinstalled the alexa skill. I there maybe an issue with a new alexa app update?

**Comment by NorthernMan54** [comment]
Is there anything in the Homebridge logs in regard to Alexa ?

**Comment by janwagner** [comment]
No errors or warnings. Homebridge still discovers my connected devices. I am using another git project to have automated switches. Homebridge and apple home are discovering the switches and they are working. Just the Alexa app does not find them anymore. It worked fine till yesterday https://www.npmjs.com/package/homebridge-automation-switches

**Comment by NorthernMan54** [comment]
Can you share your homebridge.ca login so I can look at the server logs

PS 300+ people are on version 0.4.56

**Comment by janwagner** [comment]
of course. can i email it to you?

**Comment by NorthernMan54** [comment]
Or direct message via slack or discord ( just the ID and not the password )

**Comment by janwagner** [comment]
Best github support ever! THX MAN!
