### ISSUE TITLE
Garage door shown as door in Alexa app

### ISSUE THREAD

**Issue by santiagos5** [NorthernMan54/homebridge-alexa#303]
Hello, my garage door via broadlink-rm plugin, is shown as door in the Alexa app, and not as light, so i can’t say “turn on garage” for open it. It can’t be set on or off. Any suggestion?

**Comment by NorthernMan54** [comment]
Can you share a homebridge accessory dump, details are in the README.

**Comment by santiagos5** [comment]
[https://www.dropbox.com/s/ep2p6qiagb0yelx/dump.txt?dl=0](url) here my dump. Thanks

**Comment by NorthernMan54** [comment]
That dump was incomplete and corrupt and did not include the garage door

Can you try again, ( maybe use a different method of copying and including the file)

**Comment by santiagos5** [comment]
I'm sorry, here the correct file.

Thanks

[Uploading dump.txt…]()

**Comment by NorthernMan54** [comment]
I reviewed your config versus my garage door setup and they are pretty similar.  Yours also has a lock while mine doesn't.  I'm not sure if that is the issue.

With the Alexa app it shows and as door and you are not able to control it from the app.  This is a limitation of the Alexa App.  But you can control it with voice, "Alexa, turn on Garage".  And in my setup I added a routine, "Alexa, open garage door", that opens the door.

Have you tried it via voice yet?

**Comment by santiagos5** [comment]
it is the same config.json that i've on my rpi3 and there worked perfectly. Do you know how i can remove lock? 
I can't create routine on alexa app because i can't set my garage on or off..
However I use dummyswitches with alexa routine and eve rule's to avoid the problem and set garage open/close with alexa, the only problem is the state open/close are not sync between Siri and Alexa, sometimes I must say "close" to open garage and viceversa, but at least it's working

**Comment by NorthernMan54** [comment]
Before we close this, are we missing something here

In my Alexa App my garage door appears like this in the "Devices" tab as a type Door.  There are not controls available here.

![IMG_4707](https://user-images.githubusercontent.com/19808920/77713431-ba5df800-6fac-11ea-81fe-533b6b98311a.PNG)

And under the Routines option -->  add actions --> Smart Home --> Garage Door  I have this

![IMG_4708](https://user-images.githubusercontent.com/19808920/77713554-07da6500-6fad-11ea-94d6-1fbc47a6a679.PNG)

And I turn this on to open from a routine, and turn it off to close from a routine.

And this is my open routine

![IMG_4709](https://user-images.githubusercontent.com/19808920/77713669-5556d200-6fad-11ea-8468-38a9d66c0d3a.PNG)


What do you see in your app?

**Comment by santiagos5** [comment]
In Devices: 

![FF8A6670-11EA-4849-9BDC-2138F9DDAEF1](https://user-images.githubusercontent.com/35889101/77785143-10d63f80-705c-11ea-9470-c23f9ff343b7.png)

And under the Routines option --> add actions --> Smart Home --> Garage Door I have this

![A83930B9-0FC1-4580-A381-CDF7FB8FF691](https://user-images.githubusercontent.com/35889101/77785237-2fd4d180-705c-11ea-8ac5-61a02ca93bbb.png)

I Don’t have on/off.
I tried to add however in routine and I can open and close garage via routine but garage switch in HomeKit remember last state used by Siri, not Alexa. 

It’s ok, it’s not a big problem..

Thanks a lot!

**Comment by NorthernMan54** [comment]
If you can hold off I’m working though adding proper garage door control.  Give me a couple of weeks

**Comment by santiagos5** [comment]
Thank you very much!

**Comment by NorthernMan54** [comment]
If you're interested in testing the new version with support for using natural language for Garage Doors, I have finished testing everything and getting ready to roll it out to everyone.

You have see the details in the updated README here

https://github.com/NorthernMan54/homebridge-alexa/tree/inputController#garage-door-blinds-and-window-coverings

To install the test version please use this command to install, and add the option door=true to your config.json.  To rollback to the current version, just use the normal install command

npm install -g NorthernMan54/inputController

**Comment by worldwolf31** [comment]
My garage door was setup without much issue, and it does pass on the trigger to the relay switch.

I also want to know if you can add an option for checking the status of the garage door? Cause I want to do certain routines such as "if garage door is open for 10 minutes, send notification to me" kinda thing.

**Comment by NorthernMan54** [comment]
To setup that type of automation, I used node-red and the homekit-bridged and Homebridge-automation nodes.

I created an automation that causes a notification on my phone every minute if the door was left open a few hours.   Found that worked better than having Alexa announce it, as it lets me know if I’m out of the house.

**Comment by worldwolf31** [comment]
Hmm, let me look into that. But would it be possible for the Alexa plugin to know the status as well? Because it can open up things like asking Alexa whether the garage door is open or not as well.

I use this plug in to control the garage door.
https://github.com/plhyhc/homebridge-garage-door-wsensor

Which I hook up both relay and door sensor on GPIO pins.

**Comment by NorthernMan54** [comment]
If the plugin exposes a contact sensor, Alexa can monitor it for status.   My door announces when it is opened or closed using a routine triggered by the contact sensor.

![FF48E84B-4160-4702-9FD0-D4AD392D8CBC](https://user-images.githubusercontent.com/19808920/86513714-5d0ee980-bdda-11ea-9f0a-878f778781a6.png)

**Comment by worldwolf31** [comment]
Interesting, It's possible that the plugin doesn't expose the status. However, in the Home app it does show correctly the sensor status, it's just that status never pass on to Alexa. and the accessories show up as "door" instead of "Garage Door" type of device. 

I also try to add an additional contact sensor accessories. neither of them show up as programmable in a routine

**Comment by NorthernMan54** [comment]
Do you have routines true in your config?

**Comment by worldwolf31** [comment]
You're right. My bad about the routine setting. Now I just realize I can't set multiple condition in Alexa routine (only 1 condition allowed), which means I still can't do what I want (e.g. check door status and if still remain open for X minutes, notify/annouce)

**Comment by NorthernMan54** [comment]
Hence my usage of node-red for advanced automations
