### ISSUE TITLE
security system support

### ISSUE THREAD

**Issue by aficustree** [NorthernMan54/homebridge-alexa#309]
I see that security systems aren't supported yet. It looks like the [Alexa Guidance](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-securitypanelcontroller.html) supports security systems now. Would you be willing to accept a pull request that integrates this feature?

**Comment by NorthernMan54** [comment]
I would definitely support a pull request.

**Comment by aficustree** [comment]
thanks. is there an example pull request you could recommend where a feature was added so I can pattern where to insert code?

I think I've found the major areas:

+ in `alexaMessages.js` switch on the service then switch again on the adjusted characteristic (i.e., the service `SecuritySystem` and the characteristic `SecuritySystemCurrentState`)...emit the propose request/responses here
+ in `alexaActions.js` add a `alexaSecurityPanelController` , `alexaThermostatController` seems like the best to pattern off of
+ pretty sure I need to do something in `alexaTranslator.js`, specifically the `_parseHAPtoAlexa` function. It looks like it's checking for supported HAP services (`0000007E` for SecuritySystem) and then checking for characteristics. I'm not entirely sure what this is doing though.
+ also sure I need to do something to `messageUtils.js` but again, not entirely sure what this is doing vs `alexaMessages.js`

**Comment by NorthernMan54** [comment]
I haven’t been using pull requests a lot as I have been coding updates directly to increase my WAF score.  My most recent was pull request #308 which enabled InputController and and channelController but this was more of a hack than a new feature.  ( I'm working towards simple Alexa control of my non-smart TV with OTA Channels, a Kodi box, and a Apple TV with Netflix ).

My workflow for adding new features/functions is first collect a Homebridge accessory dump for just the new accessory, then using tools/newParseAccessories.js validate that the Alexa discovery response matches what Amazon Alexa expects

Ie 

In the tools directory

node newParseAccessories.js newAccessory.json

Then review the response to ensure that Alexa.discovery is correctly formatted.  This ends up being an iterative process with majority of the effort being spent in the lib/parse JS files to ensure that the parsing of the homebridge accessory dump creates the correct Alexa discovery object.  The individual files are used to create an in memory model of the Homebridge accessory dump then use the toAlexa function create the Alexa.discovery response.

newParseAccessories.js has a Alexa.discovery json validator included, but it is wonky, so if parsing fails it could be just the json validator and not your discovery response.

Once I’m comfortable with the Alexa.discovery object I use tools/liveTest.js to validate the Alexa.discovery object.  With a test account and a spare Alexa, validate that the voice commands generate the appropriate directives.

Then after that is working correctly, work on the processing of the directive control the device.  If you look at the discovery object, I use cookies to map to the actual homebridge object.

I do have a parser validation routine ( newTest.sh ) that I run before publishing parser changes to ensure nothing is broken, so I will run that before releasing.

alexaMessages.js - These are the response messages after a control directive

alexaActions.js - That makes sense, I just pick the best pattern to copy for a new function

alexaTranslator.js - This is my original homebridge accessory dump parser and is no longer used.  The files in lib/parse create an in memory model of the accessories that are used to create the Alexa.discovery response

messageUtils.js - Is a grab bag of functions used by various modules to parse and respond to requests


PS I realize this is challenging, but all the heavy lifting is in the plugin.  The cloud backend has minimal code and processing, and is just a glorified message router.  If your on Discord, we can chat in semi-real time if needed

**Comment by rackemdiscovery** [comment]
I used https://www.npmjs.com/package/homebridge-dummy to create "Stateful" dummy switches for Arm Home and Arm Away.  Then homebridge-alexa allowed these switches to be visible in Alexa so you can turn them off and on.  Then set up Automation in the Apple Home app, when Arm Home is turned on turn security system to Arm Home.  It works great.  Thank you NorthernMan54 for your great Plugin.

Dean
