### ISSUE TITLE
Pilight Homebridge Alexa 

### ISSUE THREAD

**Issue by sm17h85** [NorthernMan54/homebridge-alexa#31]
Hi,

I’m completely new to this Project. I have Alexa since last weekend and try to get my switches connected to Alexa but no devices were found.

I use Pilight with homebridge to control my switches via siri. Can somebody help me to get this done?

Cheers.

**Comment by NorthernMan54** [comment]
Can you share which Alexa device you have, and a debug log from the startup of homebridge, including when you discover devices.

Tks

**Comment by sm17h85** [comment]
I use the 2. Gen Echo. I saw already that someone else have also problems to discover devices with the new model. Maybe it depends on the model. Anyway i copied the Debug log to pastebin.

https://pastebin.com/3R4JiYgc

Thx and cheers.

**Comment by NorthernMan54** [comment]
@sm17h85 I closing this as a duplicate to Issue #32
