### ISSUE TITLE
Issue with homebridge-mqttthing (Heatercooler)

### ISSUE THREAD

**Issue by soumaxetuirk** [NorthernMan54/homebridge-alexa#312]
I am using Homebridge-mqtthing for most of my devices. 

when my device type is registered as thermostat, alexa is working as expected. But when registered as 'heaterCooler' , few things are not working.

Modes are mapped wrong i think.auto mode is changing to cool & off mode is changing to auto. 

But unable to change temp or other setting.

I got this on log when I asked to change temp.

`alexaThermostatController missing action targetSetpoint Unexpected token u in JSON at position 0 {
  thermostatModeCOOL: '{"host":"192.168.1.100","port":51826,"aid":30,"iid":12,"value":2}',
  TurnOn: '{"host":"192.168.1.100","port":51826,"aid":30,"iid":10,"value":1}',
  AdjustPowerLevel: '{"host":"192.168.1.100","port":51826,"aid":30,"iid":17}',
  upperSetpoint: '{"host":"192.168.1.100","port":51826,"aid":30,"iid":15}',
  ReportState: '[{"interface":"Alexa.PowerController","host":"192.168.1.100","port":51826,"aid":30,"iid":10},{"interface":"Alexa.ThermostatControllerthermostatMode","host":"192.168.1.100","port":51826,"aid":30,"iid":12},{"interface":"Alexa.TemperatureSensor","host":"192.168.1.100","port":51826,"aid":30,"iid":13},{"interface":"Alexa.ThermostatControllerupperSetpoint","host":"192.168.1.100","port":51826,"aid":30,"iid":15},{"interface":"Alexa.PowerLevelController","host":"192.168.1.100","port":51826,"aid":30,"iid":17}]',
  thermostatModeOFF: '{"host":"192.168.1.100","port":51826,"aid":30,"iid":12,"value":0}',
  thermostatModeAUTO: '{"host":"192.168.1.100","port":51826,"aid":30,"iid":12,"value":3}',
  SetPowerLevel: '{"host":"192.168.1.100","port":51826,"aid":30,"iid":17}',
  TurnOff: '{"host":"192.168.1.100","port":51826,"aid":30,"iid":10,"value":0}',
  thermostatModeHEAT: '{"host":"192.168.1.100","port":51826,"aid":30,"iid":12,"value":1}'`

**Comment by NorthernMan54** [comment]
Can you share an accessory dump from your homebridge instance, details are in the readme

**Comment by soumaxetuirk** [comment]
Here it is.
[dump.txt](https://github.com/NorthernMan54/homebridge-alexa/files/4458216/dump.txt)

Device name "HITACHI AC"

**Comment by NorthernMan54** [comment]
Thanks for the dump and log fragment made resolving this really easy.  Please update to the latest and try again

**Comment by soumaxetuirk** [comment]
Thank you, Temperature adjustment is working now.
However state changing are wrong.
Cool mode : setting to COOL
HEAT mode: setting to HEAT
**Auto mode: setting to Cool
OFF mode : setting to AUTO**

Homebridge log saying correct mode.But the homebridge getting wrong mode.

**Comment by NorthernMan54** [comment]
Can you share a log showing this, I looked at the code and don't see an issue

Mapping code is here

https://github.com/NorthernMan54/homebridge-alexa/blob/1927fbc0ca2ccff4784595ad18a84e6bbf8bc4d6/lib/parse/Characteristic.js#L202

**Comment by soumaxetuirk** [comment]
On mqttthing page, ModeAUTO is 0 .

Heat is 1 and COOL is 2. So heat & cool works.

**Comment by soumaxetuirk** [comment]
homebridge log when i ask to set auto mode:

`[Alexa] SetThermostatMode AUTO 192.168.1.100 51826 { characteristics: [ { aid: 30, iid: 12, status: 0 } ] } null`

but homebridge changes state to COOL.

**Comment by NorthernMan54** [comment]
In the dump you shared,  characteristic aid:30 iid:12 is this

```
{
        "iid": 12,
        "type": "000000B2-0000-1000-8000-0026BB765291",
        "perms": ["pr", "pw", "ev"],
        "format": "uint8",
        "value": 2,
        "description": "Target Heater Cooler State",
        "valid-values": [0, 2],
        "maxValue": 2,
        "minValue": 0
      }
```

And the mapping based on your dump looks like this

```
"thermostatModeOFF": "{\"host\":\"127.0.0.1\",\"port\":51826,\"aid\":30,\"iid\":12,\"value\":0}",
"thermostatModeHEAT": "{\"host\":\"127.0.0.1\",\"port\":51826,\"aid\":30,\"iid\":12,\"value\":1}",
"thermostatModeCOOL": "{\"host\":\"127.0.0.1\",\"port\":51826,\"aid\":30,\"iid\":12,\"value\":2}",
"thermostatModeAUTO": "{\"host\":\"127.0.0.1\",\"port\":51826,\"aid\":30,\"iid\":12,\"value\":3}",
```

```
[Alexa] SetThermostatMode AUTO 192.168.1.100 51826 { characteristics: [ { aid: 30, iid: 12, status: 0 } ] } null
```

In this,  **AUTO** came from Alexa and it maps to thermostatModeAUTO here in the code, which is a value of 3.  What happens to your device when it receives a 3?

https://github.com/NorthernMan54/homebridge-alexa/blob/1927fbc0ca2ccff4784595ad18a84e6bbf8bc4d6/lib/alexaActions.js#L366

**Comment by soumaxetuirk** [comment]
when Homebridge receives 3 (AUTO mode) from Homebridge-alexa, It sets the device to COOL mode.

**Comment by NorthernMan54** [comment]
If you ask Alexa to turn off or cool does it work correctly?

**Comment by soumaxetuirk** [comment]
Alexa commands  currently working without issue:
1. "turn off" or "turn on".
2. "set mode to COOL" & "set mode to HEAT"
3. adjusting temperature .

**Comment by NorthernMan54** [comment]
Can you set auto versus the Home app?

**Comment by soumaxetuirk** [comment]
I looked closely to device values while controlling AC from Apple Home app. 

No "Target Heater Cooler State" for Off state,It just changes "active" to 0. the "Target Heater Cooler State" remains unchanged. 

I don't know why the mapping in dumps has different values. But on my testing using home app
Target Heater Cooler State for AUTO mode : 0
Target Heater Cooler State for HEAT mode : 1
Target Heater Cooler State for COOL mode : 2

**Comment by NorthernMan54** [comment]
I’m stumped here as the Alexa Plugin is setting the correct values based on my testing.  The status your seeing in the Alexa log Item is the status of the change command, and zero means success.

What does the mqttthing plugin DEBUG logs show, it should log the actual values?

**Comment by soumaxetuirk** [comment]
I could not find any documentation regarding mqttthing debug. But homebridge config ui does show device's actual values. 
the above mentioned values were collected from that.
![Capture](https://user-images.githubusercontent.com/54876219/79297111-d3e2c780-7efa-11ea-8b33-8b1f5ec825d5.PNG)

**Comment by NorthernMan54** [comment]
mqttthing debug loging is the same an homebridge Alexa

DEBUG=* homebridge

I thinking MQTT thing is changing the value

**Comment by NorthernMan54** [comment]
What have I mapped report state to ? It should be Target Heating Cooling State and not Current Heating Cooling State
