### ISSUE TITLE
Accessory [Homebridge] Could not find a Characteristic with iid of 38 and aid of 17 +0ms

### ISSUE THREAD

**Issue by vcrosato** [NorthernMan54/homebridge-alexa#314]
Hi,

Configured a television with homebridge-cmd4 plugin, turning on works fine in homekit (tested with iphone). Asked alexa to "turn on television", request fail with:

  mqtt-packet:parser _newPacket: parser emit packet: packet.cmd: publish, packet.payload: {"directive":{"header":{"namespace":"Alexa.PowerController","name":"TurnOn","payloadVersion":"3","messageId":"acd4bdab-e2fd-4e48-8df8-696d18314992","correlationToken":"AAAAAAAAAABlnflTeWK4kytn7N5IKnXmDAIAAAAAAAAS+rMxUDlwYAExgd+mRBAvs1EtInE6VJ9bLnYInI1LWAZM3NdIa3m4xN8XbApTni5IyqIVD/hRWE0VEu3jz0mJdMcX6eQ1NsoXOZCm+I9QilCxPKg/i+Vz6jME2cm7gk5gTQAj9LwtqhebaMykqEoU5G75jFGqIMb0RQe3w01gNFoq2mpF8pfFKUGWpN9vU21tZQOOtsT5NA8H/KC4VnXjt9wXOhYs4N52y4E6B2MHBYr5l95kGOqT1EFTXEs4rvcxkkpsB1y0Fojiz0yyXRIzc96XjbRY8TRw4MSAn471qIUfd07XJDxQhVHHT+XF8z9jvSY6TpVRTw+IlkmKNZwjY35phyybbxe6OeQ7d0nufXD3Cn0e/4+/R8H+afVhaMUq7XpIUX1973z1KaGVYmkbOcdVfL2MLWqHz7dqPLWkLNK6KojgHN6YSAXzFB44uzUjR6JlX3DLfHKhBw4RGXOK4L+fk3pNmNIi30R5wjBds5NwTFXiqfyXQEXEG2W2acBoCbxJLjNivoolMwDsnnW311/yKU735ti4KlZcGGp9OmcALnB3bqQSvBYwEd+GNhtNmP1bhwn62hYzHFKBmCpHlrwCP86SUpBvEP0Iyx38sXZZg4+wtuPoQoarHLmhG9/yEnhYkhOL5XO6euMEEeY2a8r2LNCPdyZkHAWQXDODe3QTre2Uhr4/B8ItoQ=="},"endpoint":{"endpointId":"Q0M6MjI6M0Q6RTM6Q0U6MzAtSG9tZWJyaWRnZS1JbmRpZ28tTW9uaXRvciBEaXJlaXRvLTAwMDAwMDQzLTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==","cookie":{"TurnOn":"{\"host\":\"192.168.0.100\",\"port\":51826,\"aid\":45,\"iid\":10,\"value\":1}","ReportState":"[{\"interface\":\"Alexa.PowerController\",\"host\":\"192.168.0.100\",\"port\":51826,\"aid\":45,\"iid\":10}]","TurnOff":"{\"host\":\"192.168.0.100\",\"port\":51826,\"aid\":45,\"iid\":10,\"value\":0}"}},"payload":{}}}, packet.length: 1408 +0ms
  mqtt-packet:parser _newPacket: new packet +0ms
  mqtt-packet:parser parse: state complete. _stateCounter is now: 4 +0ms
  mqtt-packet:parser parse: packet.length: -1, buffer list length: 0 +0ms
  mqtt-packet:parser parse: exited while loop. packet: -1, buffer list length: 0 +0ms
  alexaLocal Emitting Alexa.PowerController +20m
  EventedHTTPServer [::ffff:192.168.0.100] New connection from client +2m
  EventedHTTPServer [::ffff:192.168.0.100] HTTP server listening on port 63487 +0ms
  EventedHTTPServer [::ffff:192.168.0.100] HTTP request: /characteristics +2ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":45,"iid":10,"value":1}] +1ms
  Accessory [Homebridge] **Could not find a Characteristic with iid of 45 and aid of 10** +0ms
  EventedHTTPServer [::ffff:192.168.0.100] HTTP Response is finished +0ms
[4/12/2020, 12:48:34 AM] [Alexa] PowerController TurnOn 192.168.0.100 51826 { characteristics: [ { aid: 45, iid: 10, status: -70402 } ] } null

Dont know what to do... Any ideas? Thanks

**Comment by vcrosato** [comment]
Here's an accessory dump in case it's needed
[dump.txt](https://github.com/NorthernMan54/homebridge-alexa/files/4465829/dump.txt)

**Comment by vcrosato** [comment]
homebridge-alexa plays fine with other plugins (eg: homebridge-indigo), but not with homebridge-cmd4.

Dont know if the problem is between the plugins or its related to the Television device type which are way more complex than the Switch type devices I have in Indigo... thanks

**Comment by NorthernMan54** [comment]
Looking at this the problem is that your devices keep moving around i.e. the AID number keeps changing.  And Homebridge-alexa stores the value as part of discovery process to enable it to control the device.  And restarting homebridge is triggering this.

If you restart everything then ask Alexa to discover devices it should be okay.

**Comment by vcrosato** [comment]
That solved. Thank you very much!

**Comment by vcrosato** [comment]
Solution in case somebody need it:
- Stop homebridge
- go to http://alexa.amazon.com/ (since I'm in Brazil it was http://alexa.amazon.com.br/ > Smarthome > "Forget All Devices", then "Discover Devices"
- Start homebridge

**Comment by NorthernMan54** [comment]
No need to forget all devices ( this causes you to lose your routines and groupings), you should only need to ask her to discover devices again.
