### ISSUE TITLE
Device isn't responding..

### ISSUE THREAD

**Issue by meluvalli** [NorthernMan54/homebridge-alexa#317]
Hello.  I have several devices in once instance.  Most devices are working fine, however some come back "Device isn't responding" per Alexa.  I know the devices work find because I also have Google Plugin and it's working without any issues.

I turned debug on, but only see two lines come through when I give a failing command.

` alexaLocal Emitting Alexa.PowerController +42s`
`[4/14/2020, 2:55:53 PM] [Alexa] PowerController TurnOn 10.40.162.90 51803 { characteristics: [ { aid: 45, iid: 315, status: -70402 } ] } null`
 

Any suggestions?

**Comment by NorthernMan54** [comment]
Try asking Alexa to discover devices again, then try the command again.  

The status -70402  means error, it should be 0.  The -70402 is coming from homebridge and it is likely just an outdated device address ( aid and iid ).  Asking Alexa to discover devices will refresh the mapping.

**Comment by meluvalli** [comment]
Ok.  I tried telling Alexa to re-discover without deleting the device.  I assume this is what you meant?  Any how, it said no new devices, but tried the command again and sure enough it's working now.  Lets see for how long!   It was just working yesterday when I initially set it up.  Not sure what could have happened.
