### ISSUE TITLE
Can't turn on/off Rrmotec ZXT Fibaro HC2 Thermostat

### ISSUE THREAD

**Issue by josecarlosmoimaz** [NorthernMan54/homebridge-alexa#320]
I have a Fibaro Home Center 2, where I use a Remotec ZXT-120 to control my AC's, I was used to control them from Homekit using Siri. A few weeks ago I bought an Echo Dot and started to use Alexa, but my thermostats, the same I use on Homekit, perfectly on on Alexa they are not working properly. I can change the temperature, but when I try to cool and off, Alexa says that the device is not compatible with this. 
However, I thank you guys very much for the plugin, it's awesome.

**Comment by NorthernMan54** [comment]
Can you share a homebridge accessory dump, details are in the README

**Comment by josecarlosmoimaz** [comment]
{
      "aid": 33,
      "services": [
        {
          "iid": 1,
          "type": "0000003E-0000-1000-8000-0026BB765291",
          "characteristics": [
            {
              "iid": 2,
              "type": "00000014-0000-1000-8000-0026BB765291",
              "perms": [
                "pw"
              ],
              "format": "bool",
              "description": "Identify"
            },
            {
              "iid": 3,
              "type": "00000020-0000-1000-8000-0026BB765291",
              "perms": [
                "pr"
              ],
              "format": "string",
              "value": "Remotec Technology Ltd",
              "description": "Manufacturer"
            },
            {
              "iid": 4,
              "type": "00000021-0000-1000-8000-0026BB765291",
              "perms": [
                "pr"
              ],
              "format": "string",
              "value": "com.fibaro.setPoint",
              "description": "Model"
            },
            {
              "iid": 5,
              "type": "00000023-0000-1000-8000-0026BB765291",
              "perms": [
                "pr"
              ],
              "format": "string",
              "value": "AR ALMOÇO",
              "description": "Name"
            },
            {
              "iid": 6,
              "type": "00000030-0000-1000-8000-0026BB765291",
              "perms": [
                "pr"
              ],
              "format": "string",
              "value": "<unknown>",
              "description": "Serial Number"
            },
            {
              "iid": 7,
              "type": "00000052-0000-1000-8000-0026BB765291",
              "perms": [
                "pr"
              ],
              "format": "string",
              "value": "1.1",
              "description": "Firmware Revision"
            }
          ],
          "primary": false,
          "hidden": false
        },
        {
          "iid": 8,
          "type": "0000004A-0000-1000-8000-0026BB765291",
          "characteristics": [
            {
              "iid": 9,
              "type": "00000023-0000-1000-8000-0026BB765291",
              "perms": [
                "pr"
              ],
              "format": "string",
              "value": "AR ALMOÇO",
              "description": "Name"
            },
            {
              "iid": 10,
              "type": "0000000F-0000-1000-8000-0026BB765291",
              "perms": [
                "pr",
                "ev"
              ],
              "format": "uint8",
              "value": 0,
              "description": "Current Heating Cooling State",
              "valid-values": [
                0,
                1,
                2
              ],
              "maxValue": 2,
              "minValue": 0
            },
            {
              "iid": 11,
              "type": "00000033-0000-1000-8000-0026BB765291",
              "perms": [
                "pr",
                "pw",
                "ev"
              ],
              "format": "uint8",
              "value": 0,
              "description": "Target Heating Cooling State",
              "valid-values": [
                0,
                1,
                2,
                3
              ],
              "maxValue": 3,
              "minValue": 0
            },
            {
              "iid": 12,
              "type": "00000011-0000-1000-8000-0026BB765291",
              "perms": [
                "pr",
                "ev"
              ],
              "format": "float",
              "value": 23,
              "description": "Current Temperature",
              "unit": "celsius",
              "maxValue": 100,
              "minValue": -50,
              "minStep": 0.1
            },
            {
              "iid": 13,
              "type": "00000035-0000-1000-8000-0026BB765291",
              "perms": [
                "pr",
                "pw",
                "ev"
              ],
              "format": "float",
              "value": 23,
              "description": "Target Temperature",
              "unit": "celsius",
              "maxValue": 38,
              "minValue": 10,
              "minStep": 0.1
            },
            {
              "iid": 14,
              "type": "00000036-0000-1000-8000-0026BB765291",
              "perms": [
                "pr",
                "pw",
                "ev"
              ],
              "format": "uint8",
              "value": 0,
              "description": "Temperature Display Units",
              "valid-values": [
                0,
                1
              ],
              "maxValue": 1,
              "minValue": 0
            }
          ],
          "primary": false,
          "hidden": false
        }
      ]
    },

**Comment by NorthernMan54** [comment]
Tks for the dump, I ran it thru the parser and it passes

```
node newParseAccessories.js ~/Desktop/issue#320.json 
alexaDiscovery - returned 1 devices
Alexa Message Validation Passed!
```

Can you share a log from Homebridge from when you attempt to change the thermostat mode?

**Comment by josecarlosmoimaz** [comment]
When I ask to Alexa to cool or to turn off the thermostats, she says that they are not compatible with this, there is no log at home bridge, but when I ask to Alexa, "set living room to 22ºC, that is the output:
[4/20/2020, 6:11:55 AM] [FibaroHC2] Setting value to device:  103  parameter: Target Temperature
[4/20/2020, 6:11:55 AM] [Alexa] ThermostatController SetTargetTemperature 192.168.88.225 52801 { characteristics: [ { aid: 32, iid: 13, status: 0 } ] } null
[4/20/2020, 6:11:55 AM] [FibaroHC2] Command:  setThermostatSetpoint, value: 2,10, to: 103
[4/20/2020, 6:11:55 AM] [FibaroHC2] Setting value to device:  118  parameter: Target Temperature
[4/20/2020, 6:11:55 AM] [Alexa] ThermostatController SetTargetTemperature 192.168.88.225 52801 { characteristics: [ { aid: 33, iid: 13, status: 0 } ] } null
[4/20/2020, 6:11:55 AM] [FibaroHC2] Command:  setThermostatSetpoint, value: 2,10, to: 118
[4/20/2020, 6:11:58 AM] [FibaroHC2] Updating value for device:  103  parameter: Current Temperature, value: 23.00
[4/20/2020, 6:11:58 AM] [FibaroHC2] Updating value for device:  103  parameter: Target Temperature, value: 23.00
[4/20/2020, 6:11:58 AM] [FibaroHC2] Updating value for device:  103  parameter: Temperature Display Units, value: 23.00
[4/20/2020, 6:12:00 AM] [FibaroHC2] Updating value for device:  118  parameter: Current Temperature, value: 23.00
[4/20/2020, 6:12:00 AM] [FibaroHC2] Updating value for device:  118  parameter: Target Temperature, value: 23.00
[4/20/2020, 6:12:00 AM] [FibaroHC2] Updating value for device:  118  parameter: Temperature Display Units, value: 23.00

**Comment by NorthernMan54** [comment]
I just tested your config file in my test environment and it works fine.   This is me asking Alexa to change the mode to Cool

```
  alexaLocal Emitting Alexa.ThermostatController +7s
  liveTest alexaMessage {
  "directive": {
    "header": {
      "namespace": "Alexa.ThermostatController",
      "name": "SetThermostatMode",
      "payloadVersion": "3",
      "messageId": "cf27fa0f-f9a0-4f0c-9b48-2dc02caa09e5",
      "correlationToken": "AAAAAAAAAABcnbLUqb2PjmIwfIz4/bVnDAIAAAAAAADPl37m0yTNVRxN/vJYi2nv3NJH2re2ra+9t3sGRRphtsCu6eVQsJ3Gwif86LhRAUYFlFRZAPRbUcEuSTr15knBXKgeuTE8C25ShXkWFKJ1oiUZU6OcLs1j46G8WOCCYhDBVMZOMinJj0nrmSK0Fom2Xn3dqrPhehxx8AbI1cXZeE1qD3rmlh1J9t1g5Dd/MLADqa8iXoXTkxvFhjuJNwtPuZ5sOQ19k7z/8k+5B7K8VMrk6xopvxwDyFH261ZMBviLD4iI8BJS0gJArDXTYDrxH1cQQH3sTwuu4s5AFzVZC99xEnVmFn8M8buZn7DYXigz4xGk/7LecWEJ0eHYQzUZDWZyt9iv9ogiJiW7TYz8uIerWFXbTHwBrF7k1lRvPelqPKEoEmThOmtAZyYtqcUUjHdI5fyVDORUtYklLoSlRUYtNLybxaMSdx8M5GeU/nawvTIAYGpIFhWbzWalUmckiF9uBi4wxt+4P2KldOZ618idj4ga1QJkkBply9djsp14umXafLh5A1DJch7YeUMDXM8T6PqO+xPLWSffEqecZKku8OpIploizRv40ERDnzHROI8nPRT+FXpR5Ea9df0WORbQ7A/S8CeduvgBMe6oFai83poiaFeG9gdYs1JpDiyJc9Y9pwlgiwrNzsC0YppiG8kYrmCzW6fgIGm7g+g1hynaqU0sJ/T68u5Z8w=="
    },
    "endpoint": {
      "endpointId": "Q0M6MjI6M0Q6RTM6Q0U6MzAtcGFyc2VUZXN0LVJlbW90ZWMgVGVjaG5vbG9neSBMdGQtSGVhdGVyLTAwMDAwMDRBLTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==",
      "cookie": {
        "thermostatModeCOOL": "{\"host\":\"127.0.0.1\",\"port\":51826,\"aid\":33,\"iid\":11,\"value\":2}",
        "ReportState": "[{\"interface\":\"Alexa.ThermostatControllerthermostatMode\",\"host\":\"127.0.0.1\",\"port\":51826,\"aid\":33,\"iid\":11},{\"interface\":\"Alexa.TemperatureSensor\",\"host\":\"127.0.0.1\",\"port\":51826,\"aid\":33,\"iid\":12},{\"interface\":\"Alexa.ThermostatControllertargetSetpoint\",\"host\":\"127.0.0.1\",\"port\":51826,\"aid\":33,\"iid\":13}]",
        "thermostatModeOFF": "{\"host\":\"127.0.0.1\",\"port\":51826,\"aid\":33,\"iid\":11,\"value\":0}",
        "targetSetpoint": "{\"host\":\"127.0.0.1\",\"port\":51826,\"aid\":33,\"iid\":13}",
        "thermostatMode": "{\"host\":\"127.0.0.1\",\"port\":51826,\"aid\":33,\"iid\":10}",
        "thermostatModeAUTO": "{\"host\":\"127.0.0.1\",\"port\":51826,\"aid\":33,\"iid\":11,\"value\":3}",
        "thermostatModeHEAT": "{\"host\":\"127.0.0.1\",\"port\":51826,\"aid\":33,\"iid\":11,\"value\":1}"
      }
    },
    "payload": {
      "thermostatMode": {
        "value": "COOL"
      }
    }
  }
}
```

Is there a possibility that you are in a country that doesn't support thermostats ( Check here https://developer.amazon.com/en-US/docs/alexa/device-apis/list-of-interfaces.html ) or you have multiple devices with the same name and Alexa is controlling the wrong one?

Have you tried just deleting the thermostat device in the Alexa app, then asking Alexa to discover again?
