### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by rlust** [NorthernMan54/homebridge-alexa#321]
DIR: /usr/local/lib
CMD: npm install homebridge-alexa@latest

execvp(3) failed.: No such file or directory

Command failed. Please review log for details.

**Comment by NorthernMan54** [comment]
????

**Comment by rlust** [comment]
I am using Homebridge Config UI X and during install this is what I get in the log.

**Comment by NorthernMan54** [comment]
Sorry I'm not familiar with installing thru Homebridge Config UI X.  Have you tried from the command line?

**Comment by rlust** [comment]
I found the problem, I found that NPM got messed up up my iMac. I used brew to upgrade node which re-installed NPM. I got the plugin installed.
Thanks for your help!

**Comment by NorthernMan54** [comment]
Tks for the update
