### ISSUE TITLE
Native support for Window Coverings

### ISSUE THREAD

**Issue by lukebrannon1** [NorthernMan54/homebridge-alexa#323]
Not sure if this is technically an "issue" or feature request, but would it be possible to implement native control of window coverings? I understand this historically hasn't been an option since Alexa didn't support window coverings as a device type, but looks like it is now supported per the link below as of 1/31/2020. For me, the biggest advantage of this is being able to tell the shades to "open" or "close" rather than having to tell them to turn "on" or "off" which is a bit non-intuitive for most users.

See Alexa Admin's response @ https://alexa.uservoice.com/forums/913024-alexa-smart-home/suggestions/34277038-support-for-blinds-or-shades-in-smart-home-with

How trivial would it be to have this implemented in homebridge-alexa so window coverings from homebridge could be exposed to Alexa as actual window coverings?

**Comment by NorthernMan54** [comment]
The feature is available as a beta.  And am looking for testers

The beta version can be installed with this command

npm install -g NorthernMan54/homebridge-alexa#inputController

And the updated README is here

https://github.com/NorthernMan54/homebridge-alexa/tree/inputController <https://github.com/NorthernMan54/homebridge-alexa/tree/inputController>

You will need to add a config option to enable the natural language feature.  I haven’t rolled it out yet, as it does not work in my Country yet ( Canada ), but I did test it with a US account and it worked okay.  Also I don’t have Blinds yet ( Ikea went on lock down when I was about to purchase ), so it has not had full testing yet.

There may be some minor issues, but it should be quick to resolve.

**Comment by lukebrannon1** [comment]
Thanks! So far everything seems to be working just fine. 

Just a note that I had to install with "sudo -E -n npm install -g NorthernMan54/homebridge-alexa#inputController" which mimics how the homebridge-config-ui-x plugin does installations. Otherwise I was getting permissions errors. 

Quick question since I'm not familiar - if the homebridge-alexa stable release has updates can I update or will that break the beta inputController install? And when will I know once this comes out of beta and into the general release? Just not familiar with how that sort of thing normally works.

**Comment by NorthernMan54** [comment]
If you update to the latest stable release, it will remove the new functionality.

If you "Watch" the homebridge-alexa on GitHub you can see the various releases going on, and it will notify you.

**Comment by lukebrannon1** [comment]
Copy that!

**Comment by NorthernMan54** [comment]
I have been updating the beta in the background, type this version instead


npm install -g github:NorthernMan54/homebridge-alexa#52801a3

**Comment by lukebrannon1** [comment]
Worked like a charm (with 1 warning)! Thanks! BTW, this portion of the beta seems to be working just fine since I've been using it over the last week. 

```
$ sudo -E -n npm install -g github:NorthernMan54/homebridge-alexa#52801a3
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
+ homebridge-alexa@0.5.0
updated 1 package in 20.668s
```

**Comment by NorthernMan54** [comment]
That warning can be ignored

Glad to hear it is working for you

I had the same issue with my setup as well, hence had the command at my finger tips.

How are the window coverings working out for you?

**Comment by lukebrannon1** [comment]
Working great! The natural language commands are much more intuitive than "turn off the living room shades"

**Comment by lukebrannon1** [comment]
I am in Georgia in the US.

**Comment by NorthernMan54** [comment]
Tks for confirming
