### ISSUE TITLE
Support devices (switches) with sub-devices

### ISSUE THREAD

**Issue by petschni** [NorthernMan54/homebridge-alexa#324]
I am using the https://github.com/nicoh88/homebridge-xiaomi-roborock-vacuum plugin for my vacuum cleaner. 

The plugin shows the vacuum cleaner within the `Apple home app` as one device (switch) with  multiple sub-devices:
- a switch for each room named e.g. "cleaning living room"
- a general switch
- a occupancy sensors 

I was wondering what the correct config would be to make the sub-devices visible in Alexa. Currently the "room switches" are not exported to the UI. (The general switch and the occupancy sensor are however.)

Is this something that needs to be added in the homebridge-xiaomi-roborock-vacuum plugin or a matter of the right config?

**Comment by NorthernMan54** [comment]
Can you send a homebridge accessory dump, details are in the README.  Then I can see what it is doing.

**Comment by petschni** [comment]
> Can you send a homebridge accessory dump, details are in the README. Then I can see what it is doing.
> […](#)

Actually after another restart it started working. Not sure what the cause here was but I think no need to debug this at the moment. Thanks anyway!
