### ISSUE TITLE
Homebrigde cannot start because of homebridge alexa error

### ISSUE THREAD

**Issue by naspinec** [NorthernMan54/homebridge-alexa#326]
After upgrading to homebridge 1.0.4 the plugins stopped working with the following error and rendering homebridge non functional.

> [4/30/2020, 11:33:44 PM] ====================
> [4/30/2020, 11:33:44 PM] ERROR LOADING PLUGIN homebridge-alexa:
> [4/30/2020, 11:33:44 PM] Error: Cannot find module 'request'
> Require stack:
> - /homebridge/node_modules/homebridge-alexa/node_modules/requestretry/index.js
> - /homebridge/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js
> - /homebridge/node_modules/homebridge-alexa/lib/alexaActions.js
> - /homebridge/node_modules/homebridge-alexa/plugin.js
> - /usr/local/lib/node_modules/homebridge/lib/plugin.js
> - /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
> - /usr/local/lib/node_modules/homebridge/lib/api.js
> - /usr/local/lib/node_modules/homebridge/lib/index.js
> - /usr/local/lib/node_modules/homebridge/lib/cli.js
> - /usr/local/lib/node_modules/homebridge/bin/homebridge
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:862:27)
>     at Module.require (internal/modules/cjs/loader.js:1042:19)
>     at require (internal/modules/cjs/helpers.js:77:18)
>     at Object.<anonymous> (/homebridge/node_modules/homebridge-alexa/node_modules/requestretry/index.js:12:15)
>     at Module._compile (internal/modules/cjs/loader.js:1156:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
>     at Module.load (internal/modules/cjs/loader.js:1000:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
>     at Module.require (internal/modules/cjs/loader.js:1042:19)

**Comment by NorthernMan54** [comment]
I’m working this this stay tuned

**Comment by NorthernMan54** [comment]
Fixed the issue, please reinstall homebridge-alexa, and restart homebridge

**Comment by naspinec** [comment]
I made the update and it worked fine. Thanks a lot.
