### ISSUE TITLE
Cannot find module '../build/Release/dns_sd_bindings'

### ISSUE THREAD

**Issue by WimBre** [NorthernMan54/homebridge-alexa#33]
I've tried to reinstall Homebridge but after reinstalling i get the undermentioned  error.

Please advice what to do.

Regards Wim

iMac-van-Wim:~ Bre$ homebridge
module.js:538
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by WimBre** [comment]
I've reloaded my old config.json and now the error is solved.

In the new config.json (checkt by JSON Formatter & Valuator) i'm trying to connect my Samsung Smart Tv but somethings seems to be wrong.

{
   "bridge":{
      "name":"Homebridge",
      "username":"XX:XX:XX:XX:XX:XX",
      "port":51826,
      "pin":"031-45-154"
   },
   "description":"This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
   "accessories":[
      {
         "accessory":"Toon",
         "name":"TOON",
         "username":"xxxxxxxxx",
         "password":"xxxxxxxxx"
      },
      {
         "accessory":"Spotify",
         "name":"Spotify Woonkamer",
         "fadeInTime":"4",
         "fadeOutTime":"4",
         "statusCheckInterval":"2"
      },
      {
      		"accessory": "SamsungSmartTv",
      		"name": "TV Woonkamer power",
          "type": "power",
      		"ip_address": "192.xxx.xxx.xxx",
          "mac_address": "xx:xx:xx:xx:xx:xx"
        },
        {
          "accessory": "SamsungSmartTv",
          "name": "TV Woonkamer sound",
          "type": "mute",
          "ip_address": "192.xxx.xxx.xxx",
          "mac_address": "xx:xx:xx:xx:xx:xx"
        }
   ],
   "platforms":[

   ]
}

**Comment by NorthernMan54** [comment]
Hi,

Is the problem with the Alexa connection or with the TV?  If your problem is with the Samsung smart tv config, please open an issue against that plugin.

**Comment by WimBre** [comment]
@ NorthernMan54.

Soory probleem is with the Smart TV
