### ISSUE TITLE
Exclude devices

### ISSUE THREAD

**Issue by boldiebold** [NorthernMan54/homebridge-alexa#330]
Can I exclude devices?
I have some devices I want to use via their home bridge plugin on my iPhone etc. But within Alexa I want to use their native skill.
So I want to exclude them from transferred by this plugin. Otherwise I have them double in Alexa.
Is this possible ?

Thanks

**Comment by NorthernMan54** [comment]
Yes, move them to a separate instance of homebridge, and don’t set the -I flag on that instance.
