### ISSUE TITLE
Issue with homebridge-mqttthing (outlets and switches)

### ISSUE THREAD

**Issue by Penguinwastaken** [NorthernMan54/homebridge-alexa#331]
Hello, i am new to the homebridge-alexa topic, and just got started with tasmota and MQTT. I flashed 4 outlets and one switch with tasmota to control it via MQTT. In HomeKit everything works fine, but Alexa got some problems. It can discover the devices but they are unreachable.

This is what I got after trying to turn on a outlet:

> 19.5.2020, 00:29:28 2020-05-18T22:29:28.825Z alexaLocal Emitting Alexa.PowerController

> 19.5.2020, 00:29:28 [Alexa] PowerController TurnOn 192.168.1.145 51826 { characteristics: [ { aid: 15, iid: 10, status: -70402 } ] } null

> 19.5.2020, 00:29:32 2020-05-18T22:29:32.623Z alexaLocal Emitting Alexa

> 19.5.2020, 00:29:32 2020-05-18T22:29:32.626Z alexaActions MESSAGE: {"directive":{"header":{"namespace":"Alexa","name":"ReportState","payloadVersion":"3","messageId":"83f0acbe-3bcf-441c-b803-66304e483551","correlationToken":"AAAAAAAAAQCqoUP//781sjQaTACc+BRM/AEAAAAAAADHgs+YF+ULY7IEsADqZ0eQmz9TwH+Xo9/I5MUvIr9AHaXfoWLsq8T14p8ULg4WUGLxBiukZegMYGroDTIxGR/J5XmzgNVEhVg/RKgeWUZ+25UtcfexM2lts4G3GBqzXjXkiBhXsXIX8WjspMAqNVWyXJa9mpShSwxEs2/hAG8kUEmasWgcBy5JsFshp1Mjn1aw2yGhTTMae4J8a0JE4IhzWBC279WI6P/2bVjX+znC5yxzts6f0zRGJ9utTEhCBCchJFTqtVRT91Ks99sb0yMm9kUGVTTBjNAtejWK/2C+jTudX1WM6Skp7mFP7GWm+yCaeDwn74T4g7KL4ntPZuQzc+iFNFb1d1rZBmMSvv+1gdsObKtXBb9/5kyctqwHt9Mwtrqc2nIs7gnfHudljgJjy008W7YI65bhGzwrz2ENriAmm0kJOtplRvUV6t7mEKIdz9wDBAq7K9ggtTtd8uCdTzexWuquJlX826/qCF4qa96+TWuOwKC7DSqz2tR0TO6M6DgqDAirisSRUB3RNuAdXEkLhsxJETIHm25EU+LtOQKbmgCDCdS09Df6T7f+15YRRUb9OkT/DBfBMg+T7Fm7fNllKwRecjYtUSnMeO1/KA2jEUvs7j3NAQtGjamvavZHHdE7vrEjo+t5ppDWpZoONwWNCCqMuzmxihm3"},"endpoint":{"endpointId":"Q0M6MjI6M0Q6RTM6Q0U6MzAtSE9PQlMtRGVmYXVsdC1NYW51ZmFjdHVyZXItVml0cmluZW4tMDAwMDAwNDctMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx","cookie":{"TurnOn":"{\"host\":\"192.168.1.145\",\"port\":51826,\"aid\":15,\"iid\":10,\"value\":1}","ReportState":"[{\"interface\":\"Alexa.PowerController\",\"host\":\"192.168.1.145\",\"port\":51826,\"aid\":15,\"iid\":10}]","TurnOff":"{\"host\":\"192.168.1.145\",\"port\":51826,\"aid\":15,\"iid\":10,\"value\":0}"}},"payload":{}}} {

> 19.5.2020, 00:29:32 TurnOn: '{"host":"192.168.1.145","port":51826,"aid":15,"iid":10,"value":1}',

> 19.5.2020, 00:29:32 ReportState: '[{"interface":"Alexa.PowerController","host":"192.168.1.145","port":51826,"aid":15,"iid":10}]',

> 19.5.2020, 00:29:32 TurnOff: '{"host":"192.168.1.145","port":51826,"aid":15,"iid":10,"value":0}'

> 19.5.2020, 00:29:32 }

> 19.5.2020, 00:29:32 2020-05-18T22:29:32.653Z alexaActions reportState ReportState 192.168.1.145 51826 { characteristics: [ { aid: 15, iid: 10, status: -70402 } ] } null

> 19.5.2020, 00:29:32 2020-05-18T22:29:32.655Z alexaMessageUtil StateToProperties - hbResponse [ { aid: 15, iid: 10, status: -70402 } ]

> 19.5.2020, 00:29:32 2020-05-18T22:29:32.656Z alexaMessageUtil StateToProperties - element {

> 19.5.2020, 00:29:32 interface: 'Alexa.PowerController',

> 19.5.2020, 00:29:32 host: '192.168.1.145',

> 19.5.2020, 00:29:32 port: 51826,

> 19.5.2020, 00:29:32 aid: 15,

> 19.5.2020, 00:29:32 iid: 10

> 19.5.2020, 00:29:32 }

Sorry for the "quotes" but the code was really unclear.

Thank you in advance.

**Comment by NorthernMan54** [comment]
Try asking Alexa to discover devices again.

**Comment by Penguinwastaken** [comment]
Tried it but nothing changed. It already discovered all devices and they are showing up. But if I click them or ask Alexa it is unreachable.

**Comment by NorthernMan54** [comment]
If you have asked Alexa to discover devices again ( asking her a second time refreshes the configuration, especially after changing Homebridge config ).  Please share a homebridge accessory dump, details are in the README.

**Comment by Penguinwastaken** [comment]
[dumb.txt](https://github.com/NorthernMan54/homebridge-alexa/files/4656430/dumb.txt)

Here you go.

**Comment by NorthernMan54** [comment]
Found the issue, your XiaoMi AirPurifier doesn't have a name

        "iid": 4,
        "type": "21",
        "perms": ["pr"],
        "format": "string",
        "value": "AirPurifier2S",
        "description": "Model"
      }, {
        "iid": 5,
        "type": "23",
        "perms": ["pr"],
        "format": "string",
        "value": " ",
        "description": "Name"
      }, {
        "iid": 6,
        "type": "30",
        "perms": ["pr"],
        "format": "string",
        "value": "Undefined",
        "description": "Serial Number"

Can you change your setup of the device to have a name?

**Comment by Penguinwastaken** [comment]
Hello, this causes the problem for other devices ? Cause I can control all devices except for the AirPurifier and the MQTT devices. 
I can't find wehere to change or add the name, but I will try my best

**Comment by NorthernMan54** [comment]
Yes it stops Amazon from processing the device discovery response as a result of the blank name.
