### ISSUE TITLE
Dummy Contact not Showing in Routines

### ISSUE THREAD

**Issue by Kung-Foo-Kamel** [NorthernMan54/homebridge-alexa#332]
Hi,

I have the Alexa plugin working perfectly, and has been for sometime now, so many thanks for this, as it works flawlessly.

I just discovered the Dummy switch plugin, I have set it up with the following:

{
            "accessory": "DummySwitch",
            "name": "Test Light",
            "contact": true,
            "stateful": true
        }

Everything works as expected, I now have a new light switch and a contact sensor, both turn on together and off together, all good there, they have both been added to Alexa, both also function there as well, so I can toggle the light switch from Homebridge and from Alexa, and the contact sensor and light switch change state as expected.

Now the issue is, this contact sensor is not exposed as a usable sensor when trying to create a routine, I currently have 15 Aqara contact sensors as well, they all show up as a trigger choice, but this one created through Homebridge does not, yet its in the devices list as a contact sensor, and operates as a contact sensor?

@NorthernMan54, I have read in another post you actually made this plugin specifically for this purpose, has something changed recently?

Appreciate any help.

**Comment by NorthernMan54** [comment]
@Kung-Foo-Kamel Nothing with homebridge-dummy-contact has changed recently and I'm using it as part of my setup

**Comment by Kung-Foo-Kamel** [comment]
Thanks for replying.

It might be AU specific then, I have everything working great, all Alexa integration is working except this one thing, it shows me all of my Xiaomi sensors but not the dummy ones, its weird.

**Comment by NorthernMan54** [comment]
Can you share an homebridge accessory dump, maybe something will show up there

**Comment by Kung-Foo-Kamel** [comment]
I will, just off to work now, but I will take a look tonight and upload it to you.

I mainly want to use the dummy sensor to integrate my lighting system that only has Alexa support, that way I can at least have Homekit activate them through routines.

It's a shame that the routines cant be triggered by any lite or switch in the Alexa range, seems a little narrow minded to only allow triggers from sensors.
