### ISSUE TITLE
502 Bad Gateway (homebridge.ca)

### ISSUE THREAD

**Issue by cybersi** [NorthernMan54/homebridge-alexa#334]
Hey, I'd just like to let you know that homebridge.ca seems to be down (502 Bad Gateway). Thank you again for your great work. 🙂

**Comment by NorthernMan54** [comment]
Tks just saw the alert messages from uptime, rebooting

**Comment by networks514** [comment]
Hi

Same things here ....
So Alexa skill doesn’t work..
Tks

**Comment by networks514** [comment]
> Hi
> 
> Same things here ....
> So Alexa skill doesn’t work..
> Tks

Cool.. after your reboot, works again !
Tks for your quickly intervention 😀

**Comment by NorthernMan54** [comment]
Amazon, Xymon and Uptime flooded my email inbox.   I may have too much monitoring going on

But things are back to normal again


![7E8D9B4F-F8CE-4CA0-922B-A7AE6C6330BD](https://user-images.githubusercontent.com/19808920/82739715-e5946780-9d0f-11ea-94d2-2893119e4dd5.png)

**Comment by Kohle81** [comment]
Hi @NorthernMan54 ,

the server is down again. 

Thanks for your great plugin and your work!!

Greetz from Germany

**Comment by nov-** [comment]
not working now(
