### ISSUE TITLE
502 Bad Gateway (homebridge.ca)

### ISSUE THREAD

**Issue by networks514** [NorthernMan54/homebridge-alexa#335]
Hi ,

The server seems to be down again (like yesterday) 🙁
Regards
Arnaud

**Comment by Tom2Drake** [comment]
same issue here, server is still not avilable.

**Comment by derthobo** [comment]
same here. i'm dying.

**Comment by banjohb** [comment]
same here! I’m dying too 😐

**Comment by NorthernMan54** [comment]
Just hit the reboot button

**Comment by networks514** [comment]
works again. hope it will last longer !!
thank you for your quick intervention, especially on a Sunday!

**Comment by NorthernMan54** [comment]
Would have been faster, but I’m in Toronto and the outage started during the middle of the night ( ZZZZ )

Looked at the logs and saw what the issue is.  Failed automated SSL Cert rollover.

Should be stable now for 60 days

**Comment by networks514** [comment]
the solution that you "offer" to us has become a must. we are not going to be demanding when it's free !!
thank you for your flawless support !!

> Would have been faster, but I’m in Toronto and the outage started during the middle of the night ( ZZZZ ) Looked at the logs and saw what the issue is. Failed automated SSL Cert rollover. Should be stable now for 60 days
> […](#)

the solution that you "offer" to us has become a must. we are not going to be demanding when it's free !!
thank you for your flawless support !!
