### ISSUE TITLE
HAP discovery failed when refresh is set

### ISSUE THREAD

**Issue by zerr0s** [NorthernMan54/homebridge-alexa#337]
Hi, sorry for my bad english.

I have an error every x seconds in homebridge log when I set a refresh interval for alexa:

`[6/7/2020, 08:19:19] [alexa] ERROR: HAP Discovery failed, please review config`

If I remove the refresh, no problem for alexa to discover all devices:

`[6/7/2020, 08:24:53] [alexa] alexaDiscovery - returned 29 devices`

Homebridge version: 1.1.0
Alexa plugin: v0.4.72
My config resulting from the UI config:

```json {
    "bridge": {
        "name": "Homebridge 7B9E",
        "username": "xxxxxx",
        "port": 51638,
        "pin": "xxxxxxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "domos",
            "server": "127.0.0.1",
            "port": "8080",
            "roomid": 0,
            "mqtt": true,
            "ssl": false,
            "dimFix": 0,
            "platform": "eDomoticz"
        },
        {
            "name": "alexa",
            "username": "xxxxxxx",
            "password": "xxxxxxx",
            "pin": "xxxxxxx",
            "refresh": 5,
            "platform": "Alexa"
        }
    ]
}```

Any idea ??

**Comment by NorthernMan54** [comment]
That value is in seconds and it needs a minute or so at a minimum.  But there is no need to set it.  So just don’t set it.

**Comment by zerr0s** [comment]
Hello,

If I don't set it, I have a desync between actions done directly on domoticz and alexa. If my roller shutters are closed and I open it with domoticz, alexa does not have the correct state until I launch the alexa app on my phone.

Maybe my config is not correct ?

**Comment by NorthernMan54** [comment]
The refresh config item deals with the discovery of homebridge instances and nothing in regards to passing of device state between Alexa and Homebridge.

With the Alexa it only requests device state when the Alexa app is open.  So am not sure what your attempting to accomplish?

**Comment by zerr0s** [comment]
Oh ok. So using domoticz and the voice simultaneously is not really possible to keep states in sync. Thank you for the clarification.
