### ISSUE TITLE
Device Discovery Issue

### ISSUE THREAD

**Issue by SparkyRedcar** [NorthernMan54/homebridge-alexa#339]
Alexa discovers 18 of my devices but misses the one I was hoping to use this for, my iT500 thermostat that is showing fine in Homebridge and HomeKit but doesn’t discover in Alexa.

Any ideas ?

**Comment by NorthernMan54** [comment]
Please share a homebridge accessory dump so I can look further.

**Comment by SparkyRedcar** [comment]
Randomly after about 5 hours it appeared and is now working fine.

I believe it may be a issue with the iT500 plugin as the device  periodically shows “No Response” in HomeKit.

Thakyou for your prompt reply.
