### ISSUE TITLE
Works with homebridge-lgwebos-tv

### ISSUE THREAD

**Issue by louisefindlay23** [NorthernMan54/homebridge-alexa#340]
Thought you may be interested that I've used this plugin successfully with homebridge-lgwebos-tv (the verified version) to turn on/off TV so you could add them to the Readme. 

Haven't been able to control volume or switch inputs/channels though that may be down to my config.json.

**Comment by NorthernMan54** [comment]
Tks

I have added this to the upcoming Input controller release
