### ISSUE TITLE
Instance filtering doesn’t work

### ISSUE THREAD

**Issue by miixxii** [NorthernMan54/homebridge-alexa#342]
Hello,

I do have 2 instances and only one has homebridge-alexa plugin installed with setup to filter IP:port of that instance. However devices from both instances are discovered. 

Plugin version: homebridge-alexa v0.4.72

My config:

"bridge": {
        "name": "alarmclock",
        "username": "xxxx",
        "port": 51829,
        "pin": "xxxxxxx"

"name": "alarmclock-alexa",
            "username": “xxxxx",
            "password": "xxxxxx",
            "pin": "xxxxxxx",
            "routines": true,
            "debug": true,
            "filter": "192.168.0.15:51829",
            "platform": "Alexa"

If you need logs, drop me message.

**Comment by NorthernMan54** [comment]
While I look at this an alternative approach is to not enable insecure mode for that instance.  That’s what I do in my setup

**Comment by miixxii** [comment]
Hi,

Thanks for the answer. I've tested this before reporting it here and yes, removing -I from homebridge instance that I don't want to collect devices is working, however I need to have insecure mode on that instance too.

**Comment by NorthernMan54** [comment]
I just fixed this in the beta for input controls branch

If you update to the beta version it should now work fine 

npm install -g homebridge-alexa@beta

**Comment by miixxii** [comment]
I've tested it and it's working fine :)

Many thanks
