### ISSUE TITLE
can't use device since upgrade

### ISSUE THREAD

**Issue by boscorelly** [NorthernMan54/homebridge-alexa#343]
Hi,

since the upgrade, i can't use devices. I have this in logs when i try to power on/off :

0|homebridge  | [2020-6-23 03:31:36] [Alexa] PowerController TurnOn 192.168.1.55 51826 { characteristics: [ { aid: 8, iid: 10, status: -70402 } ] } null
0|homebridge  | [2020-6-23 03:31:42] [Alexa] PowerController TurnOn 192.168.1.55 51826 { characteristics: [ { aid: 8, iid: 10, status: -70402 } ] } null
0|homebridge  | [2020-6-23 03:32:31] [Alexa] PowerController TurnOn 192.168.1.55 51826 { characteristics: [ { aid: 8, iid: 10, status: -70402 } ] } null

and in debug : 

0|homebridge  | 2020-06-23T02:16:19.137Z hapNodeJSClient Ready
0|homebridge  | 2020-06-23T02:16:19.147Z alexaActions alexaDiscovery
0|homebridge  | [2020-6-23 04:16:19] [Alexa] alexaDiscovery - returned 14 devices
0|homebridge  | 2020-06-23T02:16:19.240Z alexaActions registerEvents [ '{"host":"192.168.1.55","port":51826,"aid":21,"iid":10}': { '0': 'NOT_DETECTED',
0|homebridge  |     '1': 'DETECTED',
0|homebridge  |     endpointID: 'Q0M6MjE6M0U6RTQ6REU6MzMtSG9tZWJyaWRnZS1ob21lYnJpZGdlLWFsZXhhLUFsZXhhLTAwMDAwMDgwLTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==',
0|homebridge  |     template: 'ContactSensor' },
0|homebridge  |   '{"host":"192.168.1.55","port":51826,"aid":24,"iid":10}': { '0': 'NOT_DETECTED',
0|homebridge  |     '1': 'DETECTED',
0|homebridge  |     endpointID: 'Q0M6MjE6M0U6RTQ6REU6MzMtSG9tZWJyaWRnZS1lRG9tb3RpY3otRmVuw6p0cmUgY3Vpc2luZS0wMDAwMDA4MC0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=',
0|homebridge  |     template: 'ContactSensor' },
0|homebridge  |   '{"host":"192.168.1.55","port":51826,"aid":29,"iid":10}': { '0': 'NOT_DETECTED',
0|homebridge  |     '1': 'DETECTED',
0|homebridge  |     endpointID: 'Q0M6MjE6M0U6RTQ6REU6MzMtSG9tZWJyaWRnZS1lRG9tb3RpY3otUG9ydGUgZW50csOpZS0wMDAwMDA4MC0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=',
0|homebridge  |     template: 'ContactSensor' },
0|homebridge  |   '{"host":"192.168.1.55","port":51826,"aid":36,"iid":10}': { '0': 'DETECTED',
0|homebridge  |     '1': 'NOT_DETECTED',
0|homebridge  |     endpointID: 'Q0M6MjE6M0U6RTQ6REU6MzMtSG9tZWJyaWRnZS1lRG9tb3RpY3otVm9sZXQgY2hhbWJyZS0wMDAwMDA4Qy0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=',
0|homebridge  |     template: 'ContactSensor' },
0|homebridge  |   '{"host":"192.168.1.55","port":51826,"aid":37,"iid":10}': { '0': 'DETECTED',
0|homebridge  |     '1': 'NOT_DETECTED',
0|homebridge  |     endpointID: 'Q0M6MjE6M0U6RTQ6REU6MzMtSG9tZWJyaWRnZS1lRG9tb3RpY3otVm9sZXQgY3Vpc2luZS0wMDAwMDA4Qy0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=',
0|homebridge  |     template: 'ContactSensor' },
0|homebridge  |   '{"host":"192.168.1.55","port":51826,"aid":38,"iid":10}': { '0': 'DETECTED',
0|homebridge  |     '1': 'NOT_DETECTED',
0|homebridge  |     endpointID: 'Q0M6MjE6M0U6RTQ6REU6MzMtSG9tZWJyaWRnZS1lRG9tb3RpY3otVm9sZXQgZW50csOpZS0wMDAwMDA4Qy0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=',
0|homebridge  |     template: 'ContactSensor' },
0|homebridge  |   '{"host":"192.168.1.55","port":51826,"aid":39,"iid":10}': { '0': 'DETECTED',
0|homebridge  |     '1': 'NOT_DETECTED',
0|homebridge  |     endpointID: 'Q0M6MjE6M0U6RTQ6REU6MzMtSG9tZWJyaWRnZS1lRG9tb3RpY3otVm9sZXQgc2FsbGUgZGUgYmFpbi0wMDAwMDA4Qy0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=',
0|homebridge  |     template: 'ContactSensor' } ]
0|homebridge  | 2020-06-23T02:16:19.270Z alexaActions Event Register 192.168.1.55:51826 -> { characteristics:
0|homebridge  |    [ { aid: 21, iid: 10, ev: true },
0|homebridge  |      { aid: 24, iid: 10, ev: true },
0|homebridge  |      { aid: 29, iid: 10, ev: true },
0|homebridge  |      { aid: 36, iid: 10, ev: true },
0|homebridge  |      { aid: 37, iid: 10, ev: true },
0|homebridge  |      { aid: 38, iid: 10, ev: true },
0|homebridge  |      { aid: 39, iid: 10, ev: true } ] }

all is working perfectly in homekit btw

**Comment by NorthernMan54** [comment]
What upgrade?

**Comment by boscorelly** [comment]
of the plugin :)

update* not upgrade :)

**Comment by boscorelly** [comment]
when i try to turn on a socket from alexa app : 

0|homebridge  | 2020-06-23T17:43:04.937Z alexaLocal Emitting Alexa
0|homebridge  | 2020-06-23T17:43:04.947Z alexaActions MESSAGE: {"directive":{"header":{"namespace":"Alexa","name":"ReportState","payloadVersion":"3","messageId":"22120475-1190-44d0-988c-1b6543f2b987","correlationToken":"AAAAAAAAAQBCzm6xycsa2UBDDbG25qPi/AEAAAAAAACqKTAXmVGs36azUN9x7YciVUotNZgiNkRZ8HQD0JBRQfs7S61f4BL/TJUPylx396qKpB5l6WWD5GfGjt/zm7++wkysN+ICrbwLf0dLZPgCDMgAZTJNvyh/aEs7/xxL3iteIFm/ypWUCwNdV1YfHWP3K7qY5lJBW/j+kLR4ztv3vGNC3I9OhpeRjs9A5pHNDkc9dptfB/sMxDiy6O+vttKix7aYbYDNBvtE4uGfB/6/PTouHpsaWjIjx3srDTduZvT1Z82JVLTuRT7Qui3vLPEqJ3ju1t2p9SpkVKEO3aILcU3sqqgmhERv1LGHDdo3Exrc7p3ABXmPQFGADwHu50OmrdEdlbooPgRIEdoxgVampzk7e0lk3wJJEtoPV8FShy1/P+HKOhCaSoZtt+71TqULF8ySigi3Kke2E1yErekkXWTOqpcZZEpJmf/+dVnm9EDqpElSkX5kDpmLRWkpt+OgGjX3CzkkeImThwpZHjeRTBQBcPzVtvLxipw1SkAm2Bkzft0p4yRR3AmHbDKitcgGSsycuBDovAXP/gUyDmXm1iJplgnpNH6DbvAkMICLWuhH77InUDU0axLKE4lOSyY7t/RSEAcKGkUTBXf24Ptkxo9MiezFIfn34+LGtg2eRAkBgZCCjremuypulODA+2wLdmHWuREqV6iGYJrM"},"endpoint":{"endpointId":"Q0M6MjE6M0U6RTQ6REU6MzMtSG9tZWJyaWRnZS1lRG9tb3RpY3otUHJpc2UgbGl0LTAwMDAwMDQ5LTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==","cookie":{"TurnOn":"{\"host\":\"192.168.1.55\",\"port\":51826,\"aid\":8,\"iid\":10,\"value\":1}","ReportState":"[{\"interface\":\"Alexa.PowerController\",\"host\":\"192.168.1.55\",\"port\":51826,\"aid\":8,\"iid\":10}]","TurnOff":"{\"host\":\"192.168.1.55\",\"port\":51826,\"aid\":8,\"iid\":10,\"value\":0}"}},"payload":{}}} { TurnOn: '{"host":"192.168.1.55","port":51826,"aid":8,"iid":10,"value":1}',
0|homebridge  |   ReportState: '[{"interface":"Alexa.PowerController","host":"192.168.1.55","port":51826,"aid":8,"iid":10}]',
0|homebridge  |   TurnOff: '{"host":"192.168.1.55","port":51826,"aid":8,"iid":10,"value":0}' }
0|homebridge  | 2020-06-23T17:43:05.017Z alexaActions reportState ReportState 192.168.1.55 51826 { characteristics: [ { aid: 8, iid: 10, status: -70402 } ] } null
0|homebridge  | 2020-06-23T17:43:05.027Z alexaMessageUtil StateToProperties - hbResponse [ { aid: 8, iid: 10, status: -70402 } ]
0|homebridge  | 2020-06-23T17:43:05.036Z alexaMessageUtil StateToProperties - element { interface: 'Alexa.PowerController',
0|homebridge  |   host: '192.168.1.55',
0|homebridge  |   port: 51826,
0|homebridge  |   aid: 8,
0|homebridge  |   iid: 10 }
0|homebridge  | 2020-06-23T17:43:05.046Z alexaActions reportState {"context":{"properties":[{"namespace":"Alexa.PowerController","name":"powerState","value":"OFF","timeOfSample":"2020-06-23T17:43:05.027Z","uncertaintyInMilliseconds":500}]},"event":{"header":{"messageId":"22120475-1190-44d0-988c-1b6543f2b987","correlationToken":"AAAAAAAAAQBCzm6xycsa2UBDDbG25qPi/AEAAAAAAACqKTAXmVGs36azUN9x7YciVUotNZgiNkRZ8HQD0JBRQfs7S61f4BL/TJUPylx396qKpB5l6WWD5GfGjt/zm7++wkysN+ICrbwLf0dLZPgCDMgAZTJNvyh/aEs7/xxL3iteIFm/ypWUCwNdV1YfHWP3K7qY5lJBW/j+kLR4ztv3vGNC3I9OhpeRjs9A5pHNDkc9dptfB/sMxDiy6O+vttKix7aYbYDNBvtE4uGfB/6/PTouHpsaWjIjx3srDTduZvT1Z82JVLTuRT7Qui3vLPEqJ3ju1t2p9SpkVKEO3aILcU3sqqgmhERv1LGHDdo3Exrc7p3ABXmPQFGADwHu50OmrdEdlbooPgRIEdoxgVampzk7e0lk3wJJEtoPV8FShy1/P+HKOhCaSoZtt+71TqULF8ySigi3Kke2E1yErekkXWTOqpcZZEpJmf/+dVnm9EDqpElSkX5kDpmLRWkpt+OgGjX3CzkkeImThwpZHjeRTBQBcPzVtvLxipw1SkAm2Bkzft0p4yRR3AmHbDKitcgGSsycuBDovAXP/gUyDmXm1iJplgnpNH6DbvAkMICLWuhH77InUDU0axLKE4lOSyY7t/RSEAcKGkUTBXf24Ptkxo9MiezFIfn34+LGtg2eRAkBgZCCjremuypulODA+2wLdmHWuREqV6iGYJrM","namespace":"Alexa","name":"StateReport","payloadVersion":"3"},"endpoint":{"endpointId":"Q0M6MjE6M0U6RTQ6REU6MzMtSG9tZWJyaWRnZS1lRG9tb3RpY3otUHJpc2UgbGl0LTAwMDAwMDQ5LTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==","cookie":{}},"payload":{}}}
0|homebridge  | 2020-06-23T17:43:08.287Z alexaLocal Emitting Alexa
0|homebridge  | 2020-06-23T17:43:08.297Z alexaActions MESSAGE: {"directive":{"header":{"namespace":"Alexa","name":"ReportState","payloadVersion":"3","messageId":"0e8e533c-9042-4ca2-8960-1773fb1e4d63","correlationToken":"AAAAAAAAAQBCzm6xycsa2UBDDbG25qPi/AEAAAAAAABeyWnddoVcnvZ7coa5fy2paQQGRyouYBL+doa4dI6M6rRkXdDdeN1oROLb0C3fWpGvZDiRDp79nAdCnv4g+56/aDmTqK/04iQRahVuVRvA4y+7wQv6WIGmP8NRpo45+whlkuYYM9qQuYQ7H9/Df5nDn3GydVsn0Qc2lgootqmzlbo9K9QJPQg3NNV2nfVWsELzKZ0V+BjnS4dWAvmIAJeMjT2EnZGBFYH7ErxRikGYcXVTP49hcW0nwoyx4TwzB/GAemcUFb26mUia6MxYU7oQYK6ztgp4jKPaLSZXgRi6RkiY/KaRPcb6v5JFp2ev0drgXbDm643StrBCraJUhkDiQ3pRehxa13w1VJ9/j8CgGYjIMlopXdsz5tINswQyxX6UxGBUxkOB+UWPjSI2R7AM54sMy/CCMRJYVKYkuCZy28IoER7VSXDrZgdjal8eaiY4WXHqvl3G54J064Frk9YsMKu7xHl8gT0F4OaiXSUF9Bo3liMhGQw+V2X6edA4QZMWJcIB4c9MJ+a4KDATq3V+m+T0ps0vwZ5ol4TKyPUy6eXPHyFYr6T3CEV3tK7ERkyj+dh+AfoXaCFTvk5QapLCcFHpLIUYtXSDUIbYxcW/Q6PTHV43VZsq0p3czB7YZpqCRrBy4SJQYMy+wXYLB/wamgZjxoh/exzuoT0s"},"endpoint":{"endpointId":"Q0M6MjE6M0U6RTQ6REU6MzMtSG9tZWJyaWRnZS1lRG9tb3RpY3otUHJpc2UgbGl0LTAwMDAwMDQ5LTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==","cookie":{"TurnOn":"{\"host\":\"192.168.1.55\",\"port\":51826,\"aid\":8,\"iid\":10,\"value\":1}","ReportState":"[{\"interface\":\"Alexa.PowerController\",\"host\":\"192.168.1.55\",\"port\":51826,\"aid\":8,\"iid\":10}]","TurnOff":"{\"host\":\"192.168.1.55\",\"port\":51826,\"aid\":8,\"iid\":10,\"value\":0}"}},"payload":{}}} { TurnOn: '{"host":"192.168.1.55","port":51826,"aid":8,"iid":10,"value":1}',
0|homebridge  |   ReportState: '[{"interface":"Alexa.PowerController","host":"192.168.1.55","port":51826,"aid":8,"iid":10}]',
0|homebridge  |   TurnOff: '{"host":"192.168.1.55","port":51826,"aid":8,"iid":10,"value":0}' }
0|homebridge  | 2020-06-23T17:43:08.374Z alexaActions reportState ReportState 192.168.1.55 51826 { characteristics: [ { aid: 8, iid: 10, status: -70402 } ] } null
0|homebridge  | 2020-06-23T17:43:08.387Z alexaMessageUtil StateToProperties - hbResponse [ { aid: 8, iid: 10, status: -70402 } ]
0|homebridge  | 2020-06-23T17:43:08.403Z alexaMessageUtil StateToProperties - element { interface: 'Alexa.PowerController',
0|homebridge  |   host: '192.168.1.55',
0|homebridge  |   port: 51826,
0|homebridge  |   aid: 8,
0|homebridge  |   iid: 10 }
0|homebridge  | 2020-06-23T17:43:08.406Z alexaActions reportState {"context":{"properties":[{"namespace":"Alexa.PowerController","name":"powerState","value":"OFF","timeOfSample":"2020-06-23T17:43:08.386Z","uncertaintyInMilliseconds":500}]},"event":{"header":{"messageId":"0e8e533c-9042-4ca2-8960-1773fb1e4d63","correlationToken":"AAAAAAAAAQBCzm6xycsa2UBDDbG25qPi/AEAAAAAAABeyWnddoVcnvZ7coa5fy2paQQGRyouYBL+doa4dI6M6rRkXdDdeN1oROLb0C3fWpGvZDiRDp79nAdCnv4g+56/aDmTqK/04iQRahVuVRvA4y+7wQv6WIGmP8NRpo45+whlkuYYM9qQuYQ7H9/Df5nDn3GydVsn0Qc2lgootqmzlbo9K9QJPQg3NNV2nfVWsELzKZ0V+BjnS4dWAvmIAJeMjT2EnZGBFYH7ErxRikGYcXVTP49hcW0nwoyx4TwzB/GAemcUFb26mUia6MxYU7oQYK6ztgp4jKPaLSZXgRi6RkiY/KaRPcb6v5JFp2ev0drgXbDm643StrBCraJUhkDiQ3pRehxa13w1VJ9/j8CgGYjIMlopXdsz5tINswQyxX6UxGBUxkOB+UWPjSI2R7AM54sMy/CCMRJYVKYkuCZy28IoER7VSXDrZgdjal8eaiY4WXHqvl3G54J064Frk9YsMKu7xHl8gT0F4OaiXSUF9Bo3liMhGQw+V2X6edA4QZMWJcIB4c9MJ+a4KDATq3V+m+T0ps0vwZ5ol4TKyPUy6eXPHyFYr6T3CEV3tK7ERkyj+dh+AfoXaCFTvk5QapLCcFHpLIUYtXSDUIbYxcW/Q6PTHV43VZsq0p3czB7YZpqCRrBy4SJQYMy+wXYLB/wamgZjxoh/exzuoT0s","namespace":"Alexa","name":"StateReport","payloadVersion":"3"},"endpoint":{"endpointId":"Q0M6MjE6M0U6RTQ6REU6MzMtSG9tZWJyaWRnZS1lRG9tb3RpY3otUHJpc2UgbGl0LTAwMDAwMDQ5LTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==","cookie":{}},"payload":{}}}
0|homebridge  | 2020-06-23T17:43:08.666Z alexaLocal Emitting Alexa.PowerController
0|homebridge  | [2020-6-23 19:43:08] [Alexa] PowerController TurnOn 192.168.1.55 51826 { characteristics: [ { aid: 8, iid: 10, status: -70402 } ] } null

**Comment by NorthernMan54** [comment]
I'm asking what upgrade, as I have not made any changes to latest release in a month or so.  But have made changes to the beta.

**Comment by boscorelly** [comment]
i was not up to date since a few months ^^

**Comment by boscorelly** [comment]
Migrated to homebridge in docker #344
