### ISSUE TITLE
Migrate to another Homebridge instance

### ISSUE THREAD

**Issue by boscorelly** [NorthernMan54/homebridge-alexa#344]
Following my issue previously opened (#343), i tried to migrate to another instance in docker.
All is good for homebridge, excepted that HAP is always trying to contact old instance.

Old instance ip : 192.168.1.55
configuration :

> {
>     "bridge": {
>         "name": "Homebridge",
>         "username": "CC:21:3E:E4:DE:33",
>         "port": 51826,
>         "pin": "031-45-154"
>     },
>     "description": "Configuration file for (e)xtended Domoticz platform.",
>     "platforms": [
>         {
>             "platform": "eDomoticz",
>             "name": "eDomoticz",
>             "server": "192.168.1.55",
>             "port": "8080",
>             "ssl": 0,
>             "roomid": 5,
>             "mqtt": 1
>         },
>         {
>             "platform": "Alexa",
>             "name": "Alexa",
>             "username": "user",
>             "password": "password",
>             "refresh": 120,
>             "debug": true,
>             "routines": true
>         }
>     ],
>     "accessories": []
> }

New instance ip : 192.168.1.38
New configuration :
> "bridge": {
>         "name": "Homebridge Docker",
>         "username": "0E:E3:C5:2A:BC:CF",
>         "port": 52831,
>         "pin": "031-45-156"
>     },
>     "platforms": [
>         {
>             "name": "Domoticz",
>             "server": "192.168.1.55",
>             "port": 8080,
>             "roomid": 5,
>             "mqtt": true,
>             "ssl": false,
>             "dimFix": 0,
>             "platform": "eDomoticz-ui-x"
>         },
>         {
>             "name": "Alexa",
>             "username": "user",
>             "password": "password",
>             "pin": "031-45-156",
>             "platform": "Alexa",
>             "filter": "192.168.1.38:52831",
>             "routines": true
>         }
>     ]
> }

But, in logs i have this :
> [6/23/2020, 9:37:26 PM] [Alexa] PowerController TurnOn 192.168.1.55 51826 undefined Error: connect ECONNREFUSED 192.168.1.55:51826
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
>   errno: 'ECONNREFUSED',
>   code: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '192.168.1.55',
>   port: 51826,
>   attempts: 5
> }
> ERROR: alexaStateResponse connect ECONNREFUSED 192.168.1.55:51826
> [6/23/2020, 9:41:26 PM] [Alexa] ERROR: HAP Discovery failed, please review config

**Comment by NorthernMan54** [comment]
if you ask Alexa to discover devices again it will correct the ip addresses

**Comment by boscorelly** [comment]
what is the good sentence to discover ? alexa, discover ?

for those who are using homebridge in docker with docker-compose, the setting - HOMEBRIDGE_INSECURE=1 is not used when booting homebridge.

you must enable it in homebridge-ux like described here : https://github.com/oznu/docker-homebridge/issues/219 (this setting is overriding)

**Comment by NorthernMan54** [comment]
Alexa, discover devices

**Comment by boscorelly** [comment]
ok thanks :)

last question about this, since the new version, i have a device named "alexa" in homebridge in ios. Is it normal ? How can i hide it ?

**Comment by boscorelly** [comment]
masqued in http://ip:port/accessories
