### ISSUE TITLE
Device "Alexa"

### ISSUE THREAD

**Issue by boscorelly** [NorthernMan54/homebridge-alexa#345]
since the new version, i have a device named "alexa" in homebridge in ios. Is it normal ? How can i hide it ?

_Originally posted by @boscorelly in https://github.com/NorthernMan54/homebridge-alexa/issues/344#issuecomment-648467426_

**Comment by NorthernMan54** [comment]
Yes, new feature in recent versions.  It is a contact sensor that will go "Open" when the Alexa service losses connection to the cloud.

Move it to a empty room
