### ISSUE TITLE
Homebridge-Alexa plugin picked as an accessory

### ISSUE THREAD

**Issue by mdelag** [NorthernMan54/homebridge-alexa#347]
After updating Homebridge and some plugins Homebridge being picking the homebdige-alexa plugin as an accessory thus distributing to the Alexa App and iOS HomeKit, does anyone have this issue?

![Screen Shot 2020-06-29 at 1 18 57 AM](https://user-images.githubusercontent.com/25717236/85979724-a7413680-b9a6-11ea-814c-78dfa8153cef.png)

**Comment by NorthernMan54** [comment]
Please review the README, this was a new feature a few releases ago.

Shows the status of the cloud connection from your setup.
