### ISSUE TITLE
Air Conditioner (thermostat device) not responding to relative commands

### ISSUE THREAD

**Issue by amaisano** [NorthernMan54/homebridge-alexa#348]
According to the thermostat type specs, my Frigidaire Gallery smart AC connected through homebridge should respond to commands like "make it cooler in here" or "increase the [air conditioner] by 2 degrees."

https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-thermostatcontroller.html#utterances

However it's not working, with a response of "sorry, [air conditioner] doesn't support that".

Am I missing something or has this functionality not been mapped yet?

Or maybe it'd due to the Frigidaire API not being complete? According to the native Alexa skill, only absolute commands (set temp to XX degrees) seems to be present:

https://www.amazon.com/Frigidaire/dp/B01IU48OCI

**Comment by NorthernMan54** [comment]
I never implemented the warmer or cooler portion of the API.  It is here, but listed with a TBD

https://github.com/NorthernMan54/homebridge-alexa/blob/8b3efab01f6b071cba9918792d88edefda889c4f/lib/alexaActions.js#L405

At some point in the future I can add it

**Comment by amaisano** [comment]
Ok. Could you please confirm which utterances _should_ work today with the release code for an air conditioner? Just want to verify / do a sanity check. Something it funky here.

**Comment by amaisano** [comment]
@NorthernMan54 I've got a full report on compatibility of commands and what I'm seeing happen when interpreted by Alexa. Where's a good place to post?

**Comment by NorthernMan54** [comment]
Updating the README is best, if not just post it here and I will update it

**Comment by amaisano** [comment]
## Voice Assistant Results

| Voice Command                                                              | Frigidaire Skill (Alexa)                                                       | Notes                                  | Homebridge Plugin (Siri)                                                                           | Notes                                                                                                              | Homebridge Plugin -> Homebridge Skill (Alexa)                                  | Notes                                                                           |
| -------------------------------------------------------------------------- | ------------------------------------------------------------------------------ | -------------------------------------- | -------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------ | ------------------------------------------------------------------------------- |
| Turn `<AC>` on                                                             | ✅\*                                                                           | \*Reverts to COOL mode.                | ✅ Okay, done.\*                                                                                   | \*Reverts to ECO cooling mode (this is a Frigidaire default feature).                                              | ❌ AC doesn't support that.                                                    | Thermostats cannot be turned "on" or "off."                                     |
| Turn `<AC>` off                                                            | ✅                                                                             | -                                      | ✅ Okay, done.                                                                                     | -                                                                                                                  | ❌ AC doesn't support that.                                                    | Thermostats cannot be turned "on" or "off."                                     |
| Turn `<AC>` up<br>OR<br>Increase the temperature in the `<room with AC>`   | ❌ Please try again, using percent for brightness, or degrees for temperature. | -                                      | ❓ Okay, I'm warming the temperature from 23°C to 24°C.                                            | AC responds, but temperature does not change (possibly increasing by fractional amounts instead of whole numbers). | ❌ Please try again, using percent for brightness, or degrees for temperature. | "Increase/decrease" room commands have no effect.                               |
| Turn `<AC>` down<br>OR<br>Decrease the temperature in the `<room with AC>` | ❌ Please try again, using percent for brightness, or degrees for temperature. | -                                      | ❓ Okay, I'm cooling the temperature from 23°C to 22°C.                                            | AC responds, but temperature does not change (possibly decreasing by fractional amounts instead of whole numbers). | ❌ Please try again, using percent for brightness, or degrees for temperature. | "Increase/decrease" room commands have no effect.                               |
| Decrease/lower the `<AC>` by 2 degrees                                     | ✅ It's set to 20.                                                             | Correctly sets temperature every time. | ✅ Okay, I'm cooling the temperature from 25°C to 23°C.                                            | AC responds, but doesn't always set the right temperature.                                                         | ❌ That command doesn't work on device AC.                                     | These commands _should_ work for any thermostat device.                         |
| Increase/raise the `<AC>` by 2 degrees                                     | ✅ It's set to 25.                                                             | Correctly sets temperature every time. | ✅ Okay, I'm warming the temperature from 25°C to 27°C.                                            | AC responds, but doesn't always set the right temperature.                                                         | ❌ That command doesn't work on device AC.                                     | These commands _should_ work for any thermostat device.                         |
| Set `<AC>` to 23°                                                          | ✅ It's set to 27.                                                             | Correctly sets temperature every time. | ✅ Okay, I'm cooling the temperature to 23°C.                                                      | Usually works as expected. +1/-1 differences sometimes result in temperature setting not changing.                 | ✅ It's set to 24.                                                             | Requires "degrees" unit prefix. Often incorrectly sets temperature.             |
| Set `<AC>` to low                                                          | ❌ Please try again, using percent for brightness, or degrees for temperature. | -                                      | ❓ Okay, I changed the temperature from 22°C to 25°C                                               | WTF                                                                                                                | ❌ Please try again, using percent for brightness, or degrees for temperature. | A unit of measurement makes no sense here, even if it was supported.            |
| Set `<AC>` to medium                                                       | ❌ Please try again, using percent for brightness, or degrees for temperature. | -                                      | ❓ Okay, I'm increasing the temperature from 23°C to 50°C.                                         | WTF                                                                                                                | ❌ Please try again, using percent for brightness, or degrees for temperature. | A unit of measurement makes no sense here, even if it was supported.            |
| Set `<AC>` to high                                                         | ❌ Please try again, using percent for brightness, or degrees for temperature. | -                                      | ❓ Okay, I changed the temperature from 71°F to 100°F. Your Heat failed. You may want to check it. | WTF                                                                                                                | ❌ Please try again, using percent for brightness, or degrees for temperature. | A unit of measurement makes no sense here, even if it was supported.            |
| Set `<AC>` to auto                                                         | ❌ Hmmm. AC is not responding.                                                 | Strange, non-negative response.        | ✅ OK.                                                                                             | Turns on and OFF unit and sets cooling mode to AUTO (Eco). No change to fan speed.                                 | ✅ It's set to AUTO.                                                           | Turns an OFF unit to on, and sets cooling mode to auto (no change to fan speed) |
| Set `<AC>` speed to low                                                    | ❌ Please try again, using percent for brightness, or degrees for temperature. | -                                      | ✅ Okay, I set the AC to low.                                                                      | Sets the fan speed to low.                                                                                         | ❌ Please try again, using percent for brightness, or degrees for temperature. | A unit of measurement makes no sense here, even if it was supported.            |
| Set `<AC>` speed to medium                                                 | ❌ Please try again, using percent for brightness, or degrees for temperature. | -                                      | ✅ Okay, I set the AC to medium.                                                                   | Sets the fan speed to medium.                                                                                      | ❌ Please try again, using percent for brightness, or degrees for temperature. | A unit of measurement makes no sense here, even if it was supported.            |
| Set `<AC>` speed to high                                                   | ❌ Please try again, using percent for brightness, or degrees for temperature. | -                                      | ❓ Okay, I set the AC to high.                                                                     | Sets the fan speed to AUTO                                                                                         | ❌ Please try again, using percent for brightness, or degrees for temperature. | A unit of measurement makes no sense here, even if it was supported.            |
| Set `<AC>` speed to auto                                                   | ❌ Hmmm. AC is not responding.                                                 | Strange, non-negative response.        | ❌ Sorry, I didn't get that. Try asking me again.                                                  | I asked again. Same results each time.                                                                             | ❌ Please try again, using percent for brightness, or degrees for temperature. | A unit of measurement makes no sense here, even if it was supported.            |

## Interface

| Item         | Frigidaire Skill (Alexa) | Homebridge Plugin (HomeKit)                                 | Homebridge Plugin -> Homebridge Skill (Alexa) | Sensibo Hombridge Plugin (Homekit)                                            |
| ------------ | ------------------------ | ----------------------------------------------------------- | --------------------------------------------- | ----------------------------------------------------------------------------- |
| Type         | Other                    | Thermostat                                                  | Thermostat                                    | Thermostat + Fan + Humidity                                                   |
| Current Temp | ❌ No controls           | ✅ Present                                                  | ✅ Present                                    | ✅ Present                                                                    |
| Set Temp     | ❌ No controls           | ✅ Present. Half-degrees are problematic.                   | ✅ Present. Half-degrees are problematic.     | ✅ Present. Half-degrees are problematic.                                     |
| Cooling Mode | ❌ No controls           | ✅ OFF/HEAT/COOL/AUTO (interactive). HEAT == Fan only mode. | ❓ Present. Visible but non-interactive.      | ✅ OFF/HEAT/COOL/AUTO (controllable). HEAT == Fan only mode.                  |
| Fan Speed    | ❌ No controls           | ❌ Not present                                              | ❌ Not present                                | ✅ Present. Level: OFF, 1% to 100% (1% is AUTO speed). Slider is problematic. |
| Humidity     | ❌ No controls           | ❌ Not present                                              | ❌ Not present                                | ✅ Present                                                                    |
| Unit         | ❌ No controls           | ✅ F/C (interactive)                                        | ❌ Not present                                | ✅ F/C (interactive)                                                          |

## Automation/Routines

| Action          | Frigidaire Skill (Alexa) | Homebridge Plugin (HomeKit)                   | Homebridge Plugin -> Homebridge Skill (Alexa) | Sensibo Hombridge Plugin (Homekit)            |
| --------------- | ------------------------ | --------------------------------------------- | --------------------------------------------- | --------------------------------------------- |
| Power           | ✅ ON/OFF                | ✅ OFF/HEAT/COOL/AUTO. HEAT == Fan only mode. | ❓ Level 0 — 100 (WTF)                        | ✅ OFF/HEAT/COOL/AUTO. HEAT == Fan only mode. |
| Cooling Mode    | ❌                       | ✅ OFF/HEAT/COOL/AUTO. HEAT == Fan only mode. | ❌                                            | ✅ OFF/HEAT/COOL/AUTO. HEAT == Fan only mode. |
| Set Temperature | ✅ °C or °F              | ✅ current unit                               | ✅ °C or °F                                   | ✅ current unit                               |
| Fan Speed       | ❌                       | ❌                                            | ❌                                            | ✅ Level: OFF, 1% — 100% (1% is AUTO speed)   |

### Frigidaire Skill (Alexa)

| Home Control | Routine Options |
| -------------- | ---------------- |
| ![IMG_17CEFE08C5CA-1](https://user-images.githubusercontent.com/688435/90684554-69d68800-e236-11ea-841a-b9d852c8862e.jpeg) | ![IMG_755139AC2C84-1](https://user-images.githubusercontent.com/688435/90684644-8c68a100-e236-11ea-9a91-13883aea1ea2.jpeg) |

### Homebridge Plugin (Homekit)

| Home Control | Routine Options |
| -------------- | ---------------- |
| ![IMG_A8526FCB6E2A-1](https://user-images.githubusercontent.com/688435/90684940-000aae00-e237-11ea-8f99-8e4139b1cca8.jpeg) | (All controls present in home control are available to set) |

### Homebridge Plugin -> Homebridge Skill (Alexa)

| Home Control | Routine Options |
| -------------- | ---------------- |
| ![IMG_ABCC7F2C7926-1](https://user-images.githubusercontent.com/688435/90684794-c5a11100-e236-11ea-85eb-2859d63a81e1.jpeg) | ![IMG_8B2938CE0ACF-1](https://user-images.githubusercontent.com/688435/90684705-a5715200-e236-11ea-9aaf-88a0eda02e3d.jpeg)

### Sensibo Hombridge Plugin (Homekit)

| Home Control | Grouped Fan Device |
| -------------- | ---------------- |
![IMG_549CFC01B694-1](https://user-images.githubusercontent.com/688435/90685061-3b0ce180-e237-11ea-8208-07a5a7284042.jpeg) | ![IMG_E22EC4DABA58-1](https://user-images.githubusercontent.com/688435/90685088-44964980-e237-11ea-81c1-a5bd4d502df3.jpeg) |

## Other Notes

- https://sensi.emerson.com/en-us/support/what-commands-can-i-give-my-sensi-thermostat-using-amazon-alexa

**Comment by NorthernMan54** [comment]
Tks very much, I have added this to the Wiki and posted the link into the Wiki for everyone

For the turn on / off issue, can you share a homebridge accessory dump of your thermostat.  This may be a minor change?

For the increase / decrease I will them them to the backlog for a future release.
