### ISSUE TITLE
How to remove unexisting devices

### ISSUE THREAD

**Issue by dcaccount** [NorthernMan54/homebridge-alexa#350]
Hello,
I have added one device to Homebridge and then I have removed it.

In the Alexa app I still find this removed devices among all Alexa devices. 
How can I remove automatically the devices that do not exist any longer?

Is there a way?
Thanks,
Dan

**Comment by NorthernMan54** [comment]
Unfortunately there is no automated way to remove it.  One option is to manual remove non existent device with the Alexa app, and other you can remove all devices with the Alexa website and discover devices again.

If you accidentally remove a remove a real device asking Alexa to discover devices again will add it back
