### ISSUE TITLE
Homebridge-Alexa to ignore devices.

### ISSUE THREAD

**Issue by Silas888** [NorthernMan54/homebridge-alexa#351]
I was curious if there was a way to have homebridge-Alexa ignore certain devices￼. For example I have some door locks that I want to control ￼with HomeKit but not with Alexa. My thought is that there could be a way to list the device ids that you do NOT want￼￼ homebridge-Alexa to expose to Alexa. I know the current workaround is to simply disable the devices in the Alexa app but this suggestion would allow, in my opinion, for a cleaner execution.￼￼

**Comment by b2un0** [comment]
https://github.com/NorthernMan54/homebridge-alexa#known-issues
> Whitelisting/blacklisting
