### ISSUE TITLE
add donation links

### ISSUE THREAD

**Issue by b2un0** [NorthernMan54/homebridge-alexa#352]
hey,

you should add donation links to your project

https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Donation-Links

https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

**Comment by NorthernMan54** [comment]
I have thought about it, but so far the benefit of it doesn't outweigh the headache of managing it.   I do get a $100/Month of free Amazon AWS services as a result, which is great.
