### ISSUE TITLE
Your TV doesn't support that function

### ISSUE THREAD

**Issue by meluvalli** [NorthernMan54/homebridge-alexa#354]
I have a TV device setup in HomeBridge.  It's a not a true Apple TV, so it doesn't really support full functions.  So, I manually added switches for "HDMI 1" and "HDMI 2".   When I ask alexa to turn on "HDMI 1", it tells me my device can't support that.  However, I have physical switches named "HDMI 1" and "HDMI 2".  I looked in Alexa history and it says I said "turn on h.d.m.i one" so I tried renaming my device to "h.d.m.i. one" and get same result.  

This use to work, but I can't tell you when it last worked.  I am thinking maybe the "input controller" function maybe broke this?  Is this possible?

Is this even an issue with this plugin or Alexa itself?

**Comment by NorthernMan54** [comment]
Is homebridge-alexa recognizing your tv device as a TV ?  What plugin is it?

If homebridge-alexa is not recognizing your TV as a TV, and just plain switches then the funkiness is definitely an alexa issue.

If you share an accessory dump of your setup, then I can see what is going on better

**Comment by meluvalli** [comment]
I’m sorry, I should have updated this, 

I’m not sure what the problem was.  I ended up just redoing everything as I was just having all sorts of odd things happening.  

I have resolved it by starting fresh.  If it happens again, I’ll do a dump and creat new issue.  

Thanks for your time!
