### ISSUE TITLE
Motion sensor detected and show correct status in Alexa device list, but not show up in routines

### ISSUE THREAD

**Issue by mdelag** [NorthernMan54/homebridge-alexa#355]
Dummy sensor detected and connected to Alexa and Alexa App, able to view in "All Devices" and status updates when triggered from Homebridge. Dummy sensor not showing in "When this happens->Smart Home" when creating a new routine. Any clue?

![57130E07-2BA7-4E27-A096-3F3A14E8FE4A](https://user-images.githubusercontent.com/25717236/91278410-cd3a4b80-e749-11ea-9a49-e9d7a66f602f.png)
![9BB27051-24A2-4CED-B1B3-E6E75C030AF7](https://user-images.githubusercontent.com/25717236/91278413-ce6b7880-e749-11ea-89b1-cdc210976093.png)
![029A67AD-A065-45E1-96F7-15A5B47EFB04](https://user-images.githubusercontent.com/25717236/91278419-cf040f00-e749-11ea-8d78-d3312a0eea7e.png)

**Comment by NorthernMan54** [comment]
Did you enable routines in the homebridge-alexa config?

**Comment by mdelag** [comment]
Omg didn’t know you needed to add this config. Thank you! Got it working now.
