### ISSUE TITLE
homebridge-videodoorbell

### ISSUE THREAD

**Issue by leovj** [NorthernMan54/homebridge-alexa#357]
Hi I have install into my HOOBS homebridge-videodoorbell and my log say:
2/9/2020, 14:02:11 [Alexa] WARNING: Duplicate device name Camera Portone
2/9/2020, 14:02:11 [Alexa] WARNING: Duplicate device name Camera Portone
2/9/2020, 14:02:11 [Alexa] ERROR: Parsing failed, removing duplicate endpointID => Camera Portone
2/9/2020, 14:02:11 [Alexa] alexaDiscovery - returned 17 devices

Is there any way to resolve this conflict?
Thanks!

**Comment by NorthernMan54** [comment]
Answered on Discord
