### ISSUE TITLE
What are the security risks?

### ISSUE THREAD

**Issue by littlecharva** [NorthernMan54/homebridge-alexa#359]
First of all, thanks so much for putting so much effort into developing and maintaining such an awesome project, and for interacting with the users on here and their requests/demands!  It's thanks to generous people like yourself that we have such amazing toys!

It would be really useful if the README gave some basic details of how the connection with the homebridge.ca site and the Alexa works, and what risks there are around that.  What role does the site play?  When I issue a command to Alexa, does it go via the homebridge.ca site?  If hackers were to compromise the homebridge.ca site, would they then have access to control my devices?

If this information is already in there, then please accept my apologies, but I couldn't see it.

**Comment by NorthernMan54** [comment]
This question has been asked several times already, please review #122 and #196.  And if you have any further questions please let me know.

Keep in mind that anytime you expose yourself to the cloud you are increasing your risk.  Just having Alexa devices increases your risk profile, and any cloud based devices as well.  If you are considered about external attacks, you may not want to have an Alexa device.
