### ISSUE TITLE
This Version wont install on an Rpi

### ISSUE THREAD

**Issue by Pickowicko** [NorthernMan54/homebridge-alexa#36]
After uninstalling the normal homebridge and running

sudo npm install -g https://github.com/NorthernMan54/homebridge

there is an error and this log.

pi@raspberrypi:~/.homebridge $ sudo npm install -g https://github.com/NorthernMan54/homebridge
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/NorthernMan54/homebridge.git /root/.npm/_cacache/tmp/git-clone-60ac6462
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-60ac6462': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-03T19_05_47_420Z-debug.log

**Comment by NorthernMan54** [comment]
I found that this is a good work around

sudo su -

then proceed with the install

**Comment by Pickowicko** [comment]
I'll teat it later thanks

**Comment by Pickowicko** [comment]
Test*

**Comment by nixmeer** [comment]
I ran into a similar problem: 

npm ERR! code ENOGIT
npm ERR! No git binary found in $path

The workaround won’t work either. Pinged google, internet is up and running. Looked for spelling mistakes in the URL but couldn’t find any...

**Comment by Pickowicko** [comment]
Now it just tries to intall for a long time and outputs

gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/homebridge/node_modules/mdns/.node-gyp/8.9.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/homebridge/node_modules/mdns/.node-gyp"

over and over every 5 seconds. 

Any idea?

**Comment by Pickowicko** [comment]
I might just connected everything to open hab and use homebridge as a front end

**Comment by nixmeer** [comment]
I’ve had that exact same issue 10 minutes ago when trying to install nfarina‘s homebridge

**Comment by Pickowicko** [comment]
homebridge has been fine for me

**Comment by Pickowicko** [comment]
im goinf to try adding to --unsafe-perm flag because it is recommended in the homebridge guide

**Comment by Pickowicko** [comment]
looks like it worked so far

**Comment by Pickowicko** [comment]
Northern Man you might want to add the --unsafe-perm flag to your command to make it

sudo su -

sudo npm install -g --unsafe-perm  https://github.com/NorthernMan54/homebridge

that seems to have worked for me so far

**Comment by nixmeer** [comment]
Wow great thank you!!

Why is the Alexa support not implemented in nfarinas homebridge?

**Comment by Pickowicko** [comment]
not sure. BTW the  version that you install is an old one you ma need to updat it for plaugins to work

**Comment by Pickowicko** [comment]
Northernman can you perhaps create an updated version of homebridge alexa so thtat it is compatible with the latest plugins because some plugins require 0.4.33 and homebridge alexa is on 0.4.31

**Comment by Pickowicko** [comment]
currently it installs but i cannot use it because it is an older version

**Comment by nixmeer** [comment]
It’s an older version of nfarinas homebridge?

**Comment by nixmeer** [comment]
And could you please post the line you entered to install it?

**Comment by NorthernMan54** [comment]
@Pickowicko @nixmeer I'm in the process of merging the most recent changes to HAP-Nodejs and Homebridge, give me about an hour or two.  Once I have merged and brought it up to date, I will let you know.

**Comment by NorthernMan54** [comment]
@Pickowicko @nixmeer I have updated to the latest versions of both Homebridge ( 0.4.32 ) and HAP-NodeJS ( 0.4.36 ).

**Comment by Pickowicko** [comment]
thanks

**Comment by NorthernMan54** [comment]
@Pickowicko I just checked the Homebridge page, and as of right now it is 0.4.32.   Which plugin is this from?

**Comment by Pickowicko** [comment]
homebridge-hue says it needs 0.4.32. try running homebridge hue on this version. Is there some other incompatability?

**Comment by NorthernMan54** [comment]
@Pickowicko homebridge-hue has the wrong version.  They are saying 0.4.33, and homebridge is 0.4.32

**Comment by NorthernMan54** [comment]
I raised an issue against homebridge-hue https://github.com/ebaauw/homebridge-hue/issues/225

**Comment by Pickowicko** [comment]
i think  he github and nom version are different

**Comment by Pickowicko** [comment]
Have you managed to get it working?

**Comment by nixmeer** [comment]
I don’t know, I didn’t try Alexa yet. But it does not show the plugin when I launch homebridge.

**Comment by Pickowicko** [comment]
does homebridge -hue work?

**Comment by nixmeer** [comment]
I don’t use hue yet...

**Comment by Pickowicko** [comment]
can you try installing th plugin and see if it started homebridge or it gives you a version error

**Comment by nixmeer** [comment]
Yes I will tomorrow. When you start homebridge, does it say homebridge-alexa?

**Comment by Pickowicko** [comment]
yes but homebridge hue outputs that it should be version 2.4.33. I wonder if northern man hs updated it yet

**Comment by NorthernMan54** [comment]
@Pickowicko @nixmeer I just updated mine to 0.4.33

This is a bit odd, as the GitHub version of homebridge said 0.4.32 while the NPM version of homebridge said 0.4.33.  I have never seen that before.

**Comment by Pickowicko** [comment]
thanks dude
