### ISSUE TITLE
homebridge-alexa v0.4.74

### ISSUE THREAD

**Issue by Silas888** [NorthernMan54/homebridge-alexa#363]
Hi Question. After the last homebridge-alexa  update to v0.4.74 I appear to have a duplicate of every device in my Alexa app. The only difference is in the description section of the device it will read "Homebridge 6CGB Closet Light." The "6GCB" being the unique name of my HomeBridge instance. The new copy of the same device will read in it's description: "Homebridge Closet Light" with the "6GCB" now being absent but yet I assume unique enough for Alexa to think its a different device. Is there any way to repair this? I have several hundred smart home devices many of which are connected to routines. Its not feasible for me to rename and reassign all of these new devices to replace the same devices with a slightly different description.

Thanks in advance.

**Comment by NorthernMan54** [comment]
Please see #361
