### ISSUE TITLE
Sensors will no longer trigger routines

### ISSUE THREAD

**Issue by lukeredpath** [NorthernMan54/homebridge-alexa#364]
I've been having some trouble with some sensors that I was using to trigger some routines no longer working. 

I'm running Homebridge 1.2.2 and the latest Homebridge-Alexa plug-in. The routine support is enabled for the plugin. 

I have two sensors configured in Domoticz and exposed using the Homebridge-Domoticz plugin - a LightwaveRF contact sensor and a dummy open/close sensor that is triggered as open when my 433mhz door bell rings and automatically resets to closed after a few seconds. 

I can see both of these sensors in the Alexa app and both update as expected when I ring the doorbell or open and close the door. Both of these also appear in the Apple Home app and are triggered correctly there too so there doesn't seem to be any problems from Domoticz all the way through to HomeKit or the Echo platform. 

The problem is these sensors will not trigger any routines configured in the Alexa app. They used to work fine. I have tried both sensors to trigger a simple announcement when they are opened. However they just will not trigger even though Alexa sees the sensors open. 

I don't know if this is related but there's a recent thread on Reddit where people are having similar issues with SmartThings sensors not triggering routines either:

https://www.reddit.com/r/SmartThings/comments/ia1i2q/alexa_routines_now_broken_because_of_st_update/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by NorthernMan54** [comment]
Your issue is likely this #361 if you have updated to the latest Homebridge.  I had a similar issue

**Comment by lukeredpath** [comment]
I don't think that's the issue. I did end up with duplicates after updating Homebridge but have already gone through the process of deleting all of my Homebridge devices in the Alexa app and rediscovering them.

**Comment by NorthernMan54** [comment]
Do you have routines true in the config.json ?

**Comment by lukeredpath** [comment]
Yes, it's been enabled since I started using the plugin and it used to work fine. 

It hasn't actually worked since July but that was due to Alexa not receiving sensor events from some reason, I think I had some issue with my Homebridge setup. 

I've spent today trying to fix this, firstly by updating Homebridge and the outdated plugins, then after running into the duplicate device issue I removed all of my devices in Alexa, reinstalled the skill and rescanned for devices. As I said the Alexa sensor is now correctly receiving updates it just won't trigger any routines.

**Comment by lukeredpath** [comment]
Another post with the same symptoms but with SmartThings devices. It seems in this case the bug was in the SmartThings skill itself - could Amazon have changed something recently about how skills work with routines?

https://www.reddit.com/r/SmartThings/comments/itm8zp/alexa_routines_randomly_stopped_working/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by NorthernMan54** [comment]
I looked at the backend logs and your implementation has **not** transmitted any event messages in the last 30 minutes ;-(

Have you triggered any of your sensors ?

To take this further, please share a DEBUG log, details are in the README and include the triggering of a sensor.

PS In the last 30 minutes the backend has processed 2300 sensor event messages, and don't have any lingering issues in regards to events

**Comment by lukeredpath** [comment]
The last test I ran was at 3.49pm BST although I ran plenty of tests in the hour prior to that. I will try and get some debug logs.

**Comment by NorthernMan54** [comment]
Also you should see the last event message received update when the events are sent. This is on the homebridge.ca website


![98D17ACD-DA0B-4DEF-91AF-E4F5EC5549FF](https://user-images.githubusercontent.com/19808920/93717697-8c193980-fb45-11ea-8996-b71e1fcf9bc2.png)

**Comment by lukeredpath** [comment]
Ah, that's useful. Sorry I haven't managed to get the debug logs yet but I can see that it hasn't received a sensor event since mid July which corresponds with when I stopped receiving my doorbell alerts. 

What's a good way to debug this besides the logs? If I've enabled the routines setting, it used to work and Alexa is at least receiving device state updates and commands are working fine, what is the most likely cause of events not being sent?

**Comment by NorthernMan54** [comment]
First is the routines setting, then restarting the plugin should enable the transmission of events.  I’m expecting to see some errors in the debug Log pointing out the issue.

**Comment by lukeredpath** [comment]
Thanks for the pointers. Right, I'm running it in debug mode and I'm seeing this repeatedly:

```
  alexaActions alexaDiscovery +5s
[9/21/2020, 19:09:59] [Alexa] ERROR: HAP Discovery failed, please review config
  alexaActions registerEvents [] +0ms
```

The docs indicate this could be related to having a Hue bridge but I've disabled the Hue plugin and still get the same output.

**Comment by NorthernMan54** [comment]
You definitely have something going on with your setup as that section of the log should have a lot more detail.  This is a fragment from mine

```
[9/21/2020, 20:37:08] [Alexa] WARNING: Duplicate device name Front Porch
[9/21/2020, 20:37:08] [Alexa] ERROR: Parsing failed, removing duplicate endpointID => Vacant Porch
[9/21/2020, 20:37:08] [Alexa] alexaDiscovery - returned 85 devices
2020-09-22T00:37:08.093Z alexaActions registerEvents [
  '{"deviceID":"00:0c:c2:34:50:0c:bc:c3","aid":6,"iid":10}': {
    '0': 'NOT_DETECTED',
    '1': 'DETECTED',
    endpointID: 'MDA6MGM6YzI6MzQ6NTA6MGM6YmM6YzMtU2hlbGRvbi1Ob2RlUmVkLU5vZGUtUmVkLVdhc2hlciBJbiBVc2UtMDAwMDAwODAtMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx',
    template: 'ContactSensor'
  },

```

And what's important here is the line with registerEvents, as that is a list of your event capable devices, and yours is empty.

Have you made any changes to your setup around when it stopped working?  It appears that homebridge instance discovery is failing in your setup, and things are only continuing to work because Alexa remembers them all.   The log prior to the fragment you shared should show the discovery of each instance.

**Comment by lukeredpath** [comment]
Well I'm completely stumped. I went and wiped all of my devices from my Echo account and completely reset my Homebridge setup, cleared out all cached accessories etc. and started from scratch, and it still doesn't work. My log is also full of `[Alexa] ERROR: HAP Discovery failed, please review config` errors if that's relevant.

**Comment by lukeredpath** [comment]
Just enable debug logs again and I am seeing this - I'm not sure if it's from the Alexa plugin or the Homebridge UI plugin:

```
2020-09-24T20:16:10.534Z hapNodeJSClient Starting Homebridge instance discovery
2020-09-24T20:16:10.639Z hapNodeJSClient HAP Device discovered TRADFRI gateway
2020-09-24T20:16:10.639Z hapNodeJSClient HAP Device address TRADFRI gateway ->  {
  host: '192.168.1.161',
  port: 80,
  url: 'http://192.168.1.161:80',
  deviceID: '49:1D:B6:7A:A4:43',
  txt: {
    'c#': '23',
    ff: '1',
    id: '49:1D:B6:7A:A4:43',
    md: 'TRADFRI gateway',
    pv: '1.1',
    's#': '1',
    sf: '0',
    ci: '2',
    sh: 'lnM8mw=='
  }
}
2020-09-24T20:16:10.648Z hapNodeJSClient HAP Discover failed TRADFRI gateway -> http://192.168.1.161:80 invalid PIN or homebridge is not running in insecure mode with -I
2020-09-24T20:16:10.651Z hapNodeJSClient HAP Device discovered Homebridge 7F20
2020-09-24T20:16:10.651Z hapNodeJSClient HAP Device address Homebridge 7F20 ->  {
  host: '192.168.1.2',
  port: 51826,
  url: 'http://192.168.1.2:51826',
  deviceID: '0E:26:7F:11:51:61',
  txt: {
    'c#': '4',
    ff: '0',
    id: '0E:26:7F:11:51:61',
    md: 'homebridge',
    pv: '1.1',
    's#': '1',
    sf: '0',
    ci: '2',
    sh: 'mepHCQ=='
  }
}
2020-09-24T20:16:10.666Z hapNodeJSClient Homebridge instance discovered homebridge with 23 accessories
```

Could the Alexa plugin be picking up the TRADFRI gateway instead of Homebridge for some reason?

What confuses me is that the Echo app is showing all of the homebridge devices after running device discovery.

**Comment by NorthernMan54** [comment]
The plugin is using the HomeKit accessory discovery routine so it finds all your HomeKit devices, but it will have an error with them due to HomeKit encryption.  So this is expected if you have HomeKit devices and can be ignored.

Is everything working now?

**Comment by lukeredpath** [comment]
Everything except for routines still unfortunately. It's just not sending any events.

**Comment by NorthernMan54** [comment]
Can you share a debug log again, am looking for the line with register events.   Similar to my log from earlier
