### ISSUE TITLE
Alexa doesn’t discover any devices

### ISSUE THREAD

**Issue by ursusHU** [NorthernMan54/homebridge-alexa#365]
Just upgraded Homebridge to version 1.2.2 and node.js to  12.18.4. After that everything coming from the plugin appeared duplicated, and Alexa was not able to discover new devices. Before that it was working perfectly.
I already reinstalled the plugin, deleted Alexa from my phone, and reinstalled it linked the Homebridge skill however I can’t make Alexa to find any device. The plugin states 129 devices.
Any idea what is wrong? Thank you!

**Comment by NorthernMan54** [comment]
On the homebridge.ca website what does your account status show ?

![4FE385CC-F7BD-4D24-9E23-AD71C6260AA4](https://user-images.githubusercontent.com/19808920/93717682-655b0300-fb45-11ea-9f56-f0b47771a818.png)

**Comment by ursusHU** [comment]
Thanks for the fast response. Everything is green.

![ABBB2022-C3BA-4E14-B766-8B16C0589DC3](https://user-images.githubusercontent.com/61931127/93718808-b6d3b400-fb7e-11ea-8535-ea0434620057.png)

**Comment by ursusHU** [comment]
That’s weird, the times are definitely earlier than I last tried

**Comment by NorthernMan54** [comment]
And if you ask Alexa to discover devices does that work?

**Comment by ursusHU** [comment]
Yes, but it says it couldn’t find any new smart home devices. And nothing appears.

When I ask to discover devices in HB log I can immediately see: alexaDiscovery - returned 128 devices.

**Comment by NorthernMan54** [comment]
Let me take a look at the backend logs.  I presume your github id  is similar to homebridge.ca, if not I will need you id to find your logs.

**Comment by ursusHU** [comment]
In the meantime I found something interesting. I rebranded one of my devices in the HB config. Eg from LG tv to Bedroom Tv and Alexa found it.

**Comment by ursusHU** [comment]
Ursus_HU

**Comment by ursusHU** [comment]
I don’t know, if you have made some modification, but now I see every device again in Alexa. 
Thank you very much for your help and time! 
Great plugin with great support!

**Comment by NorthernMan54** [comment]
Nothing on my side as I have out of the house all afternoon
