### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by skirkpatrick1979** [NorthernMan54/homebridge-alexa#37]
I have tried a few times to install this, I keep getting the following errors after the sudo npm install command.  

sudo npm install -g https://github.com/NorthernMan54/homebridge
npm ERR! not a package /tmp/npm-1363-b3H3MehG/github.com/NorthernMan54/homebridge
npm ERR! Error: ENOENT: no such file or directory, open '/tmp/npm-1363-b3H3MehG/github.com/NorthernMan54/homebridge-unpack/package.json'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.41-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "https://github.com/NorthernMan54/homebridge"
npm ERR! cwd /tmp
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! path /tmp/npm-1363-b3H3MehG/github.com/NorthernMan54/homebridge-unpack/package.json
npm ERR! syscall open
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/npm-debug.log
npm ERR! not ok code 0
pi@mnop:/tmp $ cd /tmp/npm-1363-b3H3MehG/github.com/NorthernMan54/homebridge
-bash: cd: /tmp/npm-1363-b3H3MehG/github.com/NorthernMan54/homebridge: Not a directory
pi@mnop:/tmp $ cd /tmp/npm-1363-b3H3MehG/github.com/NorthernMan54/

**Comment by NorthernMan54** [comment]
Your versions of NPM and NODE are really old and out of date.   You need to update these and try again.  Personally I use the LTS versions.

**Comment by skirkpatrick1979** [comment]
Thanks.  Got passed and now this.

sudo npm install -g --unsafe-perm https://github.com/NorthernMan54/homebridge
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/NorthernMan54/homebridge.git /root/.npm/_cacache/tmp/git-clone-d33daef1
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-d33daef1': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-12T13_50_04_397Z-debug.log

**Comment by skirkpatrick1979** [comment]
I figured it out.  There is an issue with the latest npm version.  downgraded to 4.6.0 and it worked
