### ISSUE TITLE
 WARNING: Duplicate device name 

### ISSUE THREAD

**Issue by giannimp** [NorthernMan54/homebridge-alexa#371]
8/10/2020, 17:22:20 [Alexa] WARNING: Duplicate device name Balcone Cucina
8/10/2020, 17:22:20 [Alexa] WARNING: Duplicate device name Balcone Camera
8/10/2020, 17:22:20 [Alexa] WARNING: Duplicate device name Balcone Ciro Motion Trigger
8/10/2020, 17:22:20 [Alexa] WARNING: Duplicate device name Cam Cucina Motion Trigger
8/10/2020, 17:22:20 [Alexa] WARNING: Duplicate device name Fuori porta
8/10/2020, 17:22:20 [Alexa] alexaDiscovery - returned 85 devices
with: Alexa
0.5.12 Pubblicato 10/7/2020
and ffmpeg:
Camera FFMPEG
3.0.3 Pubblicato 9/3/2020
hoobs rpi 3b+
Help me please

**Comment by NorthernMan54** [comment]
Duplicate names are just a warning and can be ignored

**Comment by giannimp** [comment]
> Duplicate names are just a warning and can be ignored
> […](#)
> On Oct 8, 2020, at 11:34 AM, giannimp ***@***.***> wrote: ﻿ 8/10/2020, 17:22:20 [Alexa] WARNING: Duplicate device name Balcone Cucina 8/10/2020, 17:22:20 [Alexa] WARNING: Duplicate device name Balcone Camera 8/10/2020, 17:22:20 [Alexa] WARNING: Duplicate device name Balcone Ciro Motion Trigger 8/10/2020, 17:22:20 [Alexa] WARNING: Duplicate device name Cam Cucina Motion Trigger 8/10/2020, 17:22:20 [Alexa] WARNING: Duplicate device name Fuori porta 8/10/2020, 17:22:20 [Alexa] alexaDiscovery - returned 85 devices with: Alexa 0.5.12 Pubblicato 10/7/2020 and ffmpeg: Camera FFMPEG 3.0.3 Pubblicato 9/3/2020 hoobs rpi 3b+ Help me please — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you!
