### ISSUE TITLE
Change of channel with Sony Bravia TV (Android TV)

### ISSUE THREAD

**Issue by dcaccount** [NorthernMan54/homebridge-alexa#372]
Hello,
I have installed Sony Bravia TV (Android TV) plugin and it is working.

But I cannot change the channel with your plugin. Is it possible and how?

Can you please help?
Thanks,
Dan

**Comment by NorthernMan54** [comment]
As HomeKit doesn't have a channel change interface as part of the TV Accessory it isn't fully supported.  To workaround that gap, I had added my TV Channels as an Input selection on my LG TV Plugin ( this is 100% custom and not published plugin ).  I use OTA TV, and only have about 25 channels.  It kinda works, but Alexa is a but brain dead some days, and reminds me that I don't have video skill enabled.

With a TV Accessory Alexa while respond to the change channel commands and attempt to switch to an input that matches.  If you watch the log while attempting the command you can see how she interprets your channel wording and it needs to be an exact match to the input.  ( Homebridge-alexa also strips the string 'Station -' from the input name as well, as I had added it to the input name to make it look better in the Home app ).

My TV Accessory Inputs

![IMG_5054](https://user-images.githubusercontent.com/19808920/96390221-9ac53180-1181-11eb-8c3c-59fbb9b52445.PNG)
