### ISSUE TITLE
Routine executed twice ?

### ISSUE THREAD

**Issue by Pblondin123** [NorthernMan54/homebridge-alexa#374]
Hi, since about a week i get events that execute once in HB (i checked the logs), but the motion activated sensor routine gets executed twice.   My routine just sends an annoncement (which is said twice).   Not sure how to troubleshoot.  Thanks

**Comment by NorthernMan54** [comment]
If you run the plugin in DEBUG mode

https://github.com/NorthernMan54/homebridge-alexa#debug

It logs a lot of detail about what is going on between the plugin and the backend.  You should be able to see if 2 messages are being sent with that level of logging enabled

**Comment by Pblondin123** [comment]
turned on debug - saw single events sent, but!  as of now i get single announcements back off Alexa.  Not sure what happened but issue solved thanks !

**Comment by Pblondin123** [comment]
debug on got back single announcements (after HB restart) turned off debug and back to normal not sure what happened but problem solved !  tnks

**Comment by Martin-Palringo** [comment]
I've had this problem consistently for the last 14 days. Unfortunately for me it hasn't gone away.

I've enabled debug, and believe I've captured the relevant logs:

`2020-10-23T14:42:18.882Z hapNodeJSClient Events [{"host":"127.0.0.1","port":51826,"deviceID":"CD:22:3D:E3:CE:12","aid":27,"iid":23,"value":0,"status":0}]
2020-10-23T14:42:18.883Z alexaActions Events [{"host":"127.0.0.1","port":51826,"deviceID":"CD:22:3D:E3:CE:12","aid":27,"iid":23,"value":0,"status":0}]
2020-10-23T14:42:18.908Z hapNodeJSClient Events [{"host":"192.168.68.200","port":51826,"deviceID":"CD:22:3D:E3:CE:12","aid":27,"iid":23,"value":0,"status":0}]
2020-10-23T14:42:18.908Z alexaActions Events [{"host":"192.168.68.200","port":51826,"deviceID":"CD:22:3D:E3:CE:12","aid":27,"iid":23,"value":0,"status":0}]`

@NorthernMan54 am I correct in believing the issue is the event triggering twice, once from 127.0.0.1 and once from 192.168.68.200 (the same device)?

**Comment by Pblondin123** [comment]
just wanted to inform my problem is back as well

**Comment by NorthernMan54** [comment]
@Martin-Palringo You are correct

Question is how did that happen.  Recycling homebridge-alexa should clear it up, but what is triggering it.   Does the initial discovery process indicate duplicates?  Also the event subscriptions are included in the debug output after discovery.

The event model works like this

homebridge-alexa as part of the discovery process determines which devices it needs to be notified about in regards to events ( contact and motion sensors ), it then creates the event subscription to the homebridge instance with the device.  As recycling homebridge breaks the event subscription, it recreates them about 15 minutes later.

I'm wondering if its the initial event subscription, or the recreate process.

**Comment by ZoneMR** [comment]
Thanks - picking this up on the correct account!

It seems the initial discovery process finds the local homebridge instance on 127.0.0.1:

`2020-10-23T15:37:43.745Z hapNodeJSClient HAP Device address Homebridge ACB1 ->  {
  host: '127.0.0.1',
  port: 51826,
  url: 'http://127.0.0.1:51826',
  deviceID: 'CD:22:3D:E3:CE:12',
  txt: {
    'c#': '258',
    ff: '0',
    id: 'CD:22:3D:E3:CE:12',
    md: 'homebridge',
    pv: '1.1',
    's#': '1',
    sf: '0',
    ci: '2',
    sh: '2EOeRw=='
  }
}
2020-10-23T15:37:44.143Z hapNodeJSClient Homebridge instance discovered homebridge with 14 accessories`

Subsequent alexaDiscovery actions find the same homebridge instance via the LAN IP 192.168.68.200:

`2020-10-23T15:12:52.158Z hapNodeJSClient HAP Device address Homebridge ACB1 ->  {
  host: '192.168.68.200',
  port: 51826,
  url: 'http://192.168.68.200:51826',
  deviceID: 'CD:22:3D:E3:CE:12',
  txt: {
    'c#': '255',
    ff: '0',
    id: 'CD:22:3D:E3:CE:12',
    md: 'homebridge',
    pv: '1.1',
    's#': '1',
    sf: '0',
    ci: '2',
    sh: '2EOeRw=='
  }
}
2020-10-23T15:12:52.206Z hapNodeJSClient Homebridge instance discovered homebridge with 14 accessories`

It looks like devices in Alexa aren't duplicated, but routine events are - consistently...

Please let me know if any further log excerpts would be helpful.

**Comment by NorthernMan54** [comment]
Tks that helps

**Comment by NorthernMan54** [comment]
Looking at this further, can you share the 'register events' out in DEBUG mode just after startup of the plugin.  It is a bit long, but what I'm trying to determine is where the duplicate item is coming from.

From my setup it looks like this

```
 alexaActions registerEvents [
  '{"deviceID":"AC:22:3D:E3:CE:31","aid":2,"iid":10}': {
    endpointID: 'QUM6MjI6M0Q6RTM6Q0U6MzEtTGVvbmFyZC1BbWF6b24taG9tZWJyaWRnZS1ydGxfNDMzLUZyb250IFBvcmNoLTAwMDAwMDg1LTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==',
    true: 'DETECTED',
    false: 'NOT_DETECTED',
    template: 'MotionSensor'
  },
  '{"deviceID":"AC:22:3D:E3:CE:31","aid":40,"iid":10}': {
    endpointID: 'QUM6MjI6M0Q6RTM6Q0U6MzEtTGVvbmFyZC1BbWF6b24taG9tZWJyaWRnZS1ydGxfNDMzLURyaXZld2F5LTAwMDAwMDg1LTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==',
    true: 'DETECTED',
    false: 'NOT_DETECTED',
    template: 'MotionSensor'
  },
  '{"deviceID":"AC:22:3D:E3:CE:31","aid":41,"iid":38}': {
    '0': 'NOT_DETECTED',
    '1': 'DETECTED',
    endpointID: 'QUM6MjI6M0Q6RTM6Q0U6MzEtTGVvbmFyZC1BbWF6b24taG9tZWJyaWRnZS1ydGxfNDMzLUZyaWRnZSBBbGFybS0wMDAwMDA4MC0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=',
    template: 'ContactSensor'
  },
  '{"deviceID":"AC:22:3D:E3:CE:31","aid":44,"iid":20}': {
    '0': 'NOT_DETECTED',
    '1': 'DETECTED',
    endpointID: 'QUM6MjI6M0Q6RTM6Q0U6MzEtTGVvbmFyZC1BbWF6b24taG9tZWJyaWRnZS1ydGxfNDMzLUNoZXN0IEZyZWV6ZXIgQWxhcm0tMDAwMDAwODAtMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx',
    template: 'ContactSensor'
  },
  '{"deviceID":"AC:22:3D:E3:CE:31","aid":42,"iid":39}': {
    '0': 'NOT_DETECTED',
    '1': 'DETECTED',
    endpointID: 'QUM6MjI6M0Q6RTM6Q0U6MzEtTGVvbmFyZC1BbWF6b24taG9tZWJyaWRnZS1ydGxfNDMzLUZyZWV6ZXIgQWxhcm0tMDAwMDAwODAtMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx',
    template: 'ContactSensor'
  },
  '{"deviceID":"AC:22:3D:E3:CE:31","aid":7,"iid":13}': {
    '0': 'NOT_DETECTED',
    '1': 'DETECTED',
    endpointID: 'QUM6MjI6M0Q6RTM6Q0U6MzEtTGVvbmFyZC1BbWF6b24tRGVmYXVsdC1NYW51ZmFjdHVyZXItU2Vhbi0wMDAwMDA4MC0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=',
    template: 'ContactSensor'
  },
  '{"deviceID":"AC:22:3D:E3:CE:31","aid":8,"iid":13}': {
    '0': 'NOT_DETECTED',
    '1': 'DETECTED',
    endpointID: 'QUM6MjI6M0Q6RTM6Q0U6MzEtTGVvbmFyZC1BbWF6b24tRGVmYXVsdC1NYW51ZmFjdHVyZXItQWxpY2UtMDAwMDAwODAtMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx',
    template: 'ContactSensor'
  },
  '{"deviceID":"AC:22:3D:E3:CE:31","aid":43,"iid":16}': {
    '0': 'DETECTED',
    '1': 'NOT_DETECTED',
    endpointID: 'QUM6MjI6M0Q6RTM6Q0U6MzEtTGVvbmFyZC1BbWF6b24tV1NTRU5TT1ItR2FyYWdlIERvb3ItMDAwMDAwNDEtMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx',
    template: 'ContactSensor'
  },
  '{"deviceID":"AC:22:3D:E3:CE:30","aid":54,"iid":10}': {
    '0': 'NOT_DETECTED',
    '1': 'DETECTED',
    endpointID: 'QUM6MjI6M0Q6RTM6Q0U6MzAtTGVvbmFyZC1EZXYtaG9tZWJyaWRnZS1hbGV4YS1BbGV4YS0wMDAwMDA4MC0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=',
    template: 'ContactSensor'
  },
  '{"deviceID":"AC:22:3D:E3:CE:30","aid":249,"iid":25}': {
    endpointID: 'QUM6MjI6M0Q6RTM6Q0U6MzAtTGVvbmFyZC1EZXYtVGFzbW90YS1UZXN0IE1vdGlvbiBTd2l0Y2gxLTAwMDAwMDg1LTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==',
    true: 'DETECTED',
    false: 'NOT_DETECTED',
    template: 'MotionSensor'
  },
  '{"deviceID":"76:59:CE:25:B9:6E","aid":1,"iid":13}': {
    endpointID: 'NzY6NTk6Q0U6MjU6Qjk6NkUtV3l6ZSBDYW0gVjItY2FtZXJhLWZmbXBlZy1Gcm9udCBQb3JjaCAtIER1bW15LTAwMDAwMDg1LTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==',
    true: 'DETECTED',
    false: 'NOT_DETECTED',
    template: 'MotionSensor'
  },
  '{"deviceID":"C8:57:48:7C:2A:0C","aid":1,"iid":41}': {
    endpointID: 'Qzg6NTc6NDg6N0M6MkE6MEMtRXVmeSBDYW0gMksgRG9vcmJlbGwtY2FtZXJhLWZmbXBlZy1UZXN0IENhbWVyYSAtIER1bW15LTAwMDAwMDg1LTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==',
    true: 'DETECTED',
    false: 'NOT_DETECTED',
    template: 'MotionSensor'
  },
  '{"deviceID":"E3:B1:EB:AE:38:60","aid":1,"iid":10}': {
    '0': 'NOT_DETECTED',
    '1': 'DETECTED',
    endpointID: 'RTM6QjE6RUI6QUU6Mzg6NjAtV3l6ZSBDYW0gVjIgRG9vcmJlbGwtY2FtZXJhLWZmbXBlZy1Gcm9udCBEb29yYmVsbC0wMDAwMDEyMS0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=',
    template: 'DoorbellEventSource'
  },
  '{"deviceID":"8D:28:76:62:4B:1F","aid":1,"iid":13}': {
    endpointID: 'OEQ6Mjg6NzY6NjI6NEI6MUYtV3l6ZSBDYW0gVjItY2FtZXJhLWZmbXBlZy1Ecml2ZXdheSAtIER1bW15LTAwMDAwMDg1LTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==',
    true: 'DETECTED',
    false: 'NOT_DETECTED',
    template: 'MotionSensor'
  },
  '{"deviceID":"BC:22:3D:E3:CE:31","aid":2,"iid":10}': {
    '0': 'NOT_DETECTED',
    '1': 'DETECTED',
    endpointID: 'QkM6MjI6M0Q6RTM6Q0U6MzEtaG9tZWJyaWRnZS1ob21lYnJpZGdlLWFsZXhhLUFsZXhhLTAwMDAwMDgwLTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==',
    template: 'ContactSensor'
  },
  '{"deviceID":"00:0c:c2:34:50:0c:bc:c3","aid":6,"iid":10}': {
    '0': 'NOT_DETECTED',
    '1': 'DETECTED',
    endpointID: 'MDA6MGM6YzI6MzQ6NTA6MGM6YmM6YzMtU2hlbGRvbi1Ob2RlUmVkLU5vZGUtUmVkLVdhc2hlciBJbiBVc2UtMDAwMDAwODAtMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx',
    template: 'ContactSensor'
  },
  '{"deviceID":"00:0c:c2:34:50:0c:bc:c3","aid":7,"iid":10}': {
    '0': 'NOT_DETECTED',
    '1': 'DETECTED',
    endpointID: 'MDA6MGM6YzI6MzQ6NTA6MGM6YmM6YzMtU2hlbGRvbi1Ob2RlUmVkLU5vZGUtUmVkLURyeWVyIEluIFVzZS0wMDAwMDA4MC0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=',
    template: 'ContactSensor'
  },
  '{"deviceID":"00:0c:c2:34:50:0c:bc:c3","aid":10,"iid":10}': {
    '0': 'NOT_DETECTED',
    '1': 'DETECTED',
    endpointID: 'MDA6MGM6YzI6MzQ6NTA6MGM6YmM6YzMtU2hlbGRvbi1Ob2RlUmVkLU5vcnRoZXJuTWFuNTQtRG9vcmJlbGwtMDAwMDAwODAtMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx',
    template: 'ContactSensor'
  },
  '{"deviceID":"00:01:50:40:03:02:e7:72","aid":5,"iid":10}': {
    '0': 'NOT_DETECTED',
    '1': 'DETECTED',
    endpointID: 'MDA6MDE6NTA6NDA6MDM6MDI6ZTc6NzItTGVvbmFyZC1Ob2RlUmVkLURlZmF1bHQgTWFudWZhY3R1cmVyLUdhcmFnZSBPcGVuLTAwMDAwMDgwLTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==',
    template: 'ContactSensor'
  }
] +1ms
  alexaActions Event Register AC:22:3D:E3:CE:31 -> {
  characteristics: [
    { aid: 2, iid: 10, ev: true },
    { aid: 40, iid: 10, ev: true },
    { aid: 41, iid: 38, ev: true },
    { aid: 44, iid: 20, ev: true },
    { aid: 42, iid: 39, ev: true },
    { aid: 7, iid: 13, ev: true },
    { aid: 8, iid: 13, ev: true },
    { aid: 43, iid: 16, ev: true }
  ]
} +2ms
  alexaActions Event Register AC:22:3D:E3:CE:30 -> {
  characteristics: [ { aid: 54, iid: 10, ev: true }, { aid: 249, iid: 25, ev: true } ]
} +6ms
  alexaActions Event Register 76:59:CE:25:B9:6E -> { characteristics: [ { aid: 1, iid: 13, ev: true } ] } +1ms
  alexaActions Event Register C8:57:48:7C:2A:0C -> { characteristics: [ { aid: 1, iid: 41, ev: true } ] } +0ms
  alexaActions Event Register E3:B1:EB:AE:38:60 -> { characteristics: [ { aid: 1, iid: 10, ev: true } ] } +1ms
  alexaActions Event Register 8D:28:76:62:4B:1F -> { characteristics: [ { aid: 1, iid: 13, ev: true } ] } +0ms
  alexaActions Event Register BC:22:3D:E3:CE:31 -> { characteristics: [ { aid: 2, iid: 10, ev: true } ] } +0ms
  alexaActions Event Register 00:0c:c2:34:50:0c:bc:c3 -> {
  characteristics: [
    { aid: 6, iid: 10, ev: true },
    { aid: 7, iid: 10, ev: true },
    { aid: 10, iid: 10, ev: true }
  ]
} +1ms
  alexaActions Event Register 00:01:50:40:03:02:e7:72 -> { characteristics: [ { aid: 5, iid: 10, ev: true } ] } +0ms
  ```

**Comment by ZoneMR** [comment]
Sure, I've included this below. Thanks for looking into this - you may wish to re-open the ticket.

`2020-10-25T21:44:09.970Z alexaActions registerEvents [
  '{"deviceID":"CD:22:3D:E3:CE:12","aid":23,"iid":10}': {
    '0': 'NOT_DETECTED',
    '1': 'DETECTED',
    endpointID: 'Q0Q6MjI6M0Q6RTM6Q0U6MTItaG9tZWJyaWRnZS1ob21lYnJpZGdlLWFsZXhhLUFsZXhhLTAwMDAwMDgwLTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==',
    template: 'ContactSensor'
  },
  '{"deviceID":"CD:22:3D:E3:CE:12","aid":12,"iid":9}': {
    '0': 'DETECTED',
    '1': 'NOT_DETECTED',
    endpointID: 'Q0Q6MjI6M0Q6RTM6Q0U6MTItaG9tZWJyaWRnZS1EZWZhdWx0LU1hbnVmYWN0dXJlci1HYXJhZ2UgUmlnaHQgRG9vci0wMDAwMDA0MS0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=',
    template: 'ContactSensor'
  },
  '{"deviceID":"CD:22:3D:E3:CE:12","aid":4,"iid":9}': {
    '0': 'DETECTED',
    '1': 'NOT_DETECTED',
    endpointID: 'Q0Q6MjI6M0Q6RTM6Q0U6MTItaG9tZWJyaWRnZS1EZWZhdWx0LU1hbnVmYWN0dXJlci1HYXJhZ2UgTGVmdCBEb29yLTAwMDAwMDQxLTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==',
    template: 'ContactSensor'
  },
  '{"deviceID":"CD:22:3D:E3:CE:12","aid":27,"iid":23}': {
    '0': 'NOT_DETECTED',
    '1': 'DETECTED',
    endpointID: 'Q0Q6MjI6M0Q6RTM6Q0U6MTItaG9tZWJyaWRnZS1JVEVBRC1MYXVuZHJ5IEN5Y2xlLTAwMDAwMDgwLTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==',
    template: 'ContactSensor'
  },
  '{"deviceID":"CD:22:3D:E3:CE:12","aid":19,"iid":32}': {
    endpointID: 'Q0Q6MjI6M0Q6RTM6Q0U6MTItaG9tZWJyaWRnZS1SaW5nLUZyb250IERvb3IgKFdlc3Rlcm4gV2F5KS0wMDAwMDA4NS0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=',
    true: 'DETECTED',
    false: 'NOT_DETECTED',
    template: 'MotionSensor'
  },
  '{"deviceID":"CD:22:3D:E3:CE:12","aid":19,"iid":35}': {
    '0': 'NOT_DETECTED',
    '1': 'DETECTED',
    endpointID: 'Q0Q6MjI6M0Q6RTM6Q0U6MTItaG9tZWJyaWRnZS1SaW5nLUZyb250IERvb3IgKFdlc3Rlcm4gV2F5KS0wMDAwMDEyMS0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=',
    template: 'DoorbellEventSource'
  },
  '{"deviceID":"CD:22:3D:E3:CE:12","aid":30,"iid":32}': {
    endpointID: 'Q0Q6MjI6M0Q6RTM6Q0U6MTItaG9tZWJyaWRnZS1SaW5nLURyaXZld2F5LTAwMDAwMDg1LTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==',
    true: 'DETECTED',
    false: 'NOT_DETECTED',
    template: 'MotionSensor'
  },
  '{"deviceID":"CD:22:3D:E3:CE:12","aid":31,"iid":32}': {
    endpointID: 'Q0Q6MjI6M0Q6RTM6Q0U6MTItaG9tZWJyaWRnZS1SaW5nLVdhbGt3YXktMDAwMDAwODUtMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx',
    true: 'DETECTED',
    false: 'NOT_DETECTED',
    template: 'MotionSensor'
  }
]
2020-10-25T21:44:09.977Z alexaActions Event Register CD:22:3D:E3:CE:12 -> {
  characteristics: [
    { aid: 23, iid: 10, ev: true },
    { aid: 12, iid: 9, ev: true },
    { aid: 4, iid: 9, ev: true },
    { aid: 27, iid: 23, ev: true },
    { aid: 19, iid: 32, ev: true },
    { aid: 19, iid: 35, ev: true },
    { aid: 30, iid: 32, ev: true },
    { aid: 31, iid: 32, ev: true }
  ]
}`

**Comment by NorthernMan54** [comment]
I think I have nailed this, please update to the latest version ( 0.5.16 ) and see how it goes.

**Comment by ZoneMR** [comment]
Thanks - so far so good here 👍

**Comment by Pblondin123** [comment]
Yes same here, looking good
