### ISSUE TITLE
Need ability to change password/delete accounts

### ISSUE THREAD

**Issue by mrkita** [NorthernMan54/homebridge-alexa#375]
From a security perspective, I think this would be pretty important. For instance when I first created an account I wasn't really sure how it worked, and if I would want it. I uninstalled the plugin, and then a week later decided to try it again.

I forgot my password (or wasn't sure), and there is no way to recover a password, nor change it.

I ended up creating a second account, but then later through the logs (passwords are plain text in the configs), I was able to determine the password of the first account. Now I would like to delete the first account, but I see no option.

**Comment by NorthernMan54** [comment]
The ability to delete accounts in is my backlog for a future enhancement.   But as the cloud service does not retain details about your setup or configuration* and is only used to maintain the amazon account linkage between your amazon account and the plugin, which is invalidated as soon as you disable the skill from the Alexa app it was never urgent.  If the cloud service maintained details about the user's account and devices I would agree with you.  All the details on your devices etc are retained on the Amazon Alexa backend, and not homebridge.ca.

* Besides log files which are purged after 7 days

**Comment by via-justa** [comment]
@NorthernMan54 just as a side note, you should state the logging scheme and what data is logged like identifiers, IPs, user names and so on (and the retention policy) on your privacy policy according to the GDPR.
Plus the right to be forgotten does require you to allow deletion of the account. I don't really care for it as you explained very well that no data is stored but you should add this option to be covered.

**Comment by NorthernMan54** [comment]
@via-justa Please keep in mind that I’m running this as a hobby so have limited resources to apply to issues or concerns but would welcome the support of the end users with maintaining and growing the service.  As I’m located in a country that is not covered by GDPR I’m not aware of the nuisances and scope of what is required, and would need an expert to provide what is needed.  A pull request with the changes would gladly be accepted.

But with the GDPR concern you are raising, should I shutdown support for locations covered by GDPR?

**Comment by via-justa** [comment]
Unfortunately I’m more a golang person so I don’t know if I can help with a PR but I can help with the GDPR things.
What I can suggest instead of blocking it is to anonymize the logs of you can, e.g. remove IPs or any other information that can link the log to a specific user if possible. That will cover you from any aspect of GDPR, at least until you have the time to add the delete account option.

Let me know if I can help with anything and continue the good work


________________________________
