### ISSUE TITLE
Stopped working with hoobs

### ISSUE THREAD

**Issue by treforparr** [NorthernMan54/homebridge-alexa#378]
It has suddenly stopped working with hoobsand shutting down the bridge since the latest update today

**Comment by sgsteyn** [comment]
Same problem all of a sudden;
10/22/2020, 10:24:03 AM Error: The requested platform 'Alexa' was not registered by any plugin. at `PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23) at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:365:45 at Array.forEach (<anonymous>) at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:351:31) at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35) at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:87:12) at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81) at Module._compile (internal/modules/cjs/loader.js:955:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10) at Module.load (internal/modules/cjs/loader.js:811:32) at Function.Module._load (internal/modules/cjs/loader.js:723:14) at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10) at internal/main/run_main_module.js:17:11`

**Comment by NorthernMan54** [comment]
This is a issue with hoobs, please raise an issue with them.  My only recommendation would be to install replace hoobs with homebridge itself.

**Comment by treforparr** [comment]
Don't wanna go to home Bridge as I'm already invested into the hoobs just needs this is difficult updating for the latest version of hoobs all plug-ins need to be up-to-date ￼￼￼

**Comment by NorthernMan54** [comment]
My understanding is that HOOBS has updated their framework and the issue may be resolved by upgrading hoobs.
