### ISSUE TITLE
How is deviceList & deviceListHandling supposed to work? Alexa no longer reacts to sensor actions.

### ISSUE THREAD

**Issue by mtressl** [NorthernMan54/homebridge-alexa#379]
Hi everyone
title says it all, I do not get the `deviceList` & `deviceListHandling` config parameters. Since the update to whitelist /blacklist devices in Alexa, I no longer get messages from Alexa based on sensor activity.

E.g. I have a contact sensor in my mailbox, and Alexa used to announce "Mailman was there" when the mailbox contact sensor was opened.
Same for the vibration sensor on the laundry machine, when she announced the event of a certain vibration.

All sensors work as expected, just Alexa does no longer catch the sensor state changes.

Anything I am missing? Do I have to put devices in the white- /blacklist array `deviceListHandling`? Or is something else broken in my setup?

**Comment by mtressl** [comment]
For reference, this is my current config:

```
        {
            "name": "Alexa Voice Assistant",
            "username": "markus@tressl.de",
            "password": "P*y3a+hrpa7>jNE4",
            "pin": "293-01-329",
            "routines": true,
            "blind": true,
            "door": false,
            "debug": false,
            "deviceListHandling": "allow",
            "platform": "Alexa"
        }
```

**Comment by mtressl** [comment]
For reference, this is my current config:

```
        {
            "name": "Alexa Voice Assistant",
            "username": "m...@t....de",
            "password": "xxx",
            "pin": "xxx",
            "routines": true,
            "blind": true,
            "door": false,
            "debug": false,
            "deviceListHandling": "allow",
            "platform": "Alexa"
        }
```

**Comment by NorthernMan54** [comment]
Are the devices possibly being filtered out?

**Comment by mtressl** [comment]
What config would filter a device out? Wouldn't that be `deviceList` with an array of devices?
I don't have that.

**Comment by mtressl** [comment]
Ok, call me stupid. Somehow all my Routines in Alexa involving sensors were deactivated.
Solved.
