### ISSUE TITLE
Homebridge-Alexa crashed after some minutes

### ISSUE THREAD

**Issue by MikeDeltaHH** [NorthernMan54/homebridge-alexa#38]
Hi!
After install homebridge-hue hb works fine for some minutes and crashed... can se the following entries in the livelog:

Dez 29 23:10:49 homebridge homebridge[24449]: /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:389
Dez 29 23:10:49 homebridge homebridge[24449]: var mac = hueDevices[lightid].uniqueid.split(':');
Dez 29 23:10:49 homebridge homebridge[24449]: ^
Dez 29 23:10:49 homebridge homebridge[24449]: TypeError: Cannot read property 'uniqueid' of undefined
Dez 29 23:10:49 homebridge homebridge[24449]: at _getAid (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:389:32)
Dez 29 23:10:49 homebridge homebridge[24449]: at hueToHK (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:167:14)
Dez 29 23:10:49 homebridge homebridge[24449]: at Object.handleHueApi (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:55:24)
Dez 29 23:10:49 homebridge homebridge[24449]: at HAPServer._handleHueApi (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:875:7)
Dez 29 23:10:49 homebridge homebridge[24449]: at HAPServer. (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:214:39)
Dez 29 23:10:49 homebridge homebridge[24449]: at emitNone (events.js:105:13)
Dez 29 23:10:49 homebridge homebridge[24449]: at IncomingMessage.emit (events.js:207:7)
Dez 29 23:10:49 homebridge homebridge[24449]: at endReadableNT (_stream_readable.js:1059:12)
Dez 29 23:10:49 homebridge homebridge[24449]: at _combinedTickCallback (internal/process/next_tick.js:138:11)
Dez 29 23:10:49 homebridge homebridge[24449]: at process._tickCallback (internal/process/next_tick.js:180:9)
Dez 29 23:10:49 homebridge systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Dez 29 23:10:49 homebridge systemd[1]: Unit homebridge.service entered failed state.
------------------------------------------------------------------------------------------------------
This is my config of the affected plugin:

{
"platform": "Hue",
"users": {
"001788FFFE22018B": "xGUJmf4CLQ1TNtRLENPtYTFEaCxrg6SRWediAVPP"
},
"lights": true

I use the Osram "LIGHTIFY Outdoor Flex RGBW! Without the plugin hb works fine!
---------------------------------------------------------------------------------------------------------
Here is the debug log:

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2017-12-30 00:04:35] Loaded plugin: homebridge-eveatmo
[2017-12-30 00:04:35] Registering platform 'homebridge-eveatmo.eveatmo'
[2017-12-30 00:04:35] ---
[2017-12-30 00:04:35] Loaded plugin: homebridge-fakebulb
[2017-12-30 00:04:35] Registering accessory 'homebridge-fakebulb.FakeBulb'
[2017-12-30 00:04:35] ---
[2017-12-30 00:04:36] Loaded plugin: homebridge-fritz
[2017-12-30 00:04:36] Registering platform 'homebridge-fritz.Fritz!Box'
[2017-12-30 00:04:36] ---
[2017-12-30 00:04:36] Loaded plugin: homebridge-harmonyhub
[2017-12-30 00:04:38] Registering platform 'homebridge-harmonyhub.HarmonyHub'
[2017-12-30 00:04:38] ---
[2017-12-30 00:04:38] Loaded plugin: homebridge-homematic
[2017-12-30 00:04:38] Registering platform 'homebridge-homematic.HomeMatic'
[2017-12-30 00:04:38] ---
[2017-12-30 00:04:38] Plugin /usr/local/lib/node_modules/homebridge-hue requires Node version of ^8.9.3 which does not satisfy the current Node version of v8.4.0. You may need to upgrade your installation of Node.
[2017-12-30 00:04:39] Loaded plugin: homebridge-hue
[2017-12-30 00:04:39] Registering platform 'homebridge-hue.Hue'
[2017-12-30 00:04:39] ---
[2017-12-30 00:04:40] Loaded plugin: homebridge-people
[2017-12-30 00:04:40] Registering platform 'homebridge-people.People'
[2017-12-30 00:04:40] Registering accessory 'homebridge-people.PeopleAccessory'
[2017-12-30 00:04:40] Registering accessory 'homebridge-people.PeopleAllAccessory'
[2017-12-30 00:04:40] ---
[2017-12-30 00:04:40] Loaded plugin: homebridge-synology
[2017-12-30 00:04:40] Registering accessory 'homebridge-synology.Synology'
[2017-12-30 00:04:40] ---
[2017-12-30 00:04:40] Loaded plugin: homebridge-wol
[2017-12-30 00:04:40] Registering accessory 'homebridge-wol.NetworkDevice'
[2017-12-30 00:04:40] ---
[2017-12-30 00:04:40] config.json (/home/pi/.homebridge/config.json) not found.
Load homebridge-harmonyhub.HarmonyHub
[2017-12-30 00:04:40] [homebridge-harmonyhub.HarmonyHub] Ignoring Harmony Platform setup because it is not configured
Setup Payload:
X-HM://0023ISYWYC43A
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

  ssdp Not starting SSDP Server +0ms
  EventedHTTPServer Server listening on port 44587 +5ms

--------------------------------------------------------------------------------------------------

Regards!
Mike

**Comment by NorthernMan54** [comment]
Mike,

After adding the plugin, you should have Alexa do “Discover Devices”.  The error is caused by Alexa sending over a light identifier that is not valid in homebridge.

**Comment by MikeDeltaHH** [comment]
Hi!
After adding the plugin homebridge will crash after a while with or without "Discover Devices" by Alexa ! So i have to update the node version to eleminate the error?

**Comment by MikeDeltaHH** [comment]
This message appears when i start homebridge:

Dez 30 00:31:08 homebridge homebridge[27159]: [2017-12-30 00:31:08] [Hue] Philips hue: /lights/20: warning: using default colour gamut for unknown light model {"state":{"on":false,"bri":254,"hue":4352,"sat":208,"effect":"none","xy":[0.4608,0.4107],"ct":370,"alert":"select","colormode":"ct","mode":"homeautomation","reachable":true},"swupdate":{"state":"notupdatable","lastinstall":null},"type":"Extended color light","name":"Licht Terrasse","modelid":"LIGHTIFY Outdoor Flex RGBW","manufacturername":"OSRAM","capabilities":{"streaming":{"renderer":false,"proxy":false}},"uniqueid":"7c:b0:3e:aa:00:a3:7d:e5-03","swversion":"V1.04.93"}

This Osram light is the only reason for me to use the hue plugin and it works!

**Comment by NorthernMan54** [comment]
@MikeDeltaHH That message is from the hue plugin, and should be shared with Eric so he can add it.

Are you still getting this error?

Dez 29 23:10:49 homebridge homebridge[24449]: /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:389

Could you share a longer log fragment, including the messages from before the error?

**Comment by MikeDeltaHH** [comment]
Very strange... let Alexa do some "Discover Devices" and do some homebridge restarts but at the moment  homebridge will not crash... don´t understand that...

**Comment by NorthernMan54** [comment]
The original error was caused by adding more devices to homebridge, and the device sync between alexa and homebridge getting out of whack.  Doing discover devices resolved it.

**Comment by MikeDeltaHH** [comment]
Ok - plan to add more devices to my configuration in the next days and this is a good hint, thanks a lot!
