### ISSUE TITLE
Turning on/off devices via Alexa doesn't work anymore

### ISSUE THREAD

**Issue by florkl** [NorthernMan54/homebridge-alexa#382]
Hi,
I'm receiving this error message when trying to turn on/off any device via Alexa:
[Alexa] PowerController TurnOff undefined undefined Error: ERROR: HB Instance not found
    at /usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:130:18
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:189:7)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

I think this since I updated to Node.js v12.19.0. Are there any known incompatibilities?

Thanks!

**Comment by NorthernMan54** [comment]
Ask Alexa to discover devices again, it will reset the instance references

**Comment by florkl** [comment]
That was easy.

Thanks a lot!
