### ISSUE TITLE
Question about "blind" parameter

### ISSUE THREAD

**Issue by vzlgdu** [NorthernMan54/homebridge-alexa#385]
Hi, I've configured "blind" parameter in my system (before this  used the command "Alexa set blind in room x at 50%"); now I can use the command "Alexa set up/down blind in room x" and it works. The only problem is that the blind goes up if I say "down" and down if I say "up" (in Italian I say "alza or abbassa". My domotic system is Bticino. Is there a way to invert the situation?
Thanks

**Comment by NorthernMan54** [comment]
As I don't have blinds in my setup, can you share a portion of the homebridge-alexa log file.  In particular
what appears in the log when you ask her to control the blinds?

It should be a line containing 

```
ModeController
```

**Comment by vzlgdu** [comment]
Sorry, after some check I discovered it was my mistake…. Sorry again...

**Comment by NorthernMan54** [comment]
Tks
