### ISSUE TITLE
Expose switches as lights for Harmony devices

### ISSUE THREAD

**Issue by JalilCejin** [NorthernMan54/homebridge-alexa#386]
Alexa has a weird situation with room awareness with "light" devices where if you group the Alexa device and the lights together, they will be controlled just fine even if 2 devices share the same name (on a different room). However if you group the Alexa device and switches (instead of lights) Alexa gets messed up and will not control them.

Harmony devices and activities are exposed as switches so when you group them together with Alexa in the same room, they will not be controlled.

I kindly request the option to show switch devices as lights, it looks Alexa likes lights over switches.

Thanks.

**Comment by NorthernMan54** [comment]
If you go into the amazon Alexa app you can control this already. Look at the settings for your device.
