### ISSUE TITLE
Devices with similar names get allowed when they shouldn't

### ISSUE THREAD

**Issue by JalilCejin** [NorthernMan54/homebridge-alexa#387]
Hello,

I found a scenario, where devices with similar names get allowed even when they are not on the allowed list, for example:

Allow list
Apple TV

Device list
Apple TV +
Apple TV 1
Apple TV

Based on the configuration, it should only allow "Apple TV" but instead it's allowing the 3 devices with similar names.

I hope this was helpful, thanks for you efforts.

**Comment by NorthernMan54** [comment]
The filtering is using regular expressions and treats the short name as a match, hence what your seeing.

**Comment by JalilCejin** [comment]
Great, so adding ^ and $ should do the exact match right?

Thanks!
