### ISSUE TITLE
Can't get alexa to see anything from combine

### ISSUE THREAD

**Issue by enishoca** [NorthernMan54/homebridge-alexa#388]
I am using the @kiwi_cam  Homebridge Broadlink Rm Pro from @kiwi_cam https://github.com/kiwi-cam/homebridge-broadlink-rm
"Telly" and "Sound" below are defined as switches in the Broadlink config and they are discovered by Alexa and work properly on their own.  When I try to use combine the logs don't show any errors but Alexa keeps saying TV not found. What I am trying to do is turn on TV and soundbar together

        {
            "name": "Alexa",
            "platform": "Alexa",
            "username": "xxxxx",
            "password": "xxxx,
            "pin": "0xxx",
            "routines": false,
            "blind": false,
            "door": false,
            "debug": true,
            "filter": "192.168.0.20:51827",
            "deviceListHandling": "allow",
            "combine": [
                {
                    "into": "TV",
                    "from": ["Telly","Sound"]
                }
            ] 
        }
—————-///////////————————————
Device Dump
[dump.txt](https://github.com/NorthernMan54/homebridge-alexa/files/5537717/dump.txt)
—————///////——————————————
This is what I see in logs
2020-11-13T15:10:50.308Z alexaActions alexaDiscovery
2020-11-13T15:10:50.311Z alexa:Messages Combine-2 true [ { into: 'TV', from: [ [Array] ] } ]
2020-11-13T15:10:50.311Z alexa:Messages combine { into: 'TV', from: [ [ 'Telly', 'Sound' ] ] }
2020-11-13T15:10:50.311Z alexaActions Cookie Object:  280
2020-11-13T15:10:50.312Z alexaActions Cookie Object:  283
2020-11-13T15:10:50.312Z alexaActions Cookie Object:  280
2020-11-13T15:10:50.312Z alexaActions Cookie Object:  283
2020-11-13T15:10:50.312Z alexaActions Cookie Object:  280
2020-11-13T15:10:50.312Z alexaActions Cookie Object:  544
2020-11-13T15:10:50.312Z alexaActions Cookie Object:  280
2020-11-13T15:10:50.312Z alexaActions Cookie Object:  116
2020-11-13T15:10:50.313Z alexaActions alexaDiscovery - returned 14 devices

**Comment by NorthernMan54** [comment]
If you can share an accessory dump, details are in the read me, I will run it thru the device parser and see what comes out for your TV

**Comment by enishoca** [comment]
Already did - dump.txt is attached in the original post

**Comment by NorthernMan54** [comment]
Sorry that, give me a day to take a look

**Comment by NorthernMan54** [comment]
I think I need to explain what combine does and doesn't do better, as what your trying to do isn't the intended use case for combine.

Combine is meant to be used with an existing device and combine/merge in into another existing device.  Under the covers I'm merging a device into another devices Alexa discovery response message.  It does not create a new device, but merges existing devices.  And is doing it with the Alexa discovery response message which assumes that the various capabilities don't collide with each other as well.

I created this to merge my volume controls device ( an IR Blaster ) into my TV ( Apple TV Remote ), and be able to say 'Pause TV' or 'raise volume on TV'.  It is a bit hacky but works on my setup.

For your use case, you need to try a different approach

1 - Use Alexa routines to control both devices when you say 'turn on TV'

2 - In homebridge create a combo device using homerbridge-dummy, and automations to have a device called TV when turned on, controls your Telly and Sound devices.  There are other options and approaches as well.

**Comment by NorthernMan54** [comment]
PS I also added a bit more debug logging as well for the combine function, and identify missing or incorrect values.
