### ISSUE TITLE
Can l discover HomeKit device for example Leviton DH6HD-1BZ 600W Decora Smart Dimmer, Works with Apple HomeKit?

### ISSUE THREAD

**Issue by bmbking56** [NorthernMan54/homebridge-alexa#39]
Hi I'm enjoying homebridge-alexa. It's working well and I can control TV via Alexa that's not supported Amazon echo.
But does homebridge-alexa support only supported HomeKit device for example Leviton DH6HD-1BZ 600W Decora Smart Dimmer, Works with Apple HomeKit ?  Or does it support only the device controlled by homebridge ?

**Comment by NorthernMan54** [comment]
Sorry, it only works with devices controlled by homebridge.
