### ISSUE TITLE
Discover HomeKit devices not created by Homebridge

### ISSUE THREAD

**Issue by ChristopherNeuwirth** [NorthernMan54/homebridge-alexa#390]
Hello, I have the following problem or I don't know if I made a mistake in guessing.

What I expected after installing the Homebridge-alexa plugin:
All devices I have available in HomeKit will be displayed as devices in the Alexa app by using the Homebridge skill.

What the status is:
Only digital devices or devices created by me in config.json are shown in my Alexa app.

I'm not sure if this is a problem caused by this plugin. In the Homebridge UI I only see the devices I configured in config.json.

Thanks for any advice how to solve this issue.

**Comment by NorthernMan54** [comment]
This plugin only exposes home bridge devices to Alexa, and not native HomeKit devices.
