### ISSUE TITLE
Alexa App always shows old devices

### ISSUE THREAD

**Issue by ChristopherNeuwirth** [NorthernMan54/homebridge-alexa#391]
Hi, I played around with virtual devices during the initial setup of the Homebridge Alexa plugin. 

The connection between my Homebridge instance and the Alexa device with installed skill works perfectly.

Old devices that no longer exist in `config.json` are still displayed after disabling the skill and re-enabling it with subsequent device discovery mode and do not disappear.

I assume that they are cached somewhere?
What I would like to avoid is to empty the cache of the whole homebridge instance, because I would have to reconfigure all my devices.

Thanks for any kind of help.

**Comment by NorthernMan54** [comment]
Homebridge-Alexa only caches in memory and restarting the plugin will clear it.

**Comment by ChristopherNeuwirth** [comment]
What do you mean by `restarting the plugin`?

So far I did: 

- Uninstall and Reinstall the skill from the Alexa device several times
- Restart Homebridge service on RaspberryPi
- Deleted the configuration from the `config.json` file

**Comment by NorthernMan54** [comment]
Did you delete them from the Alexa app?

**Comment by ChristopherNeuwirth** [comment]
Did not know that this is possible. Thanks that solved the issue 👌.
