### ISSUE TITLE
Errors at HB shutdown

### ISSUE THREAD

**Issue by vzlgdu** [NorthernMan54/homebridge-alexa#393]
Hi, when I shutdown my HB istance, i receive the following error messages. At restart everithing seems to be ok...

dic 07 10:07:20 homebridgea systemd[1]: Stopping Node.js HomeKit Server...
dic 07 10:07:21 homebridgea homebridge[2801]: [7/12/2020, 10:07:21] TypeError: Cannot read property 'toString' of undefined
dic 07 10:07:21 homebridgea homebridge[2801]:     at Object.eventMessage (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaMessages.js:592:47)
dic 07 10:07:21 homebridgea homebridge[2801]:     at /usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:963:35
dic 07 10:07:21 homebridgea homebridge[2801]:     at Array.forEach (<anonymous>)
dic 07 10:07:21 homebridgea homebridge[2801]:     at alexaHome.alexaEvent (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:953:10)
dic 07 10:07:21 homebridgea homebridge[2801]:     at EventEmitter.emit (events.js:315:20)
dic 07 10:07:21 homebridgea homebridge[2801]:     at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:48:22)
dic 07 10:07:21 homebridgea homebridge[2801]:     at HAPNodeJSClient.emit (events.js:315:20)
dic 07 10:07:21 homebridgea homebridge[2801]:     at HAPNodeJSClient._reconnectServer (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:309:8)
dic 07 10:07:21 homebridgea homebridge[2801]:     at EventEmitter.emit (events.js:315:20)
dic 07 10:07:21 homebridgea homebridge[2801]:     at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/lib/eventedHttpClient.js:90:24)
dic 07 10:07:25 homebridgea systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
dic 07 10:07:25 homebridgea systemd[1]: Stopped Node.js HomeKit Server.
dic 07 10:07:25 homebridgea systemd[1]: homebridge.service: Unit entered failed state.
dic 07 10:07:25 homebridgea systemd[1]: homebridge.service: Failed with result 'exit-code'.
dic 07 10:07:25 homebridgea systemd[1]: Started Node.js HomeKit Server.

**Comment by NorthernMan54** [comment]
Looks like the plugin was in the middle of processing an event message during the shutdown and it errored out.

**Comment by NorthernMan54** [comment]
As everything is okay, am going to close this

**Comment by vzlgdu** [comment]
It seems this happen at Avery restart of HB...

> Il giorno 7 dic 2020, alle ore 16:24, Northern Man <notifications@github.com> ha scritto:
> 
> Looks like the plugin was in the middle of processing an event message during the shutdown and it errored out.
