### ISSUE TITLE
Unclear how to refresh devices

### ISSUE THREAD

**Issue by williamw** [NorthernMan54/homebridge-alexa#396]
I can’t seem to figure out how to refresh the list of Homebridge devices that Alexa can access. Any devices I’ve added to Homebridge after the initial sync with Alexa do not appear. I’ve tried running Discover Devices, but the new devices are not discovered. 

Perhaps you could add a Refresh Devices button to the homebridge.ca web app?

**Comment by NorthernMan54** [comment]
Can you share the steps you took to setup the plugin? And your homebridge environment?

This sounds similar to #395 and is more than likely a local setup issue

**Comment by williamw** [comment]
I'm not sure what's up. I don't recall exactly what I did to set things up. However, I did notice I can disable and re-enable Alexa skill on Amazon's end, and it seems to be a non-destructive actions — I don't seem to lose anything when I disable it, and everything that was there comes back + the newly added devices.

**Comment by NorthernMan54** [comment]
If you ask Alexa to discover devices it will refresh the list ( I guess this was assumed as my side )

**Comment by Jacksonbm1** [comment]
I know this is closed, but it took me quite a bit of time to figure this out. I think users might find this helpful if you put it in the main docs.
