### ISSUE TITLE
Unable to get sensor values

### ISSUE THREAD

**Issue by mabiste** [NorthernMan54/homebridge-alexa#397]
Hello,

I have a problem getting sensor values, such as room temperatures, from my Alexa.

Until the last update all worked fine, but now I get a 'device is not responding' message from Alexa if I ask her for the temperature. Actors, such as switching lights on or off, are working. I've tried to roll back to previous version (0.5.18), but the same issue.

On the log I can see the following message:
`2020-12-12T09:18:06.518Z alexaActions alexaMessage: Response {
  "event": {
    "header": {
      "namespace": "Alexa",
      "name": "ErrorResponse",
      "messageId": "02ff4c1f-d382-470a-b298-3e870e939896",
      "correlationToken": "XXX",
      "payloadVersion": "3"
    },
    "endpoint": {
      "endpointId": "XXX"
    },
    "payload": {
      "type": "ENDPOINT_UNREACHABLE",
      "message": "ERROR: HB Instance not found"
    }
  }
}`

Anyone any idea?

**Comment by NorthernMan54** [comment]
"type": "ENDPOINT_UNREACHABLE", "message": "ERROR: HB Instance not found" 

This is saying that it can't reach your homebridge instance.  Trying asking Alexa to discover devices and try again

**Comment by mabiste** [comment]
I've already tried to remove and readd (by discovering) the devices, but no change... The actors are working and they can find the (same) homebridge instance!

**Comment by NorthernMan54** [comment]
Are you running the latest version of the plugin ?

**Comment by mabiste** [comment]
Yes!

**Comment by NorthernMan54** [comment]
Delete the unreachable device from the Alexa app.

**Comment by mabiste** [comment]
I've already tried this, no change...

**Comment by NorthernMan54** [comment]
I'm stumped with this

If you have removed the unreachable device for the Alexa app, then this should not occur

Please keep in mind that Alexa maintains a cache of your HomeBridge devices, and if the data gets out of whack this will occur.  Fix is to remove the not responding devices from the Alexa side.  And asking Alexa to discover devices.  Sometimes just asking Alexa to discover devices will resolve the issue.

**Comment by mabiste** [comment]
Ok, I will try to completely reset my configuration...
