### ISSUE TITLE
ERROR: connect ECONNREFUSED

### ISSUE THREAD

**Issue by martinorob** [NorthernMan54/homebridge-alexa#398]
Hi all, 
after today update I have some issue:
Debug log tell mi this:

2020-12-18T13:26:12.920Z alexaLocal ERROR: connect ECONNREFUSED 35.169.132.61:1883 ->  ECONNREFUSED
2020-12-18T13:26:18.040Z alexaLocal reconnect

and if I telnet I have this response:

telnet 35.169.132.61 1883
Trying 35.169.132.61...
telnet: connect to address 35.169.132.61: Connection refused
telnet: Unable to connect to remote host

Is there some problem on the cloud of homebridge-alexa?

**Comment by NorthernMan54** [comment]
Looks like you have tripped the dos protection, stop the plugin for 2 minutes then start it again.

**Comment by martinorob** [comment]
ok thank you
