### ISSUE TITLE
Amazon Fire TV

### ISSUE THREAD

**Issue by simonrb2000** [NorthernMan54/homebridge-alexa#4]
Hi all,

Not really an issue however I have just seen that my Amazon Fire TV has been updated and supports Alexa now. Does this work with that also? I'd assume so however wanted to confirm before I set this up.. 

Cheers

**Comment by NorthernMan54** [comment]
To be honest I don't know if it will work or not.  I did a quick google and received conflicting information.  One site said yes and one said no.  If you could try and let me know, I can update the readme.
