### ISSUE TITLE
Feature Request - Open to Help

### ISSUE THREAD

**Issue by brentleeper** [NorthernMan54/homebridge-alexa#400]
Hello NorthernMan! 

I am not sure if it would be possible, but if so the idea is as follows.

For basic devices such as plugs and switches (on/off control only) would it be possible to create a stateful dummy switch automatically which would be exposed to Alexa and that could somehow be connected to the real switch in Homebridge? 

This might require the use of automations within HomeKit itself since the whole issue is that the devices cannot be exposed to Homebridge and the Automatic creation of the dummy switches could be a setting. 

Thoughts?
-Brent

**Comment by NorthernMan54** [comment]
Unfortunately, what you're suggesting is not feasible.  Homebridge plugins don't have the ability to create automations in the Home app.
