### ISSUE TITLE
Error: EACCES: permission denied, open 'alexaDiscovery.json'

### ISSUE THREAD

**Issue by dazzlee69** [NorthernMan54/homebridge-alexa#402]
The latest version, v0.5.20, which dumps out alexaDiscovery.json when debug is true, fails on homebridge running as a service on linux VM, due to the services cwd -> / and running as non-root user.

Please provide an option to specify where the file should be written, if it should be written or use the homebridge storage path to store the file somewhere that is designed to be writeable.

Thanks

Log from syslog:

Dec 28 09:43:45 ananke homebridge[7939]: [12/28/2020, 09:43:45] [Alexa] alexaDiscovery - returned 30 devices
Dec 28 09:43:45 ananke homebridge[7939]: [12/28/2020, 09:43:45] Error: EACCES: permission denied, open 'alexaDiscovery.json'
Dec 28 09:43:45 ananke homebridge[7939]:     at Object.openSync (fs.js:440:3)
Dec 28 09:43:45 ananke homebridge[7939]:     at Object.writeFileSync (fs.js:1265:35)
Dec 28 09:43:45 ananke homebridge[7939]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge-alexa/lib/alexaActions.js:136:10)
Dec 28 09:43:45 ananke homebridge[7939]:     at HAPNodeJSClient.HAPaccessories (/usr/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:207:3)
Dec 28 09:43:45 ananke homebridge[7939]:     at Object.alexaDiscovery (/usr/lib/node_modules/homebridge-alexa/lib/alexaActions.js:95:14)
Dec 28 09:43:45 ananke homebridge[7939]:     at HAPNodeJSClient.<anonymous> (/usr/lib/node_modules/homebridge-alexa/lib/alexaActions.js:36:20)
Dec 28 09:43:45 ananke homebridge[7939]:     at HAPNodeJSClient.emit (events.js:210:5)
Dec 28 09:43:45 ananke homebridge[7939]:     at HAPNodeJSClient.<anonymous> (/usr/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:116:10)
Dec 28 09:43:45 ananke homebridge[7939]:     at Timeout._onTimeout (/usr/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:190:7)
Dec 28 09:43:45 ananke homebridge[7939]:     at listOnTimeout (internal/timers.js:531:17)
Dec 28 09:43:45 ananke homebridge[7939]: [12/28/2020, 09:43:45] Got SIGTERM, shutting down Homebridge...

**Comment by NorthernMan54** [comment]
Tks for sharing that, removed that feature from the last version
