### ISSUE TITLE
Credentials do not work with special characters

### ISSUE THREAD

**Issue by Hackencrash** [NorthernMan54/homebridge-alexa#403]
I created a username with a capital H and a password with a dot '.' in it. Whilst this worked from the iOS Alexa app linking the skill, it failed from the Homebridge plugin shown in the logs and on homebridge.ca.  Created another account with all lower username and password without a dot and all worked as expected.

**Comment by NorthernMan54** [comment]
Tks for reporting, will update the docs to mention this.
