### ISSUE TITLE
today instaled  shelly contact door/window 2

### ISSUE THREAD

**Issue by platini76** [NorthernMan54/homebridge-alexa#406]
I is read from the shelly plugin and also from alexa plugin thst create a double sensor that also take no event trigger..

so in my homekit I have one right shelly door/window
and one homebridge-alexa sensor... 
what it the problem?

**Comment by NorthernMan54** [comment]
Not sure I understand the question?

**Comment by platini76** [comment]
forget it.. I was probably tired and I exchange door contact with alexa contact sensor... that is everywhere... ahahah
