### ISSUE TITLE
Alexa devices visibility in Homekit

### ISSUE THREAD

**Issue by sgrizzi** [NorthernMan54/homebridge-alexa#407]
Forgive me if my question is weird...
I just installed the Alexa plugin and it is working fine. In Alexa I can see two accessories -Daikin airco's- which are managed by the relevant Homebridge plugin, and I can control the two units from Alexa.
I can also see the two airco's in my Homekit network.
Yet the opposite is not true, i.e. in Homekit/Homebridge I cannot see any of the accessories which are active in Alexa, e.g. smarplugs, doorbells, temp. sensors, an Echo8 device, etc.
Is this just correct or am I doing anything wrong or have not properly setup something somewhere?
Thanks for any help....
Rgds.

**Comment by NorthernMan54** [comment]
This plugin does not expose Alexa devices into HomeKit, only Homebridge devices into Alexa.  Your setup is correct

**Comment by sgrizzi** [comment]
Thanks for your prompt answer.

 

PITY ! ☹

Are you aware of any way/another plug-in/planned future feature/or other to indeed expose Alexa devices into Homekit?

 

Rgds.

**Comment by NorthernMan54** [comment]
Unfortunately not
