### ISSUE TITLE
5 - Date of last plugin response

### ISSUE THREAD

**Issue by NicAshby** [NorthernMan54/homebridge-alexa#409]
No longer getting a plugin response.  Was working. Everything else seems to work. Not sure where to start troubleshooting.

**Comment by NorthernMan54** [comment]
Looking at your logs on homebridge or restarting?

**Comment by NicAshby** [comment]
> Looking at your logs on homebridge or restarting?

Nothing there of use there, and no effect.

**Comment by NicAshby** [comment]
Resolved itself after several hours of leaving alone.
