### ISSUE TITLE
Is Device Descriptor Correct for latest version of Echo Dot software?

### ISSUE THREAD

**Issue by pauleec** [NorthernMan54/homebridge-alexa#41]
@NorthernMan54 I am using your build of homebridge with the homebridge-milight plugin to control 8 grouped zones of milight RGB-CCT lights via the new v6 milight bridge hardware and noticed that the new version of the Echo Dot (597465220) software now shows the lights as "Royal Philips" "Lux Bulbs" which display as White Dimmable bulbs with no configurable Colour property. The echo dot software did not show this level of detail in earlier releases. Given my lights do have full colour support how can this be corrected to allow for me to be able to set the colour of the lights with Alexa?

**Comment by NorthernMan54** [comment]
Setting colours is not supported at this time, as the method I’m using to interface with Alexa only support on/off and brightness.  This winter I’m going to change my interface approach, to a proper skill and once that is complete it should support colours afterwards.   The interface rewrite is needed as new Amazon devices like the 2nd generation echo don’t work with this approach.

Check back in a few weeks

**Comment by pauleec** [comment]
Great stuff! If you need a tester I would be keen! I’ve got a whole apartment fitted out with new latest RGB-CCT  Mi-Light downlighters, spots and bulbs which are configured into 8 zones via the new v6 bridge lamp. Currently configured to work with Alexa via the node-milight-promise, Homebridge-Alexa and the Homebridge-milight plugin.

Does the v2 update also break the BWS Hue emulation? Another piece of software that has used the emulation approach is the Tasker RM plugin. It makes each BroadLink learnt IR or rf code it has copied/learnt behave like an “On” or an “ Off” of an emulated Hue bulb. I’ve also noticed that the Android Tasker BroadLink plugin has stopped working since the update (RM plugin). The Rm plugin still shows its configured alexa  devices as Hue bulbs though in the new Alexa smart Home Devices Panel (hence my suspicions and question about the descriptir).

When do you think you’ll have some new code to test? Will it be the same repo/same name or a completely new project? Any thoughts on a new name for it given it is such a break from the old approach?

**Comment by jat80** [comment]
@NorthernMan54 so with the re-write will it just be a plugin for homebridge (normal version) or will you still have your "special version" of homebridge to expose the accessories to Alexa?

**Comment by NorthernMan54** [comment]
@jat80 JT, I hoping this time to avoid the "special version" of home bridge approach, but as I need to tap into all the plugins, it will require changes to HAP-NodeJS to enable.  I had discussed an approach for implementing with Tian previously, but he was looking to keep HAP-NodeJS clean.  This time I think I have an approach which would minimize the changes to HAP-NodeJS and hopefully pass muster to avoid the "special version".

**Comment by jat80** [comment]
@NorthernMan54 Amazing!  Thank you for the quick reply.  I will look forward to your future updates.  

FYI the issues I had previously with the RM Mini3 and homebridge have been resolved.  I have managed to fix it [here](https://github.com/lprhodes/homebridge-broadlink-rm/issues/196) So with that in mind, may use your version again of homebridge to expose them to Alexa.

**Comment by NorthernMan54** [comment]
@jat80 For IR Control of devices I had looked at the Broadlink mini, but didn't like the support it had so I went with these.

https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster

A little bit of DIY, but a lot more control.  And I even created a home bridge plugin for it

https://github.com/NorthernMan54/homebridge-HTTP-IRBlaster

I may be something to look at.

**Comment by pauleec** [comment]
Hi I am not sure what you mean by “Send me a direct message via slack / Homebridge at NorthernMan54 with your amazon login.” Im keen to test out the new beta code but not sure how..... can you elaborate? Thx

**Comment by NorthernMan54** [comment]
In order to sign up people to the beta test and give them access to the homebridge amazon smart home skill I need your amazon logon.  And I figured the easiest way for people to share it discreetly was via slack, and to send me a direct message.

On the homebridge README there are the instructions for signing up to slack, and once you are signed up, just send me a direct message via slack with your amazon logon
