### ISSUE TITLE
Alexa error connect

### ISSUE THREAD

**Issue by giannimp** [NorthernMan54/homebridge-alexa#411]
Help me My wife kill me!!
14/1/2021, 20:07:35 2021-01-14T19:07:35.518Z alexaLocal reconnect
14/1/2021, 20:07:35 2021-01-14T19:07:35.644Z alexaLocal ERROR: connect ECONNREFUSED 35.169.132.61:1883 ->  ECONNREFUSED
14/1/2021, 20:08:02 2021-01-14T19:08:02.797Z hapNodeJSClient Events [{"host":"192.168.2.190","port":51826,"aid":20,"iid":10,"value":true,"status":true}]
14/1/2021, 20:08:20 2021-01-14T19:08:20.648Z alexaLocal reconnect
14/1/2021, 20:08:20 2021-01-14T19:08:20.772Z alexaLocal ERROR: connect ECONNREFUSED 35.169.132.61:1883 ->  ECONNREFUSED
Thank you

**Comment by NorthernMan54** [comment]
Try stopping the plugin for 5 minutes and try again
