### ISSUE TITLE
Additional Devices?

### ISSUE THREAD

**Issue by dehsgr** [NorthernMan54/homebridge-alexa#42]
It would be nice, oder there would be some more devices in Alexa, such as Windows, Doors, Garagedoor, Shutter.

**Comment by NorthernMan54** [comment]
The current interface I’m using from Alexa uses the original API from Amazon which only supported white light bulbs, that you can turn on/off and dim.  I’m looking at reworking this as a smart Home skill in the future.  Check back in the few months.

If one of these makes sense to appear to Alexa as a lightbulb, I can as quick change make it appear.  It would need to make sense to work as

Turn garage door on/turn garage door off

**Comment by dehsgr** [comment]
Okay. I'll wait for rework. Thanks a lot!
