### ISSUE TITLE
Motion Not Detected in Alexa ?

### ISSUE THREAD

**Issue by Pblondin123** [NorthernMan54/homebridge-alexa#420]
Hi since approx 6pmEST 2021-02-19 seems that motion events are not going thru in Alexa (at least, my setup :-) ).   I checked the homebridge site (all green), disabled/enabled the skill, rediscovered devices (2 devices were added from a new plugin, which shows that the skill is talking to my home setup).  But am running out of ideas on how to troubleshoot why my motion triggers are not happening.  Fyi i upgraded to the latest Homebridge UI not sure if this involves anything.  tia.

**Comment by NorthernMan54** [comment]
If you run the plugin with the DEBUG flag set in the config it will log a lot more details around events.

With logging enabled I would then follow these steps to troubleshoot

1 - Restart homebridge-alexa plugin ( to reset event connections to homebridge instances )

2 - Ask Alexa to discover devices again ( this will reset the device to Alexa settings )

3 - Trigger your motion sensor ( you should see a log message indicating a event message being sent to the Alexa backend )

**Comment by Pblondin123** [comment]
i just realized that my issue is likely with the delay timer plugin which for some reason i thought was linked to the Alexa plugin.   Will contact the plugin developer sorry and thanks
