### ISSUE TITLE
Each routine executes the command 5 times

### ISSUE THREAD

**Issue by Loginbug** [NorthernMan54/homebridge-alexa#422]
I'm using homebridge-alexa and homebridge-cmdswitch2 to run some bash script.
Each alexa routine executes the command 5 times. So, when i run 'light on the interruptor' routine, alexa light up the interruptor 5 times. Same thing for switch off routine.
Thanks for any help.

Please note that interrupt state is not defined:
`{
    "name": "VI-P0-INC",
    "on_cmd": "removed",
    "off_cmd": "removed",
    "timeout": 60
},
{
    "name": "VI-P0-BIN",
    "on_cmd": "removed",
    "off_cmd": "removed",
    "timeout": 60
},`

[debug.log](https://github.com/NorthernMan54/homebridge-alexa/files/6022917/debug.log)

**Comment by NorthernMan54** [comment]
I looked at the backend logs and my skill received multiple unique requests from the Alexa backend, how are you controlling this from the Alexa side ?

**Comment by Loginbug** [comment]
Found a solution by myself.
The problem was this:
`"timeout": 60`
Alexa plugin thinks that command is timed-out so it send it 5 times.
I have put `"timeout": 1` and problem disappear.

**Comment by Loginbug** [comment]
Thanks anyway for your excellent work

**Comment by NorthernMan54** [comment]
Alexa hangs up after 8 seconds, so you have a couple of seconds to play with.  Maybe 5
