### ISSUE TITLE
Alexa Routines Virtual Device

### ISSUE THREAD

**Issue by Damianod27** [NorthernMan54/homebridge-alexa#427]
Is it possible in upcoming updates to add support for Virtual Devices ON/OFF in routines?  Alexa does not have the functionality to perform this activity only once a day when using the Motion sensor, Contact Sensor, button etc. in the routine.  This can be done in HomeKit and transferred to Alexa, but a virtual device is needed for that.

The homekit can be initialized: that if Motion Sensor is detected then Virtual Decice ON.  In Alexa, he sets up a routine that if Virtual Device On should do so and so.  That's what I had at Smarthings before.  Now I have everything in FIBARO HOME Center 2 Z-Wave + Raspberry Pi 4 and Canbee 2 Zigbee. 

![image](https://user-images.githubusercontent.com/79320859/110169240-b5c6d400-7df8-11eb-988d-8f67d0cd6a4b.jpeg)

**Comment by NorthernMan54** [comment]
Which plugin is creating the virtual devices ?

**Comment by Damianod27** [comment]
The plug from the picture below.  It's nice if you could add devices from the list you have.  But it would be enough with Virtual Switch.  You can then do that if Motion Sensor detected and Door Sensor Detected to Virtual Switch On.  In Alexa that if Virtual Switch On will do it and this.  Maybe someday it will be unnecessary but Alexa is poor in conditions now.  You cannot add two conditions or trigger them in any particular way.  Sorry for my English.
![image](https://user-images.githubusercontent.com/79320859/110207960-97a7b500-7e86-11eb-9a6e-4c674e6d8097.jpeg)

**Comment by NorthernMan54** [comment]
This is already supported, have you asked Alexa to discover devices ? If they don't appear, have you looked at the logs for any messages ?

Please keep in mind that only motion and contact sensors can be used to trigger a routine, and this is not a motion or contact sensor.  This limitation exists on the Amazon Alexa side and not with this plugin.

**Comment by Damianod27** [comment]
When I was a mile away from Huba Smartthings, I was able to add Virtuals to trigger scenes in Alexa routines.  Virualne devices work in Alexa for me.  They don't work in routines.  As already mentioned in smarthings they worked.  So I think it can be done.
![image](https://user-images.githubusercontent.com/79320859/110210133-93809500-7e90-11eb-8362-f0a8dd6d93ac.jpeg)

**Comment by NorthernMan54** [comment]
**Please keep in mind that only motion and contact sensors can be used to trigger a routine, and this is not a motion or contact sensor. This limitation exists on the Amazon Alexa side and not with this plugin.**

**Comment by Damianod27** [comment]
Yes, of course I know.  I think that if it was possible in SmartThings, it can be here.  It worked perfectly for me.  However, I changed the platform.  It was possible to add a virtual device to trigger scenes in routines

https://youtu.be/BqJ3cHHcNyc

https://github.com/bjpierron/SmartThings-Alexa

**Comment by NorthernMan54** [comment]
You need to use a virtual motion or contact sensor, and not a switch!

**Comment by Damianod27** [comment]
I had the Smarthings Hub and it worked.  In Alex, a virtual device created in smarthings could be used to trigger routines.  In the Smarthings hub, I had a routine set up with Motion sensor Detected to Virtual Switch on.  In Alexa, I had a routine triggered with Virtual Switch.  If Virtual Switch ON then do this and this.  It worked perfectly for me.  However, I sold smarthings hub because I have FIBARO HC2 and Raspberry Pi 4 with Canbee 2. I needed Smarthings Hub only for Zigbee devices now I have Canbee 2 Zigbee.  If I had Hub SmartThings I would show it to you.  I think if it could be done there, it could be done in Homebridge.

**Comment by NorthernMan54** [comment]
And yes it can be done, as I use several in my setup, you just need to use a virtual motion or contact sensor, and not a switch!  The plugin you are using is the wrong one.  Look for a dummy contact sensor

**Comment by Damianod27** [comment]
Can you recommend me something?  What are you using.  Does your triggering routine work in Alexa?
Thank you for your time

**Comment by NorthernMan54** [comment]
google 'homebridge dummy contact sensor'

**Comment by Damianod27** [comment]
Thank you very much.  I have already installed and configured.  Everything works as I wanted.  It is a pity that we did not understand each other immediately

![image](https://user-images.githubusercontent.com/79320859/110225274-6231b480-7ee4-11eb-8c99-55e360ddc44a.png)
