### ISSUE TITLE
Duplicate devices

### ISSUE THREAD

**Issue by dcaccount** [NorthernMan54/homebridge-alexa#428]
Hello,
I have just discovered that all Smart Home devices under Alexa have been lately duplicated, precisely I do not know when but it happened lately.

What has happened, any idea on how to solve it?

Thanks,
Dan

**Comment by NorthernMan54** [comment]
I would expect that one of your plugins changed its ‘signature’ and triggered this.  I had it also occur recently, and it was triggered by a plugin changing the ‘manufacturer’ value

with the Alexa plugin I’m using the device name, type and manufacturer fields to create a unique identifier, and if any change you get a new unique Id for the device which triggers the duplicate or orphaned old entry.

**Comment by dcaccount** [comment]
> with the Alexa plugin I’m using the device name, type and manufacturer fields to create a unique identifier, and if any change you get a new unique Id for the device which triggers the duplicate or orphaned old entry.

Thanks for reply. This sound interesting but I have not understood it. 

How can I implement it? Can you please implement it?
Thanks!
Dan

**Comment by dcaccount** [comment]
> Nothing to implement, unfortunately just identify and remove the duplicates.

It is clear, but I have missed one point, how can I identify and then duplicates? Can you please clarify?

Thanks!
