### ISSUE TITLE
Devices already paired with Alexa

### ISSUE THREAD

**Issue by tamasharasztosi** [NorthernMan54/homebridge-alexa#43]
First of all, I love it, thank you!

There's a part in readme I don't really understand:
  _If the setting is not enabled, then your homebridge instance will not be visible to Alexa, useful when     you have devices / plugins that you don't want Alexa to see. For example, Philips hue or Belkin wemo devices._

I add the "ssdp": 1900 line to the bridge and then all of my HomeKit device shows up in Alexa.
So how can I hide devices from Alexa?

**Comment by NorthernMan54** [comment]
Sorry I didn't explain it that well.  On my RPI I'm running several copies of homebridge at the same time, and for one of them I don't want the devices exposed to Alexa.  So in the instance I don't include the "ssdp": 1900 setting.

I'm running several instances as it makes it more stable, and faster response times.

**Comment by tamasharasztosi** [comment]
Ok, i see. So i assume it’s not possible at this stage of developing to hide certain accessories, plugins from homebridge.
I think then it’s closed, thank you!
