### ISSUE TITLE
How to identify duplicated

### ISSUE THREAD

**Issue by dcaccount** [NorthernMan54/homebridge-alexa#430]
Hello,
I refer to a closed issue (Duplicated devices).

It is not clear to me how to identify the duplicated devices under the list of Alexa smart home devices.

For instance I have two Shelly 1 C4XXYY, first one is:

> homebridge Shelly 1 C4XXYY Switch

and the second one is:

> Homebridge 95E8 Shelly 1 C4XXYY Switch

Which one has to be deleted? Please advise.

Thanks,
Dan

**Comment by NorthernMan54** [comment]
I really can't say as one is likely to work and the other not.

My guess would be the one

`Homebridge 95E8 Shelly 1 C4XXYY Switch`

**Comment by dcaccount** [comment]
> I really can't say as one is likely to work and the other not.
> 
> My guess would be the one
> 
> `Homebridge 95E8 Shelly 1 C4XXYY Switch`

As the duplicates are an issue especially when we have many devices, is it possible to implement a sort of renaming of the duplicated device in order to clearly identify the old and the new one under Alesa app?

I mean if there is a device:

> Shelly 1 AABB

the duplicated becomes under Alexa app:

> Shelly 1 AABB-1

What do you think, is it possible?
Thanks

**Comment by NorthernMan54** [comment]
I wish it was that easy, the device management api from amazon does not have that capability.
