### ISSUE TITLE
Install Skill on Multiple HomeBridges/Different Pins/Same Alexa Account?

### ISSUE THREAD

**Issue by Ramias1** [NorthernMan54/homebridge-alexa#436]
I want to publish devices to Alexa with this plugin but not to the Home App; for that and another reason I have a homebridge instance running on a separate host.  With a separate Homebridge PIN (I don't want all of my devices on both homebridges).  Can I install this plugin on both and use the same username/password to connect to the web service?

**Comment by NorthernMan54** [comment]
You can only install and run this once in your environment, multiple copies will cause issues.

And the same pin must be used

But you do not need to pair the homebridge instance to the home app for the plugin to work
