### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by networks514** [NorthernMan54/homebridge-alexa#437]
Hi,

down server ? I have this error when I want activate the skill. Same on http://www.homebridge.ca/

regards

**Comment by thehauntedmattress** [comment]
Having same issue.  I was dumb enough to delete all my devices thinking it was my echo dot that lost the connection.

**Comment by Venger2005** [comment]
https://stats.uptimerobot.com/2WmEDHyV6

**Comment by networks514** [comment]
> https://stats.uptimerobot.com/2WmEDHyV6

Tks for the link!

**Comment by thehauntedmattress** [comment]
@Venger2005 what specifically are those two websites (Homebridge LB and Homebridge WS) that are down?

**Comment by NorthernMan54** [comment]
And the discord channel #homebridge-alexa on the homebridge discord server

**Comment by NorthernMan54** [comment]
The LB is the network load balancer in front of the servers and WS is the web service that the Alexa cloud talks to

**Comment by thehauntedmattress** [comment]
Gotcha thank you for your help as always.

**Comment by Venger2005** [comment]
> @Venger2005 what specifically are those two websites (Homebridge LB and Homebridge WS) that are down?

I’m not the owner or operator of that site so best to ask said person who posted immediately below you.

**Comment by thehauntedmattress** [comment]
I use this plugin literally every day and I love it.

**Comment by networks514** [comment]
> The LB is the network load balancer in front of the servers and WS is the web service that the Alexa cloud talks to

Many tks! always so fast !! very good weekend
