### ISSUE TITLE
Restarting Homebridge Triggers Alexa Doorbell Notification

### ISSUE THREAD

**Issue by SMJ0724** [NorthernMan54/homebridge-alexa#441]
Everytime I restart Homebridge, I receive a doorbell notification on all of my Alexa devices. I do have a doorbell configured to issue Alexa notifications, and it works correctly when the doorbell is pressed, but can get annoying when installing plugin updates, or downright terrifying when Homebridge restarts automatically.

Nothing seems to be placed in the log when this happens, and it occurs almost immediately when shutting down the Homebridge service in order to complete a restart.

**Comment by NorthernMan54** [comment]
I have the same issue, but I find it is the restart of homebridge-camera-ffmpeg that triggers it.

How is your doorbell integrated? Ie which plugin

**Comment by SMJ0724** [comment]
I'm using Homebridge Unifi Protect

**Comment by NorthernMan54** [comment]
If you restart that plugin, does it trigger ?

**Comment by SMJ0724** [comment]
I'm unsure how to restart just one specific plugin. When I run subo hb-service restart, teh doorbell notification happens as soon as `Got SIGTERM, shutting down Homebridge...` appears in the log.

**Comment by NorthernMan54** [comment]
In my setup the Alexa plugin runs on a different raspberrypi than the camera plugin

I’m going to assume this is the same issue as I’m experiencing

**Comment by Venger2005** [comment]
> In my setup the Alexa plugin runs on a different raspberrypi than the camera plugin
> 
> I’m going to assume this is the same issue as I’m experiencing

I had this exact same issue too and yes I was running your plug-in on a different pi to the one running the doorbell plug-in.

**Comment by NorthernMan54** [comment]
Just to confirm everyone is seeing the same issue that the doorbell is being triggered when the camera-ffmpeg plugin is restarted?

**Comment by Venger2005** [comment]
> Just to confirm everyone is seeing the same issue that the doorbell is being triggered when the camera-ffmpeg plugin is restarted?

I was until I started using the native Alexa integration to trigger doorbell notifications on my echos rather than doing it via homebridge as I got fed up of phantom notifications which were no fun when they would occur at 3am.

**Comment by NorthernMan54** [comment]
Version v0.5.39 should fully resolve this issue
