### ISSUE TITLE
Need help: Alexa not finding any devices since today

### ISSUE THREAD

**Issue by aski71** [NorthernMan54/homebridge-alexa#449]
Hi,
I‘m using homebridge, homebridge-fhem and homebridge-alexa, latest versions each with node.js 12.22.1.
Today I updated homebridge-fhem to the latest version via the GUI.
Then I restarted homebridge.
Since then Alexa says my devices are not reacting.
This is true for every device.
Siri works fine.
I can‘t see anything in the logs. 
Thanks for help.
Alex

**Comment by NorthernMan54** [comment]
Please try again, the backend was down.  The current status of the backend status is monitored in the homebridge-alexa channel on the homebridge discord server.

**Comment by aski71** [comment]
Oh, thanks. Yes, it works again!
I was worried for quite a moment.
