### ISSUE TITLE
Reset HomeKit Now issues

### ISSUE THREAD

**Issue by meluvalli** [NorthernMan54/homebridge-alexa#451]
Hello.  I had reset my HomeKit completely.  I have everything working 100% except for Alexa.   I also use Google and it's working fine.

My issue:
I have several devices.   TV's as "Switches", "Lights", and "Lamps".   Issue I'm having is if I tell Alexa to turn on/off "Master Bedroom Light", it tries to turn on/off "Master Bedroom TV".  I have a device named "Master Bedroom Light" in Alexa, so I'm not sure why it's trying to turn on/off the TV.

I ended up getting so frustrated with it, I deleted my Master Bedroom TV completely.  Now, If I say "Turn Master Bedroom Light on", it says "A few things share the name Master Bedroom Light.  Which one did you want?".

I have been working on this for hours.  These are the things I have tried:
1. I have tried creating a whole new account on homebridge.ca site to start fresh.  Same Resault.
2. I have tried creating a whole new Amazon account and then creating yet another homebridge.ca account to start EXTRA fresh.  Same Resault.

I'm pulling my hair on this one!  I can't figure out what's causing Alexa not to see my devices correctly!

A little note about my setup:
In Homebridge, I have the devices named "[Device Name].[Room Name]" for simplicity when I go to add them to Google/Alexa/HomeKit.   So for example "TV.MasterBedroom" is my Master Bedroom TV and "Light.MasterBedroom" is my light.  I then go into Alexa/Google/Homekit and rename the devices and put them in the appropriate room.

Home this makes sense!  

I would appreciate any troubleshooting tips!  Not I have had this working for a long time before I reset homekit.  My Configuration hasn't changed on config.json except for my  MACAddress, and PIN.

**Comment by NorthernMan54** [comment]
A couple of comments

1 - The homebridge.ca site does not store any data related to your account and just proxy's the request from the Alexa cloud to your homebridge implemenation and vice versa, so deleting and recreating your account would have no impact.

2 - Sounds like Amazon Alexa is confused by your device naming approach and possibly device types.  I'm not an expert on how Amazon handles names and what optimizations or things they are doing to normalize names for handling voice recognition.  Also the type of device changes how she recognizes devices.

3 - To manage devices etc, I use a combination of the Alexa web site and the app, and religiously look for duplicates.

**Comment by meluvalli** [comment]
I have verified no duplicates.  So, I know that's not the issue. 

I guess I'm confused why it was working with my naming scene before, but no longer :(   But, if homebridge.ca doesn't cache devices or anything, I guess it has to be an issue on Alexa side.  Just wish I knew how to fix it :( \

I guess I could rename all my devices and setup HomeKit and Google all over again.  I can try naming them LR for Living Room, MB for Master Bedroom etc...

**Comment by meluvalli** [comment]
May I ask....  

Is it best to setup Alexa with "Groups" as the Room Name and then when you add the light to the Group, should you name the light "Light" or should you name it "[Room Name] Light" Example: "Living Room Light"

**Comment by NorthernMan54** [comment]
My setup is a little bit different and I don't put individual lights into an Alexa group, but instead use node-red to create a dummy/virtual light for each Alexa device, and group the lights to the virtual device in node-red.  

https://github.com/NorthernMan54/node-red-contrib-homebridge-automation/wiki/Stateful-Lights

And using node-red I'm able to have the each light in the group be stateful and resume previous state.  So for example, if you had manually turned on a light in the room, then ask Alexa to turn the lights and then turn them off a few minutes later the original light would remain on.  If find this feature really useful for Alexa.

**Comment by meluvalli** [comment]
Ok!  Thanks for your help!  I appreciate it!
