### ISSUE TITLE
Not able to add light to HomeBridge

### ISSUE THREAD

**Issue by CobreDev** [NorthernMan54/homebridge-alexa#453]
I have an Echo Dot, and a Sengled Lightbulb that doesn't have a hub or skill. I'd like to add it to HomeBridge, and found this plugin. However, I can't figure out how to add it, or add any device for that matter.

Am I doing something wrong, is this light not supported, or both?

Thanks!

**Comment by NorthernMan54** [comment]
Is this the same as #442

**Comment by CobreDev** [comment]
I guess it is, I was under the impression that this plug-in did both. Sorry for the trouble!
