### ISSUE TITLE
Alexa unable to find Apple TV power switch

### ISSUE THREAD

**Issue by andypburke** [NorthernMan54/homebridge-alexa#455]
I am trying to expose the Apple TV power switch so I can get Alexa to turn on/off my Apple TV.   I have installed homebridge-apple-tv-remote and it seems to work but the switch isn't discovered.  Config details below.  Any ideas what I am doing wrong?

            "name": "Apple TV Platform",
            "devices": [
                {
                    "name": "Extension 4K (App TV)",
                    "credentials": ".......",
                    "isOnOffSwitchEnabled": true,
                    "onOffSwitchName": "Apple TV Power",
                    "isOnOffTvEnabled": true,
                    "isPlayPauseSwitchEnabled": true
                }
            ],
            "platform": "AppleTvPlatform"
        },
        {
            "name": "Alexa",
            "username": "ZZZZ",
            "password": "XXX",
            "pin": "791-16-454",
            "routines": true,
            "blind": false,
            "door": false,
            "debug": false,
            "deviceListHandling": "allow",
            "combine": [
                {
                    "into": "App TV",
                    "from": [
                        "Apple TV Power"
                    ]
                }
            ],
            "platform": "Alexa"
        }
    ],

**Comment by NorthernMan54** [comment]
Did you read this section of the README ?

https://github.com/NorthernMan54/homebridge-alexa#apple-tv

and in particular the second example from my setup ?

The naming requirements need to be followed exactly or it won't work.

**Comment by andypburke** [comment]
Hi @NorthernMan54  Thanks for this.  I thought it was correct, but I have made a few more tweaks and it has now appeared.  I am just testing it now as it doesn't always switch on or off when invoked, but I think that might be an issue with the appletv-remote plugin.

**Comment by NorthernMan54** [comment]
Okay, will close this
