### ISSUE TITLE
if AID is greater than 100, device control is failing

### ISSUE THREAD

**Issue by NorthernMan54** [NorthernMan54/homebridge-alexa#46]
Spec says max value for AID is basically unlimited.  Need to revisit this.

**Comment by NorthernMan54** [comment]
Will be resolved in the next version

**Comment by jelvs** [comment]
Hey, u mean the number of the devices right? On my homebridge I have 89 accessories

**Comment by NorthernMan54** [comment]
@jelvs I'm just starting the beta test of the next version which should resolve your issue.  Details on getting access to the beta test are here.

https://github.com/NorthernMan54/homebridge-alexa/tree/Alexa2ndGen
