### ISSUE TITLE
Filter on one Homebridge doesn't find any devices

### ISSUE THREAD

**Issue by superpower10** [NorthernMan54/homebridge-alexa#462]
I have two dockers with Homebridges running on my Synology. 

Both have different plugins installed.

Homebridge-Alexa ist only installed on one Homebridge. On this Homebridge-Homematic is installed so Alexa will find and control them.

If I activate the parameter "filter" of the Homebridge-Alexa-Plugin to only find that specific Homebridge no devices are found. If I deactivate it devices from the other Homebridge are found - what I don't want.

Here some more information:

Homebridge with Alexa-Plugin:
{
    "bridge": {
        "name": "Homebridge Alexa 380",
        "username": "0E:24:36:49:A4:B7",
        "port": 51400,
        "pin": "031-45-155",
        "advertiser": "ciao"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8081,
            "platform": "config"
        },
        {
            "name": "HomeMatic CCU",
            "ccu_ip": "192.168.0.60",
            "subsection": "HomeKit",
            "enable_hmip": true,
            "enable_wired": false,
            "ios10": true,
            "platform": "HomeMatic"
        },
        {
            "name": "Alexa",
            "username": "xxxx",
            "password": "xxxxxx",
            "pin": "031-45-155",
            "routines": true,
            "blind": true,
            "debug": true,
            "filter": "192.168.0.180:51400",
            "platform": "Alexa"
        }
    ]
}

Debug output:

Starting to advertise 'Homebridge Alexa 380 0380' using ciao backend!
[9/7/2021, 5:20:13 PM] Homebridge v1.3.4 (Homebridge Alexa 380) is running on port 51400.
2021-09-07T15:20:14.901Z hapNodeJSClient HAP Device discovered Homebridge Alexa 380 0380
2021-09-07T15:20:14.903Z hapNodeJSClient Filtered HAP instance address: homebridge -> http://127.0.0.1:51400
2021-09-07T15:20:21.282Z hapNodeJSClient Ready
2021-09-07T15:20:21.283Z alexaActions alexaDiscovery
[9/7/2021, 5:20:21 PM] [Alexa] ERROR: HAP Discovery failed, please review config
2021-09-07T15:20:21.286Z alexaActions registerEvents []

**Comment by NorthernMan54** [comment]
If you look at the log it lists what instances where filtered

  2021-09-07T15:20:14.903Z hapNodeJSClient Filtered HAP instance address: homebridge -> http://127.0.0.1:51400

change your filter to match

**Comment by superpower10** [comment]
Thanks for your fast answer. That was not the problem. It was the refresh time. After that all my devices where found. :-)
