### ISSUE TITLE
Don't know how to add new devices 

### ISSUE THREAD

**Issue by paulxw** [NorthernMan54/homebridge-alexa#463]
Hi, I have the following problem,
I would like to be able to control the devices that I have added to my Alexa app via Apple Homekit.
My code cannot easily be changed without background knowledge. Maybe you could help me so that I can set the correct code.
I only have light bulbs and sockets and a controller for RGB Lightstripe. They are all stored with Alexa. Perhaps you can help me.

This is my current code:
{
     "accessories": [],
     "platforms": [
         {
             "platform": "Alexa",
             "name": "Alexa",
             "username": "***",
             "password": "***",
             "deviceListHandling": "allow",
             "pin": "031-45-154",
             "debug": false
         }
     ]
}

Thanks alot

Paul

**Comment by NorthernMan54** [comment]
This plugin does the opposite and allows homebridge devices to be controlled by Alexa.
