### ISSUE TITLE
Devices not responding temporarily

### ISSUE THREAD

**Issue by aski71** [NorthernMan54/homebridge-alexa#464]
Hi,

I'm using homebridge 1.3.4 and homebridge-alexa 0.5.42 together with homebridge-fhem 0.5.31.
Recently I'm getting "Device not responding" answers regularly from Alexa for existing devices temporarily.
If I then use Siri with the same device (same configuration: Siri via homebridge and homebridge-fhem), the respective device reacts just fine.

Like this morning: I tried to switch on a certain device by saying "Switch on <device>" to Alexa -> "Device not responding". Then I told Siri the same -> Worked. Then I said "Switch off <device>" to Alexa an hour later -> it worked again.

This happens frequently recently.
I don't know if it is connected with a node update I did. Node version is: V12.22.6 and npm is V6.14.15.

No hints in the logfiles.

Thanks for help, 
Alex

**Comment by NorthernMan54** [comment]
Pls share a log from homebridge, I’m wondering if it is losing connection?

is this a duplicate of #459 ?

**Comment by aski71** [comment]
Not sure it is, as I don't have a permanent problem, but a reoccurring one.
What type of log do you need. I don't see anything relevant in it.
How do I configure the log level?
Also: currently it works.
Happy to enable debugging and share logging once the problem reoccurs.

What is that refresh time option in the other thread and how do I modify it? Happy to try this as well with the stated beta version.

**Comment by NorthernMan54** [comment]
Issue #459 can be intermittent hence the behaviour your seeing

If you install the beta version, it uses a different keepalive value, which may resolve the issue.

**Comment by aski71** [comment]
I had the behaviour this morning that Alexa said "Device not responding" but then the command worked anyway after a certain delay. Did not see anything helpful in the log.
Installing @beta now to check if that helps.

**Comment by aski71** [comment]
Did not help. I had another "Device not responding" occurence. This time the device was not switched on.
Still not able to see anything relevant in the logs.

**Comment by aski71** [comment]
Today I also get 502 Bad Gateway when opening homebridge.ca. :-O

**Comment by NorthernMan54** [comment]
@aski71 if you watch the discord, you can see that the cloud server went offline about 5 hours ago, just restarting it now.

**Comment by aski71** [comment]
Since the server is back again I did not experience any more "Device not responding" issues. So it seems the @beta also did it for me. Thanks a lot!
