### ISSUE TITLE
homebridge.ca is offline

### ISSUE THREAD

**Issue by Loginbug** [NorthernMan54/homebridge-alexa#466]
site offline now

**Comment by phyllox** [comment]
For me too, site is answering 502 Bad gateway, and Alexa is not working anymore.
Is that temporary ?
Thanks

**Comment by lucaesse** [comment]
Me too 🥺

**Comment by charliekmcmahon** [comment]
Yup, seems like a common issue

**Comment by NorthernMan54** [comment]
If you watch the homebridge-Alexa channel on the homebridge discord server you can see that the cloud server went offline about 4 hours ago.  It has been restarted.

**Comment by phyllox** [comment]
It down again ?

**Comment by NorthernMan54** [comment]
Yes, restarting
