### ISSUE TITLE
Echo 2nd Gen Backlog

### ISSUE THREAD

**Issue by NorthernMan54** [NorthernMan54/homebridge-alexa#47]
## awsLambda - Alexa HomeSkill Lambda Function

* [x] Create Alexa homeskill to interface between Lambda and the Website
* [x] Pass Homeskill directive to website
* [x] Create toolchain to publish directly to AWS and GitHub
* [x] Cleanup and remove redundant code
* [x] Complete skill publishing details, including icons

## awsWebsite - Skill linking website

* [x] Create toolchain to publish directly to AWS and GitHub
* [x] Install Mongo DB 3.6
* [x] Install Mosquito lastest
* [x] Install Mosquito Auth Plugin
* [x] Create local/file credentials
* [x] Enable MQTT Authentication
* [x] Create alexa directive message router
* [x] Create homebridge-alexa website content
* [x] Create Authentication model to link Alexa skill to website
* [x] Route alexa directive to end user homebridge plugin using endpoint.scope.token to determine end user MQTT channel.
* [x] Pass Homeskill response from homebridge-plugin to homeskill
* [x] Add last login, last connect and last message date/time to user profile
* [x] Cleanup and remove redundant code
* [x] Reporting via Google Analytics
* [x] Create database cleanup and initialize script
* [x] Improve security of website - Block authorize screen to just Amazon REFER's
* [x] Implement - https://github.com/alexa-js/alexa-verifier-middleware

## Homebridge-Alexa plugin

* [x] Create plugin the opens a MQTTS channel to the website in Amazon lightsail
* [x] Create Module that receives alexa directives, and generate nodes events based on message namespace directive.header.namespace.  ( ie Alexa.PowerController -> event is PowerController )
* [x] Create handler for Alexa homeskill message
* [x] Implement Alexa Message Schema Validation - https://github.com/epoberezkin/ajv
* [x] All devices show up as a switch
* [x] Create event handler for Alexa.ReportState directive
* [x] Create event handler for  Alexa.TemperatureSensor directive
* [x] Create event handler for alexa.discovery directive
* [x] Create event handler for Alexa.PowerController directive
* [x] Create event handler for Alexa.PowerLevelController directive
* [x] Create event handler for Alexa.ReportState directive
* [x] Create event handler for Alexa.StateReport directive
* [x] Create event handler for Alexa.ColorController directive
* [x] Add debug level logging to enable troubleshooting users
* [x] When homebridge calls fail, return an error back to Alexa

## Clean-up prior to production

* [x] refactor awsWeb and awsLambda into a separate GitHub repository
* [x] restructure awsWeb directory structure for proper security isolation

## Device Support

* [x] Outlet ( on/off )
* [x] Light ( on/off )
* [x] Dimmable light 
* [x] Fan ( on/off/speed )
* [x] Window Coverings
* [x] Temperature Sensor
* [x] Color/RGB light

**Comment by chrisx9** [comment]
Thanks for your efforts! I can't help building stuff, but i can offer to help testing! My setup includes Echo 2nd Gen and Echo Dot 2nd, Homebridge, Philipps Hue Bridge, Ikea Tradfri, Netatmo, Denon AVR, various Plugs (via http plugin, remote and 433MHz) and a lot of ESP8266/DHT22 Sensors.

**Comment by NorthernMan54** [comment]
Tks for the offer, I’m still a few weeks away from beta testing but it is getting close.  Stay tuned, I will be looking for beta testers

**Comment by NorthernMan54** [comment]
@chrisx9 If your feeling like trying something, I'm opening up the beta test. Details are here

https://github.com/NorthernMan54/homebridge-alexa/tree/Alexa2ndGen

**Comment by chrisx9** [comment]
@NorthernMan54 Great! Where can i place questions or give feedback? E.g. i dont find the skill on the alexa app.

**Comment by NorthernMan54** [comment]
You need to send me your amazon Id / email and I will sign you up for the beta.  For privacy, I would suggest a direct message over slack.

**Comment by AndreiFAD** [comment]
hi! I can to help testing, I have 3 rip with DhtSensors, MotionSensors, IkeaTradfri, ContactSensor, broadlink rm mini 3 and relays.
