### ISSUE TITLE
Question: Only Discovering One Device.

### ISSUE THREAD

**Issue by polmv123** [NorthernMan54/homebridge-alexa#472]
I was wondering if it would be possible to only allow Alexa to discover a signle device. I have both my accessories on Homebridge and on Alexa, but there I created a "dummy switch (fake switch)" for advanced automations. Would it be possible to only show that device to Alexa, and not all the devices on Homebridge? Thanks :)

**Comment by NorthernMan54** [comment]
This is already supported, please read the README
