### ISSUE TITLE
Device not responding

### ISSUE THREAD

**Issue by Silas888** [NorthernMan54/homebridge-alexa#477]
Is there an issue with the Homebridge-Alexa plugin connection today? All devices in Alexa are offline. When I tried to disable to Homebridge app and then authenticate, I receive the error message that I'm unable to link Homebridge-Alexa with Alexa. The Homebridge-Alexa status page shows that everything is operational.

https://stats.uptimerobot.com/2WmEDHyV6/

**Comment by NorthernMan54** [comment]
See #476 

And I just experienced the same issue

**Comment by NorthernMan54** [comment]
https://downdetector.ca/status/amazon-alexa/

**Comment by djcrawleravp** [comment]
Same here
