### ISSUE TITLE
Device no response

### ISSUE THREAD

**Issue by hAMMERlized** [NorthernMan54/homebridge-alexa#479]
Hi,

all devices in the Alexa App do not response nearly the whole day. 

While checking my account at homebridge.ca I've noticed that there is an error at the account status, "5. Date of last plugin response". There is a red dot and it seems the plugin didn't response for hours.

I'm using Pi-Hole and set already the homebridge.ca URL on the whitelist.

Right now I am running the latest beta of the plugin but I got the same error while using the latest stable. Unfortunately like this the plugin is not useable.

Regards

![image](https://user-images.githubusercontent.com/95163968/145896005-60749c59-41db-442d-8d04-9d091e3fceab.png)

![image](https://user-images.githubusercontent.com/95163968/145896040-8c412e86-f28f-4eee-a029-edf9f0d391c9.png)

**Comment by NorthernMan54** [comment]
Please check your pi-hole config, your blocking communications between the plugin and the cloud servers.

**Comment by hAMMERlized** [comment]
Any ideas what exactly to check? I am not that deep into the pi hole materia. Thanks.

**Comment by NorthernMan54** [comment]
Sorry I'm not a user of Pi-Hole, so can't really say what to check

The other possibility might be the DDOS protection on the cloud servers.   Shutdown the plugin for 5 to 10 minutes, then try again.

**Comment by hAMMERlized** [comment]
Thanks for the quick response. You mean deactivating the plugin in the Homebridge Web UI and reactivating it after a few minutes?

![image](https://user-images.githubusercontent.com/95163968/145903143-4be2588c-a4ce-4eab-b432-47c5d25df2c3.jpeg)

**Comment by NorthernMan54** [comment]
Easiest it to just unplug your RPI for 5 minutes

**Comment by hAMMERlized** [comment]
Thanks for your help but it seems as I was able to solve it. I've put the following string to the redex whitelist and, so far, it seems to work.

avs-alexa-[0-9]{1,2}-(na|eu|fe).amazon.com

**Comment by hAMMERlized** [comment]
Am I right that I should be able to control the devices in the Alexa App from to go? When I am not at home?

**Comment by NorthernMan54** [comment]
That address is not part the homebridge Alexa cloud servers, I have the homebridge.ca domain.

And yes you should be control devices from the Alexa app when you are not home, not recommended though as the Home app has a significantly better user experience.

**Comment by hAMMERlized** [comment]
I have the Homebridge.ca domain also whitelisted, but today I've seen the device didn't response again, 2 times. It became better already since I whitelisted the redex link as said above, but not 100%.

**Comment by hAMMERlized** [comment]
Nope it's not solved and has nothing to do with pi-hole. Pi Hole is turned off since hours and since than the devices were already not responding.

**Comment by hAMMERlized** [comment]
Meanwhile Pi-Hole is uninstalled and the devices still do not response several times a day. Like this your plugin is useless. How about a debug log that you can take a deeper look into or something that could help you?

**Comment by NorthernMan54** [comment]
You can enable debug in the config and it will log more messages

Did you see this issue #459 ?

**Comment by hAMMERlized** [comment]
Hi,

I didn't know about that issue. I've red it and will try it this evening. 

I've also got the Warning that I have 2 duplicated devices which now appears every 450 Seconds in the homebridge protocol. Setting it down to 60 seconds will spam the log enormous. As far as I've red this warning can be ignored but is there any way to hide this in the homebridge protocol and or log?

**Comment by NorthernMan54** [comment]
Don’t adjust the refresh setting and leave it at 900 aka 15 minutes, that is the interval that the cache of accessories is refreshed, and isn’t the issue. Setting it to 60 will spam your logs as you found.

Try changing the cloud server keep alive downwards to see if it changes the behavior.

**Comment by hAMMERlized** [comment]
Left the "refresh setting" at 15 Minutes and put the "keep alive" interva to 1 Minute. Since yesterday evening, so far so good.

**Comment by kolorfilm** [comment]
I have the same problem with a fresh configured System (conbee + Alexa Homebridge + Homebridge Hue). No problem at all with HomeKit + Homebridge, but sometimes Alexa didn't respond. How can I change the "keep alive" to 60? Within the configuration? @hAMMERlized @NorthernMan54

**Comment by hAMMERlized** [comment]
With the latest beta.

**Comment by djcrawleravp** [comment]
> avs-alexa-[0-9]{1,2}-(na|eu|fe).amazon.com

whitelisting on pihole?

**Comment by hAMMERlized** [comment]
> > avs-alexa-[0-9]{1,2}-(na|eu|fe).amazon.com
> 
> 
> 
> whitelisting on pihole?

Yes

**Comment by hAMMERlized** [comment]
@NorthernMan54 The latest beta and keep alive option seemed to fix it. I think this issue can be closed. Thanks for the help.

**Comment by NorthernMan54** [comment]
Glad to hear

**Comment by kolorfilm** [comment]
After I installed the latest beta also everything works fine without any issues for me. I changed the "keep alive" to 10 minutes. Thanks guys. 🙏🏻

**Comment by djcrawleravp** [comment]
Just updated the plugin and the same error appeared again, don't remember which version was the good one

**Comment by NorthernMan54** [comment]
The beta has the fix this issue, and the latest release does not have this fix.  I needed to do a quick fix to the main release to resolve an issue with a package dependancy.

So you need to re-install the beta again.

**Comment by djcrawleravp** [comment]
Got it!, reverted to beta and everything is fine again, Thanks!

**Comment by hAMMERlized** [comment]
When can we expect an stable update with the "keep alive" option?

**Comment by WinfriedO** [comment]
Yesterday I updated the Alexa plugin and it seems the issue is back.
I tried 120 sec (this setting was lost after the update !?) and 100, 60, 50 sec. Nothing helps.
Will go back to version 0.5.50. Please advice.

**Comment by NorthernMan54** [comment]
@hAMMERlized @WinfriedO - Early today I merged the beta into the main package, and released it as 0.5.55

**Comment by djcrawleravp** [comment]
Working flawlessly!!

**Comment by NorthernMan54** [comment]
For the folks that had this issue, I launched a new beta today which uses a different protocol to connect to the cloud servers which may behave better.  You may want to give it a try.
