### ISSUE TITLE
Errors Installing...

### ISSUE THREAD

**Issue by Silentbob101** [NorthernMan54/homebridge-alexa#48]
hi, I have tried installing and getting this error

`sudo npm install -g https://github.com/NorthernMan54/homebridge
Password:
npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git clone -q https://github.com/NorthernMan54/homebridge.git /Users/Chris/.npm/_cacache/tmp/git-clone-3795fc99
npm ERR! /Users/Chris/.npm/_cacache/tmp/git-clone-3795fc99/.git: Permission denied
npm ERR! `

any help on how to get around this?

**Comment by NorthernMan54** [comment]
Please try the unsafe perms option

sudo npm install -g --unsafe-perm https://github.com/NorthernMan54/homebridge

**Comment by Silentbob101** [comment]
Hi sorry for so long between posts

tried that and still get the below error

```
MacMiniServer:~ Chris$ sudo npm install -g --unsafe-perm https://github.com/NorthernMan54/homebridge
Password:
npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git clone -q https://github.com/NorthernMan54/homebridge.git /Users/Chris/.npm/_cacache/tmp/git-clone-7e53c0bd
npm ERR! /Users/Chris/.npm/_cacache/tmp/git-clone-7e53c0bd/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Chris/.npm/_logs/2018-02-12T12_38_48_010Z-debug.log
```

**Comment by NorthernMan54** [comment]
Okay, try this this

sudo su
sudo npm install -g --unsafe-perm https://github.com/NorthernMan54/homebridge

**Comment by Silentbob101** [comment]
that did the trick... root FTW!

Thanks
