### ISSUE TITLE
Devices unavailable + duplicates

### ISSUE THREAD

**Issue by schweppy** [NorthernMan54/homebridge-alexa#486]
Hello

I regularly have issues surrounding the following found in the troubleshooting wiki - “After restarting homebridge Alexa can't find devices and needs to discover them again. Or you have duplicate devices in Alexa”

Usually I have to either restart homebridge or rediscover devices in Alexa app several times as all devices show as unavailable. 

As per the wiki, I have a port number set for homebridge. Is there anything else I can try so that I don’t get a regularly annoyed wife 😂?? 

Many thanks

**Comment by NorthernMan54** [comment]
Did you see this issue and the workaround 'keep alive' setting that is available with the current beta release ?

https://github.com/NorthernMan54/homebridge-alexa/issues/479

**Comment by schweppy** [comment]
Sorry I didn’t! Will play with those settings and report back! Many thanks

**Comment by WinfriedO** [comment]
updated to 0.5.55, looks better

**Comment by aski71** [comment]
@NorthernMan54 
I experience something quite similar now with 0.5.55.
After a recent reboot there is on device where I get "Device is unresponsive".
It's a Philips Hue Light configured in fhem.
Switching on/off and dimming via Siri and homebridge works fine, though.
Any thoughts?

**Comment by NorthernMan54** [comment]
@aski71 have you tried asking Alexa to discover devices again?

**Comment by aski71** [comment]
Yes. Alexa does not find any new devices.

**Comment by NorthernMan54** [comment]
But does it now work?

**Comment by aski71** [comment]
Ok. You got me. 😂
As it did not find anything and it did not look any different in the Alexa App UI, that was the one thing I didn't try.
Yes. It works again.

**Comment by NorthernMan54** [comment]
Asking Alexa to discover devices again refreshes the device cache on the Alexa side and fixes a broken device mapping like this.
