### ISSUE TITLE
Nbr Messages too high back with v53 ?

### ISSUE THREAD

**Issue by Pblondin123** [NorthernMan54/homebridge-alexa#487]
Hi, i was scratching my head some messages were not executed by Alexa, to find out that the message too high error was occuring in 53.   I reverted back to v51 in the meantime and will troubleshoot.

**Comment by NorthernMan54** [comment]
51 is the beta release with some more features than 53.  53 was a quick fix for a production issue

the numbering is a bit screwy as I had to increment past the beta release number to publish the master

shortly I will be merging the beta into master/production release

**Comment by NorthernMan54** [comment]
Release 0.5.55 now includes the beta features, so no issue with future updates.

**Comment by Pblondin123** [comment]
> Release 0.5.55 now includes the beta features, so no issue with future updates.

Thanks.   Installed and testing.
