### ISSUE TITLE
All devices offline after upgrade to 0.5.53

### ISSUE THREAD

**Issue by aski71** [NorthernMan54/homebridge-alexa#488]
Hi, I just upgraded to 0.5.53.
Now all my devices are offline in Alexa.
hombridge.ca shows this:
<img width="614" alt="Bildschirmfoto 2022-01-01 um 13 19 42" src="https://user-images.githubusercontent.com/5214169/147850447-18155bdd-b599-4c06-9110-0e17e32d2768.png">

Thanks for help.

**Comment by NorthernMan54** [comment]
Anything in the logs ?

I'm thinking you may have tripped the DDOS protection on the cloud servers.  Stop homebridge for 5 minutes, then try again.

**Comment by aski71** [comment]
Stopping and starting worked.
How do I prevent this from happening again?
It seems to have come in with 0.5.53. Everything worked fine before I updated.

I don't see anything additional in the logs.

**Comment by NorthernMan54** [comment]
The DDOS protection on the cloud servers will start blocking an IP address if it sees too many new connections in a short period of time.  Stopping homebridge for a few minutes allows the DDOS to reset.  I'm thinking that during the update process you stopped and started homebridge a couple of time pretty quickly and that triggered it.

DDOS has been on the cloud servers for almost a year, so if you have been running for a while you might not have been tripped up by it.

**Comment by aski71** [comment]
Ok, interesting. Thanks.

Before I opened the ticket I did the following:
Restarted everything and it worked again.
Then went out for a few hours and when I came back I had the same status as above again.
Then I stopped homenbridge again for about an hour or so and restarted it.

Since then it seems to be stable. I'll observe.

**Comment by NorthernMan54** [comment]
Tks

**Comment by aski71** [comment]
I'm experiencing the same symptom again this morning (see screenshot above).
No reboots or anything in the meantime.
Just normal operation. Now 5 is red again.
As I said this is since I upgraded to 0.5.53. 
Before that no issue whatsoever.

**Comment by aski71** [comment]
Now even stopping and restarting after 15 minutes doesn't solve the problem anymore.

**Comment by NorthernMan54** [comment]
Did you see this issue and the workaround 'keep alive' setting that is available with the current beta release ?

https://github.com/NorthernMan54/homebridge-alexa/issues/479

**Comment by aski71** [comment]
Thanks, looked at it but am confused what to do now.

It talks about some sort of whitelisting, but I have no clue what to whitelist where.
And it talks about adjusting a keep alive time, but again not where this setting can be tweaked and I can't find it.

Can you provide some more insight what needs to be adjusted where?

Thanks.

**Comment by NorthernMan54** [comment]
If you install the beta version, it exposes a new tuning option called keep alive. You can try adjusting that to 10 or lower to see if resolves the issue

**Comment by aski71** [comment]
How do I do this? Installing the beta?

**Comment by aski71** [comment]
Can you point me in the right direction, please?
Same issue this morning again. :-(

**Comment by NorthernMan54** [comment]
I went and merged the beta release into production this AM, so version 0.5.55 includes the feature "Cloud Server Connection Keepalive", try setting it to 10 minutes or lower.

**Comment by aski71** [comment]
Ok, thanks.
I updated and set it to 10 minutes.
Will observe.

**Comment by aski71** [comment]
Looking good with 10 minutes.
No more outage for the last 24 hours.

**Comment by NorthernMan54** [comment]
Fingers crossed
