### ISSUE TITLE
Devices don't response

### ISSUE THREAD

**Issue by ellagan** [NorthernMan54/homebridge-alexa#493]
Hello,

I have the same issues than #488.
I stopped Homebridge for 30 min and it came back  but failed again. It randomly stops working after some time.

My homebridge system perfectly workss with other assistants (Siri and Google)

My plugin version : 0.5.55
I tried several keepalive settings with no success with several versions of the plugin.
Turned on the debug logs : no errors in logs whatever the plugin version
Rolled back to 0.5.53beta : same issue and no errors in logs.
Tried with homebridge installed in Docker and natively in Ubuntu VM.

All my network installation is behind a virtualized PFSense firewall and DNS served by Pi-Hole (Regex for homebridge.ca and avs-alexa-[0-9]{1,2}-(na|eu|fe).amazon.com whitelisted.

![alexa_bridge](https://user-images.githubusercontent.com/36123818/149079180-9a2ef3e9-6b88-4750-8e55-ece46ee650e6.png)
![homebridge_ca](https://user-images.githubusercontent.com/36123818/149079198-fcc745a3-5b22-45b2-8c40-0a69e914389f.png)

**Comment by NorthernMan54** [comment]
If you have tried lowering the "Cloud Server Connection Keepalive" down to as low as 1, and the issue re-occurs I'm a bit stumped.  Can you reach out to me via the homebridge-discord server and the "homebridge-alexa" channel ?

https://discord.gg/87UeeEt2

**Comment by NorthernMan54** [comment]
Issue was resolved by end user tuning their firewall settings (pfsense) to increase the idle timeout to over 20 minutes
