### ISSUE TITLE
No response or sending minutes later 

### ISSUE THREAD

**Issue by idna001** [NorthernMan54/homebridge-alexa#494]
Hello,

I have the Plugin since 2019 in everyday action. But now the last few months my Alexa has a few issues to send the commands to homebridge.
In the Apple Home App, it's working all fine. But Alexa is not responding at all sometimes, or seems to act without effect . Sometimes it even turns on only after a few minutes
.
Here you can see that not every command get a response:
![grafik](https://user-images.githubusercontent.com/46223359/149399652-cad81a96-df33-4b55-b4c8-5bc895d38f0d.png)

Maybe it is that from a new update?
Does someone have a similar problem?
Or know how I can fix that? 

Because it's pretty annoying when it's not working.

Here are my Sets: 
Node.js Version: v16.13.1
npm: v8.3.0
Homebridge Version: v1.3.9 

All running on Raspberry 3B.
Thanks for hints, help or fix.

Greetings
idna

**Comment by NorthernMan54** [comment]
In 0.5.55 their is a tuning option called  "Cloud Server Connection Keepalive", try lowering it to 10 minutes or lower.

**Comment by idna001** [comment]
Thx for hint. 
Where can I find this "Cloud Server Connection keepalive"?

In der Homebridge config?
In the code?

Idna001

**Comment by NorthernMan54** [comment]
If your using the homebridge UI it is listed as an advanced option.

**Comment by WinfriedO** [comment]
I exchanged my hardware, had a first gen. pi, but this could not be updated to hoobs 4. 
On the Pi 3B+ I now installed Hoobs 4 and the plugins I had in use. And now...
Have Alexa plugin 0.5.55 , have again connection problems and do not find a "keep alive" setting..

**Comment by NorthernMan54** [comment]
The keepalive setting is keepalive, try starting at 10 and decrease as needed

**Comment by WinfriedO** [comment]
ok, super

**Comment by idna001** [comment]
Okay I found it, thanks :-)
I have reduced it to 8, and I will see what happens in the next days.
I will let you know.

**Comment by WinfriedO** [comment]
Think 10 means 10 Minutes but the setting is in seconds. I at least added

"keepalive" : 120

in the advanced config for 2 minutes. This is what I had on the old Pi and works now for a day..

**Comment by idna001** [comment]
Why do you think that it means seconds?
I use the UI, and there it says minutes.
Here is a screenshot:
<img width="757" alt="Bildschirmfoto 2022-01-15 um 17 55 31" src="https://user-images.githubusercontent.com/46223359/149630456-2a84670d-448d-4217-a8b7-b19d13a061b1.png">

**Comment by NorthernMan54** [comment]
I actually coded it as seconds or minutes, if the number is greater than 60 it is seconds, and less than 60 it is minutes 

Hence the 10 minute comment

**Comment by idna001** [comment]
Ah, tricky

**Comment by NorthernMan54** [comment]
For the folks with this issue, I launched a new beta today which uses a different protocol to connect to the cloud servers which may behave better.  You may want to give it a try.

**Comment by idna001** [comment]
Wow great.
So far reducing the keepalive value, works also - no issues so far.
But I will also try the beta.

Thanks for your great support.

**Comment by WinfriedO** [comment]
installed the beda, eleminated the "keepalive" setting, now running half an hour without problems.
Will now leave and be back in about 8 hours and then check again.

**Comment by WinfriedO** [comment]
well running, so thx

**Comment by swilalaa** [comment]
Same issue here - tried to tweak the keepalive to 10 minutes and didn't help - now testing v0.5.60-beta.0

In case you need the full cleaned log, have a look here (according to homebridge.ca last plugin response was Tue Jan 25 2022 10:11:54 GMT / my system time is running on CET though): 


[swilalaa_errorlog.txt](https://github.com/NorthernMan54/homebridge-alexa/files/7933232/swilalaa_errorlog.txt)

**Comment by NorthernMan54** [comment]
There was an operational event with the cloud servers overnight which might explain this.  Has the issue resolved ?

**Comment by swilalaa** [comment]
The issue is with the current beta still persistent (just now)

2022-01-25T14:31:47.355Z alexaLocal reconnect
[25/01/2022, 15:31:47] [Alexa] ERROR: ( homebridge-alexa) You have an issue with your installation, please review the README.

**Comment by swilalaa** [comment]
As it keeps re-connecting here and there after a while without changing any other parameters in my setup it could be indeed a cloud problem
