### ISSUE TITLE
Accessories not responding

### ISSUE THREAD

**Issue by Stetocasa** [NorthernMan54/homebridge-alexa#496]
I had the issue already last week,turning keep alive at 1 second this solved.
Today after homebridge reboot the plug-in stops to work 
![image](https://user-images.githubusercontent.com/70729310/149636668-301ec174-6396-45f9-b43c-a9eb9e927cf6.png)
![image](https://user-images.githubusercontent.com/70729310/149636672-c16c0217-3ab8-4161-b92d-08384787f9be.png)

I have installed the last version plug-in

**Comment by NorthernMan54** [comment]
Have you possibly tripped the DDOS protection due to too many restarts in a short period of time.  Stop the plugin or your RPI for five minutes and try again.

**Comment by Stetocasa** [comment]
> Have you possibly tripped the DDOS protection due to too many restarts in a short period of time.  Stop the plugin or your RPI for five minutes and try again.

I disabled the plug-in and await 20 minutes.
After enable again the issue persist
All accessory not responding

**Comment by NorthernMan54** [comment]
Is the date of last plugin response still not updating?

**Comment by Stetocasa** [comment]
> Is the date of last plugin response still not updating?

Yes

**Comment by NorthernMan54** [comment]
Ok, are you available in about 2 hours on the homebridge discord server, want to look deeper at this.

**Comment by Stetocasa** [comment]
> Ok, are you available in about 2 hours on the homebridge discord server, want to look deeper at this.

I live in Italy, could you provide another slot tomorrow ?

**Comment by NorthernMan54** [comment]
9am eastern aka Toronto / New York ?

**Comment by Stetocasa** [comment]
> 9am eastern aka Toronto / New York ?

That's fine, talk tomorrow at 9am NYC on Discord

**Comment by Stetocasa** [comment]
> 9am eastern aka Toronto / New York ?

What's the link for discord ?

**Comment by NorthernMan54** [comment]
Resolved by having the end user re-install the plugin.  It appears that something happened while updating the plugin and the plugin was left in a non-functional state.
