### ISSUE TITLE
Devices not responding / homebridge.ca down (504)

### ISSUE THREAD

**Issue by kolorfilm** [NorthernMan54/homebridge-alexa#497]
All alexa devices are not responding. It seems the reason is homebridge.ca that is currently down (504 gateway timeout)?

**Comment by kolorfilm** [comment]
Seems to be fixed! Thanks.

**Comment by jcalmeida** [comment]
Is it really fixed? My Alexa say all my devices are not responding for a few days now. homebridge.ca seems to be working and Home (apple) and Google can manage my devices just right. It's only alexa that stopped working.
Homebridge logs shows Alexa discovering the devices. Have any ideas how to sort this out?

**Comment by NorthernMan54** [comment]
Had an operational issue a couple of days ago and has been stable for at least 72 hours, so if your having issues it is something else.
