### ISSUE TITLE
homebridge.ca 504 Gateway Time-out

### ISSUE THREAD

**Issue by AlexKusnezov** [NorthernMan54/homebridge-alexa#498]
Hey Guys,

today I had no response on any of my alexa devices, then I tried to re-activate the skill and got this:

**504 Gateway Time-out**

is the server down?

**Comment by Fsalvanha** [comment]
Same issue for me!!! I tried the website to check status and the message is the same.

**Comment by Fsalvanha** [comment]
It is back online!!! @NorthernMan54  you are the MAN!!!!

**Comment by NorthernMan54** [comment]
When is something going to crash, when your sleeping. :-(
