### ISSUE TITLE
Plug-in not responding

### ISSUE THREAD

**Issue by josecarlosmoimaz** [NorthernMan54/homebridge-alexa#499]
Firstly, thanks for all your work on this plugin, I’m using it for more than 2 years. Recently, my Alexa stopped controlling my devices, there is no error showing on logs, but in homebridge.ca I can see that the plug-in is not responding, it shows a red mark, everything else is ok, plug-in log in, Alexa command, but it’s not responding any more. If I restart the raspberry, It works for some short time, and then stops again.

**Comment by josecarlosmoimaz** [comment]
I have already updated everything I could, docker compose, homebridge server, all the plugins, also reactivated the skill, but I keeps happening.

**Comment by NorthernMan54** [comment]
It could be one of 2 things

1 - The cloud server DDOS protection was tripped, to reset it, stop Homebridge / VM for about 5 minutes then start it again

2 - Cloud server connection keepalive, try changing the setting down to 10 or 5 minutes
