### ISSUE TITLE
Beta test

### ISSUE THREAD

**Issue by Luftloch80** [NorthernMan54/homebridge-alexa#50]
Great Progress. Any Plans for a Beta Test.

**Comment by NorthernMan54** [comment]
I will absolutely be doing alpha and beta testing.  Keep an eye out in a few weeks.

**Comment by NorthernMan54** [comment]
Instructions to get access to the beta are here

https://github.com/NorthernMan54/homebridge-alexa/tree/Alexa2ndGen
