### ISSUE TITLE
Device becomes unresponsive on Alexa

### ISSUE THREAD

**Issue by mariomaz87** [NorthernMan54/homebridge-alexa#502]
Hi,
I've just installed the plugin and configured one switch to be available in Alexa. I added the switch, it worked for a while but then became "unresponsive" on Alexa. If I reset Homebridge it works again for a few minutes and then stops. On Homebride.ca check number 5 is red (Date of last plugin response), everything else is green. 
This is my config:

{
    "name": "Alexa",
    "username": "xxx",
    "password": "xxx",
    "pin": "481-71-980",
    "routines": false,
    "blind": false,
    "door": false,
    "debug": false,
    "deviceListHandling": "allow",
    "deviceList": [
        "Dummytvspentaalexa"
    ],
    "platform": "Alexa"
}

Can you suggest somethings? Thanks!

**Comment by mariomaz87** [comment]
Thanks, I tried installing the latest beta and the problem seems solved. Do you want me to try installing the previous version and try your settings?

**Comment by alekz44** [comment]
> Please try lowering the KeepAliveTimeout setting, to 10 minutes or 5 minutes

Facing the same issue since yesterday.
KeepAliveTimout is „9“.

Any other suggestions?

**Comment by NorthernMan54** [comment]
@alekz44 Can you try disabling the skill and enable it again on the Amazon Alexa App

**Comment by alekz44** [comment]
> @alekz44 Can you try disabling the skill and enable it again on the Amazon Alexa App

Will try it tomorrow.
I guess all Homebridge devices than have to be reconnected? Will be some work with 56 devices :(

**Comment by NorthernMan54** [comment]
They should just reconnect

**Comment by alekz44** [comment]
Thank you very much! Works again! And all devices still in correct order.
Hope it stays.
Thanks again!!:)
