### ISSUE TITLE
Doorbell isn't being triggered

### ISSUE THREAD

**Issue by GrumpyGoslin** [NorthernMan54/homebridge-alexa#505]
Hi,

I have setup my nest hello (wired) doorbell to alert when someone press the button through homebridge-google-nest-sdm and this is happening successfully, with a notification appearing on multiple apple devices

I want to then get Alexa to notify everyone that this has happened as well. However it doesn't seem to trigger at all.

Alexa App can see a Device as a "Front Doorbell" through homebridge-alexa and I have enabled it in the app.

Is there something I am missing? Here is the config

```
  {
            "name": "Alexa",
            "username": "xxxxx",
            "password": "xxxxx",
            "pin": "same-as-homebridge",
            "routines": true,
            "blind": false,
            "door": false,
            "debug": false,
            "deviceListHandling": "allow",
            "platform": "Alexa"
        },
```

**Comment by NorthernMan54** [comment]
A few questions

1 - what is your account status on homebridge.ca?  Can you share a screen shot of the status.

2 - Any log messages in the homebridge console

**Comment by GrumpyGoslin** [comment]
Thanks for getting back so fast 
![image](https://user-images.githubusercontent.com/6287706/156010078-9c1975f5-eec3-4d62-af85-4edc44696c41.png)


I do get some messages about Duplicates which I am not sure I can do anything about....

`[28/02/2022, 14:15:50] [Alexa] ERROR: HAP Discovery failed, please review config
[28/02/2022, 14:23:12] [Alexa] WARNING: Duplicate device name Front Door Doorbell
[28/02/2022, 14:23:12] [Alexa] WARNING: Duplicate device name Front Door Doorbell
[28/02/2022, 14:23:12] [Alexa] WARNING: Duplicate device name Kitchen Camera
[28/02/2022, 14:23:12] [Alexa] WARNING: Duplicate device name Living Room Camera`

**Comment by GrumpyGoslin** [comment]
Just an update on this, I can create a routine that works with the motion detection and announces itself, so just seems to be the doorbell trigger that isn't being processed

**Comment by NorthernMan54** [comment]
The warnings are just a warning and not an issue

this is concerning, as the message is only triggered when no devices are being passed to Alexa

** ERROR: HAP Discovery failed, please review config**

and I’m wondering if this is blocking something, ** "deviceListHandling": "allow",** without a device list

also item 6 on the status updates for each doorbell or sensor message, so it should update for a doorbell press.

**Comment by GrumpyGoslin** [comment]
So after I wired up the motions events it's started to work which I find probably a coincidence.

There is a 10 second delay however so I am now investigating the root behind it. It is probably related to [458](https://github.com/NorthernMan54/homebridge-alexa/issues/458) so will try narrowing the deviceListHandling as suggested.

Create plugin though. So great to be able to wire up my Nest doorbell to Alexa where most sights say it can't be done.

Thanks

**Comment by NorthernMan54** [comment]
Tks for the update
