### ISSUE TITLE
Alexa PowerController TurnOff CD:22:3D:E3:CE:64 undefined null

### ISSUE THREAD

**Issue by dastr010** [NorthernMan54/homebridge-alexa#509]
Describe the bug
Not really a bug just a quick question

I changed from "homebridge hue" plugin to the "Homebridg deconz" plugin. When I say "Alexa turn on Lamp Kitchen" I notice that I  get in the Homebridge log "undefined null". It works as expected but I'm just interested what the "undefined null" means.

Example:
[27.3.2022, 19:37:26] [Alexa] PowerController TurnOn CD:22:3D:E3:CE:64 undefined null
[27.3.2022, 19:39:37] [Alexa] PowerController TurnOff CD:22:3D:E3:CE:64 undefined null

**Comment by NorthernMan54** [comment]
The undefined and null are where errors would appear from the request.  Undefined and null is a good response
