### ISSUE TITLE
Question compatability 

### ISSUE THREAD

**Issue by jelvs** [NorthernMan54/homebridge-alexa#51]
Hey nice project, I have a a proper homebridge system already implemented with a lot of things,and I would like to connect an echo as you describe on ur project and I don't have the patience to do all over again for another platform. When u said echo 2 generation isn't supported , u are saying all of them right? the dot The normal echo & plus right? I'm really interested in this project, if u want any help testing or developing, maybe I can help u with something.

Cheers keep up with the good work,

Tiago

**Comment by NorthernMan54** [comment]
I have an echo 2nd generation purchased in Nov 2017, and it does not discover homebridge-alexa devices, and I have an echo dot 2nd generation purchased in the spring of 2017, and it discovers homebridge-alexa devices.  And if they are both in your house, the echo 2nd generation can control homebridge-alexa.

If you can wait for a bit, I’m well down the path of creating the next version which will work with an echo 2nd generation.

**Comment by jelvs** [comment]
Oh nice, I'll wait, I'm going to receive today the echo dot 2 generation, u recommend to wait then? Cheers thks for your reply

**Comment by NorthernMan54** [comment]
Your call, your dot should work with the current version.

**Comment by jelvs** [comment]
Hey, after your reply, I give it a try by installing all the necessarys to make it work, I'm not sure if it was all necessary I installed the special homebridge, and homebridge-alexa.then I I added the ssdp:1900, I tried with that, and also tried with the platform alexa, cause I didn't know for sure what was necessary. I have in my homebridge, the homebridge aqara for the xiaomi devices and the broadlink, I have two of them. I installed everything and run it, it starts, but when I ask alexa to discover devices it starts by executing a command that I have for the broadlink with the name stop, that works for a IR command to stop a playback from an android box, I'm going to use DE debug mode then I'll post here or on slack, what do I have to do to have access to slack? Do u know what could it be? 

Thank u so much, Cheers

Tiago

**Comment by NorthernMan54** [comment]
A debug log would be helpful, and a log of the command you used to install this version, and any output from that.  After reading what you said you may have installed too much.


The slack invite is here, https://github.com/nfarina/homebridge down in the community section

**Comment by jelvs** [comment]
hey, i'm doing the debug write know as we speak. For the debug log it seems the alexa discovers all but in the alexa app it seems that doesn't found anything , first i uninstall the homebridge and the nodejs. then i installed the special version sudo npm install -g --unsafe-perm https://github.com/NorthernMan54/homebridge. after that i tried it with this with ssdp:1900. and failed so i installed the sudo npm install -g --unsafe-perm https://github.com/NorthernMan54/homebridge-alexa, but didn't do nothing else, do u want me to post here the debug or in slack?

**Comment by NorthernMan54** [comment]
Slack or here, Whatever is easier for yourself.

**Comment by jelvs** [comment]
[Untitled.zip](https://github.com/NorthernMan54/homebridge-alexa/files/1719768/Untitled.zip)
here u go

**Comment by NorthernMan54** [comment]
This issue is a case issue #46
