### ISSUE TITLE
Last Plugin Response issue after purchase 

### ISSUE THREAD

**Issue by brsexton** [NorthernMan54/homebridge-alexa#513]
Hello. I downloaded and installed this plugin last Saturday and got everything up and running perfectly I had been so busy with work, I didn't get a chance to purchase the plugin, but I knew I would have time today. I made the purchase and everything turned green except for the Last Plugin Response. That is still red and nothing works. I have changed the keep alive time to 1, I have reinstalled the Skill, I have reinstalled the Homebridge Plugin, and I have disabled the plugin for at least 30 minutes. Nothing seems to resolve the plug response error. 

I assumed everything would just begin working again once I made the purchase, but that doesn't seem to be the case. I was wondering if anyone can assist me with this? Thanks in advance. 
![Screen Shot 2022-04-09 at 10 01 43 AM](https://user-images.githubusercontent.com/90535815/162577857-35839170-2c34-494d-9e81-f8d1cee1fa50.png)

**Comment by NorthernMan54** [comment]
@brsexton - Can you DM me via the Homebridge discord server ? https://discord.gg/efg9ZESr

Want to look at your account details, and this issue.  Seems like you have already tried the usual issues

**Comment by brsexton** [comment]
> @brsexton - Can you DM me via the Homebridge discord server ? https://discord.gg/efg9ZESr
> 
> Want to look at your account details, and this issue. Seems like you have already tried the usual issues

**Comment by brsexton** [comment]
@NorthernMan54  - I have created an account and sent you a DM.

**Comment by brsexton** [comment]
Problem was resolved quickly by @NorthernMan54. Seems to have been an issue with my account stuck on the expired trial.
