### ISSUE TITLE
Alexa timeout? Hm, I'm having trouble reaching null.

### ISSUE THREAD

**Issue by ashbyjm** [NorthernMan54/homebridge-alexa#516]
After an overnight or other period of disuse, Alexa fails to execute the command and says "Hm, I'm having trouble reaching null." Homebridge Alexa Cloud Services reflects the failure of the last command. Afterward, trying it with other devices or groups it still fails. I can still operate the device from the Homebridge Accessory page. However, if I wait a few hours it will often fix itself. Rebooting Homebridge also fixes it. Any suggestions on how to address this?

The devices are supported by the Insteonlocal plug-in, and will always work from Homebridge or the Apple Home app.  Alexa, however, is dropping out several times a day.

**Comment by NorthernMan54** [comment]
This sounds similar to #510, please try adjusting the same setting.

**Comment by ashbyjm** [comment]
Great news! I noted that the original _Keepalive_ value after installation was 30, so I had already set it back to 20 which the software notes as the default value. But as you indicated in [#510](https://github.com/NorthernMan54/homebridge-alexa/issues/510), I set it down to 10. It's stayed online since last night!
Thanks again for your support- I'll go ahead and subscribe.
