### ISSUE TITLE
Can't login/ can't create new account/ still being charged

### ISSUE THREAD

**Issue by alittler** [NorthernMan54/homebridge-alexa#518]
(I know this isn't really a coding issue, but whatever.)

The title says it all - I made an account to subscribe with, and a few days later, I stopped being able to log in. I tried recreating my account with the same password, email, username and all that jazz, and while they all get those sweet, sweet check marks, I still get this error: ** A user with the given username is already registered **

I would have brought it up earlier, but I just got charged after the seven day demo, which suddenly makes my inability to log in a bit more of an issue.

🤷

**Comment by NorthernMan54** [comment]
Can you reach out to me directly via the homebridge discord server, I need your username in order to find the account and other details and want to keep your info private.

Discord link https://discord.gg/6WBNPUauvA

**Comment by NorthernMan54** [comment]
We chatted via discord and identified that the user had never validated their email address hence the service issue and inability to reset their password.

To resolve I had the user create a new account, and canceled the old account, and subscription. Also refunded the subscription.
