### ISSUE TITLE
Echo 2nd Gen Phase 2 Backlog

### ISSUE THREAD

**Issue by NorthernMan54** [NorthernMan54/homebridge-alexa#52]
## awsWebsite - Skill linking website

* [ ] Implement message routing to homebridge instance
* [ ] Enable MQTTS
* [x] Automate SSL Cert renewall process
* [x] Automate DNS link process

### Yamaha Stereo Integration

* [ ] Each Zone is a separate device ( Two Zones - Front and Rear )
* [ ] Ability to change volume and inputs.  Can presets be used for channels?
* [ ] Integration for Yamaha Stereo - Fork homebridge-yamaha to homebridge-yamahaAlexa and custom characteristics for ones not supported by HomeKit
* [ ] Integration for Yamaha Stereo - Turn things on and off | Alexa.PowerController
* [ ] Integration for Yamaha Stereo - Change the channel on a device | Alexa.ChannelController
* [ ] Integration for Yamaha Stereo - Change the input of a playback device | Alexa.InputController
* [ ] Integration for Yamaha Stereo - Change the volume in incremental steps | Alexa.StepSpeaker
* [ ] Integration for Yamaha Stereo - Change the volume to anywhere on a continuous range | Alexa.Speaker

### Not supporting this feature

* [ ] Integration for Yamaha Stereo - Control the playback of device; fast forward, rewind and pause | Alexa.PlaybackController

### Other Backlog items

* [ ] Add homebridge instance name to cookie
* [ ] Subscribe to messages based on instance name
* [ ] Create event handler for Alexa.BrightnessController directive
* [x] Create event handler for Alexa.ColorTemperatureController message
* [ ] Create event handler for Alexa.LockController message
* [ ] Create event handler for Alexa.ThermostatController message
* [ ] Create event handler for Alexa.PercentageController message
* [ ] Create event handler for Alexa.ChangeReport message
* [ ] Create event handler for Alexa.DeferredResponse message
* [ ] Create event handler for Alexa.EndpointHealth message
* [ ] Create event handler for Alexa.SceneController message
* [ ] Fix state report for window coverings/blinds
* [x] Need to manage homebridge add and remove devices

## HAPNode-JS

* [ ] Determine method for accessing accessories and accessory events in HAPNode-JS

### Device Support

**Comment by jt8277** [comment]
Hi NorthernMan54, I have tried to contact you through Slack, but cannot seem to do so.  Could we get in touch so you can set my Amazon login to your list of Beta testers, because I am keen to try this new version, which looks amazing so far.

**Comment by jt8277** [comment]
Thanks for letting me know, that will be great.  

I have been waiting for something like this.

**Comment by Sheldor81** [comment]
Hello,

Can you please add me to the beta list?

Thank you

greeting
Michael

**Comment by NorthernMan54** [comment]
I will need your amazon login to add you to the beta, or if you can wait a few days I should be published by then.   Submitted yesterday for the second time.

**Comment by Sheldor81** [comment]
Hi,
where can I send you my Amazon ID? Do not want to post her here.

greeting

**Comment by NorthernMan54** [comment]
I’m on homebridge’s slack as northernman54

You can access slack here

https://slackin-znyruquwmv.now.sh

**Comment by jt8277** [comment]
Hi NorthernMan54,
I wanted to take the time to thank you for your efforts with this.  I have just seen the Homebridge Skill on Amazon, and setup the details on my homebridge server.  Despite the names coming through a bit weird (which I think is my fault) they were discovered without issue by Alexa.

So thank you very much for this.  I am really happy now.

Yours
JT

**Comment by vaadkins** [comment]
Why when the homebridge device type is a "fan" does it show up as a "light" in Alexa?  If you must use a generic device type then a "switch" would be better than a "light".  Whenever you say "Alexa lights on" in a specific room if the fan is in that room and it is set up as a light then it comes on.  If it was set up as a switch it wouldn't do that.

**Comment by NorthernMan54** [comment]
As Alexa doesn’t have support for fans, I needed to map them to something close to the features of a fan, which was on/off and speed.  So I picked a dimmable light bulb which was closet.  For the issue you are describing, in my groups/rooms I just left the fan out of the group.  Problem solved.

**Comment by Daniel167** [comment]
Sorry i Need Filter for 2 switch.

**Comment by Daniel167** [comment]
Ok Thanks. I hope i can two switch Import to Alexa. Because in homebridge i have 70 switch and i Need two from this.

**Comment by LucLisette** [comment]
Alexa listens and reacts to my command but nothing happens.
I use in homekit this sort of http commands with succes on raspberry pi
On another Pi with Alexa working she wont do it, she says yes but that is it.
Here an example of my command in config.json:

"accessory": "HTTP-SWITCH",
"name": "Light",
"switchType": "stateless",
"onUrl": "http://192.168.1.7/command?XC_USER=Name@xxxx.be&XC_PASS=LLXXXXXXGG&XC_FNC=doAction&id=02/switchOn"

Could you please tell me what is wrong? Thank you.

**Comment by NorthernMan54** [comment]
If you start homebridge with debug logging, homebridge-Alexa will log everything it receives from Alexa.  Can you collect this and open a separate issue.

Tks

**Comment by LucLisette** [comment]
Hello,

That problem is solved, I made a mistake? sorry. Just new to all this.

Another problem occurs. In the json file I have to write what stands below:
This works fine with the first solved problem and the accesoiries.

"platforms": [{
			"platform": "Alexa",
			"name": "Alexa",
			"username": “……...",
			"password": “……..;”



But I also have GPIO ’s working in homekit and would like them to integrade in Alexa.
I just don’t know how I proceed with the two platforms.
Below is a working peace in homebridge for homekit.
Could you tell me how to join the two platforms together in config.json?


> "platforms": [
>         {
>             "platform" : "WiringPiPlatform",
>             "name" : "Pi GPIO (WiringPi)",
>             "overrideCache" : "false",
>             "autoExport" : "true",
> 	    "gpiopins" : [{
> 		        "name" : "Hek open",
> 		        "pin"  : 22,
>                 	"enabled" : "true",
> 		        "mode" : "out",
>                 	"pull" : "up",
> 		        "inverted" : "true",
>                 	"duration" : 500,
> 			"polling" : "true"
> 	    },{
> 		        "name" : "Hek dicht",
> 		        "pin"  : 5,
>                 	"enabled" : "true",
> 		        "mode" : "out",
>                 	"pull" : "up”,…………………

Best regards,

Luc


> Op 5 jun. 2018, om 18:15 heeft Northern Man <notifications@github.com> het volgende geschreven:
> 
> If you start homebridge with debug logging, homebridge-Alexa will log everything it receives from Alexa. Can you collect this and open a separate issue.
> 
> Tks
>

**Comment by NorthernMan54** [comment]
@LucLisette If you search the issue log on the main homebridge repository how to add multiple platforms in a single repository has been answered several times already.

**Comment by LucLisette** [comment]
Thank you

> Op 5 jun. 2018 om 18:15 heeft Northern Man <notifications@github.com> het volgende geschreven:
> 
> If you start homebridge with debug logging, homebridge-Alexa will log everything it receives from Alexa. Can you collect this and open a separate issue.
> 
> Tks
>

**Comment by LucLisette** [comment]
Hello again,

Sorry but I still have a problem.
Everything seems to work fine and as it should, except when I reboot the pi.

This is what I get:

> [2018-6-6 12:25:46] [Pi GPIO (WiringPi)] Loading cached GPIO pins complete
> events.js:165
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: listen EADDRINUSE :::51820
>     at Server.setupListenHandle [as _listen2] (net.js:1346:14)
>     at listenInCluster (net.js:1387:12)
>     at Server.listen (net.js:1475:7)
>     at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
>     at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
>     at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:607:16)
>     at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:126:16)
>     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:96:10)
>     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
>     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
> Emitted 'error' event at:
>     at emitErrorNT (net.js:1366:8)
>     at process._tickCallback (internal/process/next_tick.js:178:19)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
>     at startup (internal/bootstrap/node.js:201:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)


I have to change the “name” and “port” in the config.json file.
Then in the Alexa app do a new device discovery and then it works.

When I reboot again the same happens, I can then go to the previous name and port, make a new discovery and it works again.
Every reboot this happens. Can you tell me what is going on?

Regards


Luc



> Op 5 jun. 2018, om 18:15 heeft Northern Man <notifications@github.com> het volgende geschreven:
> 
> If you start homebridge with debug logging, homebridge-Alexa will log everything it receives from Alexa. Can you collect this and open a separate issue.
> 
> Tks
>

**Comment by LucLisette** [comment]
Forgotten something,

> ERROR: ( homebridge-alexa) You have an issue with your installation, please review the README.

Even when evrything is working  this missage repeates. I dont’ know what it means?


Luc 


> Op 5 jun. 2018, om 18:15 heeft Northern Man <notifications@github.com> het volgende geschreven:
> 
> If you start homebridge with debug logging, homebridge-Alexa will log everything it receives from Alexa. Can you collect this and open a separate issue.
> 
> Tks
>

**Comment by NorthernMan54** [comment]
These are all symptoms of the same issue, it appears that you are running homebridge twice.  Am thinking you have one instance starting up with auto start scripts and the second you are starting from the command line.

**Comment by LucLisette** [comment]
Hey,

Please tell me how to solve it. I'm a newbee with almost no experiance.
How can I shut down the wrong homebridge.
How do I integrate " homebridge -l" for start on bootup?

Thank you

Luc

> Op 6 jun. 2018 om 18:41 heeft Northern Man <notifications@github.com> het volgende geschreven:
> 
> These are all symptoms of the same issue, it appears that you are running homebridge twice. Am thinking you have one instance starting up with auto start scripts and the second you are starting from the command line.
> 
>

**Comment by NorthernMan54** [comment]
As a newbie this could get complex, as how to add the -I really depends on which auto start scripts you use. In the readme how to add this to systemd is documented.

Which guide did you follow to setup homebridge?

**Comment by LucLisette** [comment]
Hey,

Autostart with systemd I followed the script by Pyssel in the pdf I send you with this mail.

In this script homebridge.service for Alexa, I think, is autostarted. It’s in /etc/systemd/system


[Unit]
Description=Node.js HomeKit Server 
After=syslog.target network-online.target
         
[Service]
Type=simple
User=pi
# Could be /usr/local/bin/homebridge
ExecStart=/usr/bin/homebridge
Restart=on-failure
RestartSec=10
KillMode=process
         
[Install]
WantedBy=multi-user.target


In a second script homebridge_Siri.service is the autostart for Siri homebridge. Also in /etc/systemd/system


[Unit]
Description=Node.js HomeKit Server 
After=syslog.target network-online.target
         
[Service]
Type=simple
User=pi
# Could be /usr/local/bin/homebridge
ExecStart=/usr/bin/homebridge -U /home/pi/.homebridge_Siri
Restart=on-failure
RestartSec=10
KillMode=process
         
[Install]
WantedBy=multi-user.target


I know yhe -I is in the readme but I dont know how to implement it in the script.
Final goal is to run Siri and Alexa side by side on he same raspberry pi.
More or less it seems to work then I can command both.

Just problem with autostart and error with Alexa alltough she reponds to commands.

Thank you for helping me

Regards

Luc






Op 6 jun. 2018, om 21:15 heeft Northern Man <notifications@github.com> het volgende geschreven:
> 
> As a newbie this could get complex, as how to add the -I really depends on which auto start scripts you use. In the readme how to add this to systemd is documented.
> 
> Which guide did you follow to setup homebridge?
>

**Comment by LucLisette** [comment]
Hello,

I also gave the next command in terminal to stop “one” homebridge.
Then your debug command gave me no errors anymore.
"sudo systemctl disable homebridge” 

 Luc

Op 6 jun. 2018, om 21:15 heeft Northern Man <notifications@github.com> het volgende geschreven:
> 
> As a newbie this could get complex, as how to add the -I really depends on which auto start scripts you use. In the readme how to add this to systemd is documented.
> 
> Which guide did you follow to setup homebridge?
>

**Comment by NorthernMan54** [comment]
The -I goes in /etc/default/homebridge in the line HOMEBRIDGE_OPTS

Please look at the README

**Comment by LucLisette** [comment]
Hello,

I did read the readme several times, over and over again. 
On my pi I can not find /etc/default/homebridge, it just does not exists. (not even hidden)
In the /etc/default/ folder there is no homebridge file.
So I can not change HOMEBRIDGE_OPTS because can not find it.

Homebridge is apparently not installed in a default place.




> Op 7 jun. 2018, om 13:00 heeft Northern Man <notifications@github.com> het volgende geschreven:
> 
> The -I goes in /etc/default/homebridge in the line HOMEBRIDGE_OPTS
> 
> Please look at the README
> 
> Sent from my iPad
>

**Comment by NorthernMan54** [comment]
The creation of that file is a separate step and is documented here on the wiki as part of start on boot up.

https://github.com/nfarina/homebridge/wiki

**Comment by LucLisette** [comment]
Hello again,

Homebridge is starting on reboot but Alexa doesn'tt work. 
When I do "sudo systemctl status homebridge” after reboot homebrigde is always running. (and on the correct port)

In debug mode afer every reboot I get an "Error: listen EADDRINUSE :::51819” .
When I change the port number in json and try debug again a “name" error appears. Changing the name also and everything works.
So after every reboot I have to change port and name in the json file.

could you give me some help?

Luc



Op 7 jun. 2018, om 19:21 heeft Northern Man <notifications@github.com> het volgende geschreven:
> 
> The creation of that file is a separate step and is documented here on the wiki as part of start on boot up.
> 
> https://github.com/nfarina/homebridge/wiki
>

**Comment by NorthernMan54** [comment]
Luc,

If you want to run in DEBUG mode you need to stop the instance running under systemctl first, then you can start in DEBUG mode.  Only one instance of homebridge can use a particular config.json at a time.  This is because the file contains the port number, which causes the error you are seeing.

To stop homebridge under systemctl try this

sudo systemctl stop homebridge

**Comment by LucLisette** [comment]
Hey,

I already discovered it yesterday by accident. Debug mode starts homebridge a second time. So to use debug I stop the already running homebridge first, then debug.
Finally I got it working. It ’s easy when you know it. 

Thank you and success with wathever is you do,

Luc


> Op 12 jun. 2018, om 19:30 heeft Northern Man <notifications@github.com> het volgende geschreven:
> 
> Luc,
> 
> If you want to run in DEBUG mode you need to stop the instance running under systemctl first, then you can start in DEBUG mode. Only one instance of homebridge can use a particular config.json at a time. This is because the file contains the port number, which causes the error you are seeing.
> 
> To stop homebridge under systemctl try this
> 
> sudo systemctl stop homebridge
> 
> 
> 
>

**Comment by LucLisette** [comment]
Hi,

Is it possible to change the wake-up word? If so how can I do it?
I have to say several times "alexa" different ways before she responds.
Perhaps an other wake-up word is better.

Luc

**Comment by NorthernMan54** [comment]
Luc,

The wake word and speech recognition quality is part of the amazon Alexa eco system and not part of the plugin itself.  With that said I think you can change the wake word from the Alexa app in settings.

**Comment by mitnits** [comment]
I have 2 Alexa dots in different corners of the house. I’d like to achieve the following: when I say “Alexa turn off tv” or “Alexa turn off A/C” it would run the command that shuts off device near to where I am :). So far I achieved this using wemo emulation and by signing up to different amazon accounts on different echo dots. In wemo emulation you get the IP of issuing echo dot and can differentiate further. 

Any suggestions on how to set this up using homebridge Alexa? I was thinking maybe running two homebridge instances side-by-side?

**Comment by NorthernMan54** [comment]
Unfortunately the amazon Alexa API doesn’t expose any details about which Alexa device made the request.  So the only way to achieve this would be what you are already thinking about, two Amazon alexa accounts, two linking accounts and two instances of homebridge-Alexa.

Then use a routine to pick the proper device.

**Comment by Garywoo** [comment]
Hi @NorthernMan54,

Is the ability to whitelist/blacklist devices to be discovered by Alexa on the roadmap?
I'm running a second instance of Homebridge to do this right now, but would really prefer not to have to.
Most of my devices are supported by Alexa though skills already, so I don't want to add duplicate devices though this plugin. I only want one or two devices exposed to Alexa for discovery. Running a whole separate instance of Homebridge seems like overkill for such a minor configuration change.
Enabling the filter property to whitelist more than one device would be perfect. What do you think?

Great work on the plugin so far!
- Gary

**Comment by NorthernMan54** [comment]
@Garywoo I can add this to the list, but it might be a while before I can get to it.  Current focus is AV Controller and Speakers

**Comment by b2un0** [comment]
@Garywoo @NorthernMan54  i'm awaiting for the same, see #80
