### ISSUE TITLE
Bond Plugin Awnings Not Responsive

### ISSUE THREAD

**Issue by peternear** [NorthernMan54/homebridge-alexa#521]
I use the Homebridge Plugin "Homebridge Bond" which exposes devices connected to the Bond RF bridge.  Lights and fans connected via this plugin are passed through to Alexa and work.  My Blinds connected via this plugin work fine in Homebridge, are discovered in Alexa as Window Blinds, but show as "Device is Unresponsive" in Alexa with no controls.  

Happy to provide more info.

**Comment by NorthernMan54** [comment]
Can you share a homebridge accessory dump from your blinds ?

https://github.com/NorthernMan54/homebridge-alexa#homebridge-accessory-dump

**Comment by peternear** [comment]
I've updated the IP and port, PIN appears to be default, but here's the error I'm getting.  {"statusCode":415,"message":"Unsupported Media Type: Application/json"}

I'm over on the Discord channel as well now if that's easier for realtime troubleshooting

**Comment by peternear** [comment]
The output wasn't well formatted at all sorry, but I wanted to paste it as-is.

{"accessories":[{"aid":1,"services":[{"type":"3E","iid":1,"characteristics":[{"type":"14","iid":2,"perms":["pw"],"description":"Identify","format":"bool"},{"type":"20","iid":3,"value":"homebridge.io","perms":["pr"],"description":"Manufacturer","format":"string","maxLen":64},{"type":"21","iid":4,"value":"homebridge","perms":["pr"],"description":"Model","format":"string","maxLen":64},{"type":"23","iid":5,"value":"Homebridge E63D 3A55","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"30","iid":6,"value":"0E:04:8E:2A:E6:3D","perms":["pr"],"description":"Serial Number","format":"string","maxLen":64},{"type":"52","iid":7,"value":"1.4.1","perms":["pr"],"description":"Firmware Revision","format":"string"}]},{"type":"A2","iid":2000000008,"characteristics":[{"type":"37","iid":9,"value":"1.1.0","perms":["pr"],"description":"Version","format":"string","maxLen":64}]}]},{"aid":12,"services":[{"type":"3E","iid":1,"characteristics":[{"type":"14","iid":2,"perms":["pw"],"description":"Identify","format":"bool"},{"type":"20","iid":3,"value":"homebridge-alexa","perms":["pr"],"description":"Manufacturer","format":"string","maxLen":64},{"type":"21","iid":4,"value":"Default-Model","perms":["pr"],"description":"Model","format":"string","maxLen":64},{"type":"23","iid":5,"value":"Alexa","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"30","iid":6,"value":"homebridge","perms":["pr"],"description":"Serial Number","format":"string","maxLen":64},{"type":"52","iid":7,"value":"0.5.63","perms":["pr"],"description":"Firmware Revision","format":"string"}]},{"type":"80","iid":8,"characteristics":[{"type":"23","iid":9,"value":"Alexa","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"6A","iid":10,"value":0,"perms":["ev","pr"],"description":"Contact Sensor State","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]}]}]},{"aid":2,"services":[{"type":"3E","iid":1,"characteristics":[{"type":"14","iid":2,"perms":["pw"],"description":"Identify","format":"bool"},{"type":"20","iid":3,"value":"Chamberlain","perms":["pr"],"description":"Manufacturer","format":"string"},{"type":"21","iid":4,"value":"WiFi GDO AC 3/4 HP","perms":["pr"],"description":"Model","format":"string"},{"type":"23","iid":5,"value":"Garage Door Opener","perms":["pr"],"description":"Name","format":"string"},{"type":"30","iid":6,"value":"CG086013D105","perms":["pr"],"description":"Serial Number","format":"string"},{"type":"52","iid":7,"value":"3.12","perms":["pr"],"description":"Firmware Revision","format":"string"}]},{"type":"41","iid":8,"characteristics":[{"type":"23","iid":9,"value":"Garage Door Opener","perms":["pr"],"description":"Name","format":"string"},{"type":"32","iid":11,"value":1,"perms":["pr","pw","ev"],"description":"Target Door State","format":"uint8","minValue":0,"maxValue":1,"valid-values":[0,1]},{"type":"E","iid":10,"value":1,"perms":["pr","ev"],"description":"Current Door State","format":"uint8","minValue":0,"maxValue":4,"valid-values":[0,1,2,3,4]},{"type":"24","iid":12,"value":0,"perms":["pr","ev"],"description":"Obstruction Detected","format":"bool"}],"primary":true}]},{"aid":3,"services":[{"type":"3E","iid":1,"characteristics":[{"type":"14","iid":2,"perms":["pw"],"description":"Identify","format":"bool"},{"type":"20","iid":3,"value":"Bond (snowbird)","perms":["pr"],"description":"Manufacturer","format":"string"},{"type":"21","iid":4,"value":"Default-Model","perms":["pr"],"description":"Model","format":"string"},{"type":"23","iid":5,"value":"My Room Deck Fan","perms":["pr"],"description":"Name","format":"string"},{"type":"30","iid":6,"value":"BD2790100000003","perms":["pr"],"description":"Serial Number","format":"string"},{"type":"52","iid":7,"value":"2.17.4.3","perms":["pr"],"description":"Firmware Revision","format":"string"}]},{"type":"40","iid":8,"characteristics":[{"type":"23","iid":9,"value":"My Room Deck Fan","perms":["pr"],"description":"Name","format":"string"},{"type":"25","iid":10,"value":1,"perms":["pr","pw","ev"],"description":"On","format":"bool"},{"type":"29","iid":11,"value":3,"perms":["pr","pw","ev"],"description":"Rotation Speed","format":"float","unit":"percentage","minValue":0,"maxValue":3,"minStep":1}]},{"type":"43","iid":12,"characteristics":[{"type":"23","iid":13,"value":"My Room Deck Fan Light","perms":["pr"],"description":"Name","format":"string"},{"type":"25","iid":14,"value":0,"perms":["pr","pw","ev"],"description":"On","format":"bool"}]},{"type":"49","iid":15,"characteristics":[{"type":"23","iid":16,"value":"Toggle Light State","perms":["pr"],"description":"Name","format":"string"},{"type":"25","iid":17,"value":0,"perms":["pr","pw","ev"],"description":"On","format":"bool"}]}]},{"aid":4,"services":[{"type":"3E","iid":1,"characteristics":[{"type":"14","iid":2,"perms":["pw"],"description":"Identify","format":"bool"},{"type":"20","iid":3,"value":"Bond (snowbird)","perms":["pr"],"description":"Manufacturer","format":"string"},{"type":"21","iid":4,"value":"Default-Model","perms":["pr"],"description":"Model","format":"string"},{"type":"23","iid":5,"value":"Master Bedroom Bedroom Fan","perms":["pr"],"description":"Name","format":"string"},{"type":"30","iid":6,"value":"BD2790100000018","perms":["pr"],"description":"Serial Number","format":"string"},{"type":"52","iid":7,"value":"2.17.4.3","perms":["pr"],"description":"Firmware Revision","format":"string"}]},{"type":"40","iid":8,"characteristics":[{"type":"23","iid":9,"value":"Master Bedroom Bedroom Fan","perms":["pr"],"description":"Name","format":"string"},{"type":"25","iid":10,"value":0,"perms":["pr","pw","ev"],"description":"On","format":"bool"},{"type":"29","iid":11,"value":0,"perms":["pr","pw","ev"],"description":"Rotation Speed","format":"float","unit":"percentage","minValue":0,"maxValue":3,"minStep":1}]},{"type":"43","iid":12,"characteristics":[{"type":"23","iid":13,"value":"Master Bedroom Bedroom Fan Light","perms":["pr"],"description":"Name","format":"string"},{"type":"25","iid":14,"value":0,"perms":["pr","pw","ev"],"description":"On","format":"bool"}]},{"type":"49","iid":15,"characteristics":[{"type":"23","iid":16,"value":"Toggle Light State","perms":["pr"],"description":"Name","format":"string"},{"type":"25","iid":17,"value":0,"perms":["pr","pw","ev"],"description":"On","format":"bool"}]}]},{"aid":5,"services":[{"type":"3E","iid":1,"characteristics":[{"type":"14","iid":2,"perms":["pw"],"description":"Identify","format":"bool"},{"type":"20","iid":3,"value":"Bond (snowbird)","perms":["pr"],"description":"Manufacturer","format":"string"},{"type":"21","iid":4,"value":"Default-Model","perms":["pr"],"description":"Model","format":"string"},{"type":"23","iid":5,"value":"Patio Awning","perms":["pr"],"description":"Name","format":"string"},{"type":"30","iid":6,"value":"BD27901309f740c","perms":["pr"],"description":"Serial Number","format":"string"},{"type":"52","iid":7,"value":"2.17.4.3","perms":["pr"],"description":"Firmware Revision","format":"string"}]},{"type":"8C","iid":8,"characteristics":[{"type":"23","iid":9,"value":"Patio Awning","perms":["pr"],"description":"Name","format":"string"},{"type":"6D","iid":10,"value":0,"perms":["pr","ev"],"description":"Current Position","format":"uint8","unit":"percentage","minValue":0,"maxValue":100,"minStep":1},{"type":"7C","iid":11,"value":0,"perms":["pr","pw","ev"],"description":"Target Position","format":"uint8","unit":"percentage","minValue":0,"maxValue":100,"minStep":100},{"type":"72","iid":12,"value":0,"perms":["pr","ev"],"description":"Position State","format":"uint8","minValue":0,"maxValue":2,"valid-values":[0,1,2]}]},{"type":"49","iid":13,"characteristics":[{"type":"23","iid":14,"value":"Toggle State","perms":["pr"],"description":"Name","format":"string"},{"type":"25","iid":15,"value":0,"perms":["pr","pw","ev"],"description":"On","format":"bool"}]},{"type":"49","iid":16,"characteristics":[{"type":"23","iid":17,"value":"Preset","perms":["pr"],"description":"Name","format":"string"},{"type":"25","iid":18,"value":0,"perms":["pr","pw","ev"],"description":"On","format":"bool"}]}]},{"aid":10,"services":[{"type":"3E","iid":1,"characteristics":[{"type":"14","iid":2,"perms":["pw"],"description":"Identify","format":"bool"},{"type":"20","iid":3,"value":"Elgato","perms":["pr"],"description":"Manufacturer","format":"string","maxLen":64},{"type":"21","iid":4,"value":"Elgato Key Light Air","perms":["pr"],"description":"Model","format":"string","maxLen":64},{"type":"23","iid":5,"value":"Right Keylight","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"30","iid":6,"value":"CW12K1A01050","perms":["pr"],"description":"Serial Number","format":"string","maxLen":64},{"type":"52","iid":7,"value":"1.0.3","perms":["pr"],"description":"Firmware Revision","format":"string"}]},{"type":"43","iid":8,"characteristics":[{"type":"23","iid":10,"value":"Elgato Key Light Air 6248","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"24B","iid":15,"value":0,"perms":["ev","pr"],"description":"Characteristic Value Active Transition Count","format":"uint8"},{"type":"144","iid":13,"value":"AQYBAQsCAQEAAAEGAQEMAgEC","perms":["pr"],"description":"Supported Characteristic Value Transition Configuration","format":"tlv8"},{"type":"143","iid":14,"value":"","perms":["pr","pw","wr"],"description":"Characteristic Value Transition Control","format":"tlv8"},{"type":"25","iid":9,"value":0,"perms":["ev","pr","pw"],"description":"On","format":"bool"},{"type":"8","iid":11,"value":8,"perms":["ev","pr","pw"],"description":"Brightness","format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1},{"type":"CE","iid":12,"value":204,"perms":["ev","pr","pw"],"description":"Color Temperature","format":"int","minValue":143,"maxValue":344,"minStep":1}]}]},{"aid":11,"services":[{"type":"3E","iid":1,"characteristics":[{"type":"14","iid":2,"perms":["pw"],"description":"Identify","format":"bool"},{"type":"20","iid":3,"value":"Elgato","perms":["pr"],"description":"Manufacturer","format":"string","maxLen":64},{"type":"21","iid":4,"value":"Elgato Key Light Air","perms":["pr"],"description":"Model","format":"string","maxLen":64},{"type":"23","iid":5,"value":"Left Keylight","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"30","iid":6,"value":"CW26K1A03661","perms":["pr"],"description":"Serial Number","format":"string","maxLen":64},{"type":"52","iid":7,"value":"1.0.3","perms":["pr"],"description":"Firmware Revision","format":"string"}]},{"type":"43","iid":8,"characteristics":[{"type":"23","iid":10,"value":"Left Keylight","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"24B","iid":15,"value":0,"perms":["ev","pr"],"description":"Characteristic Value Active Transition Count","format":"uint8"},{"type":"144","iid":13,"value":"AQYBAQsCAQEAAAEGAQEMAgEC","perms":["pr"],"description":"Supported Characteristic Value Transition Configuration","format":"tlv8"},{"type":"143","iid":14,"value":"","perms":["pr","pw","wr"],"description":"Characteristic Value Transition Control","format":"tlv8"},{"type":"25","iid":9,"value":0,"perms":["ev","pr","pw"],"description":"On","format":"bool"},{"type":"8","iid":11,"value":25,"perms":["ev","pr","pw"],"description":"Brightness","format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1},{"type":"CE","iid":12,"value":204,"perms":["ev","pr","pw"],"description":"Color Temperature","format":"int","minValue":143,"maxValue":344,"minStep":1}]}]},{"aid":6,"services":[{"type":"3E","iid":1,"characteristics":[{"type":"14","iid":2,"perms":["pw"],"description":"Identify","format":"bool"},{"type":"20","iid":3,"value":"Nest","perms":["pr"],"description":"Manufacturer","format":"string","maxLen":64},{"type":"21","iid":4,"value":"Home/Away Control","perms":["pr"],"description":"Model","format":"string","maxLen":64},{"type":"23","iid":5,"value":"Home Occupied","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"30","iid":6,"value":"b286ef10-6807-11ec-99bd-0acbc7963578","perms":["pr"],"description":"Serial Number","format":"string","maxLen":64},{"type":"52","iid":7,"value":"1.0","perms":["pr"],"description":"Firmware Revision","format":"string"}]},{"type":"49","iid":8,"characteristics":[{"type":"23","iid":9,"value":"Home Occupied","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"25","iid":10,"value":1,"perms":["ev","pr","pw"],"description":"On","format":"bool"}]}]},{"aid":7,"services":[{"type":"3E","iid":1,"characteristics":[{"type":"14","iid":2,"perms":["pw"],"description":"Identify","format":"bool"},{"type":"20","iid":3,"value":"Nest","perms":["pr"],"description":"Manufacturer","format":"string","maxLen":64},{"type":"21","iid":4,"value":"Topaz-2.33","perms":["pr"],"description":"Model","format":"string","maxLen":64},{"type":"23","iid":5,"value":"Upstairs Hallway","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"30","iid":6,"value":"06CA01AC3721041L","perms":["pr"],"description":"Serial Number","format":"string","maxLen":64},{"type":"52","iid":7,"value":"3.4rc6","perms":["pr"],"description":"Firmware Revision","format":"string"}]},{"type":"87","iid":8,"characteristics":[{"type":"23","iid":10,"value":"Upstairs Hallway Smoke","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"76","iid":9,"value":0,"perms":["ev","pr"],"description":"Smoke Detected","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"79","iid":11,"value":0,"perms":["ev","pr"],"description":"Status Low Battery","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"75","iid":12,"value":1,"perms":["ev","pr"],"description":"Status Active","format":"bool"},{"type":"D6D47D29-4643-4F44-B53C-D84015DAEBDB","iid":13,"value":0,"perms":["pr","ev"],"description":"Manual Test Active","format":"bool"}]},{"type":"7F","iid":14,"characteristics":[{"type":"23","iid":16,"value":"Upstairs Hallway Carbon Monoxide","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"69","iid":15,"value":0,"perms":["ev","pr"],"description":"Carbon Monoxide Detected","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"79","iid":17,"value":0,"perms":["ev","pr"],"description":"Status Low Battery","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"75","iid":18,"value":1,"perms":["ev","pr"],"description":"Status Active","format":"bool"},{"type":"D6D47D29-4643-4F44-B53C-D84015DAEBDB","iid":19,"value":0,"perms":["pr","ev"],"description":"Manual Test Active","format":"bool"}]},{"type":"86","iid":20,"characteristics":[{"type":"23","iid":21,"value":"Upstairs Hallway Occupancy","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"71","iid":22,"value":0,"perms":["ev","pr"],"description":"Occupancy Detected","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]}]}]},{"aid":8,"services":[{"type":"3E","iid":1,"characteristics":[{"type":"14","iid":2,"perms":["pw"],"description":"Identify","format":"bool"},{"type":"20","iid":3,"value":"Nest","perms":["pr"],"description":"Manufacturer","format":"string","maxLen":64},{"type":"21","iid":4,"value":"Topaz-2.9","perms":["pr"],"description":"Model","format":"string","maxLen":64},{"type":"23","iid":5,"value":"Ground Hallway","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"30","iid":6,"value":"06AA01AC102109HQ","perms":["pr"],"description":"Serial Number","format":"string","maxLen":64},{"type":"52","iid":7,"value":"3.4rc6","perms":["pr"],"description":"Firmware Revision","format":"string"}]},{"type":"87","iid":8,"characteristics":[{"type":"23","iid":10,"value":"Ground Hallway Smoke","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"76","iid":9,"value":0,"perms":["ev","pr"],"description":"Smoke Detected","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"79","iid":11,"value":0,"perms":["ev","pr"],"description":"Status Low Battery","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"75","iid":12,"value":1,"perms":["ev","pr"],"description":"Status Active","format":"bool"},{"type":"D6D47D29-4643-4F44-B53C-D84015DAEBDB","iid":13,"value":0,"perms":["pr","ev"],"description":"Manual Test Active","format":"bool"}]},{"type":"7F","iid":14,"characteristics":[{"type":"23","iid":16,"value":"Ground Hallway Carbon Monoxide","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"69","iid":15,"value":0,"perms":["ev","pr"],"description":"Carbon Monoxide Detected","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"79","iid":17,"value":0,"perms":["ev","pr"],"description":"Status Low Battery","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"75","iid":18,"value":1,"perms":["ev","pr"],"description":"Status Active","format":"bool"},{"type":"D6D47D29-4643-4F44-B53C-D84015DAEBDB","iid":19,"value":0,"perms":["pr","ev"],"description":"Manual Test Active","format":"bool"}]}]},{"aid":9,"services":[{"type":"3E","iid":1,"characteristics":[{"type":"14","iid":2,"perms":["pw"],"description":"Identify","format":"bool"},{"type":"20","iid":3,"value":"Nest","perms":["pr"],"description":"Manufacturer","format":"string","maxLen":64},{"type":"21","iid":4,"value":"Topaz-2.9","perms":["pr"],"description":"Model","format":"string","maxLen":64},{"type":"23","iid":5,"value":"Basement","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"30","iid":6,"value":"06AA01AC1021062U","perms":["pr"],"description":"Serial Number","format":"string","maxLen":64},{"type":"52","iid":7,"value":"3.4rc6","perms":["pr"],"description":"Firmware Revision","format":"string"}]},{"type":"87","iid":8,"characteristics":[{"type":"23","iid":10,"value":"Basement Smoke","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"76","iid":9,"value":0,"perms":["ev","pr"],"description":"Smoke Detected","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"79","iid":11,"value":0,"perms":["ev","pr"],"description":"Status Low Battery","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"75","iid":12,"value":1,"perms":["ev","pr"],"description":"Status Active","format":"bool"},{"type":"D6D47D29-4643-4F44-B53C-D84015DAEBDB","iid":13,"value":0,"perms":["pr","ev"],"description":"Manual Test Active","format":"bool"}]},{"type":"7F","iid":14,"characteristics":[{"type":"23","iid":16,"value":"Basement Carbon Monoxide","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"69","iid":15,"value":0,"perms":["ev","pr"],"description":"Carbon Monoxide Detected","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"79","iid":17,"value":0,"perms":["ev","pr"],"description":"Status Low Battery","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"75","iid":18,"value":1,"perms":["ev","pr"],"description":"Status Active","format":"bool"},{"type":"D6D47D29-4643-4F44-B53C-D84015DAEBDB","iid":19,"value":0,"perms":["pr","ev"],"description":"Manual Test Active","format":"bool"}]}]}]}bash-5.1#

**Comment by NorthernMan54** [comment]
Closing as we spoke via discord
