### ISSUE TITLE
Alexa response is fast but it takes long until it is ready for next action (blue ring flashes about 5 seconds)

### ISSUE THREAD

**Issue by kolorfilm** [NorthernMan54/homebridge-alexa#522]
Hi,

I actually don't know if this has something to do with the plugin, but since a few weeks my alexa devices (mainly dots) takes very long to stop the actual feedback (blue ring flashes). The actual call and response is fast, but it takes very long (~5-10seconds) until the device is ready for the next action. Everything looks good on homebridge.ca everything is green.

Setup:

- PI3b+
- Homebridge (latest version all up to date)
- latest version of homebridge-alexa as well
- Cloud Server Connection Keepalive is set to 10 (worked for me very well, but anything lower makes also no difference as I checked that)

Any ideas what the problem could be?

**Comment by NorthernMan54** [comment]
Under the covers a voice command is a single message and response.   Does Alexa respond quickly with the status of the request?  Or is that delayed as well.

**Comment by kolorfilm** [comment]
The response (for instance turn the lights on) is fast, but the blue ring remains flashing afterwards for about 5-10s. This only happens when controlling Homebridge devices.

**Comment by NorthernMan54** [comment]
This is a bit odd, as a request is just a single request with a single response indicating success or an issue.  And if she is quickly acknowledging the successful request quickly, I’m a bit stumped.

**Comment by kolorfilm** [comment]
https://user-images.githubusercontent.com/26705027/169372246-7260fd26-5811-4b9f-9d92-b840ca863565.MOV

**Comment by kolorfilm** [comment]
The Apple Home App is fast, also with Siri. No spinner at all. As I said, the light turns off immediately, but then it takes long.

**Comment by NorthernMan54** [comment]
That would be the success response being slow

let me see if I can recreate the issue

**Comment by NorthernMan54** [comment]
Well for me it is very quick, can you share your username for the cloud servers, I want to take a look and see what is occurring for your account when a request is processed.

If your not comfortable posting the username here, you can DM me directly thru the Homebridge discord server.

**Comment by NorthernMan54** [comment]
@kolorfilm - This should now be resolved

To recreate the issue, you needed to have an Alexa group with multiple devices, and control them via voice.  When using the app, the issue did not occur.

**Comment by kolorfilm** [comment]
I can confirm it works now! Many thanks!

**Comment by kolorfilm** [comment]
Hi @NorthernMan54 👋🏻 ,

since a few days (can't exactly say since when) I have the same problem again. A group takes long(er) to respond.

**Comment by kolorfilm** [comment]
It is fixed for me with latest beta 0.8.0-beta.15. Thanks 🙏🏻
