### ISSUE TITLE
Logs scaring me....

### ISSUE THREAD

**Issue by userbosco** [NorthernMan54/homebridge-alexa#523]
Jumped into HOOBS this AM to do a backup and an update, took a peak at my logs and went a little pop-eyed from the amount of red coming from Alexa plug-in.  Everything is green on the Homebridge dashboard, so not sure if I am going chicken little or if this is a symptom of something worth sharing...so here it is:

5/20/2022, 9:11:31 AMAlexa BridgeERROR2022-05-20T13:11:18.543Z hapNodeJSClient Starting Homebridge instance discovery
5/20/2022, 9:11:31 AMAlexa BridgeERROR2022-05-20T13:11:18.547Z alexaLocal Connecting to Homebridge Smart Home Skill
5/20/2022, 9:11:31 AMAlexa BridgeERROR2022-05-20T13:11:19.416Z hapNodeJSClient HAP Device discovered Insteon Local Bridge 1C69
5/20/2022, 9:11:31 AMAlexa BridgeERROR2022-05-20T13:11:19.685Z alexaLocal connect command/MCFLY@1516/#
5/20/2022, 9:11:31 AMAlexa BridgeERROR2022-05-20T13:11:19.837Z hapNodeJSClient Homebridge instance discovered HOOBS with 13 accessories
5/20/2022, 9:11:31 AMAlexa BridgeERROR2022-05-20T13:11:20.378Z hapNodeJSClient HAP Device discovered Alexa Bridge 5CE4
5/20/2022, 9:11:31 AMAlexa BridgeERROR2022-05-20T13:11:20.508Z hapNodeJSClient Homebridge instance discovered HOOBS with 2 accessories
5/20/2022, 9:11:38 AMAlexa BridgeERROR2022-05-20T13:11:38.547Z hapNodeJSClient Ready
5/20/2022, 9:11:38 AMAlexa BridgeERROR2022-05-20T13:11:38.550Z alexaActions alexaDiscovery
5/20/2022, 9:11:38 AMAlexa BridgeERROR2022-05-20T13:11:38.605Z alexaActions Cookie Object:  570
5/20/2022, 9:11:38 AMAlexa BridgeERROR2022-05-20T13:11:38.609Z alexaActions Cookie Object:  283
5/20/2022, 9:11:38 AMAlexa BridgeERROR2022-05-20T13:11:38.610Z alexaActions Cookie Object:  570
5/20/2022, 9:11:38 AMAlexa BridgeERROR2022-05-20T13:11:38.611Z alexaActions Cookie Object:  283
5/20/2022, 9:11:38 AMAlexa BridgeERROR2022-05-20T13:11:38.611Z alexaActions Cookie Object:  280
5/20/2022, 9:11:38 AMAlexa BridgeERROR2022-05-20T13:11:38.612Z alexaActions Cookie Object:  570
5/20/2022, 9:11:38 AMAlexa BridgeERROR2022-05-20T13:11:38.612Z alexaActions Cookie Object:  570
5/20/2022, 9:11:38 AMAlexa BridgeERROR2022-05-20T13:11:38.612Z alexaActions Cookie Object:  570
5/20/2022, 9:11:38 AMAlexa BridgeERROR2022-05-20T13:11:38.613Z alexaActions Cookie Object:  283
5/20/2022, 9:11:38 AMAlexa BridgeERROR2022-05-20T13:11:38.613Z alexaActions Cookie Object:  570
5/20/2022, 9:11:38 AMAlexa BridgeERROR2022-05-20T13:11:38.614Z alexaActions Cookie Object:  570
5/20/2022, 9:11:38 AMAlexa BridgeERROR2022-05-20T13:11:38.615Z alexaActions Cookie Object:  283
5/20/2022, 9:11:38 AMAlexa BridgeERROR2022-05-20T13:11:38.616Z alexaActions Cookie Object:  115
5/20/2022, 9:11:38 AMAlexa BridgeERROR2022-05-20T13:11:38.625Z alexa:Messages INFO: DeviceList empty feature not enabled or config error in deviceListHandling
5/20/2022, 9:11:38 AMAlexa BridgeERROR2022-05-20T13:11:38.626Z alexaActions registerEvents [
5/20/2022, 9:11:38 AMAlexa BridgeERROR'{"deviceID":"AD:DC:DA:3B:95:3C","aid":3,"iid":14}': {
5/20/2022, 9:11:38 AMAlexa BridgeERROR'0': 'NOT_DETECTED',
5/20/2022, 9:11:38 AMAlexa BridgeERROR'1': 'DETECTED',
5/20/2022, 9:11:38 AMAlexa BridgeERRORendpointID: 'QUQ6REM6REE6M0I6OTU6M0MtSE9PQlMtaG9tZWJyaWRnZS1hbGV4YS1BbGV4YS0wMDAwMDA4MC0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=',
5/20/2022, 9:11:38 AMAlexa BridgeERRORfriendlyName: 'Alexa',
5/20/2022, 9:11:38 AMAlexa BridgeERRORtemplate: 'ContactSensor'
5/20/2022, 9:11:38 AMAlexa BridgeERROR}
5/20/2022, 9:11:38 AMAlexa BridgeERROR]
5/20/2022, 9:11:38 AMAlexa BridgeERROR2022-05-20T13:11:38.635Z alexaActions Event Register AD:DC:DA:3B:95:3C -> { characteristics: [ { aid: 3, iid: 14, ev: true } ] }

**Comment by NorthernMan54** [comment]
`5/20/2022, 9:11:31 AMAlexa BridgeERROR` is coming from HOOBS and not the plugin.

It appears that HOOB's is logging debug logs with that prefix

**Comment by NorthernMan54** [comment]
So it is HOOB's logging debug messages with an ERROR prefix

**Comment by userbosco** [comment]
Understood, that's what I was hoping/expecting.  :-]  Cheers!
