### ISSUE TITLE
Unable to create routines in Alexa

### ISSUE THREAD

**Issue by scubalessons** [NorthernMan54/homebridge-alexa#524]
None of my devices are available to create routines in Alexa.  I can control them from Alexa though.

**Comment by NorthernMan54** [comment]
Amazon limits what can trigger routines to just contact and motion sensors only.

**Comment by zzack01** [comment]
Hello NorthernMan just checking the insteon devices will work in alexa? But like (example) the routine would need to start with like a voice command then it will be able to control lights and other devices?

**Comment by NorthernMan54** [comment]
Yes, you can create a routine the is started by a voice command, and control a device exposed by this plugin including Insteon.
