### ISSUE TITLE
Login to homebridge.ca failed

### ISSUE THREAD

**Issue by SCOTTS948** [NorthernMan54/homebridge-alexa#526]
I had to update my account today to the subscription service. Now my plug in doesn't work. My log says to check my credentials in the json file and restart homebridge. The credentials are correct. I've tried deleting and re adding them with no luck. 

Also my last plug in response time has a red circle and the timestamp is about 24 hours behind everything else.

Please help.  

Thanks

**Comment by NorthernMan54** [comment]
@SCOTTS948 This is weird as setting up the subscription doesn't impact plugin connectivity.  Sounds like you had tripped the DDOS protection, try stopping / powering off your RPI for 5 minutes and try again.

If it continues, can you share a log with error messages here?

**Comment by SCOTTS948** [comment]
Thanks. I assume you meant turn off my computer for 5 minutes? I run on Windows. Either way, i did that and now i'm connected again. I will keep that in mind for future issues rather than just restarting the computer. 

thanks
