### ISSUE TITLE
device unreachable

### ISSUE THREAD

**Issue by rschuler1964** [NorthernMan54/homebridge-alexa#527]
Using insteon scene (on hoobs insteon plug in) works on hoobs ui and on apple with siri, when homebridge-alexa is added it pulls the insteon scene over as a device and give message about device unresponsive (even though she does do it). Can you please screen share and walk us through it.  below is from the log when this happens:

Alexa BridgeAlexaPowerController TurnOff FD:62:23:F1:17:96 undefined Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/var/lib/hoobs/alexabridge/node_modules/request/request.js:816:19)
    at Object.onceWrapper (node:events:641:28)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'ESOCKETTIMEDOUT',
  connect: false,
  attempts: 5
}

**Comment by NorthernMan54** [comment]
Can you share which Insteon plugin you are using and your scene config ?  I want to try and recreate this

**Comment by rschuler1964** [comment]
Hi,
I am currently using the Insteon dimmer light switches.  These errors seem
to appear when I am controlling them by an Insteon Scene.  Some scenes have
2 devices and others have 5 -12 devices and I get the same error.

Here is the latest log with the errors...

5/29/2022, 2:14:23 PMPlatform Insteonlocal BridgeInsteonLocalSetting power
state of All Basement Lights to off5/29/2022, 2:14:26 PMPlatform
Insteonlocal BridgeERROR[Platform Insteonlocal Bridge ***@***.*** The write
handler for the characteristic 'On' on the accessory 'All Basement Lights'
was slow to respond!5/29/2022, 2:14:32 PMPlatform Insteonlocal
BridgeERROR[Platform
Insteonlocal Bridge ***@***.*** The write handler for the characteristic 'On'
on the accessory 'All Basement Lights' didn't respond at all!. Please check
that you properly call the callback!5/29/2022, 2:14:33 PMPlatform
Insteonlocal BridgeInsteonLocalGot updated status for Deck Plug5/29/2022,
2:14:33 PMPlatform Insteonlocal BridgeInsteonLocalGetting power state for
Deck Plug5/29/2022, 2:14:35 PMPlatform Insteonlocal BridgeInsteonLocalSetting
power state of All Basement Lights to off5/29/2022, 2:14:35 PMPlatform
Insteonlocal BridgeWARNINGunhandled rejection: TypeError: Cannot read
properties of undefined (reading 'completed')5/29/2022, 2:14:38 PMPlatform
Insteonlocal BridgeERROR[Platform Insteonlocal Bridge ***@***.*** The write
handler for the characteristic 'On' on the accessory 'All Basement Lights'
was slow to respond!5/29/2022, 2:14:44 PMPlatform Insteonlocal
BridgeERROR[Platform
Insteonlocal Bridge ***@***.*** The write handler for the characteristic 'On'
on the accessory 'All Basement Lights' didn't respond at all!. Please check
that you properly call the callback!5/29/2022, 2:14:46 PMPlatform
Insteonlocal BridgeWARNINGunhandled rejection: TypeError: Cannot read
properties of undefined (reading 'completed')5/29/2022, 2:14:47 PMPlatform
Insteonlocal BridgeInsteonLocalSetting power state of All Basement Lights
to off5/29/2022, 2:14:50 PMPlatform Insteonlocal BridgeERROR[Platform
Insteonlocal Bridge ***@***.*** The write handler for the characteristic 'On'
on the accessory 'All Basement Lights' was slow to respond!5/29/2022,
2:14:56 PMPlatform Insteonlocal BridgeERROR[Platform Insteonlocal Bridge
***@***.*** The write handler for the characteristic 'On' on the accessory
'All Basement Lights' didn't respond at all!. Please check that you
properly call the callback!5/29/2022, 2:14:57 PMPlatform Insteonlocal Bridge
WARNINGunhandled rejection: TypeError: Cannot read properties of undefined
(reading 'completed')5/29/2022, 2:14:58 PMPlatform Insteonlocal Bridge
InsteonLocalGot updated status for Back Fountain5/29/2022, 2:14:58 PMPlatform
Insteonlocal BridgeInsteonLocalGetting power state for Back Fountain5/29/2022,
2:14:59 PMPlatform Insteonlocal BridgeInsteonLocalSetting power state of
All Basement Lights to off5/29/2022, 2:15:02 PMPlatform Insteonlocal Bridge
ERROR[Platform Insteonlocal Bridge ***@***.*** The write handler for the
characteristic 'On' on the accessory 'All Basement Lights' was slow to
respond!5/29/2022, 2:15:08 PMPlatform Insteonlocal BridgeERROR[Platform
Insteonlocal Bridge ***@***.*** The write handler for the characteristic 'On'
on the accessory 'All Basement Lights' didn't respond at all!. Please check
that you properly call the callback!5/29/2022, 2:15:09 PMPlatform
Insteonlocal BridgeWARNINGunhandled rejection: TypeError: Cannot read
properties of undefined (reading 'completed')5/29/2022, 2:15:11 PMPlatform
Insteonlocal BridgeInsteonLocalSetting power state of All Basement Lights
to off5/29/2022, 2:15:14 PMPlatform Insteonlocal BridgeERROR[Platform
Insteonlocal Bridge ***@***.*** The write handler for the characteristic 'On'
on the accessory 'All Basement Lights' was slow to respond!5/29/2022,
2:15:16 PMPlatform Insteonlocal BridgeInsteonLocalGot updated status for
Front Porch Outlet5/29/2022, 2:15:16 PMPlatform Insteonlocal Bridge
InsteonLocalGetting power state for Front Porch Outlet5/29/2022,
2:15:18 PMAlexa
BridgeAlexaPowerController TurnOff FD:62:23:F1:17:96 undefined Error:
ESOCKETTIMEDOUT at ClientRequest.<anonymous>
(/var/lib/hoobs/alexabridge/node_modules/request/request.js:816:19) at
Object.onceWrapper (node:events:641:28) at ClientRequest.emit
(node:events:527:28) at Socket.emitRequestTimeout (node:_http_client:771:9)
at Object.onceWrapper (node:events:641:28) at Socket.emit
(node:events:539:35) at Socket._onTimeout (node:net:516:8) at listOnTimeout
(node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
{ code: 'ESOCKETTIMEDOUT', connect: false, attempts: 5 }5/29/2022, 2:15:20
PMPlatform Insteonlocal BridgeERROR[Platform Insteonlocal Bridge ***@***.***
The write handler for the characteristic 'On' on the accessory 'All
Basement Lights' didn't respond at all!. Please check that you properly
call the callback!5/29/2022, 2:15:21 PMPlatform Insteonlocal
BridgeWARNINGunhandled
rejection: TypeError: Cannot read properties of undefined (reading
'completed')

**Comment by NorthernMan54** [comment]
This is an issue with the Insteon plugin, and closing this and will track it via https://github.com/kuestess/homebridge-platform-insteonlocal/issues/254
