### ISSUE TITLE
Homebridge stopped communication with Alexa

### ISSUE THREAD

**Issue by groove06** [NorthernMan54/homebridge-alexa#528]
Good day where ever you are. I have a problem with homebridge connected as a skill with Alexa- all device went unresponsive. Upon troubleshooting and removing some devices, Alexa will not rediscover. I have disabled/reenable the skill. I have uninstalled and reinstalled the plugin in HOOBS, to no avail.

**Comment by NorthernMan54** [comment]
Can you share the homebridge logs from when you ask Alexa to discover devices, and a copy of your account dashboard from homebridge.ca.

Am thinking their may be an error message causing this.

Tks

**Comment by groove06** [comment]
![image](https://user-images.githubusercontent.com/60152848/173247568-d0664a16-8fd2-4eef-92ba-cb3ef85efcc7.png)

**Comment by NorthernMan54** [comment]
Took a look for your account and saw this

![image](https://user-images.githubusercontent.com/19808920/173247925-ae4a2a56-fbe1-4455-a840-ccbd0b01900c.png)

You have two accounts with the same username ( only difference being case ), and it appears that the plugin is configured with the lower case one, and Alexa skill is linked to the Upper case one.  Also your subscription is configured with the lower case one.

To fix this, login to Homebridge.ca with the Upper case account, and delete the account.  Then go into the Alexa app, unlink the homebridge skill, then link again with the lowercase account

**Comment by groove06** [comment]
Can you tell which one has the subscripton linked to it for the $2?

Byron

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by groove06** [comment]
Sorry disregard my last. You answered that question. The lower cased one.

Byron

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by groove06** [comment]
@NorthernMan54 thanks for all your help. I don't think I would have realized I had two accounts and case issues. I think I'm good  now

**Comment by NorthernMan54** [comment]
Tks, good luck
