### ISSUE TITLE
Can’t pay, can’t use

### ISSUE THREAD

**Issue by nixmeer** [NorthernMan54/homebridge-alexa#530]
Hello :)

I tried subscribing to the service this morning but the PayPal payment keeps failing with an error. 

```
{
    "name": "RATE_LIMIT_REACHED",
    "message": "Too many requests. Blocked due to rate limiting.",
    "debugId": "f716184fc1f20"
}
```

this prevents me from using the plugin.

**Comment by NorthernMan54** [comment]
@nixmeer I'm wondering if PayPal had an intermittent issue at the time you tried, I checked my cloud server logs and did not notice anything unusual.   To give us more time with this, I bumped out your subscription required by 2 weeks.

**Comment by nixmeer** [comment]
Thank you. When I read your mail a minute ago, I tried again and it worked so you can reset the 2 weeks.
