### ISSUE TITLE
Homebridge Alexa Account is not active - Homebridge.ca down

### ISSUE THREAD

**Issue by BigSirGoo** [NorthernMan54/homebridge-alexa#531]
Hi,

I see the following error in the console when I try to run any command: Homebridge Alexa Account is not active.

When I visit homebridge.ca to see what the issue is, I receive the following error: DNS_PROBE_FINISHED_NXDOMAIN

Thank you!

**Comment by NorthernMan54** [comment]
The domain/url is https://www.homebridge.ca/
