### ISSUE TITLE
authentication problem

### ISSUE THREAD

**Issue by lobmarib** [NorthernMan54/homebridge-alexa#532]
Hi there,

My old installation just stopped working because of my login (?). I had to register myself once again and now there is a subscription.
Though, it seems my credentials don't work despite of whatever I do...

"[Alexa] ERROR: ( homebridge-alexa) Login to homebridge.ca failed, please validate your credentials in config.json and restart homebridge."

I've already activated the debug and I don't see nothing related on the log.

Any help will be very appreciated.

Thanks

**Comment by lobmarib** [comment]
Thanks for the quick feedback.

Case is right as well the (new) credentials... 🙄

**Comment by NorthernMan54** [comment]
The other possibility is that you had tripped the DDOS protection. To reset it stop the plugin or your RPI for 5 minutes

**Comment by lobmarib** [comment]
@NorthernMan54  thanks for the hint, it worked. I've stopped the (docker) container the entire night and now it seems to be working - the login.
Though, the "5 - Last plugin response" is still red...

**Comment by lobmarib** [comment]
Ignore the last plugin response in red. It's all working now.
Cheers
