### ISSUE TITLE
Subscription Service

### ISSUE THREAD

**Issue by aski71** [NorthernMan54/homebridge-alexa#535]
Folks,

while I sort of understand the reasoning let me say I find it quite irritating to be simply cut off from the service without any warning.
I also think it is irritating having to pay for a service that does neither show clear terms and conditions, terms of use, etc. , nor what form of company is behind it, nor contact information, support email address or anything that makes this a credible enterprise.

Don't get me wrong, there's nothing wrong in charging for a service, but this looks very unprofessional.

**Comment by WinfriedO** [comment]
Yes, very strange behaviour.

**Comment by NorthernMan54** [comment]
“But the plans were on display…”
“On display? I eventually had to go down to the cellar to find them.”
“That’s the display department.”
“With a flashlight.”
“Ah, well, the lights had probably gone.”
“So had the stairs.”
“But look, you found the notice, didn’t you?”
“Yes,” said Arthur, “yes I did. It was on display in the bottom of a locked filing cabinet stuck in a disused lavatory with a sign on the door saying ‘Beware of the Leopard.”

Just so you are aware, notes were published months ago on Reddit in /r/homebridge, the discord server, the README on GitHub, and a welcome message on the website, not sure where else I could have published something?

I do understand your frustration with the process, but we did try to ensure that most people were well aware of the transition prior to it starting, but we did go into it knowing that not everyone would have been aware, and circumstances like yours would occur.

**Comment by WinfriedO** [comment]
Under the line
I set up a few skills on alexa as replacement for the single homebridge-alexa skill.
So finally.. homebridge is more or less useless for me.
Need an idea for the usage of 2 raspberries now :)

**Comment by aski71** [comment]
My comment is not about not announcing it properly. 

As a side note on this: I am a USER of the system. I only visit forums or notes when something's not working. Not proactively. But as I said, this is simply a side note. No one who's a simple user will do that.

My criticism is the following: Doing business in Germany (and that's what it is) requires a lot of prerequisites by law so the customer knows who is dealing with, where the money goes, what the terms and conditions are, what the payment terms are, what the cancellation periods are, data protection declarations, etc. etc.

There is not even such a thing as an Impressum on the page. There is no such thing as a business owner with contact details. This is therefore not a trustworthy operation / business to charge for any kind of service.

That's my criticism. If you want to charge for a service, do it right and lawful. People rightfully want to know who they are dealing with and expect clear terms & conditions. You might actually in the end harm yourself, if someone came up with the idea to sue you, as you're breaking several German commercial laws.

And then also as another side note: 2 EUR is the price for an Espresso, you say. Well yes, I can afford it and I eventually signed up for it anyway. But seriously: Charging 2 EUR monthly for an interface to a service that's provided for free by Amazon? Let me continue this: Ok, let's add 2 EUR a month for accessing the Miele Cloud Service from iobroker. And another two EUR per month for accessing Apples SIRI. And another 2 EUR for accessing NUKI smart locks. And another two EUR for ... you get the concept. I think in the end it'll be the death of community software. I find that sad.
