### ISSUE TITLE
Login Failure 

### ISSUE THREAD

**Issue by zaltzy** [NorthernMan54/homebridge-alexa#537]
Just recreated my account and subscribed. Updated the plugin with my credentials and receiving this error:
`[Alexa] ERROR: ( homebridge-alexa) Login to homebridge.ca failed, please validate your credentials in config.json and restart homebridge.`

Looked at #526 and #532 and tried to turn the service off, wait 5 minutes, even tried removing the plugin completely and re install it, and also tried to change my password - but no go.

Health dashboard doesn't really add any insights here (screen shot attached) and enabling debug mode also did not shed any light.
(Obviously the credentials have been reviewed by me countless times, they match completely, Case-wise as well).

Any suggestions?
![Capture](https://user-images.githubusercontent.com/4106005/179368651-6a6dffb3-f508-48a3-a7e4-0f97ec34105d.PNG)

**Comment by NorthernMan54** [comment]
If you have validated the username and password and it still shows #2 as red am thinking will need to meet on the homebridge discord and you can share the account details so I dig deeper into the issue.

Am thinking something may blocking the cloud connection or something with the username is blocking things.

**Comment by zaltzy** [comment]
Thanks @NorthernMan54.
Email is indeed verified.
Just joined the homebridge discord as zaltzy#2535.
Much appreciated!

**Comment by NorthernMan54** [comment]
We met on discord and reviewed config and other items. And identified a typo in the config.json.
