### ISSUE TITLE
cannot turn on/off devices

### ISSUE THREAD

**Issue by vcrosato** [NorthernMan54/homebridge-alexa#538]
Used homebridge-alexa for many years. 

Stop working, updated all packages then subscribed onto paid model. 

After updating it doesn't work. 

Already tried updating devices many, restarting, googling for related cases. 

Error below:
  mqtt-packet:parser _newPacket: parser emit packet: packet.cmd: publish, packet.payload: {"directive":{"header":{"messageId":"36e99a7f-38e2-4a5b-980a-40e019e4aaad","namespace":"Alexa.PowerController","name":"TurnOn","payloadVersion":"3","correlationToken":"SUdTVEs6AAE6AAg6eyJpZCI6IjVkNzEwZWZmLTE0NmQtNGQ1MC1hNzE0LTQyM2UxYTA2NjgwNiIsInVyaSI6Imh0dHBzOi8vZC1hY3JzLW5hLXAtNWYzLWIxNTg1OTE0LnVzLWVhc3QtMS5hbWF6b24uY29tOjk0NDQifQ=="},"endpoint":{"endpointId":"Q0M6MjI6M0Q6RTM6Q0U6MzAtSG9tZWJyaWRnZS1JbmRpZ28tRXNjcml0w7NyaW8gMy0wMDAwMDA0My0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=","cookie":{"TurnOn":"{\"host\":\"192.168.0.100\",\"port\":51826,\"aid\":208,\"iid\":10,\"value\":1}","AdjustPowerLevel":"{\"host\":\"192.168.0.100\",\"port\":51826,\"aid\":208,\"iid\":11}","ReportState":"[{\"interface\":\"Alexa.PowerController\",\"host\":\"192.168.0.100\",\"port\":51826,\"aid\":208,\"iid\":10},{\"interface\":\"Alexa.PowerLevelController\",\"host\":\"192.168.0.100\",\"port\":51826,\"aid\":208,\"iid\":11}]","SetPowerLevel":"{\"host\":\"192.168.0.100\",\"port\":51826,\"aid\":208,\"iid\":11}","BrightnessTurnOn":"true","TurnOff":"{\"host\":\"192.168.0.100\",\"port\":51826,\"aid\":208,\"iid\":10,\"value\":0}"}},"payload":{}}}, packet.length: 1142 +0ms
  mqttjs:client parser :: on packet push to packets array. +3ms
  mqtt-packet:parser _newPacket: new packet +0ms
  mqtt-packet:parser parse: state complete. _stateCounter is now: 4 +0ms
  mqtt-packet:parser parse: packet.length: -1, buffer list length: 0 +0ms
  mqtt-packet:parser parse: exited while loop. packet: -1, buffer list length: 0 +0ms
  mqttjs:client work :: getting next packet in queue +0ms
  mqttjs:client work :: packet pulled from queue +0ms
  mqttjs:client _handlePacket :: emitting packetreceive +0ms
  mqttjs:client _handlePublish: packet Packet { cmd: 'publish', retain: false, qos: 0, dup: false, length: 1142, topic: 'command/nexx/1', payload: <Buffer 7b 22 64 69 72 65 63 74 69 76 65 22 3a 7b 22 68 65 61 64 65 72 22 3a 7b 22 6d 65 73 73 61 67 65 49 64 22 3a 22 33 36 65 39 39 61 37 66 2d 33 38 65 32 ... 1076 more bytes> } +1ms
  mqttjs:client _handlePublish: qos 0 +0ms
  alexaLocal Emitting Alexa.PowerController +26s
  hapNodeJSClient HAP Device discovered Homebridge CAD8 +8s
[7/21/2022, 8:11:44 PM] [Alexa] PowerController TurnOn undefined undefined Error: ERROR: HB Instance not found
    at /usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:131:18
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:190:7)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
  mqttjs:client publish :: message `{"event":{"header":{"namespace":"Alexa","name":"ErrorResponse","messageId":"36e99a7f-38e2-4a5b-980a-40e019e4aaad","payloadVersion":"3"},"endpoint":{"endpointId":"Q0M6MjI6M0Q6RTM6Q0U6MzAtSG9tZWJyaWRnZS1JbmRpZ28tRXNjcml0w7NyaW8gMy0wMDAwMDA0My0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE="},"payload":{"type":"ENDPOINT_UNREACHABLE","message":"ERROR: HB Instance not found"}}}` to topic `response/nexx/1` +4s

**Comment by NorthernMan54** [comment]
Have you tried asking Alexa to discover devices again?

looks like the plugin is trying to reach incorrect homebridge instance.
