### ISSUE TITLE
Homebridge stopped working

### ISSUE THREAD

**Issue by chrisp79** [NorthernMan54/homebridge-alexa#539]
Hi. My homebridge has stopped working. I've checked my subscription and all seems fine with that but the status page is saying that my plugin hasn't communicated since about midnight last night so there seems to be a problem.

Homebridge appears to start normally but I then see "[7/25/2022, 10:11:32 AM] [Alexa] alexaDiscovery - returned 28 devices" followed by "ERROR: ( homebridge-alexa) You have an issue with your installation, please review the README." 36 times. This cycle seems to repeat about 6 times (every 15-20 minutes) then I see "ERROR: ( homebridge-alexa) Stopping Home Skill connection due to excessive reconnects, please review the README.". Thereafter, I just see the following message every 15 minutes or so... "[7/25/2022, 11:41:32 AM] [Alexa] alexaDiscovery - returned 28 devices".

Any idea what's going on here? It was all working fine up until last night and I've not many any changes to it whatsoever.

Thanks

**Comment by NorthernMan54** [comment]
It could be DDOS protection kicking in. Try stopping homebridge/ rpi for 5 minutes and starting it again

**Comment by chrisp79** [comment]
That hasn’t made any difference unfortunately. The message “ERROR: ( homebridge-alexa) You have an issue with your installation, please review the README." is still appearing every minute or so in the Homebridge window.






On 25 Jul 2022, at 21:17, Northern Man ***@***.***> wrote:

﻿

It could be DDOS protection kicking in. Try stopping homebridge/ rpi for 5 minutes and starting it again

**Comment by NorthernMan54** [comment]
That error message is triggered when the connection to the cloud servers fails.  Can you share your external IP address and account username via a direct message on the homebridge discord server so I can look further?
