### ISSUE TITLE
Error "The requested platform '" + name + "' was not registered by any plugin."

### ISSUE THREAD

**Issue by chrisx9** [NorthernMan54/homebridge-alexa#54]
(This is my first reported issue, let me know if things are missing or reported wrong...)

Installed as described using:
sudo npm install -g https://github.com/NorthernMan54/homebridge-alexa#Alexa2ndGen
+ homebridge-alexa@0.1.0
updated 1 package in 18.641s

config.json entry:
,{
      "platform": "Alexa",
      "name": "Alexa",
      "username": "MYUSER",
      "password": "MYPASS"
    },

Restarting homebridge:
sudo systemctl restart homebridge

Resulting in the following error:

Feb 21 20:06:21 pi-homebridge homebridge[1615]: /usr/lib/node_modules/homebridge/lib/api.js:122
Feb 21 20:06:21 pi-homebridge homebridge[1615]: throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
Feb 21 20:06:21 pi-homebridge homebridge[1615]: ^
Feb 21 20:06:21 pi-homebridge homebridge[1615]: Error: The requested platform 'Alexa' was not registered by any plugin.
Feb 21 20:06:21 pi-homebridge homebridge[1615]: at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:122:13)
Feb 21 20:06:21 pi-homebridge homebridge[1615]: at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:294:45)
Feb 21 20:06:21 pi-homebridge homebridge[1615]: at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:85:36)
Feb 21 20:06:21 pi-homebridge homebridge[1615]: at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
Feb 21 20:06:21 pi-homebridge homebridge[1615]: at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Feb 21 20:06:21 pi-homebridge homebridge[1615]: at Module._compile (module.js:571:32)
Feb 21 20:06:21 pi-homebridge homebridge[1615]: at Object.Module._extensions..js (module.js:580:10)
Feb 21 20:06:21 pi-homebridge homebridge[1615]: at Module.load (module.js:488:32)
Feb 21 20:06:21 pi-homebridge homebridge[1615]: at tryModuleLoad (module.js:447:12)
Feb 21 20:06:21 pi-homebridge homebridge[1615]: at Function.Module._load (module.js:439:3)
Feb 21 20:06:21 pi-homebridge systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Feb 21 20:06:21 pi-homebridge systemd[1]: Unit homebridge.service entered failed state.

**Comment by NorthernMan54** [comment]
@chrisx9 

I would suggest removing/uninstalling homebridge-alexa and re-installing it.  It looks like the install did not work for some reason.

**Comment by chrisx9** [comment]
Ok, done. Looks like the issue is in the install. When i install, i get lots and lots of repeating lines like the following:
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/homebridge-alexa/node_modules/mdns/.node-gyp/7.10.1"

i checked the folder /usr/lib/node_modules/homebridge-alexa/node_modules/mdns/. There is no subfolder ".node-gyp" etc

**Comment by NorthernMan54** [comment]
I think that this is an issue with the latest version of NPM, you should be able to workaround it with this

sudo su
sudo npm install -g —unsafe-perm https://github.com/NorthernMan54/homebridge-alexa#Alexa2ndGen

**Comment by chrisx9** [comment]
Thanks! that solved it! Alexa discovers all devices (as switches regardless if hue bulbs or switches). However if i turn them on or off, nothing happens but after a second or so a notice is display in the alexa app "a problem occured". I am supposed to create a new issue out of this, right?
