### ISSUE TITLE
Confirmation Email not received

### ISSUE THREAD

**Issue by drpau** [NorthernMan54/homebridge-alexa#540]
Hi, long time user, i have subscribed and have entered my email.

no email validation sent.  done it twice now.

no its not in spam.

**Comment by NorthernMan54** [comment]
Can you share your username ? And can take a look?

**Comment by drpau** [comment]
davidreid

**Comment by drpau** [comment]
any update?
plugin still not working..... presumably because of this.

![image](https://user-images.githubusercontent.com/13581275/184075861-b20c51a5-1caf-4e08-979b-006f7838eeee.png)

**Comment by NorthernMan54** [comment]
@drpau I went and reset the email requirement on your account, so it should now resume working.   As your not able to receive the email validation message, I think we should just leave that as is with an un-supplied email.

Looking at your account status, I see the last plugin response was back in June.  Can you try it again now, and see if the last plugin response updates.  

![Screen Shot 2022-08-11 at 12 53 15 PM](https://user-images.githubusercontent.com/19808920/184190826-f82a5611-a61b-403f-afdc-511b50735177.png)

**Comment by drpau** [comment]
working now and not getting api errors in homebridge thanks.

**Comment by NorthernMan54** [comment]
I looked on the server logs for any email logs, and did not see anything indicating it wasn’t sent. So I went in and removed the email requirement from your account.
