### ISSUE TITLE
Account disappeared 

### ISSUE THREAD

**Issue by gmum4d** [NorthernMan54/homebridge-alexa#543]
I’ve been a user for a long time and have only just found out that this is now subscription based. This is fine with me so I tried to login to my account to enrol but I can’t login. I tried the password reset but it states user in recognised??  Has my old account been deleted?  I read your site that says legacy users can simply login to update

**Comment by NorthernMan54** [comment]
Likely it has been deleted. The system has been deleting accounts inactive over 30 days.

Just create a new account, and set it up again
