### ISSUE TITLE
Panasonic TV cant be allowed

### ISSUE THREAD

**Issue by MikeMighty** [NorthernMan54/homebridge-alexa#546]
I installed the Homebridge Alexa plugin. All works fine for my receiver and thermostat. But i cant seem to get my tv working. I am using the tested Panasonic TV: - homebridge-panasonic-viera-tv@4.1.0. Works fine in the homekit, but cant get it on allow in the Homebridge Alexa. I tried several names. The exact name like written in the homekit, but also al the names that were shown in the Homebridge logs, like TX-58DX780W and Panasonic TV 9266. 

What can be the problem?

**Comment by MikeMighty** [comment]
Solved, couple restarts.

**Comment by NorthernMan54** [comment]
glad to hear you solved this
