### ISSUE TITLE
Dropped event message, message rate too high?

### ISSUE THREAD

**Issue by Pblondin123** [NorthernMan54/homebridge-alexa#547]
Hi, i added a couple events this week which are causing the dropped event message to come in regularly.   Are you aware if this can be bumped higher at all and if not do you have any recommendation (other that bundle events in one routine which is what i started to do but feel stuck coding workarounds :-) Thanks.

**Comment by NorthernMan54** [comment]
Do you have any sensors that are just creating noise events and could be filtered out from your configuration?

**Comment by Pblondin123** [comment]
Thanks.  Sounds like i will have to tweak my automations to space up in time the triggers so that i don’t get more than 10 in the backlog.  Am too chicken to change the code! Suggestion would be to parameter it unless it s a restriction with the Alexa cloud.  Closing thanks.
