### ISSUE TITLE
Not able to discover from multiple HomeBridges

### ISSUE THREAD

**Issue by frederickcwong** [NorthernMan54/homebridge-alexa#548]
Hi - 

Don't know where to ask for help so I created this issue. I have HomeBridge installed on the pi and have the plugin installed, connected, and working ok except for other instances of HomeBridges created in my Home Assistant environment. It seems Alexa cannot see those instances that are living in the Home Assistant process (my Home app is able to communicate with those instances).

How come the discovery process cannot see those instances? Almost all my devices are on Home Assistant and my pi's HomeBridge is used for one device that Home Assistant does not support. Please help! Thanks!

**Comment by NorthernMan54** [comment]
Let me play back my understanding of the question

You have homeassistant running, and it connects to multiple devices within your setup.  And you have enabled the [HomeKit](https://www.home-assistant.io/integrations/homekit/) support within the home app, and are trying to discover these devices with the homebridge-alexa plugin ?

Does the home assistant/homekit module support an 'insecure' mode of access ?  This is needed for the homebridge-alexa plugin to discover the devices.

**Comment by NorthernMan54** [comment]
FYI - I believe this is the home assistant/homekit module - https://github.com/ikalchev/HAP-python and after quickly reviewing the documentation I didn't notice an insecure setting.

**Comment by frederickcwong** [comment]
Hi - I forgot to mention, I have HomeBridge running on a Pi and that is the instance where I have HomeBridge-Alexa installed. I don't think I can install the plugin on those instances within the Home Assistant.

**Comment by NorthernMan54** [comment]
The homebridge-Alexa plugin can be installed anywhere on your network.

**Comment by frederickcwong** [comment]
Thanks for your help but I can't get Alexa to see other HomeBridge instances inside Home Assistant no matter what I tried. I decided to go with another route to connect. Thanks!
