### ISSUE TITLE
Can't Validate Email

### ISSUE THREAD

**Issue by woodboreds** [NorthernMan54/homebridge-alexa#549]
Hello, I'm unable to validate my email address. I've tried a few times though I am able to login, it won't complete the validation.

Thanks.

**Comment by Willempy** [comment]
Having the same problem on dec 24th 2022

**Comment by NorthernMan54** [comment]
I'm not sure why, but for some reason a few people aren't able to receive to the validation email. So @Willempy I removed that requirement from your account.

You should be good now

**Comment by Willempy** [comment]
ok, thank you.
