### ISSUE TITLE
blinds Not implemented

### ISSUE THREAD

**Issue by Luftloch80** [NorthernMan54/homebridge-alexa#55]
Everything working except blinds. 
Great Job

**Comment by NorthernMan54** [comment]
I was looking, and I didn't see blinds or window coverings being supported in the alexa smart home API.  Any thoughts on how to make it work?  I could have it appear to be a light.

Also what plugin are you using for the blinds?

**Comment by Luftloch80** [comment]
homebridge-homematic

**Comment by Darko2** [comment]
Im using homebridge-homewizard for the blinds.
Dimmable lights sound like a good idea.

**Comment by jelvs** [comment]
yh yh, i think the best way is using Dimmable lights

**Comment by NorthernMan54** [comment]
And have also mapped turn on/turn off for open and close as well.  Please let me know how it works

**Comment by Luftloch80** [comment]
Working good. But when blinds are on 100% the lamp device shows still off instead of on. 
 It it does work perfect

**Comment by NorthernMan54** [comment]
@Luftloch80 Okay let me look at state reporting for blinds further.  Awesome to hear that they are working though.

**Comment by NorthernMan54** [comment]
@Luftloch80 Are these working okay with the latest release?

**Comment by Luftloch80** [comment]
Yes Wirkung great

**Comment by NorthernMan54** [comment]
Awesome
