### ISSUE TITLE
Child Bridge

### ISSUE THREAD

**Issue by Daniel167** [NorthernMan54/homebridge-alexa#550]
Hello, 

sorry for my bad english.

The homebridge-alexa don't work with homebridge (childbridge).
I have a home bridge with 2 Instanz and is work with Filter Port.

Than i delete the 2 Instanz and make one homebridge with a lot of child bridge.
I need the Alexa plugin for one child bridge. 

I give the Alexa Plugin the ip with port from child bridge 192.xxx.xxx.xxx:31971

The Plugin give me this answer in log.
[Alexa] ERROR: HAP Discovery failed, please review config

Please help me

**Comment by NorthernMan54** [comment]
That message is the plugin saying that no devices were found.

have you tried the device list option instead?

**Comment by Daniel167** [comment]
Can you speak german, is better for me?

**Comment by NorthernMan54** [comment]
I just confirmed and the filter option does work correctly with child bridges, but you need to include the port number in the child bridge configuration.

ie port number in child bridge configuration

```
   "platforms": [
        {
            "_bridge": {
                "username": "CC:22:3D:E3:CF:38",
                "port": 51827
            },
            "platform": "yamaha-home",
            "radio_presets": true,
            "preset_num": true,
```

If you enable debug logging, the log will contain details of the filtering ( https://github.com/NorthernMan54/homebridge-alexa/blob/master/Installation.md#debug )

```
  hapNodeJSClient HAP Device discovered People Bridge 1 0BA3 +308ms
  hapNodeJSClient Filtered HAP instance address: 1.4.3 -> http://192.168.1.11:44505 +0ms
  hapNodeJSClient HAP Device discovered Thermostat 49C7 +2ms
  hapNodeJSClient Filtered HAP instance address: homebridge -> http://192.168.1.11:37067 +0ms
  hapNodeJSClient HAP Device discovered Hue B509 +1ms
  hapNodeJSClient Filtered HAP instance address: homebridge -> http://192.168.1.11:39401 +0ms
  hapNodeJSClient HAP Device discovered homebridge-homekit-control A7DD +1ms
  hapNodeJSClient Filtered HAP instance address: homebridge -> http://192.168.1.11:31821 +0ms
  hapNodeJSClient HAP Device discovered eWeLink AE8E +1ms
  hapNodeJSClient Filtered HAP instance address: homebridge -> http://192.168.1.11:36132 +0ms
  hapNodeJSClient HAP Device discovered Alexa E33F +1ms
  hapNodeJSClient Filtered HAP instance address: homebridge -> http://192.168.1.11:44047 +0ms
  hapNodeJSClient HAP Device discovered homebridge-yamaha-home 680B +1ms
  hapNodeJSClient HAP Device discovered RFLink Platform A3A6 +7ms
  hapNodeJSClient Filtered HAP instance address: homebridge -> http://192.168.1.11:38127 +0ms
  hapNodeJSClient HAP Device discovered Main Room TV 4258 +1ms
  hapNodeJSClient Filtered HAP instance address: homebridge -> http://192.168.1.11:40343 +0ms
  hapNodeJSClient HAP Device discovered Raj-NodeRed 98E6 +0ms
  hapNodeJSClient Filtered HAP instance address: Default Model -> http://192.168.1.11:51830 +0ms
  hapNodeJSClient HAP Device discovered Bird Feeder 2EB2 +1ms
  hapNodeJSClient Filtered HAP instance address: Axis P3365 -> http://192.168.1.11:39911 +0ms
  hapNodeJSClient HAP Device discovered Cottage Porch 6CE1 +0ms
  hapNodeJSClient Filtered HAP instance address: Indoor Cam 2K -> http://192.168.1.11:37307 +0ms
  hapNodeJSClient HAP Device discovered Backyard 313D +0ms
  hapNodeJSClient Filtered HAP instance address: Indoor Cam 2K -> http://192.168.1.11:43623 +0ms
  hapNodeJSClient HAP Device discovered Raj AE42 +0ms
  hapNodeJSClient Filtered HAP instance address: homebridge -> http://192.168.1.11:51826 +0ms
  hapNodeJSClient HAP Device discovered Music Port 3005 +0ms
  hapNodeJSClient Filtered HAP instance address: homebridge -> http://192.168.1.11:43063 +0ms
  hapNodeJSClient HAP Device discovered Tuner 8723 +0ms
  hapNodeJSClient Filtered HAP instance address: homebridge -> http://192.168.1.11:39809 +0ms
  hapNodeJSClient HAP Device discovered Stereo AFA3 +1ms
  hapNodeJSClient Filtered HAP instance address: homebridge -> http://192.168.1.11:35619 +0ms
  hapNodeJSClient HAP Device discovered Tasmota 5019 +0ms
  hapNodeJSClient Filtered HAP instance address: homebridge -> http://192.168.1.11:43481 +0ms
  hapNodeJSClient HAP Device discovered IndoorCam 2K-3341 +0ms
  hapNodeJSClient Filtered HAP instance address: T8400 -> http://192.168.1.26:35602 +0ms
  hapNodeJSClient HAP Device discovered IndoorCam 2K-44ED +0ms
  hapNodeJSClient Filtered HAP instance address: T8400 -> http://192.168.1.24:59346 +1ms
  hapNodeJSClient HAP Device discovered SIMPLEconnect Fan-82F815 +0ms
  hapNodeJSClient Filtered HAP instance address: SIMPLEconnect -> http://192.168.1.30:80 +0ms
  hapNodeJSClient Homebridge instance discovered homebridge-yamaha-home 680B @ http://192.168.1.11:51827 with 11 accessories +569ms
  hapNodeJSClient HAP Device discovered Heisenberg 4534 +88ms
  hapNodeJSClient Filtered HAP instance address: homebridge -> http://192.168.1.63:51826 +0ms
  hapNodeJSClient Ready +19s
  alexaActions alexaDiscovery +0ms
  alexaActions  +14ms
[Alexa] alexaDiscovery - returned 10 devices
```

This is my configuration

```
  "platforms": [{
    "platform": "Alexa",
    "name": "Alexa",
    "username": "xxxxxxxx",
    "password": "xxxxxxxxx",
    "beta": false,
    "filter": "192.168.1.11:51827",
    "debug": true,

```

**Comment by Daniel167** [comment]
Thanks, but dont run on my System with Child Bridge. 

The Plugin give me this answer in log.
[Alexa] ERROR: HAP Discovery failed, please review config

Alexa Config:
 {
            "name": "Alexa",
            "username": "Danielxxxx",
            "password": "xxxxxxxx/",
            "pin": "185-47-xxx",
            "debug": true,
            "filter": "192.168.1.xxx:52531",
            "platform": "Alexa"
        }

plugin

  {
            "name": "HomeMatic CCU3",
            "ccu_ip": "192.168.1.xx",
            "subsection": "Homekit",
            "enable_hmip": true,
            "enable_wired": false,
            "ios10": false,
            "platform": "HomeMatic",
            "_bridge": {
                "username": "0E:1A:41:4E:xx:xx",
                "port": 52531
            }

**Comment by Daniel167** [comment]
Hello, i have found the Problem. I change the Frequenz Intervall to 100 and Alexa found the HomeMatic Switches. Is 100 a problem for Homebridge? Wath is a good Tine? Trank you

**Comment by NorthernMan54** [comment]
refresh ???

https://github.com/NorthernMan54/homebridge-alexa/blob/master/Installation.md#refresh

**Comment by Daniel167** [comment]
With the Option refresh 500 it Works 

name": "Alexa",
            "username": "Danxxxx",
            "password": "xxx/",
            "pin": "185-47-xxx",
            "routines": false,
            "blind": false,
            "door": false,
            "debug": false,
            "refresh": 500,
            "filter": "192.168.111.xxx:52531",
            "deviceListHandling": "allow",
            "platform": "Alexa"

**Comment by NorthernMan54** [comment]
Default for refresh is 900, closer to that number is better
