### ISSUE TITLE
Not able to Enable Skill

### ISSUE THREAD

**Issue by baker0408** [NorthernMan54/homebridge-alexa#552]
I recently did a fresh install of Homebridge and unable to reconnect this plugin. I am using the sam credentials as before, but getting an unsuccessfully linked, or incorrect login error within the Alexa Skill. Everything seems to be working as expected on the Homebridge.ca account and within my instance of Homebridge.

**Comment by NorthernMan54** [comment]
Can you share your cloud username via a dm on discord ?

The channel is called #homebridge-alexa [Invite](https://discord.gg/6WBNPUauvA)

**Comment by NorthernMan54** [comment]
Found your username, so no need to share.

Looking at the logs, when you attempted to do the link your username was incorrect, it had `@gmail.com` appended

**Comment by baker0408** [comment]
Thanks for the quick response! I fixed that in my HB instance, but still unsuccessful in the Alexa skill

**Comment by NorthernMan54** [comment]
Looking at the logs, your last attempt to link the skill was at 20:53:53 GMT, and it had the incorrect username and for some reason you hit the cancel button

Please try it again with the correct username and password ( The account you use when linking the skill is the homebridge.ca credentials )

**Comment by baker0408** [comment]
OK so I forgot I had changed my password and hadn't updated my instance. However, I still received a "linking unsuccessful" in the Alexa skill.

**Comment by NorthernMan54** [comment]
Last attempt @ 21:23:48 had the wrong username and the cancel button was pressed

**Comment by baker0408** [comment]
So I got the password/user name issue resolved and see the devices in Alexa, however they’re not responding when engaged in Alexa with a “server not responsive” error. I get the attached message in my log file. 
![331766A5-8109-478E-96DB-64FAD10B0081](https://user-images.githubusercontent.com/88755683/198903452-a6405757-73da-4adc-9450-196cf3fc5a21.jpeg)

**Comment by NorthernMan54** [comment]
Glad to hear you got past the linking issue.  Have you tried asking Alexa to ‘Discover Devices’, this should resolve this issue.  ( Occasionally the device pointers between homebridge and Alexa get and of wack, and this resets them )

**Comment by baker0408** [comment]
That did the trick! Really appreciate your help and quick responses!
