### ISSUE TITLE
After a few minutes devices not responding

### ISSUE THREAD

**Issue by PRONOVATEK** [NorthernMan54/homebridge-alexa#559]
Hi, I need some help with my account. Every time I attempt using alexa to turn off or on any device, it (her) answers me “device not responding”. I’ve tried every solution finded on this Issues section (trying to reinstall homebridge, making a new configuration from scratch, modifying refresh settings from 60 seconds to 900 and also turning off the plugin for at least 15 minutes) and always my solution is to restart homebridge, but it just work for some minutes (if I’m lucky for a couple of hours) and again it fails. I dont know if I’m doing something wrong. 

Attach the response from page
![1C3FF100-3034-41FE-B44B-648EFBC392DC](https://user-images.githubusercontent.com/5448117/208275922-14b3ebe9-d69a-48e4-8152-f73bfa188cfc.png)

And this is what appears on my log every time I restart homebridge (it registers devices and not generate any message later) :

![921EC124-817A-4C85-AB4E-B36A1B6A8FBB](https://user-images.githubusercontent.com/5448117/208276121-944a4f61-c3f6-4ffb-b0bc-9277f3d0c5d8.jpeg)
![EFE759E6-4B61-4A71-9A55-E6402801AE87](https://user-images.githubusercontent.com/5448117/208276122-1c459c60-f5cd-43c3-9c7f-b529b035f6b0.jpeg)
![82A8813F-D3DD-418A-95E7-8EADDBEBCA7F](https://user-images.githubusercontent.com/5448117/208276123-a3536e2d-96a2-4dd5-ba4f-45c7f26f277b.jpeg)

I really appreciate every help about it.

Regards.

**Comment by PRONOVATEK** [comment]
I forgot to mention that sometimes when I run the Alexa app and try to force turn on/off any device it works and I can control devices again but just for a few minutes.

**Comment by NorthernMan54** [comment]
The `refresh` setting only changes how often the plugin scans the local network to refresh the accessory information details, changing the setting away from the default won't resolve this.

I was looking at the logs on the cloud server, and I see that the plugin is reconnecting to the cloud about every 10 minutes.  Is your homebridge environment restarting every 10 minutes ?

If your homebridge environment is not restarting every 10 minutes, try changing `keepalive` to 1.

**Comment by PRONOVATEK** [comment]
Ok I try with your suggestion and keep you inform

**Comment by PRONOVATEK** [comment]
Hi, reporting advance, two days and apparently not have more failures, I modify to keepalive 1 as you suggest and service work I keep waiting one week and report if that fail or close my issue

**Comment by NorthernMan54** [comment]
Closing as issue appears to be resolved
