### ISSUE TITLE
Devices do not react when switched on/off in alexa app  

### ISSUE THREAD

**Issue by chrisx9** [NorthernMan54/homebridge-alexa#56]
Alexa finds all devices. They show up as switches regardless of their type. If i turn on/off switches, nothing happens. After a short period, i get a message in the alexa app "an error occured" (in german language). 

When starting up homebridge, the following errors show up (i checked manually, http://192.168.1.115:8080 is not reachable, instead http://192.168.1.115 is reachable):

Feb 21 22:17:34 pi-homebridge homebridge[2511]: Wed, 21 Feb 2018 21:17:34 GMT alexaLocal offline
Feb 21 22:17:34 pi-homebridge homebridge[2511]: Wed, 21 Feb 2018 21:17:34 GMT alexaHAP HAP Discover failed Philips hue - AC0A31 http://192.168.1.115:8080 error code 470
Feb 21 22:17:34 pi-homebridge homebridge[2511]: Wed, 21 Feb 2018 21:17:34 GMT alexaHAP HAP Discover failed Philips hue - AC0A31 http://192.168.1.115:8080 error code 470

When trying to turn a switch on/off, i get the following log:

Feb 21 22:22:22 pi-homebridge homebridge[2511]: Wed, 21 Feb 2018 21:22:22 GMT alexaLocal Emitting alexa.powercontroller
Feb 21 22:22:22 pi-homebridge homebridge[2511]: Wed, 21 Feb 2018 21:22:22 GMT alexaPlugin alexa.powercontroller TurnOff 192.168.1.55 51826 { characteristics: [ { aid: 122, iid:
Feb 21 22:22:22 pi-homebridge homebridge[2511]: Wed, 21 Feb 2018 21:22:22 GMT EventedHTTPServer [::ffff:192.168.1.55] New connection from client
Feb 21 22:22:22 pi-homebridge homebridge[2511]: Wed, 21 Feb 2018 21:22:22 GMT EventedHTTPServer [::ffff:192.168.1.55] HTTP server listening on port 45287
Feb 21 22:22:22 pi-homebridge homebridge[2511]: Wed, 21 Feb 2018 21:22:22 GMT EventedHTTPServer [::ffff:192.168.1.55] HTTP request: /characteristics
Feb 21 22:22:22 pi-homebridge homebridge[2511]: Wed, 21 Feb 2018 21:22:22 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics
Feb 21 22:22:22 pi-homebridge homebridge[2511]: Wed, 21 Feb 2018 21:22:22 GMT EventedHTTPServer [::ffff:192.168.1.55] HTTP Response is finished
Feb 21 22:22:22 pi-homebridge homebridge[2511]: Wed, 21 Feb 2018 21:22:22 GMT alexaHAP Homebridge Control failed 192.168.1.55:51826 {"characteristics":[{"aid":122,"iid":10,"val
Feb 21 22:22:22 pi-homebridge homebridge[2511]: Wed, 21 Feb 2018 21:22:22 GMT alexaPlugin Status TurnOff 192.168.1.55 51826 Error: Login failed
Feb 21 22:22:22 pi-homebridge homebridge[2511]: at Request._callback (/usr/lib/node_modules/homebridge-alexa/lib/HAPInterface.js:92:16)
Feb 21 22:22:22 pi-homebridge homebridge[2511]: at Request.self.callback (/usr/lib/node_modules/homebridge-alexa/node_modules/request/request.js:186:22)
Feb 21 22:22:22 pi-homebridge homebridge[2511]: at emitTwo (events.js:106:13)
Feb 21 22:22:22 pi-homebridge homebridge[2511]: at Request.emit (events.js:194:7)
Feb 21 22:22:22 pi-homebridge homebridge[2511]: at Request.<anonymous> (/usr/lib/node_modules/homebridge-alexa/node_modules/request/request.js:1163:10)
Feb 21 22:22:22 pi-homebridge homebridge[2511]: at emitOne (events.js:96:13)
Feb 21 22:22:22 pi-homebridge homebridge[2511]: at Request.emit (events.js:191:7)
Feb 21 22:22:22 pi-homebridge homebridge[2511]: at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-alexa/node_modules/request/request.js:1085:12)
Feb 21 22:22:22 pi-homebridge homebridge[2511]: at Object.onceWrapper (events.js:293:19)
Feb 21 22:22:22 pi-homebridge homebridge[2511]: at emitNone (events.js:91:20) undefined
Feb 21 22:22:22 pi-homebridge homebridge[2511]: Wed, 21 Feb 2018 21:22:22 GMT EventedHTTPServer [::ffff:192.168.1.55] Client connection closed
Feb 21 22:22:22 pi-homebridge homebridge[2511]: Wed, 21 Feb 2018 21:22:22 GMT EventedHTTPServer [::ffff:192.168.1.55] HTTP connection was closed
Feb 21 22:22:22 pi-homebridge homebridge[2511]: Wed, 21 Feb 2018 21:22:22 GMT EventedHTTPServer [::ffff:192.168.1.55] HTTP server was closed

**Comment by NorthernMan54** [comment]
@chrisx9 

In the debug output, this line should have more information at the end of it detailing what failed.  Any chance you could share that?  

Feb 21 22:22:22 pi-homebridge homebridge[2511]: Wed, 21 Feb 2018 21:22:22 GMT alexaHAP Homebridge Control failed 192.168.1.55:51826 {"characteristics":[{"aid":122,"iid":10,"val

Also what plugin is it trying to control?  Are there any errors happening at the plugin side?

For your other questions

1 - http://192.168.1.115 - I think this is a Philips Hue Hub on your network with a HomeKit interface.  And the error is from the homebridge discovery process when it can't login with the PIN.  This is okay as long as it is not a homebridge instance.

2 -in the alexa app "an error occured" - This is a known issue, as I have not implemented the device status API yet ( Alexa.ReportState ), and the error is from that.  It does not impact functionality, only the app doesn't know the current status.

3 - show up as switches regardless of their type - Sorry I had not noticed that, I will need to look into that further.

**Comment by chrisx9** [comment]
Yes, sure! Thanks for looking into it.

Here is the complete output of that row
Feb 22 07:37:32 pi-homebridge homebridge[1917]: Thu, 22 Feb 2018 06:37:32 GMT alexaHAP Homebridge Control failed 192.168.1.55:51826 {"characteristics":[{"aid":117,"iid":10,"value":0}]} null {"status":-70401}

This is the device (but basically it happens to all registered devices):
,{
       "accessory": "Http",
       "name": "4b-funksteckdose",
       "switchHandling": "yes",
       "http_method": "GET",
       "on_url":      "http://192.168.1.55/remote/index.php?group=11100&sys=1&switch=08&action=1&delay=0",
       "off_url":     "http://192.168.1.55/remote/index.php?group=11100&sys=1&switch=08&action=0&delay=0",
       "status_url":  "http://192.168.1.55/remote/status2.php?sys=1&group=11100&switch=08",
       "service": "Switch",
       "brightnessHandling": "no",
       "brightness_url":     "",
       "brightnesslvl_url":  "",
       "sendimmediately": "",
       "username" : "",
       "password" : ""
    },

**Comment by NorthernMan54** [comment]
Did you change the homebridge pin ?  I’m remote, but am thinking it’s a bad pin error

**Comment by chrisx9** [comment]
No, i am not using the pin-paramter.

**Comment by NorthernMan54** [comment]
@cgatnet My principle when developing plugins etc, is to minimize the config needed and default everything.  Hence the default for the PIN option to be the default PIN.  Would a wording change in the README have the same effect?

**Comment by cgatnet** [comment]
@NorthernMan54 thanks for your response! Ok, as you like :) 
Maybe you add a hint for the optional PIN property in the section **HomeBridge-alexa plugin configuration**. think that would have helped me, because I stoped reading and started bugfixing there and read the following lines later <SMILE>
Although I read the error with the PIN in the logs a had no idea it could be a optional property. 
Best regards
