### ISSUE TITLE
Error: HAP discovery failed, please check config

### ISSUE THREAD

**Issue by oohs1** [NorthernMan54/homebridge-alexa#567]
I have supported devices connected to Alexa and I have enabled -I insecure mode. Have reinstalled plug-in. And updated home bridge. But I keep getting same error. What should I do

**Comment by NorthernMan54** [comment]
What Homebridge plugin are you using for your devices

**Comment by oohs1** [comment]
The only plug-in I have is the Alexa plugin. I don’t know if that answered your question.

When ever I ask Alexa to discover devices. What devices should show up? because nothing shows up and the plug-in is linked with my Alexa/Amazon account. And the contact sensor is closed.

**Comment by oohs1** [comment]
And everything I have connected to alexa is not showing up. I have Smart lights and smart plugs connected to alexa but nothing shows up in  homebridge.

**Comment by NorthernMan54** [comment]
This connects the opposite way, homebridge devices to Alexa and not Alexa devices to HomeKit....

**Comment by oohs1** [comment]
Is there a way I can connect Alexa devices to HomeKit because someone had recently gave me a HomePod and I would like to use it with my alexa devices. When I looked up how to put alexa devices in HomeKit it says to use home bridge. Is there any way to put alexa devices into HomeKit

**Comment by NorthernMan54** [comment]
homebridge-alexa-player, allows you to control your Alexa speaker
