### ISSUE TITLE
Device works in Alexa app, but not showing up in Homekit

### ISSUE THREAD

**Issue by Homekitdude** [NorthernMan54/homebridge-alexa#568]
I set this up with HOOBS and have the Alexa added to HomeKit as a hub with a closed sensor, so it sees it properly.

I've added the Black+Decker under cabinet lights to Alexa and can control them in the Alexa app with my voice and by touching the light. What am I missing? Shouldn't it be showing in HomeKit if it's in the Alexa app? I feel really dumb with this stuff, I'm definitely a newbie.

Thanks for the help.

**Comment by NorthernMan54** [comment]
This works the other way, it allows you to control you homebridge devices from Alexa, and not your Alexa devices from homebridge/homekit

**Comment by Homekitdude** [comment]
Ah gosh, thanks for the reply. Do you happen to know of anything that would get Alexa devices on HomeKit?

**Comment by NorthernMan54** [comment]
Unfortunately not
