### ISSUE TITLE
Alexa and home bridge

### ISSUE THREAD

**Issue by Kilo132** [NorthernMan54/homebridge-alexa#574]
Does homebridge keep a record of activity with its interaction with the Alexa app? I know the Alexa app has an activity log but I am curious if homebridge does.

**Comment by NorthernMan54** [comment]
The only log would be what you see in the homebridge.log.  You can increase the level of detail recorded by increasing the plugin's debug log level.

**Comment by Kilo132** [comment]
How do I access the log?

**Comment by Kilo132** [comment]
Will the log show what lights or devices were controlled through the Alexa app?

**Comment by NorthernMan54** [comment]
It will log the internal api call, with the internal identifier for each device.  With some effort it is feasible to determine which is which
