### ISSUE TITLE
Car skill support

### ISSUE THREAD

**Issue by terleevuk** [NorthernMan54/homebridge-alexa#586]
### Current Situation

My car has support of Alexa and its skill is available via the link

https://www.amazon.co.uk/Jaguar-Land-Rover-Remote/dp/B097CHMVK2/ref=sr_1_6?qid=1700592416&rnid=10068518031&s=alexa-skills&sr=1-6

I think it would be cool to have access from Home app to the car as it would be easier to start the climate in the morning and unlock the car to load / unload rather than using a remote

### Proposed Change

Add a car device if it exists in HomeKit at the time or add each function (climate on/off)  as a device on HomeKit thru Alexa

**Comment by NorthernMan54** [comment]
I'm thinking this is a question for homebridge-alexa-smarthome
