### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jat80** [NorthernMan54/homebridge-alexa#6]
Ok, i've just received my echo dot today and looking forward to installing this but realised that it's a special version of homebridge.  

I have just the normal version of homebridge running which I use for controlling my TV and Air Con.  They are all switches so should work with your homebridge-alexa.  

What's the best way to set this up as I have homebridge on my Macmini so would need to re-install this over the top of it which will get rid of my current setup of plugins i'm assuming?

**Comment by NorthernMan54** [comment]
I just installed over top of the existing homebridge and everything just worked.  I didn't need to reinstall any plugins.

**Comment by jat80** [comment]
Thanks for the quick reply.  So the config file doesn't get reset?

**Comment by NorthernMan54** [comment]
Correct, the config does not get reset

**Comment by jat80** [comment]
This worked perfectly!  Thanks so much!
