### ISSUE TITLE
Error Code 401/470 and TCP/UDP

### ISSUE THREAD

**Issue by SeydX** [NorthernMan54/homebridge-alexa#60]
Hey, first of all thanks for this great plugin 

i have an alexa dot, own instance for homebridge-alexa, and several instances for other devices/plugins. And im using the default pin "031-45-154" for all instances

My config.json looks like this:

``  {
    "platform": "Alexa",
    "name": "Alexa",
    "username": "XXX",
    "password": "XXX"
  }``

Homebridge is running with systemd so i added the '-I' tag to the .service file of the instance which i want to control with alexa, like this:

`ExecStart=/usr/local/bin/homebridge $HOMEBRIDGE_OPTS -I`

After installing homebridge-alexa and restarting homebridge, i get following error and alexa cant find any new devices

Feb 27 21:16:08 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:08 GMT alexaLocal offline
Feb 27 21:16:08 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:08 GMT alexaHAP HAP Discover failed Homebridge CMD http://192.168.178.52:51877 error code 401
Feb 27 21:16:08 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:08 GMT alexaHAP HAP Discovered Homebridge-MyPlugins 9 device(s)
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discover failed Homebridge-Sonoff http://192.168.178.52:51543 error code 401
Feb 27 21:16:09 raspberrypi homebridge[15455]: Discovered Broadlink RM device at 192.168.178.36 (34:ea:34:b5:33:ef)
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discover failed Homebridge-Xiaomi Mi http://192.168.178.52:51848 error code 401
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discover failed Koogeek-LS1-772B87 http://192.168.178.72:80 error code 470
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discover failed logi:E4:60 http://192.168.178.64:8080 error code 470
Feb 27 21:16:09 raspberrypi homebridge[15455]: Discovered Broadlink RM device at 192.168.178.54 (34:ea:34:40:8b:3b)
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discover failed Homebridge http://192.168.178.52:51826 error code 401
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discover failed Homebridge-Plugins http://192.168.178.52:51841 error code 401
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discover failed Homebridge-MagicLED http://192.168.178.52:51843 error code 401
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discovered Homebridge-MyPlugins 9 device(s)
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discover failed Homebridge CMD http://192.168.178.52:51877 error code 401
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discover failed Homebridge-Sonoff http://192.168.178.52:51543 error code 401
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discover failed Homebridge-Xiaomi Mi http://192.168.178.52:51848 error code 401
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discover failed logi:E4:60 http://192.168.178.64:8080 error code 470
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discover failed Homebridge http://192.168.178.52:51826 error code 401
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discovered Sicherheitskamera 1 device(s)
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discover failed Homebridge-MagicLED http://192.168.178.52:51843 error code 401
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discover failed Homebridge-Plugins http://192.168.178.52:51841 error code 401
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discovered iSight Camera 1 device(s)
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discover failed Homebridge-Tests http://192.168.178.52:51893 error code 401
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discover failed Homebridge-Tests http://192.168.178.52:51893 error code 401
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discovered Homebridge Mac 14 device(s)
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discovered iSight Camera 1 device(s)
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discovered Homebridge Mac 14 device(s)
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discovered Sicherheitskamera 1 device(s)
Feb 27 21:16:09 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:09 GMT alexaHAP HAP Discover failed Koogeek-LS1-772B87 http://192.168.178.72:80 error code 470
Feb 27 21:16:13 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:13 GMT alexaLocal reconnect
Feb 27 21:16:14 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:14 GMT alexaLocal connect command/SeyitAbi/#
Feb 27 21:16:19 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:19 GMT alexaHAP HAP Discover failed tado Internet Bridge IB3505980672 http://192.168.178.53:3000 error ETIMEDOUT
Feb 27 21:16:19 raspberrypi homebridge[15455]: Tue, 27 Feb 2018 20:16:19 GMT alexaHAP HAP Discover failed tado Internet Bridge IB3505980672 http://192.168.178.53:3000 error ETIMEDOUT
Feb 27 21:16:46 raspberrypi homebridge[15455]: Error: protocol must be either '_tcp' or '_udp' but is 'undefined'
Feb 27 21:16:46 raspberrypi homebridge[15455]:     at checkProtocolU (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mdns/lib/service_type.js:184:11)
Feb 27 21:16:46 raspberrypi homebridge[15455]:     at ServiceType.fromString (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mdns/lib/service_type.js:62:3)
Feb 27 21:16:46 raspberrypi homebridge[15455]:     at new ServiceType (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mdns/lib/service_type.js:15:14)
Feb 27 21:16:46 raspberrypi homebridge[15455]:     at Object.makeServiceType (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mdns/lib/service_type.js:133:10)
Feb 27 21:16:46 raspberrypi homebridge[15455]:     at Browser.on_service_changed (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mdns/lib/browser.js:43:19)
Feb 27 21:16:46 raspberrypi homebridge[15455]:     at SocketWatcher.MDNSService.self.watcher.callback (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mdns/lib/mdns_service.js:18:40)
Feb 27 21:16:46 raspberrypi homebridge[15455]: Error: protocol must be either '_tcp' or '_udp' but is 'undefined'
Feb 27 21:16:46 raspberrypi homebridge[15455]:     at checkProtocolU (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mdns/lib/service_type.js:184:11)
Feb 27 21:16:46 raspberrypi homebridge[15455]:     at ServiceType.fromString (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mdns/lib/service_type.js:62:3)
Feb 27 21:16:46 raspberrypi homebridge[15455]:     at new ServiceType (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mdns/lib/service_type.js:15:14)
Feb 27 21:16:46 raspberrypi homebridge[15455]:     at Object.makeServiceType (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mdns/lib/service_type.js:133:10)
Feb 27 21:16:46 raspberrypi homebridge[15455]:     at Browser.on_service_changed (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mdns/lib/browser.js:43:19)
Feb 27 21:16:46 raspberrypi homebridge[15455]:     at SocketWatcher.MDNSService.self.watcher.callback (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mdns/lib/mdns_service.js:18:40)

**Comment by NorthernMan54** [comment]
Resolved with try2

sudo npm install -g northernMan54/homebridge-alexa#try2
