### ISSUE TITLE
xiaomi aqara sensors - Name in Alexa is last update time

### ISSUE THREAD

**Issue by NorthernMan54** [NorthernMan54/homebridge-alexa#61]
homebridge-hue uses the name characteristic for last updated, and my accessory object parsing logic doesn't expect to have multiple name characteristics for one device.

**Comment by MikeDeltaHH** [comment]
Hi NorthernMan54!
Sorry for capture this open issue but i will test the beta and need an option to send you a pn with my amazon account, don´t find any way at slack...

**Comment by NorthernMan54** [comment]
You can get onto the homebridge’s slack here https://slackin-znyruquwmv.now.sh <https://slackin-znyruquwmv.now.sh/>

Then you can just do a direct message to me NorthernMan54 with the account details
