### ISSUE TITLE
Support for plugin

### ISSUE THREAD

**Issue by Segeco** [NorthernMan54/homebridge-alexa#709]
### Current Situation

Please can support be added for the homebridge plugin; homebridge-playstation

https://github.com/kopiro/homebridge-playstation#readme

### Proposed Change

N:A

**Comment by NorthernMan54** [comment]
Could you collect an homebridge accessory dump from the plugin, I would need to see what type of HomeKit accessories are created, then I should be able to add it.

What type of support are you looking for ?  I can see On/Off being straight forward anything else ?
