### ISSUE TITLE
White Ikea Tradfri bulbs appear as color bulbs

### ISSUE THREAD

**Issue by NorthernMan54** [NorthernMan54/homebridge-alexa#73]

**Comment by chrisx9** [comment]
Here is the requested output. Through "curl -X PUT http://127.0.0.1:51826/accessories --header "Content-Type:Application/json" --header "authorization: 031-45-154" > output.txt"

[output.txt](https://github.com/NorthernMan54/homebridge-alexa/files/1805210/output.txt)

**Comment by NorthernMan54** [comment]
chrisx9 [1:54 AM]
‚Wohnzimmertisch‘ :-)

**Comment by NorthernMan54** [comment]
Resolved with pull request #74
