### ISSUE TITLE
error by installing(fixed)

### ISSUE THREAD

**Issue by ItsFelix** [NorthernMan54/homebridge-alexa#8]
Hello, if i want to install homebridge-alexa i get this error:

pi@raspberrypi:~ $ sudo npm install -g https://github.com/NorthernMan54/homebridge
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/NorthernMan54/homebridge.git /root/.npm/_git-remotes/git-https-github-com-NorthernMan54-homebridge-git-a6b381b2: Klone in Bare-Repository '/root/.npm/_git-remotes/git-https-github-com-NorthernMan54-homebridge-git-a6b381b2'...
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/NorthernMan54/homebridge.git /root/.npm/_git-remotes/git-https-github-com-NorthernMan54-homebridge-git-a6b381b2: fatal: unable to access 'https://github.com/NorthernMan54/homebridge.git/': Failed to connect to github.com port 443: Connection refused
npm ERR! Linux 4.4.50-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "https://github.com/NorthernMan54/homebridge"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/NorthernMan54/homebridge.git /root/.npm/_git-remotes/git-https-github-com-NorthernMan54-homebridge-git-a6b381b2
npm ERR! Klone in Bare-Repository '/root/.npm/_git-remotes/git-https-github-com-NorthernMan54-homebridge-git-a6b381b2'...
npm ERR! fatal: unable to access 'https://github.com/NorthernMan54/homebridge.git/': Failed to connect to github.com port 443: Connection refused
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

i think it's my Fritzbox barrier but im not sure :/

**Comment by chongkwongsheng** [comment]
May I know how this was fixed? I had a similar issue today:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'https://github.com/NorthernMan54/homebridge' ]
2 info using npm@5.0.3
3 info using node@v8.1.3
4 verbose npm-session e93399f536fec237
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for git+https://github.com/NorthernMan54/homebridge.git Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/NorthernMan54/homebridge.git /root/.npm/_cacache/tmp/git-clone-42a691db
7 silly fetchPackageMetaData fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-42a691db': Permission denied
8 verbose stack Error: Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/NorthernMan54/homebridge.git /root/.npm/_cacache/tmp/git-clone-42a691db
8 verbose stack fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-42a691db': Permission denied
8 verbose stack
8 verbose stack     at ChildProcess.exithandler (child_process.js:270:12)
8 verbose stack     at emitTwo (events.js:125:13)
8 verbose stack     at ChildProcess.emit (events.js:213:7)
8 verbose stack     at maybeClose (internal/child_process.js:897:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
9 verbose cwd /home/pi
10 verbose Linux 4.9.28-v7+
11 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "https://github.com/NorthernMan54/homebridge"
12 verbose node v8.1.3
13 verbose npm  v5.0.3
14 error code 128
15 error Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/NorthernMan54/homebridge.git /root/.npm/_cacache/tmp/git-clone-42a691db
15 error fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-42a691db': Permission denied
16 verbose exit [ 1, true ]

**Comment by NorthernMan54** [comment]
I googled your error and they gave a couple of fixes, but I think this should resolve it.

sudo npm install -g --unsafe-perm https://github.com/NorthernMan54/homebridge

Please note that these errors are just general installation and not related to my package.

**Comment by chongkwongsheng** [comment]
That didn't work. In fact, I've given up on my current set up and reinstalled everything from fresh and now it works. Took over an hour but everything works now. I used the unsafe perm command as you suggested this time round as well.
