### ISSUE TITLE
HAP Discovery failed, please review config (Docker, multiple homebridge instance)

### ISSUE THREAD

**Issue by quacktacular** [NorthernMan54/homebridge-alexa#81]
I have multiple homebridge instances setup with the oznu's docker-homebridge image. Each runs on its own port with its own pin. 

I only really want to use one with homebridge-alexa (for my webos tv)

- Set that container to start up using insecure home (using HOMEBRIDGE_INSECURE=1 for env)
- Used the PIN from above container in my homebridge-alexa config.
- Also started homebridge-alexa instance with insecure mode, and with debug enabled.

config on homebridge-webos instance
```
    "bridge": {
        "name": "TVbert Bridge",
        "username": "CC:22:3D:E3:00:00",
        "port": 51000,
        "pin": "031-45-000"
    },
```

config on homebridge-alexa instance
```
    "platforms": [
        {
            "platform": "Alexa",
            "name": "Alexa",
            "username": "myusername",
            "password": "mypassword",
            "pin": "031-45-000"
        }
    ]
```
Confirmed the homebridge-webos instance is starting up in insecure mode: 
```
Starting homebridge in insecure mode...
-U /homebridge -P /homebridge/node_modules -I
```
This is all I get: `[Alexa] ERROR: HAP Discovery failed, please review config`

What am I missing?

**Comment by NorthernMan54** [comment]
Try moving the -I as the first parameter rather than the last.

The review config error is caused by having no devices passed to Alexa.

**Comment by quacktacular** [comment]
Thanks! Because the instance is in a docker container I wasn't able to change the arg order in a persistent way (without editing the image), but by turning off the debug option entirely it started working. Woohoo.

Follow up question--if I later on wanted to connect to a second homebridge instance with a different PIN, would that be possible?

**Comment by NorthernMan54** [comment]
Sorry, all the pins must be identical.

Which Docker container are you running?
