### ISSUE TITLE
Error when loading the plugin

### ISSUE THREAD

**Issue by macpoupou** [NorthernMan54/homebridge-alexa#83]
Homebridge is installed in Docker on my Synology (https://hub.docker.com/r/cbrandlehner/homebridge/).
I have set the variables DEBUG=alexa* and HOMEBRIDGE_INSECURE=1.

But when homebridge load the plugin, I have this error:

![capture d ecran 2018-03-31 a sam 31 22 04 23](https://user-images.githubusercontent.com/325015/38167076-943e0c00-352f-11e8-8c26-574eb562914a.png)

**Comment by NorthernMan54** [comment]
@macpoupou Have you tried this docker container?  I did testing with Oznu

https://github.com/oznu/docker-homebridge

**Comment by macpoupou** [comment]
Perfect ! it works !
