### ISSUE TITLE
HOMEBRIDGE_OPTS=-I -U /var/homebridge can not save file 

### ISSUE THREAD

**Issue by wroblewski6** [NorthernMan54/homebridge-alexa#85]
I followed on my RPI this instruction to start with systemd, http://pysselilivet.blogspot.com/2017/01/homebridge-autostart-with-systemd.html

do i have to change something in /etc/default/homebridge. 

now I have 

# Defaults / Configuration options for homebridge
# The following settings tells homebridge where to find the config.json file and where to persist the data (i.e. pairing and others)
HOMEBRIDGE_OPTS=-U /var/homebridge

# If you uncomment the following line, homebridge will log more 
# You can display this via systemd's journalctl: journalctl -f -u homebridge
# DEBUG=*

So I should change to 

# Defaults / Configuration options for homebridge
# The following settings tells homebridge where to find the config.json file and where to persist the data (i.e. pairing and others)
HOMEBRIDGE_OPTS=-I -U /var/homebridge

# If you uncomment the following line, homebridge will log more 
# You can display this via systemd's journalctl: journalctl -f -u homebridge
# DEBUG=*

But I can not do this because I can not save this file because I have access denied information, 
I tried it on cyber duck and directly on raspberry

**Comment by maimbe** [comment]
how u make it for working?
