### ISSUE TITLE
Any chance you could add a color saturation variable to allow for RGB-CCT LEDs supporting the feature to be completely configurable

### ISSUE THREAD

**Issue by pauleec** [NorthernMan54/homebridge-alexa#87]
I finally got round to updating the old version of the homebridge-alexa plugin today. The update went without too many problems and I've now got the ability to switch on and off, set the brightness and color of all the Mi-Light lights I am using. The latest Mi-Light bulbs are setup in the Mi-light plugin as "fullColor" and have RGB-CCT (Configurable Color Temperature white) and have a color saturation capability which allows for the color and white LEDs to change the color saturation/intensity of the lighting.

Would it be possible to do this in the homebridge-alexa plugin light support? Is there a way to support color saturation and white temperature?

If I wanted to set a custom color setting (with a saturation value) and have it display in the Alexa app as a new color how is this done?

Thanks again for such a great piece of work. I'd been delaying the update to give me enough time to get it working right. In the end it  only took 10 mins!

Thanks

Paul

**Comment by NorthernMan54** [comment]
Paul,

This is doable, I just don’t have any method of testing this.  Once I have it wired up, I will need you to test this.

Stay tuned.

**Comment by pauleec** [comment]
Ok if you like I can send you a bridge and rgb-c ct ligbt to help. Keen to assist in any way I can. This is a great piece of work!

**Comment by NorthernMan54** [comment]
I’m working on colour temperature 

https://github.com/NorthernMan54/homebridge-alexa/tree/ColorTemperature <https://github.com/NorthernMan54/homebridge-alexa/tree/ColorTemperature>

Aka 

https://developer.amazon.com/docs/device-apis/alexa-colortemperaturecontroller.html <https://developer.amazon.com/docs/device-apis/alexa-colortemperaturecontroller.html>

Is this what your thinking of ?

**Comment by pauleec** [comment]
The RGB-CCT bulbs/remotes/app provide White configurable color - which is
what you have the details on. There is also the ability to add color to the
white light (ie colorsaturation). The remotes have a sliding adjustment for
both.

So you can vary the white temperature. Or you can make the colours whiter
by providing a way to vary the white light added to the colored.

The limitlessled.com/dev site has more detail on the new functions. It
looks like there is a color, saturation, brightness and kelvin variable.
Here are the commands:


   - *List of {COMMAND}s:*
   - format of {command} 9 byte packet = 0x31 {PasswordByte1 default 00}
   {PasswordByte2 default 00} {remoteStyle 08 for RGBW/WW/CW or 00 for bridge
   lamp} {LightCommandByte1} {LightCommandByte2} 0x00 0x00 0x00 {Zone1-4
   0=All} 0x00 {Checksum}
   - 31 00 00 08 04 01 00 00 00 = Light ON
   - 31 00 00 08 04 02 00 00 00 = Light OFF
   - 31 00 00 08 04 05 00 00 00 = Night Light ON
   - 31 00 00 08 05 64 00 00 00 = White Light ON (Color RGB OFF)
   - 31 00 00 08 01 BA BA BA BA = Set Color to Blue (0xBA) (0xFF = Red, D9
   = Lavender, BA = Blue, 85 = Aqua, 7A = Green, 54 = Lime, 3B = Yellow, 1E =
   Orange)
   - 31 00 00 08 02 SS 00 00 00 = Saturation (SS hex values 0x00 to 0x64 :
   examples: 00 = 0%, 19 = 25%, 32 = 50%, 4B, = 75%, 64 = 100%)
   - 31 00 00 08 03 BN 00 00 00 = BrightNess (BN hex values 0x00 to 0x64 :
   examples: 00 = 0%, 19 = 25%, 32 = 50%, 4B, = 75%, 64 = 100%)
   - 31 00 00 08 05 KV 00 00 00 = Kelvin (KV hex values 0x00 to 0x64 :
   examples: 00 = 2700K (Warm White), 19 = 3650K, 32 = 4600K, 4B, = 5550K, 64
   = 6500K (Cool White))
   - 31 00 00 08 06 MO 00 00 00 = Mode Number (MO hex values 0x01 to 0x09 :
   examples: 01 = Mode1, 02 = Mode2, 03 = Mode3 .. 09 = Mode9)
   - 31 00 00 08 04 04 00 00 00 = Mode Speed Decrease--
   - 31 00 00 08 04 03 00 00 00 = Mode Speed Increase++
   - 3D 00 00 08 00 00 00 00 00 = Link (Sync Bulb within 3 seconds of
   lightbulb socket power on)
   - 3E 00 00 08 00 00 00 00 00 = UnLink (Clear Bulb within 3 seconds of
   lightbulb socket power on)

**Comment by NorthernMan54** [comment]
@pauleec 

I think I have color temperature working for white light bulbs that support color temperature.  I don't have an actual bulb, but I simulated the bulb using the homebridge-magichome plugin and it appears to work correctly.

You would need to install this version of homebridge-alexa, and discover devices again

sudo npm install -g northernman54/homebridge-alexa#ColorTemperature

**Comment by pauleec** [comment]
@NorthernMan54 

Hi,

I am happy to confirm that I now have a range of rgb colours and a range of warm to cold white settings that can be applied with Alexa via the updated homebridge-Alexa app.

Huge improvement on before! 

I’ve included some screenshots of the Mi-Light app and how they handle both white temperature and Color saturation. If the lights are not in a white mode (ie where the W is not pressed/set to on), the RGB Color saturation value can be set which allows for more pastel colours to be possible.

It’s really good work though.Alexa controls everything round my house now :-)

One thing I noticed. The Color is set and is displayed in the Alexa app light as the correct Color for about 10 seconds and then goes back to a white.... is that normal?

I’ve included some screenshots of how the Alexa app shows the light zones that are defined in the Mi-Light bridge I have setup here.

I am running the RM Tasker plugin as a way to expose my Broadlink-RM Pro defined devices to Alexa and am starting to test the homebridge-broadlink-rm plugin as an alternative and to remove the extra android component (which runs the RM Tasker plugin). I’ll keep you posted because initial tests of the way the new homebridge-alexa plugin open and close the window coverings based on time per signal sent doesn’t seem to work with the curtains I have here. (Rm Tasker sends a single open or close signal rather than many signals) I’ll keep investigating.

Thanks again for this! Would you like me to send you a Mi-Light bridge and a rgb-cut 8 zone cabable light for your own testing? If so send me your mail address and I’ll post it to you.

All the best
![72d17a62-50c1-4460-a3f1-76353a72c6f2](https://user-images.githubusercontent.com/4813009/38892954-27674d80-42cc-11e8-9346-afd60db8e325.jpeg)
![55f5aaa7-e9bc-4166-8b1e-329f03277bd3](https://user-images.githubusercontent.com/4813009/38892955-27b16e4c-42cc-11e8-8472-d82ac7ccaa0c.png)
![a8ac0bf8-b9bc-43a0-bead-0639c03ead11](https://user-images.githubusercontent.com/4813009/38892956-27ecd2ca-42cc-11e8-995e-2ed929597153.png)
![ff8bc6c0-5847-4c6e-9b3a-a27236b8e457](https://user-images.githubusercontent.com/4813009/38892958-2824bc1c-42cc-11e8-8ef8-232d675a220b.png)
![e99e8c6b-d973-4f8e-afa1-0fef483c7062](https://user-images.githubusercontent.com/4813009/38892959-28603c56-42cc-11e8-901c-6bf0449d51ce.png)
![6e1a0fd7-02ca-4803-b693-972c5046e54b](https://user-images.githubusercontent.com/4813009/38892960-2899f8f6-42cc-11e8-8598-20645c1ced03.png)
![7121f21e-e6d8-49fe-8dcc-ddc623627e84](https://user-images.githubusercontent.com/4813009/38892962-2998b904-42cc-11e8-9867-c18c6f1fcc6a.jpeg)
![cbf2fa42-db61-403e-b200-14f48981e18f](https://user-images.githubusercontent.com/4813009/38892965-29d5c0e2-42cc-11e8-9e10-067ce93c21eb.jpeg)
![c56361f7-c1a1-464a-bb3c-82b7f0a4c656](https://user-images.githubusercontent.com/4813009/38892990-3e29f306-42cc-11e8-8a17-b4abfecd9ea8.jpeg)
![211dfcb8-66b5-4dd7-88ec-716f428759c3](https://user-images.githubusercontent.com/4813009/38892991-3e6a9ec4-42cc-11e8-91f2-beac0d84471e.jpeg)

**Comment by pauleec** [comment]
@NorthernMan54 

Sure here you go

{"accessories":[{"aid":1,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Nick Farina","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Homebridge","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"DanksStreet","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"CC:22:3D:E3:CE:31","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"0.4.38","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":2000000008,"type":"49FB9D4D-0FEA-4BF1-8FA6-E7B18AB86DCE","characteristics":[{"iid":9,"type":"77474A2F-FA98-485E-97BE-4762458774D8","perms":["pr","ev"],"format":"uint8","value":0,"description":"State","maxValue":1,"minValue":0,"minStep":1},{"iid":10,"type":"FD9FE4CC-D06F-4FFE-96C6-595D464E1026","perms":["pr","ev"],"format":"string","value":"1.0","description":"Version"},{"iid":11,"type":"5819A4C2-E1B0-4C9D-B761-3EB1AFF43073","perms":["pr","pw","ev"],"format":"data","value":null,"description":"Control Point"}],"primary":false,"hidden":false}]},{"aid":2,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"MiLight","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"fullColor8Zone","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Kitchen Downlighters","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"12345","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Kitchen Downlighters","description":"Name"},{"iid":10,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":false,"description":"On"},{"iid":11,"type":"00000008-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"int","value":0,"description":"Brightness","unit":"percentage","maxValue":100,"minValue":0,"minStep":1},{"iid":12,"type":"0000002F-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":0,"description":"Saturation","unit":"percentage","maxValue":100,"minValue":0,"minStep":1},{"iid":13,"type":"00000013-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":0,"description":"Hue","unit":"arcdegrees","maxValue":360,"minValue":0,"minStep":1},{"iid":14,"type":"000000CE-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"uint32","value":153,"description":"Color Temperature","maxValue":370,"minValue":153,"minStep":1}],"primary":false,"hidden":false}]},{"aid":3,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"MiLight","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"fullColor8Zone","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Kitchen Bulbs","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"12345","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Kitchen Bulbs","description":"Name"},{"iid":10,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":false,"description":"On"},{"iid":11,"type":"00000008-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"int","value":0,"description":"Brightness","unit":"percentage","maxValue":100,"minValue":0,"minStep":1},{"iid":12,"type":"0000002F-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":0,"description":"Saturation","unit":"percentage","maxValue":100,"minValue":0,"minStep":1},{"iid":13,"type":"00000013-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":0,"description":"Hue","unit":"arcdegrees","maxValue":360,"minValue":0,"minStep":1},{"iid":14,"type":"000000CE-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"uint32","value":153,"description":"Color Temperature","maxValue":370,"minValue":153,"minStep":1}],"primary":false,"hidden":false}]},{"aid":4,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"MiLight","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"fullColor8Zone","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Bathroom","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"12345","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Bathroom","description":"Name"},{"iid":10,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":false,"description":"On"},{"iid":11,"type":"00000008-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"int","value":0,"description":"Brightness","unit":"percentage","maxValue":100,"minValue":0,"minStep":1},{"iid":12,"type":"0000002F-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":0,"description":"Saturation","unit":"percentage","maxValue":100,"minValue":0,"minStep":1},{"iid":13,"type":"00000013-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":0,"description":"Hue","unit":"arcdegrees","maxValue":360,"minValue":0,"minStep":1},{"iid":14,"type":"000000CE-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"uint32","value":153,"description":"Color Temperature","maxValue":370,"minValue":153,"minStep":1}],"primary":false,"hidden":false}]},{"aid":5,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"MiLight","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"fullColor8Zone","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Bedside Downlighters","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"12345","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Bedside Downlighters","description":"Name"},{"iid":10,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":false,"description":"On"},{"iid":11,"type":"00000008-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"int","value":0,"description":"Brightness","unit":"percentage","maxValue":100,"minValue":0,"minStep":1},{"iid":12,"type":"0000002F-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":0,"description":"Saturation","unit":"percentage","maxValue":100,"minValue":0,"minStep":1},{"iid":13,"type":"00000013-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":0,"description":"Hue","unit":"arcdegrees","maxValue":360,"minValue":0,"minStep":1},{"iid":14,"type":"000000CE-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"uint32","value":153,"description":"Color Temperature","maxValue":370,"minValue":153,"minStep":1}],"primary":false,"hidden":false}]},{"aid":6,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"MiLight","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"fullColor8Zone","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Bedside Lamps","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"12345","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Bedside Lamps","description":"Name"},{"iid":10,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":true,"description":"On"},{"iid":11,"type":"00000008-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"int","value":0,"description":"Brightness","unit":"percentage","maxValue":100,"minValue":0,"minStep":1},{"iid":12,"type":"0000002F-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":0,"description":"Saturation","unit":"percentage","maxValue":100,"minValue":0,"minStep":1},{"iid":13,"type":"00000013-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":0,"description":"Hue","unit":"arcdegrees","maxValue":360,"minValue":0,"minStep":1},{"iid":14,"type":"000000CE-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"uint32","value":153,"description":"Color Temperature","maxValue":370,"minValue":153,"minStep":1}],"primary":false,"hidden":false}]},{"aid":7,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"MiLight","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"fullColor8Zone","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Guest Bathroom","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"12345","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Guest Bathroom","description":"Name"},{"iid":10,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":true,"description":"On"},{"iid":11,"type":"00000008-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"int","value":0,"description":"Brightness","unit":"percentage","maxValue":100,"minValue":0,"minStep":1},{"iid":12,"type":"0000002F-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":0,"description":"Saturation","unit":"percentage","maxValue":100,"minValue":0,"minStep":1},{"iid":13,"type":"00000013-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":0,"description":"Hue","unit":"arcdegrees","maxValue":360,"minValue":0,"minStep":1},{"iid":14,"type":"000000CE-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"uint32","value":153,"description":"Color Temperature","maxValue":370,"minValue":153,"minStep":1}],"primary":false,"hidden":false}]},{"aid":8,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"MiLight","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"fullColor8Zone","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Workshop","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"12345","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Workshop","description":"Name"},{"iid":10,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":true,"description":"On"},{"iid":11,"type":"00000008-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"int","value":0,"description":"Brightness","unit":"percentage","maxValue":100,"minValue":0,"minStep":1},{"iid":12,"type":"0000002F-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":0,"description":"Saturation","unit":"percentage","maxValue":100,"minValue":0,"minStep":1},{"iid":13,"type":"00000013-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":0,"description":"Hue","unit":"arcdegrees","maxValue":360,"minValue":0,"minStep":1},{"iid":14,"type":"000000CE-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"uint32","value":153,"description":"Color Temperature","maxValue":370,"minValue":153,"minStep":1}],"primary":false,"hidden":false}]},{"aid":9,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"MiLight","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"rgbw","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Kitchen LED Strips","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"12345","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000043-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Kitchen LED Strips","description":"Name"},{"iid":10,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":false,"description":"On"},{"iid":11,"type":"00000008-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"int","value":0,"description":"Brightness","unit":"percentage","maxValue":100,"minValue":0,"minStep":1},{"iid":12,"type":"0000002F-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":0,"description":"Saturation","unit":"percentage","maxValue":100,"minValue":0,"minStep":1},{"iid":13,"type":"00000013-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"float","value":0,"description":"Hue","unit":"arcdegrees","maxValue":360,"minValue":0,"minStep":1}],"primary":false,"hidden":false}]},{"aid":10,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Broadlink","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"RM Mini or Pro","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Learn","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"619ae4e6-288d-4e1b-9703-04e6110642bd","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000049-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Learn","description":"Name"},{"iid":10,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":false,"description":"On"}],"primary":false,"hidden":false}]},{"aid":11,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Broadlink","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"RM Mini or Pro","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Scan Frequency","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"a7c4991c-f585-4ca7-9628-530c8daf2aa8","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"00000049-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Scan Frequency","description":"Name"},{"iid":10,"type":"00000025-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"bool","value":false,"description":"On"}],"primary":false,"hidden":false}]},{"aid":12,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Broadlink","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"RM Mini or Pro","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Curtains","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"5a5d3c79-9bce-479b-acd6-aab799cba45f","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"1.0","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":8,"type":"0000008C-0000-1000-8000-0026BB765291","characteristics":[{"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Curtains","description":"Name"},{"iid":10,"type":"0000006D-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"uint8","value":0,"description":"Current Position","unit":"percentage","maxValue":100,"minValue":0,"minStep":1},{"iid":11,"type":"0000007C-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"uint8","value":0,"description":"Target Position","unit":"percentage","maxValue":100,"minValue":0,"minStep":1},{"iid":12,"type":"00000072-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"uint8","value":2,"description":"Position State","valid-values":[0,1,2],"maxValue":2,"minValue":0}],"primary":false,"hidden":false}]}]}

I’ve also taken a load of screenshots from the Apple Home iPhone app and also some shots from other HomeKit supporting apps. I found the Elvato Eve one to be the best.

Here are the screenshots:







I found that the Egatp Eve app was the best for Color/saturation implementation.

Paul

**Comment by NorthernMan54** [comment]
@pauleec Tks Paul for that

Looking at the details, I see that the bulbs have five controls in homebridge

On/Off
Hue - Controls color
Saturation - Controls color
Brightness
ColorTemperature

I was thinking there might have been a control to switch between colour and colortemperature mode, but I didn't see anything, are you aware of anything?  It could be a case where setting hue and saturation to 0, switch the bulbs into colortemperature mode.

**Comment by NorthernMan54** [comment]
Okay, I will discuss with them.

From my experience it is okay to use homebridge-alexa and Siri or the Home app.  Homebridge-Alexa is simulating a local guest iOS device just like a guest you have invited thru the Home app.

Can you describe the bug you are seeing more?

**Comment by pauleec** [comment]
@NorthernMan54 the groups and scenes that I create in homekit or one of the supporting apps are not showing in the Alexa Groups or Scenes. Is this normal?
I think the problem I was seeing may have been user error! Each Group I was creating was always being created with an "All Lights" member. I tested it out some more last night and deleted the groups I had previously setup and setup new groups and scenes and the setup is running well - in homekit. It would be great if the groups and scenes in homekit were able to show up as Alexa Groups and Scenes. I wasn't able to get that to happen! Would that be a feature request or can it be raised as an issue/defect?

**Comment by NorthernMan54** [comment]
Groups and scenes you create in the Home app are not visible to the hap interface and homebridge, so I can’t see them to expose to Alexa.  This is a limitation from Apple/HomeKit.

Alexa does have a scene controller api that I was looking at, but it would need to have the group config setup in config.json.
