### ISSUE TITLE
Required network details for Alexa discovery protocol

### ISSUE THREAD

**Issue by jpawlowski** [NorthernMan54/homebridge-alexa#88]
Hi Norbert,

can you somehow share some network details that the protocol requires?
I am running homebridge in a FreeBSD jail with firewall rules enabled and would need to know a little more about what kind of traffic needs to be allowed.

If you could point me to some useful documentation, I'd be very thankful for it.

Regards,
Julian

**Comment by NorthernMan54** [comment]
Julian,

This is all open source, so you can roll your own flavor if you desire.  Amazon has done a great job with tutorials around creating your own skill, so there is no magic here.  And that is how I got started.

For the domain I’m using, please keep in mind that this homeskill is a free service I’m running as a hobby outside of my day job.  And that dns service is also free as well.  If someone wanted to fund getting a proper domain, I’m all for it.
