### ISSUE TITLE
Is there an Option To get the Old Version back?

### ISSUE THREAD

**Issue by ItsFelix** [NorthernMan54/homebridge-alexa#9]
Hello, i have the normal Homebridge Version now Running, But is it Possible when i install the Special Version from homebridge To install the old Version again if i don't like the Special Version ?
(SRY for My Bad Englisch i come From Germany:))

**Comment by NorthernMan54** [comment]
Yes, just remove the setting in config.json and install the regular version of homebridge, the regular way

sudo npm install -g homebridge

**Comment by ItsFelix** [comment]
okay thx
