### ISSUE TITLE
Multiple filters?

### ISSUE THREAD

**Issue by imsturmdernacht** [NorthernMan54/homebridge-alexa#90]
Dear NorthernMan54,

just a little question. Is it possible to use multiple filters for more than one device? Is there a separator?
For example:

"platforms": [
  {
    "platform": "Alexa",
    "name": "Alexa",
    "username": "....",
    "password": "....",
    "filter": "Office Light; Bedroom Light; Kitchen Light"
  }
],

Regards, Oli.

**Comment by NorthernMan54** [comment]
Sorry no, it is only for meant for one device.  It was a quick implementation I did to restrict amazon access during certification testing.
