### ISSUE TITLE
Schlage Sense

### ISSUE THREAD

**Issue by alanfromtoronto** [NorthernMan54/homebridge-alexa#92]
I have a Schlage Sense lock which is a native homekit lock.  Is there a way to register it on homebridge so I can use it via Alexa?

**Comment by NorthernMan54** [comment]
Alan,

Unfortunately this only works with devices exposed by homebridge.  Have you looked for a homebridge plugin for your Schlege sense?

If there is a plugin, I could wire it up, as Alexa supports locks.

https://developer.amazon.com/docs/device-apis/alexa-lockcontroller.html
