### ISSUE TITLE
launchd macOS - insecure mode

### ISSUE THREAD

**Issue by jat80** [NorthernMan54/homebridge-alexa#96]
Hi mate,

I'm about to try and set this up but I'm using launchd as shown [here](https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-macOS) for auto starting homebridge on my mac mini.  How do I make it launch in insecure mode?

**Comment by NorthernMan54** [comment]
Sorry, I’m not familiar with launchd, but looking at the example I saw the -I there. Did you try it?

**Comment by jat80** [comment]
@NorthernMan54 oh I just saw that in the example. I will try it tomorrow and report back.  Thanks!

**Comment by jat80** [comment]
@NorthernMan54 installed (seamlessly I might add) and working perfectly mate!  No need to change launchd config as it is already configured for insecure mode as shown in link above for macOS users.

Thanks so much for your work on this.  Such a great homebridge plugin!!!
