### ISSUE TITLE
Alexa Discovers Duplicate Devices

### ISSUE THREAD

**Issue by brentleeper** [NorthernMan54/homebridge-alexa#97]
Each time you ask Alexa to discover devices, she creates duplicates of all current devices plus the new device/s. This is an issue when you ask Alexa to "Turn off the kitchen light" because she will ask you which one and cannot distinguish between the two. 

This occurs after stoping Homebridge, adding a new accessory in config.json, starting Homebridge, and then asking Alexa to discover devices.

**Comment by Darko2** [comment]
I have the same issue. My workarround was deleting all devices on Alexa website, then discover again. But its a bad way to do it as you have to setup all your Routines again.

**Comment by NorthernMan54** [comment]
Give me a couple of days on this, I need to look at how it linking the HomeBridge devices to Alexa devices and think you have uncovered a couple of use cases that cause issues.

**Comment by jak1502** [comment]
I thought that might be the case but no I’m not seeing new devices in HomeKit, they stay static.

**Comment by Darko2** [comment]
Im running five homebridge instances and every one has a unique port, pin, name and username.

**Comment by NorthernMan54** [comment]
One potential cause of this issue, is your homebridge server changing ip addresses or port.  As part of the unique id of a device I'm including the ip address and port of your homebridge instance.

**Comment by sschuste** [comment]
Some additional info from me: my homebridge server never changes its IP address or the port and I only use one instance. A few weeks ago all switches were displayed twice in the Alexa app, some even three times. After I had deleted all devices using the Alexa app, the problem only remains with homebridge-zp. This is actually displayed 14 times. I can use every of the 14 switches to control my Sonos system. They all work. I hardly ever use the Alexa app, so it doesn't bother me too much.

**Comment by lily148** [comment]
I can confirm when the device IP is changed, new device will discover then the old device can't be control (become unresponsive in Alexa app).
Possible to use MAC address as a identifier so it won't duplicate new device and still able to control when IP is different?

**Comment by NorthernMan54** [comment]
The current endpoint identifier code is

https://github.com/NorthernMan54/homebridge-alexa/blob/dc0ba68b6856e06c8fb2af85e8acef463798d792/lib/alexaTranslator.js#L409

Which uses homebridge host and port plus the device aid/Iid

With this pattern, there also is a use case where homebridge changes the device aid/iid as well.  And causes the same issue, I see that in my setup occasionally as well.

I have been thinking about changing the endpoint identifier logic, but as it would be a breaking change am rather reluctant to proceed with it.

**Comment by NorthernMan54** [comment]
I was looking at my setup, as I have a single device that moves around after restart of homebridge and found that the IID was changing for the last characteristic on the device.  And the plugin was using the last IID as the unique endpoint ID.

**Comment by NorthernMan54** [comment]
For this issue, I have implemented a fix in the event branch of the plugin, so I will be publishing this shortly to the world.  I'm waiting for the current skill back to be certified by Amazon before publishing this to the world.

For the fix, I changed the unique device key supplied to Amazon Alexa to be a combination of homebridge name, homebridge username, plugin manufacturer, accessory name and service characteristic.  ( homebridge name and username are from the config.json bridge settings.)  As part of updating to the newer version, you will need to have Alexa forget all your existing devices and discover again.

If this is an annoying issue for yourself, you could install a early version of this.  Let me know

https://github.com/NorthernMan54/homebridge-alexa/tree/event

**Comment by nicoh88** [comment]
Hi @NorthernMan54, 

i had exactly this problem two weeks ago and i disable the plugin. Is the problem solved? Does the amazon skill need to be updated or only the homebridge plugin?

Is the _event_ branch meanwhile merged into the _master_ branch?

Many Greetings
Nico

**Comment by NorthernMan54** [comment]
@nicoh88 The event branch is not merged into the main branch yet. I have been completing more testing of the events module to ensure it is 100% ready for prime time prior to releasing.  But it is stable enough for use, as I have been using it for a few weeks along with several others.

**Comment by NorthernMan54** [comment]
This was published as the main version about a month ago, so this issue is now resolved.

**Comment by bubez81** [comment]
Hello, i'm not sure this is the right place, but in the logs i can see:
[2019-9-5 07:56:33] [Alexa] WARNING: Duplicate device name Zona Giorno
[2019-9-5 07:56:33] [Alexa] WARNING: Duplicate device name Zona Notte
they are not the same device and alexa recognize the two device separately.
I can't understand what does that mean.

**Comment by NorthernMan54** [comment]
What the warning is saying is that you have 2 devices named Zona Giorno and 2 devices named Zona Notte that were passed to Alexa.  This is just an FYI, and if you look in the Alexa app you may find duplicate devices

**Comment by bubez81** [comment]
eh...it's not true I can see only one device named Zona giorno and one Zona Notte.
...ahhh ok....in homebridge this daikin conditioner is divided into two devices, one for the split and one for the fan...maybe it's this the problem!

**Comment by NorthernMan54** [comment]
That sounds like why the warning is being triggered

**Comment by bubez81** [comment]
the warning is gone....

**Comment by NorthernMan54** [comment]
Cool

**Comment by BenAndDevelopment** [comment]
Hi, 
I have the following error with all my yeelights:
[Alexa] WARNING: Duplicate device name Color Light
[Alexa] ERROR: Parsing failed, removing duplicate endpointID => Color Light

I get this for every light and in the end I have only one light in the home app. I tried renaming them with the yeelight plugin, but no success. I renamed them everywhere I cloud find them. Any idea why this is?

**Comment by NorthernMan54** [comment]
@BenAndDevelopment Please open as a new issue, and include a homebridge accessory dump, details are in the README.  Also what plugin are you using for the yee lights ( GitHub url )

**Comment by varn-lt** [comment]
I have the same warnings with https://github.com/homebridge-plugins/homebridge-camera-ffmpeg plugin where each camera gets duplicates in Alexa:
```
[6/29/2020, 13:05:00] [Alexa] WARNING: Duplicate device name Garage View
[6/29/2020, 13:05:00] [Alexa] WARNING: Duplicate device name Garage View
[6/29/2020, 13:05:00] [Alexa] WARNING: Duplicate device name Parking View
[6/29/2020, 13:05:00] [Alexa] WARNING: Duplicate device name Parking View
[6/29/2020, 13:05:00] [Alexa] ERROR: Parsing failed, removing duplicate endpointID => Garage View
[6/29/2020, 13:05:00] [Alexa] ERROR: Parsing failed, removing duplicate endpointID => Parking View
```

and here is what I see in https://alexa.amazon.com :
![Capture](https://user-images.githubusercontent.com/45877788/86004749-684dc800-ba1c-11ea-9d34-ed958f4e416b.PNG)
question would be who should fix this bug homebridge-alexa or homebridge-camera-ffmpeg

**Comment by NorthernMan54** [comment]
As the duplicates are camera’s they can be ignored

**Comment by varn-lt** [comment]
I understand it but log full of warnings and errors does not look nice and correct, there should be a way how to solve it. For example there could be option where I could set list of devices I do not want to send to alexa from homebridge, so I could ignore all cameras and other unsupported devices
