### ISSUE TITLE
Error: ECONNREFUSED

### ISSUE THREAD

**Issue by Mick93340** [NorthernMan54/homebridge-alexa#98]
Hi,

Everything has been working fine for weeks, but this morning I woke up and none of my devicesare responding, I have the following error:
ERROR: alexaStateResponse connect ECONNREFUSED 192.168.1.136:51826.

Any clue?

Thanks,

**Comment by NorthernMan54** [comment]
That message is from homebridge Alexa trying to talk to homebridge at that IP address and port.  Is your homebridge up and running?   If it is, try discovering devices again.

**Comment by Mick93340** [comment]
Working now, Thx Mate. Had to redo all my routines and groups. Quite the pain in the #$%$.
Cheers,
